perses/perses

- internal/api/front/perses/angular.json
- internal/api/front/perses/src/app-loading.scss
- internal/api/front/perses/src/index.html
> add a loading-screen that appears when the application is loading

- .circleci/config.yml
- .gitignore
- .goreleaser.yml
- Dockerfile
- Makefile
this PR includes the build of a docker image too.
> use goreleaser to have a cross build of perses

- dev/populate.sh
thanks to https://github.com/moby/moby/issues/24029#issuecomment-250412919 this PR fix #15.
Tested with git bash on windows, works like a charm
> fix absolute path being changed with git bash on windows

- internal/api/impl/v1/dashboard/service.go
- internal/api/impl/v1/dashboard/variable/variable.go
- internal/api/impl/v1/dashboard/variable/variable_test.go
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard_panel.go
- pkg/model/api/v1/dashboard_variable.go
The build order will be usefull later when we will have to perform the query associated to each variable.
For the moment it is used to check if there is no circular dependency and no variable used but not defined.
> Review the datamodel of the variable and provide a way to determinate the build order of the variable.

- internal/api/e2e/datasource_test.go
- internal/api/e2e/project_test.go
- internal/api/e2e/user_test.go
- pkg/client/api/v1/datasource_test.go
- pkg/client/api/v1/project_test.go
- pkg/client/api/v1/user_test.go
- pkg/model/api/v1/datasource.go
- pkg/model/api/v1/user.go
- utils/test.go
it also add e2e test on datasource and user
> provide a set of methods use to stabilize the e2e test

- internal/api/front/perses/package-lock.json
- internal/api/front/perses/package.json
- internal/api/front/perses/src/app/project/dashboard/dashboard-details/dashboard-details.component.html
- internal/api/front/perses/src/app/project/dashboard/dashboard-details/dashboard-details.component.ts
- internal/api/front/perses/src/app/project/dashboard/dashboard-routing.module.ts
- internal/api/front/perses/src/app/project/dashboard/dashboard.model.ts
- internal/api/front/perses/src/app/project/dashboard/dashboard.module.ts
- internal/api/front/perses/src/app/project/dashboard/dashboard.service.ts
- internal/api/front/perses/src/app/project/project-routing.module.ts
- internal/api/front/perses/src/app/project/project-template/project-template.component.ts
Initialize module, component and datamodel. It will help to start with a common struct :)
@AntoineThebaud hope it will help you
/cc @juliusv frontend is coming :D
> initialize dashboard module

- internal/api/front/perses/src/app/core/template/template.component.html
- internal/api/front/perses/src/app/project/project-template/project-template.component.html
- internal/api/front/perses/src/app/shared/component/line/line.component.html
- internal/api/front/perses/src/app/shared/component/line/line.component.scss
- internal/api/front/perses/src/app/shared/component/line/line.component.ts
- internal/api/front/perses/src/app/shared/shared.module.ts
@celian-garcia @AntoineThebaud could help if you want to put items on the same line.
> add a line component and use it to align things

- docs/dashboard.md
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard_test.go
- pkg/model/api/v1/dashboard_variable.go
- pkg/model/api/v1/dashboard_variable_test.go
related to the changes describe in #55 regarding the variable.
/cc @AntoineThebaud @ahurtaud
> add displayed_name attribute for the variables and additional check

- cmd/perses/main.go
> A few language and content improvements in main.go

- .github/workflows/react.yml
- README.md
- web/package-lock.json
- web/package.json
@juliusv I enabling a beginning of ci for React. For the moment it will just run the linter.
> enable react ci + reshuffle npm deps

- README.md
> define a rough roadmap

- README.md
I changed the language around a lot in some places, but hopefully the
overall result is smoother to read and easier to understand, while
conveying the same meaning.
> Editorial changes to README.md

- internal/api/impl/v1/dashboard/variable/build_order.go
- internal/api/impl/v1/dashboard/variable/build_order_test.go
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard/jsonref.go
- pkg/model/api/v1/dashboard/jsonref_test.go
- pkg/model/api/v1/dashboard/layout.go
- pkg/model/api/v1/dashboard/layout_test.go
- pkg/model/api/v1/dashboard/panel.go
- pkg/model/api/v1/dashboard/panel_test.go
- pkg/model/api/v1/dashboard/variable.go
- pkg/model/api/v1/dashboard/variable_test.go
- pkg/model/api/v1/dashboard_test.go
> move dashboard spec component in a dedicated package

- .github/workflows/go.yml
- Makefile
- check_license.sh
- internal/api/core/middleware/proxy.go
- internal/api/front/doc.go
- internal/api/front/generate.go
- internal/api/front/server.go
- internal/api/impl/v1/health/endpoint.go
- internal/api/impl/v1/health/persistence.go
- internal/api/impl/v1/health/service.go
- internal/api/interface/v1/health/interface.go
- pkg/model/api/v1/dashboard/layout.go
- pkg/model/api/v1/dashboard/layout_test.go
- pkg/model/api/v1/health.go
- ui/.eslintrc.base.js
- ui/.eslintrc.web.js
- ui/app/.eslintrc.js
- ui/app/webpack.analyze.ts
- ui/app/webpack.common.ts
- ui/app/webpack.dev.ts
- ui/app/webpack.prod.ts
- ui/core/.eslintrc.js
- ui/panels-plugin/.eslintrc.js
- ui/prometheus-plugin/.eslintrc.js
> add a way to verify that the the license header is present in the js, ts, go files

- ui/app/src/App.tsx
> Add TODO comment to plugin registry import line

- ui/app/.gitignore
- ui/app/sample-data/dashboard.ts
- ui/app/sample-data/datasource.ts
> add sample-data

- .github/workflows/build.yaml
- internal/api/front/generate.go
> enable react-build

- check_license.sh
hopefully fixing the script checklicense to work on multiple different shell. (at least works again on mine ...)
Also it ignores all sub folder `dist` `node_modules` instead of just the one at the root package.
> fix checklicense to work on different shell

- Makefile
> add tsx to the license check

- codecov.yml
> disable codecov comments

- .github/dependabot.yml
> simplify the update of the npm dependencies

- .gitpod.yml
- ui/app/webpack.dev.ts
> disable host check and disable https config in gitpod env

- ui/app/src/App.tsx
- ui/app/src/components/Footer.tsx
> put the footer at the bottom

- CONTRIBUTING.md
- ui/README.md
> Improve wordings in CONTRIBUTING.md

- internal/api/impl/v1/dashboard/service.go
- internal/api/impl/v1/dashboard/variable/build_order.go
- internal/api/impl/v1/dashboard/variable/build_order_test.go
- internal/api/impl/v1/datasource/service.go
- internal/api/impl/v1/globaldatasource/service.go
- internal/api/impl/v1/project/service.go
- internal/api/impl/v1/user/service.go
- internal/api/shared/database/dao.go
- pkg/model/api/v1/common/jsonref.go
- pkg/model/api/v1/common/jsonref_test.go
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard/layout.go
- pkg/model/api/v1/dashboard/panel.go
- pkg/model/api/v1/dashboard/panel_test.go
- pkg/model/api/v1/dashboard/variable.go
- pkg/model/api/v1/dashboard/variable_test.go
- pkg/model/api/v1/datasource.go
- pkg/model/api/v1/datasource/datasource.go
- pkg/model/api/v1/datasource/http.go
- pkg/model/api/v1/kind.go
- pkg/model/api/v1/metadata_test.go
- pkg/model/api/v1/project.go
- pkg/model/api/v1/user.go
> Golang fmt: replace '%s' by %q

- pkg/model/api/v1/metadata.go
> fix when getting all dashboards at once

- .gitpod.yml
> build cli in gitpod

- ui/components/package.json
- ui/core/package.json
- ui/dashboards/package.json
- ui/panels-plugin/package.json
- ui/plugin-system/package.json
- ui/prometheus-plugin/package.json
> add perses link in all packages

- .github/workflows/release.yaml
Fix the path to the `ui_release.sh` script in our GitHub actions flow.
> Fix path to script

- internal/cli/cmd/version/version.go
- internal/cli/cmd/version/version_test.go
- pkg/client/fake_api/fake_v1/health.go
> CLI: fix the cmd version to be able print it even if the remote API is not connected or doesn't respond

- .github/workflows/build_and_release.yaml
- .github/workflows/go.yml
- go.mod
- go.sum
> bump go to v1.18

- .github/workflows/build_and_release.yaml
- .gitignore
- Makefile
- RELEASE.md
- scripts/release.sh
- scripts/ui_release.sh
This PR provides a way to extract the release note of the last version written in the file `CHANGELOG.md`. The content is written in a file called `GENERATED_CHANGELOG.md` and then provided to goreleaser when it is used to release the project.
> provide a way to extract the changelog and give it to goreleaser

- .github/dependabot.yml
> deactivate dependabot for npm dependencies

- go.mod
- go.sum
- internal/cli/cmd/get/get.go
- internal/cli/cmd/remove/remove.go
- internal/cli/utils/resource.go
- internal/cli/utils/service/dashboard.go
- internal/cli/utils/service/datasource.go
- internal/cli/utils/service/folder.go
- internal/cli/utils/service/globaldatasource.go
- internal/cli/utils/service/project.go
- internal/cli/utils/service/service.go
> use generics to simplify the way to convert slice in CLI

- internal/api/front/generate.go
- internal/api/generate.go
- internal/api/shared/database/dao.go
- internal/cli/utils/config.go
- pkg/client/perseshttp/client.go
- pkg/client/perseshttp/request.go
- pkg/model/api/v1/datasource/http.go
> replace ioutil usage by os

- internal/api/impl/v1/dashboard/schemas/validator.go
- internal/cli/cmd/lint/lint.go
> CLI: lint cmd can load CUE schema to validate dashboards locally

- .goreleaser.yml
> update release title template to include the date

- Makefile
- cue.mod/module.cue
- internal/api/impl/v1/dashboard/schemas/testdata/base.cue
- internal/api/impl/v1/dashboard/schemas/testdata/plugins/first/panel.cue
- internal/api/impl/v1/dashboard/schemas/testdata/plugins/second/panel.cue
- schemas/base.cue
- schemas/charts/gauge/gauge.cue
- schemas/charts/line/line.cue
- schemas/charts/stat/stat.cue
- schemas/common/calculation.cue
- schemas/common/prometheus/query.cue
- schemas/common/threshold.cue
- schemas/common/unit.cue
- schemas/plugins/bar/panel.cue
> add license header on top of cue files

- Dockerfile
> update maintainer labels

- internal/api/e2e/datasource_test.go
- internal/api/impl/v1/dashboard/service.go
- internal/api/impl/v1/datasource/service.go
- internal/api/impl/v1/folder/service.go
- internal/api/impl/v1/globaldatasource/service.go
- internal/api/impl/v1/project/service.go
- internal/api/impl/v1/user/service.go
- pkg/model/api/v1/metadata.go
- ui/core/src/model/resource.ts
> add a version number at metadata level an increment it at each update of the resource

- docs/kubernetes.md
> add documentation regarding how Perses might work on k8s

- internal/api/impl/v1/dashboard/schemas/validator_test.go
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard/layout.go
- pkg/model/api/v1/dashboard/layout_test.go
- pkg/model/api/v1/dashboard_test.go
- ui/app/sample-data/benchmarkDashboard.ts
- ui/app/sample-data/convert/convert-layouts.ts
- ui/app/sample-data/convert/convert.ts
- ui/app/sample-data/layoutDemo.ts
- ui/app/sample-data/nodeExporterDashboard.ts
- ui/core/src/model/layout.ts
- ui/dashboards/src/components/GridLayout/GridLayout.tsx
> align layout definition between frontend and backend

- .github/workflows/go.yml
- Makefile
> check cue file format and verify go.mod is in good shape

- internal/api/front/generate.go
> update mime types supported

- go.mod
- go.sum
- internal/cli/cmd/get/get.go
> bump viper to v1.5.0 and use MarkFlagsMutuallyExclusive for get cmd

- ui/package-lock.json
- ui/prometheus-plugin/package.json
- ui/prometheus-plugin/src/model/templating.ts
Switch prometheus-plugin package.json and imports to use @prometheus-io/lezer-promql
> fix install errors in prometheus-plugin

- .github/workflows/build_and_release.yaml
- .goreleaser.yml
- Makefile
It's just reuse more what is defined in the Makefile, so the CI/CD is a bit more reproductible.
> review the way to cross build Perses

- internal/cli/cmd/apply/apply.go
- internal/cli/cmd/describe/describe.go
- internal/cli/cmd/get/get.go
- internal/cli/cmd/lint/lint.go
- internal/cli/cmd/remove/remove.go
- internal/cli/opt/opt.go
> create optional flag that can be used across different command

- ui/app/sample-data/benchmarkDashboard.ts
- ui/dashboards/package.json
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/package-lock.json
To help with performance this PR lazy loads panel content on scroll using react-intersection-observer
> lazy load panels on scroll

- docs/datasource.md
> add datasource documentation based on discussion #404

- Makefile
Release v0.6.0 didn't end up correctly. this PR is supposed to make it work again
> missing makefile target 'cross-release'

- CONTRIBUTING.md
I added bullet point about `jq`. I want people to know they can delete this if we ever stop using it in the `populate.sh` script.
> [contributing.md] Add explanation for jq package

- .github/workflows/build_and_release.yaml
- .github/workflows/go.yml
- internal/api/impl/v1/dashboard/variable/build_order.go
> upgrade to go 1.19

- ui/dashboards/src/components/PanelDrawer/PanelDrawer.test.tsx
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.tsx
- ui/panels-plugin/src/plugins/markdown/MarkdownPanelOptionsEditor.tsx
This is a start at making it possible to edit the markdown panel: 
> Make it possible to edit markdown

- ui/panels-plugin/src/plugins/markdown/MarkdownPanelOptionsEditor.tsx
* maxRows => rows
* Add a link to the markdown guide (link goes to: https://www.markdownguide.org/cheat-sheet, double-checking with design that they like this) (other option is https://commonmark.org/help)
> Markdown editor polish

- ui/dashboards/src/components/DashboardToolbar.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
This PR just makes the dashboard toolbar looks nicer :) 
- moved TemplateVariableList into DashboardToolbar
Before: 
After:
> Update Perses Header 

- .github/workflows/ci.yaml
- Makefile
- go.mod
- go.sum
- scripts/generate_changelog.go
- scripts/release.sh
I'm introducing a go script to extract the entry in the changelog.
Like that we shouldn't have any parsing issues we encounter with the bash script.
> extract properly the changelog and use it for goreleaser

- .goreleaser.yml
- Makefile
> fix release template with a less verbose date and a better version

- ui/dashboards/src/components/PanelDrawer/PanelPreview.tsx
Accidentally broke the build when I didn't rebase my #604 branch and thought CI was lying
> fix build after PanelEditorValues import change

- ui/dashboards/src/components/PanelDrawer/PanelDrawer.test.tsx
- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
> Update PanelEditor for designs

- schemas/queries/prometheus/query.cue
> use the prometheus datasource kind for the query

- ui/dashboards/src/components/GridLayout/GridTitle.tsx
- ui/dashboards/src/components/PanelGroupDialog/DeletePanelGroupDialog.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupDialog.test.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupDialog.tsx
- ui/dashboards/src/context/DashboardProvider/dashboard-provider-api.ts
- ui/dashboards/src/context/DashboardProvider/layout-slice.tsx
- ui/dashboards/src/context/DashboardProvider/panel-group-slice.tsx
- ui/dashboards/src/test/testDashboard.ts
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
- ui/dashboards/src/views/ViewDashboard/tests/panelGroups.test.tsx
> Delete Panel Group

- ui/prometheus-plugin/src/plugins/prometheus-variables.ts
> add missing optional matcher for Prometheus LabelName Variable

- internal/api/impl/v1/datasource/service.go
- internal/api/impl/v1/globaldatasource/service.go
> check unicity of default datasource per kind

- internal/api/impl/v1/dashboard/service.go
- internal/api/impl/v1/datasource/service.go
- internal/api/impl/v1/globaldatasource/service.go
- internal/api/shared/validate/validate.go
- internal/cli/cmd/lint/lint.go
- pkg/model/api/v1/datasource.go
> add validate package to put in common the way to validate dashboard and datasource

- schemas/datasources/prometheus/prometheus.json
- scripts/cue-test/cue-test.go
> add cue test for the datasources

- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
Implement adding and deleting queries
> Add and delete queries

- pkg/model/api/v1/dashboard/variable.go
- pkg/model/api/v1/dashboard/variable_build_order.go
> check the name of the variable

- ui/components/package.json
- ui/components/src/TimeRangeSelector/TimeRangeSelector.tsx
- ui/package-lock.json
Replace @mui/icons-material/Event with mdi-material-ui/Calendar and update components/package.json to use mdi-material-ui. This keeps this dependency consistent with what's used now in app and dashboards package.
> change mui icon dependency in components package

- internal/api/shared/database/dao.go
Before this PR, `curl -XGET /api/v1/dashboards` wasn't returning anything.
It will help for #663 to build the root page that would display the list of available dashboard regardless the project.
> fix dao file to be able to return the list when we are at the root of the resources

- .gitpod.yml
> stop running docker-compose on gitpod workplace

- ui/dashboards/src/components/DashboardToolbar.tsx
- ui/dashboards/src/context/useDashboardSpec.tsx
Loom demo: https://www.loom.com/share/461968eb948d491ebb61e41156897a94
Implements the ability to revert the spec to the original state before edit mode
> Implement Variable editing cancel

- ui/app/src/theme/palette/background.ts
- ui/app/src/theme/palette/common.ts
- ui/app/src/theme/palette/palette-options.ts
- ui/app/src/theme/palette/text.ts
- ui/app/src/theme/theme.ts
- ui/components/src/InfoTooltip/InfoTooltip.tsx
- ui/dashboards/src/components/GridLayout/GridLayout.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/context/TimeRangeProvider.tsx
- changed panel header font size and padding 
- updated tooltip theme colors 
- removed padding around react-grid-layout so it aligns with the panel group header
> Fix tooltip and other stylings

- ui/dashboards/src/components/Panel/index.ts
Signed-off-by: Eunice Wong <eunicewong@live.com>
> export delete panel dialog

- ui/app/src/App.tsx
- ui/app/src/components/Header.tsx
- ui/app/src/model/dashboard-client.ts
- ui/app/src/views/ViewDashboard.tsx
- ui/app/src/views/ViewDashboardList.tsx
- ui/dashboards/src/utils/time-range-params.ts
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
This PR proposed a first version to display the list of available dashboard.
> display the dashboard list

- ui/plugin-system/src/runtime/time-series-queries.ts
This just removes the "suggested step size" from the `react-query` key when running time series queries. Should fix the issue where queries get re-run when the browser is resized.
> Remove suggested step from time series query key

- ui/dashboards/src/context/useDashboardSpec.tsx
This PR fixes an issue where the order of layouts in the dashboard JSON does not match what is shown in UI
> Reorder Layouts in Dashboard Spec

- pkg/model/api/v1/dashboard/variable.go
> fix yaml field for list variable

- pkg/model/api/v1/dashboard/variable.go
- pkg/model/api/v1/dashboard_test.go
> remove omitempty option for boolean field in the variable list

- GOVERNANCE.md
Signed-off-by: Augustin Husson <augustin.husson@amadeus.com>
> fix link to the perses team and sort members

- ui/dashboards/src/components/GridLayout/GridTitle.tsx
- ui/dashboards/src/context/DashboardProvider/dashboard-provider-api.ts
https://docs.pmnd.rs/zustand/recipes/recipes#memoizing-selectors
> Memoize selectors to prevent unnecessary computations each render

- CHANGELOG.md
- internal/api/shared/schemas/schemas_test.go
- pkg/model/api/v1/dashboard/variable.go
- pkg/model/api/v1/dashboard/variable_build_order_test.go
- pkg/model/api/v1/dashboard/variable_test.go
- pkg/model/api/v1/dashboard_test.go
- ui/core/src/model/datasource.ts
- ui/core/src/model/display.ts
- ui/core/src/model/panels.ts
- ui/core/src/model/variables.ts
- ui/dashboards/src/components/Variables/Variable.tsx
- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/dashboards/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/dashboards/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts
> Sync Variable model between backend and frontend

- CONTRIBUTING.md
- README.md
- ui/README.md
Here a proposal of the main README. The idea is to have an accurate status, a better idea about what we are trying to achieve in Perses and a better guideline how to start with Perses.
I'm aware it's not perfect and it probably requires more user documentations like how to build a dashboard. But hey that's a start :).
> rewrite README and format others markdown docs

- CHANGELOG.md
> Update changelog for dependsOn

- CHANGELOG.md
- docs/examples/config.archive.yaml
- docs/examples/config.docker.yaml
> update config file example used for the archive and the docker images

- scripts/cue-test/cue-test.go
> activate cue validation for the variables

- ui/prometheus-plugin/src/plugins/prometheus-variables.tsx
> fix dependsOn for labelValues and labelNames variables

- CHANGELOG.md
- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/dashboards/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
See this PR for context: https://github.com/perses/perses/pull/783
> Make all headers in editors look the same

- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard_test.go
- ui/app/src/components/DashboardList.tsx
- ui/app/src/views/ViewDashboard.tsx
- ui/core/src/model/dashboard.ts
- ui/core/src/model/index.ts
> add a display field to the dashboards

- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/GridLayout/GridTitle.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.tsx
- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- Updated some spacing to match designs
- Also did some code consistency updates while I was looking at this: `direction={'row'}` => `direction="row"`, `sx={{ marginLeft: 'auto' }}` => `marginLeft="auto"`
> Update spacing to match designs and do cleanup

- dev/data/dashboard.json
- internal/api/e2e/dashboard_test.go
- internal/api/e2e/framework/data.go
- internal/api/e2e/framework/server.go
- pkg/model/api/v1/common/validate.go
> add API e2e tests on the dashboard

- ui/components/src/AxisLabel.tsx
- ui/components/src/YAxisLabel.tsx
- ui/components/src/index.ts
- ui/components/src/utils/theme-gen.test.ts
- ui/components/src/utils/theme-gen.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditorSettings.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/YAxisOptionsEditor.tsx
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
Follow up to PR #767 with visual editing of new TimeSeriesChart y_axis options, `label`, `min`, `max`
- adding more tests, validation / helperText, option to hide y_axis
https://user-images.githubusercontent.com/9369625/202747996-e671cb9c-2800-4f7d-b845-5415850be5c8.mp4
> form controls for new y_axis options

- CHANGELOG.md
- ui/app/src/model/config-client.ts
- ui/app/src/views/ViewDashboard.tsx
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
- ui/dashboards/src/views/ViewDashboard/tests/panelGroups.test.tsx
> Read config to set UI in readonly mode

- ui/components/src/theme/theme.ts
- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/dashboards/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/prometheus-plugin/src/plugins/MatcherEditor.tsx
**Before**
**After**
cc @foxbat07
> Minor Style Fixes for Variables Editor

- ui/package-lock.json
> Update package lock

- ui/dashboards/src/components/Variables/VariableList.tsx
Fixes a bug in https://github.com/perses/perses/pull/842
> [BUGFIX] show variables when not in edit mode

- Makefile
> [IGNORE] Use the new name for the extracted changelog

- internal/cli/cmd/lint/lint.go
> [ENHANCEMENT] CLI can use variables schemas during the validation of dashboard

- ui/app/src/components/Footer.tsx
> [ENHANCEMENT] Add a link to the release in the footer

- CONTRIBUTING.md
- scripts/api_backend_dev.sh
Hoping this will speed up a few steps during local dev for UI-focused devs. This may also be helpful for starting things up quickly in CI if we end up setting up end-to-end tests against the app in the future.
> [IGNORE] Add script to automate api backend for dev

- README.md
> [IGNORE] fix ci badges and add go quality badge

- internal/cli/cmd/lint/lint.go
Signed-off-by: Augustin Husson <augustin.husson@amadeus.com>
> [BUGFIX] Fix loading of the cue schemas in the command lint

- ui/components/src/model/units/units.test.ts
PR feedback follow up from #847 (see [comment here](https://github.com/perses/perses/pull/847#discussion_r1043799735))
> [IGNORE] unit formatter tests refactor

- dev/data/dashboard.json
- ui/e2e/README.md
- ui/e2e/src/pages/DashboardPage.ts
- ui/e2e/src/pages/Panel.ts
- ui/e2e/src/pages/PanelEditor.ts
- ui/e2e/src/pages/PanelGroup.ts
- ui/e2e/src/tests/panels.spec.ts
Also includes some improvements to testing utils and docs.
> Add more panel tests

- .github/pull_request_template.md
- CONTRIBUTING.md
And clarify use of the `IGNORE` catalog entry in the docs
This will finish up the last remaining task for https://github.com/perses/perses/issues/838 so we can close it.
> [IGNORE] Add PR template

- internal/api/e2e/dashboard_test.go
- pkg/model/api/v1/metadata.go
- pkg/model/api/v1/metadata_test.go
The version were never incremented before this PR.
> [BUGFIX] Fix increased metadata.version

- .github/pull_request_template.md
- .github/workflows/go.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- GOVERNANCE.md
- MAINTAINERS.md
- Makefile
- README.md
- RELEASE.md
- docs/cli.md
- docs/configuration.md
- docs/cue.md
- docs/dashboard.md
- docs/datasource.md
- docs/kubernetes.md
- ui/.prettierignore
- ui/components/README.md
- ui/components/src/DateTimeRangePicker/DateTimeRangePicker.md
- ui/components/src/Drawer/Drawer.md
- ui/components/src/InfoTooltip/InfoTooltip.md
- ui/components/src/LineChart/LineChart.md
- ui/e2e/README.md
- ui/ui-guidelines.md
This PR introduced the usage of [mdox](https://github.com/bwplotka/mdox) to ensure the different documentation written in the markdown files are well formatted.
The tool will also ensure that every links are working. Spoiler alert, some were broken :).
It fixed #889 
> [IGNORE] enable checking format of the markdown docs

- dev/data/dashboard.json
- ui/e2e/src/pages/Panel.ts
- ui/e2e/src/tests/markdownPanel.spec.ts
I caught a few minor issues with the visual tests while moving on to the more complicated case of creating tests for charts. I wanted to get these in first as a smaller, separate PR, and will follow-up with a PR for the chart tests later.
- Adjust check for loading to finish.
- Rename markdown test file to clarify it's for the panel.
- Use parent of panel to ensure the height/width are maintained.
> [IGNORE] minor visual test improvements

- ui/app/src/components/AddProjectDialog/AddProjectDialog.tsx
- ui/app/src/components/DeleteProjectDialog/DeleteProjectDialog.tsx
- ui/app/src/model/http.ts
- ui/app/src/model/project-client.ts
- ui/app/src/views/ViewDashboard.tsx
- ui/app/src/views/ViewDashboardList.tsx
- ui/app/src/views/ViewProject.tsx
Signed-off-by: Célian Garcia <celian.garcia@amadeus.com>
This PR initiates the project CRUD. It includes : 
> Regarding the second point, to be discussed with designer about the clarity of having the dashboards stored by project in the home page view. 
> Despite the bug that removing a project does not remove dashboard (will be soon fixed), I would find clearer to have directly a list of dashboards (with project mention on the line).
> [FEATURE] Initiate project creation/deletion in the frontend

- ui/app/src/components/AddProjectDialog/AddProjectDialog.tsx
- ui/app/src/components/CreateDashboardDialog/CreateDashboardDialog.tsx
- ui/app/src/components/DeleteDashboardDialog/DeleteDashboardDialog.tsx
- ui/app/src/components/DeleteProjectDialog/DeleteProjectDialog.tsx
- ui/app/src/components/RenameDashboardDialog/RenameDashboardDialog.tsx
- ui/app/src/views/ViewDashboardList.tsx
- ui/app/src/views/ViewProject.tsx
Migrate custom dialog to generic dialog component (#948)
> [ENHANCEMENT] Migrate custom dialogs to generic dialog component

- ui/dashboards/package.json
- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
- ui/package-lock.json
> [IGNORE] upgrade zustand to latest

- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
> [IGNORE] fix data-transform debug line

- docs/datasource.md
This PR fixes the example values to match the current API definitions
> [IGNORE] fix datasource docs examples

- dev/data/dashboard.json
- ui/e2e/src/pages/PanelEditor.ts
- ui/e2e/src/tests/gaugeChartPanel.spec.ts
- ui/e2e/src/tests/statChartPanel.spec.ts
- ui/e2e/src/tests/timeSeriesChartPanel.spec.ts
added e2e tests and new happo screenshots for thresholds
> [IGNORE] Add visual tests for thresholds

- internal/api/core/core.go
- internal/api/core/middleware/error.go
- internal/api/core/middleware/verification.go
- internal/api/impl/migrate/migrate.go
- internal/api/impl/validate/validate.go
- internal/api/shared/toolbox.go
> [IGNORE] add a middleware to ensure every error are correctly wrapped

- scripts/cue-test/cue-test.go
I just figured out we are starting to have plenty of dashboard in `dev/data` and maybe having something that is validating the dashboards will ensure the `dev/data` are compatible with the current version of the application.
> [IGNORE] Validate all dashboards and dts contain in dev/data

- ui/dashboards/src/components/Dashboard/Dashboard.stories.tsx
- ui/dashboards/src/components/Dashboard/Dashboard.tsx
- ui/dashboards/src/stories/decorators/WithDashboard.tsx
> [BUGFIX] Make emptyDashboardProps optional on Dashboard

- ui/core/src/utils/index.ts
that should help a bit for the PR #1062
> [IGNORE] export utils text method in the core component

- ui/app/src/components/Header.tsx
Add an "Empty" item in the project dropdown, if there is no projects.
> [ENHANCEMENT] Add empty item in Project dropdown

- GOVERNANCE.md
@juliepagano you were missing in the team member list :). Just fixing this mistake
> [IGNORE] add Julie Pagano to the team member

- ui/dashboards/src/components/index.ts
Needed for embed use cases for saving default time range and variables, see #1165 
> [ENHANCEMENT] Export SaveDashboardButton from dashboards package

- ui/prometheus-plugin/src/index.ts
Exporting all Prometheus plugin types
> [ENHANCEMENT] Export prom variables types

- dev/data/dashboard.json
- ui/components/src/StatChart/StatChart.test.tsx
- ui/components/src/StatChart/StatChart.tsx
- ui/components/src/StatChart/calculateFontSize.test.ts
- ui/components/src/StatChart/calculateFontSize.ts
- ui/components/src/model/theme.ts
- ui/e2e/src/pages/DashboardPage.ts
- ui/e2e/src/tests/statChartPanel.spec.ts
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
This PR not only supports multi-series stat chart but also improves font size. Font size will now automatically grow to fit the available space.
https://github.com/perses/perses/assets/9817826/b04e2ca6-2c84-43ed-9d6b-0f67909b29c7
TO DO:
We want to add a manual option for adding your own font size as well.
> [FEATURE] Support Multi-Series Stat Chart

- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
- Move the info tooltip directly next to the panel title
- Keep the tooltip visible in both view and edit modes
- Do not show the tooltip if the text is all whitespace
Info icon shown to the far right of the panel header in view mode:
Info icon hidden in edit mode:
Info icon shown directly after panel title in both view and edit mode:
https://github.com/perses/perses/assets/22085207/cf1a18df-508a-4834-88c2-bf698a7458ad
> [ENHANCEMENT] Update panel header info tooltips

- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
Improved this layout + this code by working with our designer Claire
Getting this improved code in Perses too.
> [ENHANCEMENT] Improve the responsive layout of the toolbar buttons

- dev/data/dashboard.json
- ui/components/src/Legend/CompactLegend.tsx
- ui/components/src/Legend/Legend.stories.tsx
- ui/components/src/Legend/Legend.test.tsx
- ui/components/src/Legend/Legend.tsx
- ui/components/src/Legend/ListLegend.tsx
- ui/components/src/Legend/ListLegendItem.tsx
- ui/components/src/Legend/TableLegend.test.tsx
- ui/components/src/Legend/TableLegend.tsx
- ui/components/src/LineChart/LineChart.stories.tsx
- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/Table/Table.stories.tsx
- ui/components/src/Table/Table.test.tsx
- ui/components/src/Table/VirtualizedTable.tsx
- ui/components/src/Table/model/table-model.ts
- ui/e2e/src/tests/timeSeriesChartLegends.spec.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
https://github.com/perses/perses/assets/396962/3c54f2c7-9ed7-435f-8961-8a7edede6ff4
https://github.com/perses/perses/assets/396962/8b6402f9-d64c-4ed9-90fa-e100e1c10fc6
https://github.com/perses/perses/assets/396962/dcd20e88-383d-476b-899f-851be87c414f
https://github.com/perses/perses/assets/396962/7f368b49-6396-425f-b9ee-f5687f473d69
> [ENHANCEMENT] Highlight associated line on mouseover legend item

- ui/core/src/model/units/bytes.ts
- ui/core/src/model/units/decimal.ts
- ui/core/src/model/units/percent.ts
- ui/core/src/model/units/time.ts
- ui/core/src/model/units/units.ts
Stylistic changes to the number formatting code -- No functional changes
Hopefully these changes make it easier for anyone new to this code to figure out what's going on.
* Added comments
* Alphabetized code
* Made code consistent 
* Made it more obvious what the formatter is
> [IGNORE] Add comments + stylistic updates for number formatting code

- .github/actions/setup_helmlint/action.yaml
- .github/workflows/lint-test-helm-chart.yaml
- charts/perses/.helmignore
- charts/perses/Chart.yaml
- charts/perses/templates/NOTES.txt
- charts/perses/templates/_helpers.tpl
- charts/perses/templates/config.yaml
- charts/perses/templates/ingress.yaml
- charts/perses/templates/pvc.yaml
- charts/perses/templates/service.yaml
- charts/perses/templates/serviceaccount.yaml
- charts/perses/templates/statefulset.yaml
- charts/perses/values.schema.json
- charts/perses/values.yaml
Adding Perses Helm Chart Solves: #1270
> [FEATURE] starting helm chart

- ui/dashboards/src/components/Variables/TemplateVariable.test.ts
- ui/dashboards/src/components/Variables/TemplateVariable.tsx
Encapsulates the complex part which manages the default selected value of a list variable into a function. 
It allowed me to make some interesting tests and fixes.
fixes #1312 
It's implementing the flow described in the issue + an additional behavior : when the default value or value from query param is not present in the list, it falls back to the first value of the list. 
> No screenshots as it is quite hard to capture in a screen. I let people reviewing the PR play with it locally.
> [BUGFIX] Default selection for variables of type list

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/pull_request_template.md
> [FEATURE] Add templating to issues

- internal/api/impl/v1/variable/service.go
- internal/api/impl/validate/validate.go
- internal/api/shared/validate/validate.go
- internal/cli/cmd/lint/lint.go
- pkg/model/api/v1/utils/variable_build_order.go
- pkg/model/api/v1/utils/variable_build_order_test.go
- pkg/model/api/v1/variable.go
- ui/app/src/model/variables.ts
- ui/app/src/utils/variables.ts
- ui/app/src/views/admin/AdminTabs.tsx
- ui/core/src/model/variables.ts
- ui/dashboards/src/components/AddPanelButton/AddPanelButton.stories.tsx
- ui/dashboards/src/components/EmptyDashboard/EmptyDashboard.stories.tsx
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupDialog.test.tsx
- ui/dashboards/src/components/Variables/EditVariablesButton.stories.tsx
- ui/dashboards/src/components/Variables/EditVariablesButton.tsx
- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
- ui/e2e/src/tests/variables.spec.ts
- ui/plugin-system/src/runtime/builtin-variables.ts
- ui/plugin-system/src/runtime/index.ts
- ui/plugin-system/src/runtime/template-variables.ts
Added support for basic builtin variables, wdyt about the implementation? I still need to figure out how to implement plugin builtin variables (i.e.: $__rate_interval for prometheus-plugin)
Builtin variables are dynamic variables computed when the dashboard is rendered / refreshed.
Builtin variables implemented:
- `$__dashboard`: the dashboard display name name, if not set dashboard metadata name
- `$__project`: the dashboard project name
- `$__from`: the start time of the dashboard
- `$__to`: the end time of the dashboard
Know issues: 
- $__from and $_to are not updated with auto-refresh, related to: #1280 
- $__from and $__to variables are not consistent with our current naming, in the code / url, it's `start` and `end`. Should we rename variables?
Closes #1347 
Closes #1346 
- Is the …
> [FEATURE] Add builtin variables ($__dashboard, $__project, $__from, $__to)

- internal/api/core/middleware/verification.go
- ui/app/src/GuardedProjectRoute.tsx
- ui/app/src/Router.tsx
- ui/app/src/model/project-client.ts
- ui/app/src/views/ViewDashboard.tsx
This PR is introducing a sort of guard on the route.
It will check if the project exist and in case it doesn't exist, the user is redirected to the home page.
fix #1349
> [BUGFIX] Fix direct link with unknown project redirect now to the home page

- internal/api/config/database.go
This PR is adding a new key `password_file` in the backend config so we can read a file that contains the password for the sql config.
This is part of the issue #1368 
/cc @nicolastakashi
> [ENHANCEMENT] Add a new key password_file in the sql config

- ui/app/src/model/project-client.ts
> [BUGFIX] Delete project does not refresh the list

- ui/endpoint.go
> [BUGFIX] Fix reloading /admin route in react

- ui/dashboards/src/components/SaveDashboardButton/SaveDashboardButton.tsx
> [BUGFIX] Fix dashboard save button staying disabled after failing to save dashboard

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Automatically add label for issue or feature requests. Closes #1391
> [IGNORE] Automatically add label for issues or feature requests

- internal/api/shared/database/file/file.go
This is PR fixed #1420.
Like that you will need the accurate case to get your document. Otherwise it will return nothing.
> [BUGFIX] Fix the way to get an unique document. It is now case sensitive

- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
> [ENHANCEMENT] Increase max width for variable dropdowns

- internal/api/shared/database/file/file.go
- internal/api/shared/database/sql/query.go
- internal/api/shared/database/sql/sql.go
- internal/cli/file/read.go
When using the yaml files for the database, it appears there is a loading issue when getting the GlobalDatasource.
I think it's the same issue and (and so same fix) that was done in the CLI in #822
> [BUGFIX] Fix json/yaml files loading by using jsoniter at the database layer level

- ui/dashboards/src/components/Variables/TemplateVariable.tsx
If the value of a variable input is too long, it will be wrapped and it will be impossible to see the full value. The title attribute allow you to see the full value when you hover on the component.
> [ENHANCEMENT] Add title to variable inputs

- ui/app/src/views/MigrateView.tsx
The migration page needs a refactoring, but for now here is a quick enhancement 😄 
> [ENHANCEMENT] Quickly improve migration page design

- dev/config-mariadb.yaml
- docs/configuration.md
I'm just completing the documentation about the config. Even if the explanations are not exhaustive, it will be nicer than having to look at the code to know exactly what to put in the yaml config file
> [IGNORE] Complete doc about the config

- go.mod
- internal/api/core/server.go
- internal/api/doc.go
- internal/api/e2e/api/user_test.go
- internal/api/e2e/framework/data.go
- internal/api/generate.go
- internal/api/impl/v1/user/persistence.go
- internal/api/impl/v1/user/service.go
- internal/api/interface/v1/user/interface.go
- internal/api/shared/database/file/file.go
- internal/api/shared/database/file/query.go
- internal/api/shared/database/sql/query.go
- internal/api/shared/database/sql/sql.go
- internal/api/shared/dependency/persistence_manager.go
- internal/api/shared/dependency/service_manager.go
- internal/api/shared/utils.go
- internal/cli/resource/resource.go
- pkg/client/api/v1/client.go
- pkg/client/api/v1/user.go
- pkg/model/api/v1/kind.go
- pkg/model/api/v1/project.go
- pkg/model/api/v1/public_user.go
- pkg/model/api/v1/user.go
This PR is adding the support of a new resource "User".
This should help for the authentication.
> [FEATURE] Add support of user

- docs/datasource.md
- docs/secret.md
- pkg/model/api/v1/secret/authorization.go
I'm starting a documentation about the `Secret` and the `GlobalSecret`.
> [IGNORE] Add doc about secret

- internal/api/core/core.go
- internal/api/core/server.go
- internal/api/e2e/api/auth_test.go
- internal/api/e2e/framework/data.go
- internal/api/impl/auth/auth.go
- internal/api/impl/migrate/migrate.go
- internal/api/impl/v1/user/service.go
- internal/api/shared/crypto/hash.go
- pkg/model/api/auth.go
- pkg/model/api/v1/user.go
This PR is adding a new endpoint `/api/auth` that should be used to authenticate a user with a login and a password.
When the login is successful it doesn't return anything yet. Later it will return a JWT token
> [FEATURE] Add authentication endpoint

- docs/authorization.md
Add doc for future authorization
> [IGNORE] Add authorization doc

- internal/api/core/middleware/proxy.go
- internal/api/e2e/framework/data.go
- internal/api/shared/crypto/crypto.go
- pkg/model/api/v1/public_secret.go
- pkg/model/api/v1/secret.go
- pkg/model/api/v1/secret/tls_config.go
- ui/app/src/components/dialogs/CreateDashboardDialog.tsx
- ui/app/src/components/dialogs/CreateProjectDialog.tsx
- ui/app/src/components/dialogs/DeleteDashboardDialog.tsx
- ui/app/src/components/dialogs/DeleteDatasourceDialog.tsx
- ui/app/src/components/dialogs/DeleteProjectDialog.tsx
- ui/app/src/components/dialogs/DeleteSecretDialog.tsx
- ui/app/src/components/dialogs/DeleteVariableDialog.tsx
- ui/app/src/components/dialogs/RenameDashboardDialog.tsx
- ui/app/src/components/dialogs/index.ts
- ui/app/src/components/secret/SecretDataGrid.tsx
- ui/app/src/components/secret/SecretList.tsx
- ui/app/src/model/global-secret-client.ts
- ui/app/src/model/secret-client.ts
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/admin/tabs/GlobalSecret.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/tabs/ProjectSecrets.tsx
- ui/core/src/model/index.ts
- ui/core/src/model/secrets.ts
Add Secret & GlobalSecret list view as Datasource, Variable, ...
TODO
> [FEATURE] Add Secret & GlobalSecret list view

- docs/cue.md
- internal/api/shared/migrate/mapping.cuepart
- internal/api/shared/migrate/testdata/old_grafana_query_perses_dashboard.json
- internal/api/shared/migrate/testdata/simple_grafana_dashboard.json
- internal/api/shared/migrate/testdata/simple_perses_dashboard.json
- pkg/model/api/v1/variable/list.go
- ui/core/src/model/variables.ts
- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts
Add sorting capability for ListVariable.
Grafana migration logic added accordingly.
https://github.com/perses/perses/assets/7058693/133b4774-0f62-438b-9f3d-9d4ff9674460
> [FEATURE] Add sorting capability for ListVariable

- ui/app/src/components/DashboardCard/DashboardCard.tsx
- ui/app/src/components/Header.tsx
- ui/app/src/views/home/RecentDashboards.tsx
- ui/e2e/src/pages/AppHomePage.ts
Allow opening dashboards/projects in new tabs for header and recent projects only. It missing table links of the issue #1544
> [ENHANCEMENT] Allow opening dashboards/projects in new tabs

- docs/user/index.md
First commit, starting on the user documentation, this is the initial ToC that I'll be working out.
None.
> [ENHANCEMENT] Added first user documentation structure with ToC

- dev/config-mariadb.yaml
- dev/config.yaml
- docs/configuration.md
- internal/api/config/config.go
- internal/api/config/security.go
- internal/api/core/server.go
- internal/api/e2e/framework/server.go
- internal/api/shared/dependency/service_manager.go
- ui/app/src/guard/GuardedAuthRoute.tsx
- ui/app/src/model/config-client.ts
I'm adding a new config called `security` that will contain any configuration regarding the permission, roles ..etc.
> [BREAKINGCHANGE] Move any securiy config to a dedicated struct

- docs/user/index.md
- docs/user/section-1.md
Second try at this PR and hopefully cleaner.
None.
> [ENHANCEMENT] Added user documentation for section 1, introduction to Perses.

- ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts
> [BUGFIX] saved value for allowMultiple was not retrieved

- ui/dashboards/src/components/Variables/TemplateVariable.tsx
Follow-up on https://github.com/perses/perses/pull/1576. In the end it was not a bug from MUI but my bad 😅 Solution found here https://github.com/mui/material-ui/issues/31073#issuecomment-1106323690.
> [BUGFIX] ListVariable: fix scroll reset after a new option is selected

- ui/dashboards/src/components/QuerySummaryTable/QuerySummaryTable.tsx
This fixes up a small typo in the `QuerySummaryTable` - `datasourcClient` should be `datasourceClient`
> [BUGFIX] Fix typo in QuerySummaryTable

- docs/user/index.md
- docs/user/section-1.md
- docs/user/section-2-podman.md
- docs/user/section-2-source.md
- docs/user/section-2.md
Added section 2 and container installation with placeholder for source code install.
None.
> [ENHANCEMENT] Added section 2 with container installation

- ui/ui-guidelines.md
I want to propose a change to the UI guideline: allow to use falsiness of TS/JS.
It's way easier and shorter:
- for checking if a string is `undefined`, `null` or empty ("")
- for checking if an object is `undefined` or `null`
Code can still use explicit `null` or `undefined` checks if needed.
For info, these are the following falsy values in TypeScript and JavaScript:
- `0`
- `false`
- `NaN`
-  `""` (empty string)
- `0n` (bigint version of zero)
- `null`
- `undefined`
> [IGNORE] Allow the use of JS/TS falsiness

- internal/api/impl/auth/auth.go
- internal/api/shared/crypto/jwt.go
- ui/app/src/components/Header.tsx
- ui/app/src/model/auth-client.ts
- ui/e2e/src/pages/DashboardPage.ts
This PR is adding an account menu on the navbar. For the moment you just have the theme and the way to logout.
https://github.com/perses/perses/assets/4548045/6685d3b6-90c4-4553-b58b-d961d07f6813
> [ENHANCEMENT] Add a short account menu with a way to logout

- internal/api/impl/v1/user/endpoint.go
- internal/api/shared/rbac/cache.go
- internal/api/shared/rbac/disabled.go
- internal/api/shared/rbac/rbac.go
- internal/api/shared/toolbox.go
- ui/app/src/App.tsx
- ui/app/src/components/CRUDButton/CRUDButton.tsx
- ui/app/src/components/CRUDButton/CRUDGridActionsCellItem.tsx
- ui/app/src/components/DashboardList/DashboardList.tsx
- ui/app/src/components/DashboardList/RecentDashboardList.tsx
- ui/app/src/components/datasource/DatasourceList.tsx
- ui/app/src/components/rolebindings/RoleBindingList.tsx
- ui/app/src/components/roles/RoleList.tsx
- ui/app/src/components/secret/SecretList.tsx
- ui/app/src/components/variable/VariableList.tsx
- ui/app/src/context/Authorization.tsx
- ui/app/src/model/auth-client.ts
- ui/app/src/model/project-client.ts
- ui/app/src/model/url-builder.ts
- ui/app/src/model/user-client.ts
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/home/HomeView.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/ProjectView.tsx
Add an authorization provider, that can used to check if an user has the permission to a specific action
Example of an user trying to edit the dashboard without permission
> [FEATURE] Add Authorization Provider + User Permission API Endpoint

- .gitignore
- Makefile
> [IGNORE] Fix CI for the release

- ui/app/src/components/CRUDButton/CRUDButton.tsx
- ui/app/src/components/DashboardCard/DashboardCard.tsx
- ui/app/src/components/DashboardList/DashboardList.tsx
- ui/app/src/views/home/HomeView.tsx
- ui/app/src/views/home/ProjectsAndDashboards.tsx
- ui/app/src/views/home/RecentDashboards.tsx
Improve home page responsive with smaller screens + hide delete project button if the user doesn't have the permission
## iPhone 12 (375px * 812px)
include:
> [ENHANCEMENT] UI - Improve home page responsive

- internal/api/core/server.go
- internal/api/impl/auth/auth.go
- internal/api/impl/config/config.go
- internal/api/impl/migrate/migrate.go
- internal/api/impl/v1/dashboard/endpoint.go
- internal/api/impl/v1/datasource/endpoint.go
- internal/api/impl/v1/folder/endpoint.go
- internal/api/impl/v1/globaldatasource/endpoint.go
- internal/api/impl/v1/globalrole/endpoint.go
- internal/api/impl/v1/globalrolebinding/endpoint.go
- internal/api/impl/v1/globalsecret/endpoint.go
- internal/api/impl/v1/globalvariable/endpoint.go
- internal/api/impl/v1/health/endpoint.go
- internal/api/impl/v1/project/endpoint.go
- internal/api/impl/v1/role/endpoint.go
- internal/api/impl/v1/rolebinding/endpoint.go
- internal/api/impl/v1/secret/endpoint.go
- internal/api/impl/v1/user/endpoint.go
- internal/api/impl/v1/variable/endpoint.go
- internal/api/impl/validate/validate.go
- internal/api/shared/route/route.go
I'm just moving our custom route to a dedicated package. Should help for #1637
> [IGNORE] move custom route and endpoint interface to a dedicated package

- schemas/common/proxy/http.cue
- ui/app/src/components/CRUDButton/CRUDButton.tsx
- ui/app/src/components/breadcrumbs/ProjectBreadcrumbs.tsx
- ui/app/src/components/dialogs/CreateDashboardDialog.tsx
- ui/app/src/components/dialogs/CreateProjectDialog.tsx
- ui/app/src/components/dialogs/RenameDashboardDialog.tsx
- ui/app/src/views/MigrateView.tsx
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/admin/AdminView.tsx
- ui/app/src/views/config/ConfigView.tsx
- ui/app/src/views/home/HomeView.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/ProjectView.tsx
- ui/app/src/views/projects/tabs/ProjectDashboards.tsx
Similar to the PR for the home page, this PR will add better mobile support for project and admin views.
For info, the breadcrumb is scroll-able when the project name is long. Tabs are scroll-able too.
:-------------------------:|:-------------------------:
include:
- Does it have loading states? You need to wait for loading to …
> [ENHANCEMENT] UI - Improve project, admin, migrate and config pages responsive

- ui/app/src/components/Header.tsx
- ui/app/src/utils/browser-size.ts
- ui/components/src/Drawer/Drawer.tsx
Fixing drawers width with small screens
|---|---|
| ![image](https://github.com/perses/perses/assets/5657041/0a052b09-4315-4870-89f0-0447ef894522) | ![image](https://github.com/perses/perses/assets/5657041/f0dec6e2-d3b5-469a-919f-09ee857c5a1d) |
| ![image](https://github.com/perses/perses/assets/5657041/cf52ac58-37c5-4d84-b7a4-fdf62838c60b) | ![image](https://github.com/perses/perses/assets/5657041/af8d5160-3ff2-4a60-bd30-6eb978bac46f) |
| ![image](https://github.com/perses/perses/assets/5657041/7ab82c3a-1289-4132-b82f-bc8580cda681) | ![image](https://github.com/perses/perses/assets/5657041/507d5817-fdff-4ed5-8c5b-662a21a64126) |
| ![image](https://github.com/perses/perses/assets/5657041/24797226-ffb8-4dda-8464-8bd902753972) | …
> [ENHANCEMENT] Improve drawers responsive

- internal/cli/cmd/login/login.go
- pkg/client/api/client.go
- pkg/client/fake/api/client.go
when auth is not activated, it shouldn't ask for the login and password in the prompt
> [BUGFIX] Fix the login cmd when the auth is not activated

- pkg/model/api/v1/utils/default.go
Currently for the default role, the creation date is not set. This PR is fixing that
> [BUGFIX] Fix creation date of the default role created for a new project

- README.md
> [DOC] Rephrase some parts of the main README

- docs/user-guides/installing-perses-from-source.md
Docs update to add installing perses from source section.
include:
> [DOC] Docs update to add installing perses from source section.

- docs/user-guides/configuration.md
- docs/user-guides/provisioning.md
I'm adding a little doc about the provisioning. Perhaps it will help a bit to understand what is this feature and how to activate it.
> [DOC] Add a doc about the provisioning

- .github/workflows/ci.yaml
> bump actions/download and actions/upload from 3 to 4

- internal/api/impl/proxy/proxy.go
- internal/api/shared/error.go
when we move the proxy to a list of endpoint with https://github.com/perses/perses/pull/1644, it appears the final error created when contacting the datasource is hidden by the middleware [HandleError](https://github.com/perses/perses/blob/main/internal/api/core/middleware/error.go).
This PR intends to be transparent about what the datasource is returning. It might fix https://github.com/perses/perses/issues/1537.
As an example, I have a created a dummy instance, and it returns the accurate error:
> [BUGFIX] Fix the error generated  when datasource is contacted

- internal/api/impl/auth/auth.go
> [BUGFIX] OAuth/OIDC get redirect_uri from request considering X-Forwarded-* headers + guess scheme from request.TLS

- .github/workflows/ci.yaml
- .github/workflows/delete-snapshot.yml
- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/react.yml
- cue/model/api/v1/public_user_go_gen.cue
- cue/model/api/v1/user_go_gen.cue
should help to simplify a bit the github actions modifition in #1699
> bump perses github actions to v0.3.2

- docs/tooling/cli.md
> [DOC] Reference DaC doc in CLI doc

- ui/app/package.json
- ui/app/src/model/config-client.ts
- ui/app/src/views/auth/SignWrapper.tsx
- ui/package-lock.json
> [ENHANCEMENT] Sign in with branded button for external auth provider

- docs/design-docs/authentication.md
This PR introduce only a design documentation. This is not yet implemented but this is how I plan to do it. 
Not a big deal if it changes while I implement, I will modify.
I'm doing this to not forget my idea as the implementation might come in several weeks due to personal business.
> Note that this PR is also improving the Authorization Code flow merging both previous diagrams in one, and improving a bit the readability
include:
- …
> [DOC] Design Device code authentication flow

- ui/panels-plugin/src/plugins/scatterplot/scatter-chart-model.ts
**TLDR;** Fix incorrect initial scatter chart options. This fixes the JSON to correctly adhere to the schemas set in `scatter.cue`.   </br>
Scatter chart options allow users to manipulate settings and formatting on a chart. No additional options are available yet for the scatter chart panel. Some scaffolding has been done to allow scatter chart formatting options in the future. 
**Before** 
_Figure 1._ Incorrect JSON. `spec.query:{...}` should be removed. 
**After** 
_Figure 2._ Correct JSON, which matches schema set in scatter.cue -- removes `spec.query:{...}`. 
and …
> [BUGFIX] Fix initial scatter chart options

- docs/user-guides/dashboard-as-code.md
- go-sdk/exec.go
- internal/cli/cmd/dac/build/build.go
- internal/cli/cmd/dac/build/build_test.go
- internal/cli/cmd/dac/build/testdata_go/go.mod
- internal/cli/cmd/dac/build/testdata_go/main.go
Add Golang SDK support for command: `percli dac build`
> [FEATURE] Add Golang SDK support for `percli dac build`

- ui/app/src/context/Authorization.tsx
- ui/app/src/views/home/HomeView.tsx
Improve project suggestion when creating dashboard. To only show projects where the user has the permission to create a dashboard 😄 
> [ENHANCEMENT] Improve project suggestion when creating dashboard

- docs/user-guides/configuration.md
- internal/api/core/core.go
- pkg/model/api/config/config.go
- pkg/model/api/config/config_test.go
that's a mitigation to solve https://github.com/perses/perses/issues/1556
> [FEATURE] By config, Perses can stop to serve the UI

- docs/dac/cue/README.md
- docs/dac/cue/dashboard.md
- docs/dac/cue/panel-groups.md
- docs/dac/cue/prometheus/panel.md
- docs/dac/cue/prometheus/variables.md
- docs/user-guides/dashboard-as-code.md
rendered version: https://github.com/perses/perses/tree/antoinethebaud/doc-cue-sdk/docs/dac/cue
> [DOC] Add DaC CUE SDK documentation

- ui/app/src/components/datasource/DatasourceDrawer.tsx
- ui/app/src/components/drawer.tsx
- ui/app/src/components/rolebindings/RoleBindingDrawer.tsx
- ui/app/src/components/roles/RoleDrawer.tsx
- ui/app/src/components/secrets/SecretDrawer.tsx
- ui/app/src/components/variable/VariableDrawer.tsx
- ui/core/src/model/datasource.ts
- ui/dashboards/src/components/Datasources/DatasourceEditor.tsx
- ui/dashboards/src/context/DatasourceStoreProvider.tsx
- ui/plugin-system/src/components/DatasourceEditorForm/DatasourceEditorForm.tsx
> [IGNORE] Reduce duplication in resources drawers code

- ui/app/src/components/DashboardList/DashboardList.tsx
- ui/app/src/components/EphemeralDashboardList/EphemeralDashboardList.tsx
- ui/app/src/components/datasource/DatasourceList.tsx
- ui/app/src/components/list.tsx
- ui/app/src/components/rolebindings/RoleBindingList.tsx
- ui/app/src/components/roles/RoleList.tsx
- ui/app/src/components/secrets/SecretList.tsx
- ui/app/src/components/variable/VariableList.tsx
> [IGNORE] Reduce duplication in resources lists code

- docs/dac/cue/README.md
- docs/dac/cue/panel-groups.md
> [DOC] Add some more tips & tricks to the CUE SDK doc

- cue/dac-utils/prometheus/panel/panel.cue
> [IGNORE] DaC CUE SDK: remove useless leftover param

- ui/app/src/components/DashboardList/DashboardList.tsx
- ui/app/src/components/dialogs/CreateDashboardDialog.tsx
- ui/app/src/validation/ephemeraldashboard.ts
- ui/app/src/views/projects/dashboards/CreateEphemeralDashboardView.tsx
https://github.com/perses/perses/assets/7058693/7d8ef27f-e276-46da-be95-b3845a45960c
include:
> [FEATURE] Allow creating ephemeral copies of regular dashboards

- internal/api/impl/auth/auth.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- internal/api/provisioning/provisioning.go
- internal/api/utils/utils.go
- internal/cli/cmd/login/login.go
- pkg/client/api/auth.go
- pkg/model/api/config/authentication.go
Implementation of the device auth flow according to the [specs](https://github.com/perses/perses/blob/main/docs/design-docs/authentication.md#-login-from-external-oidc-or-oauth20-provider-through-percli-command-line) .
After this PR we can sign in with an external provider through percli
> [FEATURE] Device code authentication flow through CLI

- docs/design-docs/authentication.md
- docs/user-guides/configuration.md
> [DOC] Device code authentication flow

- docs/design-docs/authentication.md
> [DOC] Client Credentials authentication flow 

- internal/api/core/server.go
- internal/api/interface/error.go
- internal/api/route/route.go
This PR is adding the support of middleware on any custom Perses route or group.
That should help to factorise a bit the code from the pr #1837
> [ignore] Support middleware in the custom perses routes

- cue/dac-utils/prometheus/filter/filter.cue
- cue/dac-utils/prometheus/variable/labelnames/labelnames.cue
- cue/dac-utils/prometheus/variable/labelvalues/labelvalues.cue
- cue/dac-utils/prometheus/variable/promql/promql.cue
> [IGNORE] CUE DaC SDK: reduce code duplication in filter-related logic

- internal/api/migrate/mapping.cuepart
- internal/api/migrate/testdata/old_grafana_panels_perses_dashboard.json
- internal/api/migrate/testdata/old_grafana_query_perses_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
> [ENHANCEMENT] Grafana migrate: support capturing regexp in migration

- internal/api/impl/v1/globalvariable/service.go
- internal/api/impl/v1/variable/service.go
- internal/api/schemas/schemas.go
- internal/api/validate/validate.go
- pkg/model/api/v1/dashboard/variable.go
- pkg/model/api/v1/dashboard/variable_test.go
- pkg/model/api/v1/dashboard_test.go
- pkg/model/api/v1/variable.go
- pkg/model/api/v1/variable/datasource.go
- pkg/model/api/v1/variable/variable.go
Ref issue https://github.com/perses/perses/issues/1514.
> [FEATURE] Support new DatasourceVariable on backend side

- ROADMAP.md
Please share if you see something missing in this highlevel roadmap
> [ignore] add roadmap

- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.tsx
- ui/panels-plugin/src/plugins/scatterplot/Scatterplot.tsx
Update scatterplot to remove the ';' character that is being rendered in ScatterChartPanel.tsx. 
Update Scatterplot.tsx add eChart imports for DatasetComponent, DataZoomComponent, and LegendComponent.
N/A
include:
> [BUGFIX] Fix scatterplot to include missing imports and remove the ';' character that was accidentally rendered.

- dev/config-mariadb.yaml
- dev/config.yaml
- scripts/api_backend_dev.sh
- ui/app/src/components/DashboardList/RecentDashboardList.tsx
- ui/app/src/context/Config.tsx
- ui/app/src/model/config-client.ts
- ui/app/src/model/dashboard-client.ts
- ui/app/src/views/home/HomeView.tsx
- ui/app/src/views/home/ImportantDashboards.tsx
- ui/app/src/views/home/InformationSection.tsx
- ui/app/src/views/home/ProjectsAndDashboards.tsx
- ui/app/src/views/home/RecentDashboards.tsx
- ui/app/src/views/projects/RecentlyViewedDashboards.tsx
- ui/e2e/src/pages/AppHomePage.ts
- ui/e2e/src/pages/AppProjectPage.ts
Make some change to home page:
- Important dashboard are now showed at the top in mosaic display
- Information section has been moved on top right of the screen
include:
> [ENCHANCEMENT] Improve Home page layout

- docs/user-guides/configuration.md
- docs/user-guides/oauth-configuration-helpers.md
Bootstraping a documentation page following a discussion with @Nexucis on the complexity around oauth external provider configuration.
include:
> [DOC] Add helper for writing authentication provider config

- docs/user-guides/configuration.md
> [DOC] Add message about device_auth_url

- internal/cli/cmd/login/login.go
> [BUGFIX] Fix providers selection in percli

- ui/app/src/model/auth-client.ts
Only decode JWT token if the token is set
> [ENHANCEMENT] Only decode JWT token if provided

- docs/dac/cue/README.md
- docs/dac/go/README.md
- docs/dac/go/panel-group.md
> [DOC] Go SDK add entrypoint README

- ui/.eslintrc.base.js
- ui/app/src/components/DashboardCard/DashboardCard.tsx
- ui/app/src/components/Footer.tsx
- ui/app/src/components/Header.tsx
- ui/app/src/components/breadcrumbs/breadcrumbs.tsx
- ui/app/src/components/rolebindings/RoleBindingEditorForm.tsx
- ui/app/src/components/roles/RoleEditorForm.tsx
- ui/app/src/views/admin/AdminView.tsx
- ui/app/src/views/auth/SignWrapper.tsx
- ui/app/src/views/config/ConfigView.tsx
- ui/app/src/views/home/HomeView.tsx
- ui/app/src/views/home/ImportantDashboards.tsx
- ui/app/src/views/import/GrafanaFlow.tsx
- ui/app/src/views/import/PersesFlow.tsx
- ui/app/src/views/projects/explore/ExploreView.tsx
- ui/components/src/ColorPicker/ColorPicker.tsx
- ui/components/src/ThresholdsEditor/ThresholdsEditor.tsx
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/GridLayout/GridLayout.tsx
- ui/dashboards/src/components/Panel/Panel.stories.tsx
- ui/panels-plugin/src/plugins/time-series-chart/VisualOptionsEditor.tsx
- ui/plugin-system/src/components/ProjectSelect.tsx
Adding eslint rule for removing useless curly braces for props where it's only containing a hardcoded string
include:
> [IGNORE] eslint: Disable curly braces if text only

- ui/app/src/model/project-client.ts
Fixing issue when creating a project, you didn't have permission on the UI without doing F5.
> [BUGFIX] Fix no project permission after creating project

- ui/app/src/views/home/ProjectsAndDashboards.tsx
Small fix on the accordion of the home page
## After
include:
> [ENHANCEMENT] Improve project accordion display with lot of projects

- cue/model/api/v1/dashboard_go_gen.cue
- pkg/model/api/v1/dashboard.go
- ui/core/src/model/panels.ts
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelLinks.tsx
- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/dashboards/src/components/PanelDrawer/usePanelEditor.tsx
Following @AntoineThebaud comments on PR #1916, moving links to spec. And remove icon from menu items.
include:
> [BREAKINGCHANGE] Move links from panel display to panel spec

- internal/api/core/core.go
Reactivating the cron that reloads the schemas. Read the comment in the code for more info
> [BREAKINGCHANGE] Reactivate the cron task that reloads the schemas

- go-sdk/link/link.go
- go-sdk/link/options.go
> [FEATURE] Add panel links to Go SDK

- docs/prologue/introduction.md
Fix broken link to the contributing guide in the introduction page.
[joke] Given that I contribute a very critical change in Perses, I guess I deserve my name in the MAINTAINERS file no ? :p [/joke]
> [DOC] Fix broken link to the contributing guide in the introduction page

- ui/explore/src/components/ExploreManager/ExploreManager.tsx
- ui/explore/src/components/ExploreManager/ExplorerManagerProvider.tsx
- ui/explore/src/components/ExploreManager/ExplorerManagerProviderWithQueryParams.tsx
- ui/explore/src/components/ExploreManager/MetricsExplorer.tsx
- ui/explore/src/components/ExploreManager/TracesExplorer.tsx
- ui/explore/src/views/ViewExplore/ViewExploreApp.tsx
Explorer is sharable! When you edit something it will automatically update query params in the url 😄 
include:
> [FEATURE] Explorer is sharable

- docs/user-guides/configuration.md
I missed it when I created the frontend config in https://github.com/perses/perses/pull/1971
> [DOC] Update doc about new frontend configuration

- ui/.eslintrc.base.js
- ui/app/src/components/dialogs/CreateDashboardDialog.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/explore/ProjectExploreView.tsx
- ui/components/src/BarChart/BarChart.tsx
- ui/components/src/Table/VirtualizedTable.tsx
- ui/components/src/TimeSeriesTooltip/nearby-series.ts
- ui/components/src/utils/chart-actions.ts
- ui/core/src/model/units/throughput.ts
- ui/core/src/model/units/units.ts
- ui/dashboards/src/components/DeletePanelGroupDialog/DeletePanelGroupDialog.tsx
- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/plugin-system/src/runtime/TimeRangeProvider/query-params.ts
- ui/prometheus-plugin/src/plugins/PrometheusDatasourceEditor.tsx
> [IGNORE] add eslint rule to enforce triple-equality when applicable

- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
Scrollbar should not be present when looking at a panel in view mode
include:
> [BUGFIX] Scrollbar should not be present in panel view mode

- ui/components/src/GaugeChart/GaugeChart.tsx
Use opacity to have gauge empty part more compatible with current theme. Close #2011
include:
> [ENHANCEMENT] Make gauge chart background color close to theme color

- internal/cli/cmd/dac/build/testdata/go/go.mod
> [IGNORE] Upgrade Go version in go.mod tests

- docs/api/dashboard.md
- docs/api/datasource.md
- docs/api/role.md
- docs/api/rolebinding.md
- docs/api/secret.md
- docs/api/user.md
- docs/api/variable.md
- docs/design-docs/authentication.md
- docs/plugin/panel.md
- docs/plugin/prometheus.md
- docs/user-guides/configuration.md
- docs/user-guides/oauth-configuration-helpers.md
> [DOC] Fix wrong indentations in yaml samples

- go-sdk/dashboard/dashboard_test.go
- internal/test/dac/expected_output.json
- internal/test/dac/input.cue
Most probably a common pattern that DaC users may be interested to reproduce. IMHO not worth making builtin libs/builders for this, as it's easy to put in place and more opened to personal preference this way.
We might think to document this pattern in a "tips & tricks" section of the user doc later.
\+ cleanup some deprecated stuff in CUE DaC example file.
> [ENHANCEMENT] DaC SDKs: showcase custom configurable grouping capabilities in example files

- ui/app/src/model/project-client.ts
@Nexucis you slightly triggered my curiosity today with this issue. So now it's fixed. In home we load only once the dashboards. 
The issue was that loading projects with dashboards, we were not using ``useDashboardList`` but ``getDashboards``.
I still trust the cache mechanism of tanstack/query haha
include:
- Does it have loading states? You need …
> [BUGFIX] Load only once dashboards in home page

- ui/dashboards/src/components/SaveChangesConfirmationDialog/SaveChangesConfirmationDialog.tsx
- ui/dashboards/src/components/SaveDashboardButton/SaveDashboardButton.tsx
- ui/dashboards/src/components/Variables/EditVariablesButton.tsx
- ui/dashboards/src/components/Variables/Variable.tsx
- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/dashboards/src/context/VariableProvider/VariableProvider.tsx
- ui/dashboards/src/context/VariableProvider/hydrationUtils.test.ts
- ui/dashboards/src/context/VariableProvider/hydrationUtils.ts
- ui/dashboards/src/context/useDashboard.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
Mostly backport of some work done by @celian-garcia as part of https://github.com/perses/perses/pull/1876.
This PR is a kind of part 2 of https://github.com/perses/perses/pull/2080.
include:
> [IGNORE] Variable provider: some renames and dev documentation

- ui/app/package.json
- ui/components/package.json
- ui/dashboards/package.json
- ui/dashboards/src/components/Variables/Variable.tsx
- ui/explore/package.json
- ui/package-lock.json
- ui/panels-plugin/package.json
- ui/plugin-system/package.json
- ui/storybook/package.json
Autocomplete is fixed by MUI new versions + fix autocomplete input min height to be back to 38px
include:
> [BUGFIX] Autocomplete shouldn't resize when hovering + fix autocomplete min height

- ui/app/src/components/Header/SearchBar/SearchBar.tsx
Display the scroll bar only when necessary when searching resources
include:
> [ENHANCEMENT] Show scrollbar when necessary in search results

- internal/cli/cmd/dac/build/testdata/go/go.mod
- ui/app/package.json
- ui/app/src/components/Header/SearchBar/SearchList.tsx
- ui/package-lock.json
This PR is bumping the dependency `@nexucis/kvsearch` to the last version to be able to exclude the space during the search in the search bar.
Like that we are now able to perform a search with multi word.
> [ENHANCEMENT] Configure the search bar to support multi world searching

- internal/api/toolbox/list.go
Depending on the code path, the List endpoint may return a Base64 string.
For example, a Project, Dashboard from a user who specified empty `security.authorization.guest_permissions` in the configuration file and assigned the ProjectRole will return invalid JSON.
include:
> [BUGFIX] fix issue where Base64 string is returned in List endpoint

- cue/schemas/panels/table/migrate.cue
- internal/api/migrate/migrate_test.go
- internal/api/migrate/testdata/simple_grafana_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
Complexify the migration logic to generate a single column settings item for a given column, as even though defining multiple column settings for the same column is valid model-wise, only the first one is going to be taken into account ([ref](https://github.com/perses/perses/blob/650166141c5d2dbc4ad94897074151fa9d083304/ui/panels-plugin/src/plugins/table/TablePanel.tsx#L22)).
Also took the opportunity of this change to cover the Table panel in the migration unit tests.
> [ENHANCEMENT] Improve migration logic for the `Table` panel

- cue/schemas/panels/table/migrate.cue
- internal/api/migrate/testdata/old_grafana_panels_grafana_dashboard.json
- internal/api/migrate/testdata/old_grafana_panels_perses_dashboard.json
> [ENHANCEMENT] Support migration of grafana's legacy `table-old` panel into Perses `Table`

- cue/schemas/common/format.cue
- go-sdk/common/format.go
- internal/api/migrate/mapping.cuepart
- ui/core/src/model/units/throughput.ts
Add bits/sec format (common units used in networking)
include:
> [ENHANCEMENT] Add bits/sec format (common units used in networking)

- cue/schemas/panels/markdown/migrate.cue
- dev/config.yaml
- dev/data/9-dashboard.json
- docs/api/README.md
- docs/plugin/panel.md
- internal/api/migrate/migrate.go
- internal/api/migrate/testdata/library_panel_perses_dashboard.json
- scripts/plugin/install_plugins.sh
- ui/e2e/src/pages/DashboardPage.ts
- ui/panels-plugin/plugin.json
- ui/panels-plugin/src/plugins/markdown/MarkdownChart.ts
- ui/panels-plugin/src/plugins/markdown/index.ts
- ui/panels-plugin/src/plugins/markdown/markdown-panel-model.ts
> Fix markdown plugin

- cue/schemas/panels/time-series/migrate.cue
- internal/api/migrate/testdata/simple_grafana_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
Migrate max/min from grafana timeseries panels. 
none
> [ENHANCEMENT] TimeSeries chart: Migrate max/min from grafana

- ui/app/src/model/route.test.ts
- ui/app/src/model/route.ts
fix https://github.com/perses/perses/issues/2176
> [BUGFIX] Fix automatic detection of the API prefix in the UI

- internal/api/impl/proxy/proxy.go
> [BUGFIX] Fix issue causing panic in DataSource proxy

- ui/panels-plugin/src/plugins/scatterplot/ScatterChart.ts
- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.test.tsx
- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.tsx
- ui/panels-plugin/src/plugins/scatterplot/Scatterplot.tsx
ScatterPlot: setup onClick handler and link to the Gantt chart on the explore page by default
include:
> [ENHANCEMENT] ScatterPlot: setup onClick handler and link to explore page by default

- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.tsx
ScatterPlot: do not use useNavigate() hook in panel because downstream products, which embed this panel, may not have a compatible version of react-router installed.
no screenshots
- [X ] All commits have [DCO signoffs](https://github.com/probot/dco#how-it-works).
include:
> [IGNORE] ScatterPlot: do not use useNavigate() hook in panel

- cue/schemas/panels/trace-table/trace-table.cue
- ui/panels-plugin/src/plugins/trace-table/DataTable.tsx
- ui/panels-plugin/src/plugins/trace-table/TraceTable.ts
- ui/panels-plugin/src/plugins/trace-table/TraceTablePanel.test.tsx
- ui/panels-plugin/src/plugins/trace-table/TraceTablePanel.tsx
- ui/panels-plugin/src/plugins/trace-table/trace-table-model.ts
TraceTablePanel: support categorical color palette
Similar to #2194
include:
> [ENHANCEMENT] TraceTablePanel: support categorical color palette

- README.md
part of https://github.com/cncf/toc/issues/1411 tasks
> add openssf badges

- docs/user-guides/dashboard-as-code.md
- internal/cli/cmd/dac/setup/setup.go
Closes https://github.com/perses/perses/issues/2181.
> [DOC] Put an accurate example for `percli dac setup` command

- ui/package-lock.json
- ui/tempo-plugin/package.json
- ui/tempo-plugin/src/components/TraceQLEditor.tsx
- ui/tempo-plugin/src/components/TraceQLExtension.ts
- ui/tempo-plugin/src/components/highlight.ts
- ui/tempo-plugin/src/components/index.ts
- ui/tempo-plugin/src/plugins/tempo-trace-query/DashboardTempoTraceQueryEditor.tsx
TraceQL query editor: add syntax highlighting with Lezer
include:
> [ENHANCEMENT] TraceQL query editor: add syntax highlighting with Lezer

- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/GanttTable.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/GanttTableRow.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/TracingGanttChart.tsx
Mark the current selected row by applying a different background color.
include:
> [ENHANCEMENT] TracingGanttChart: indicate selected row

- MAINTAINERS.md
Thank you @andreasgerstmayr for joining the Perses maintainers 🙏! 
Hope you will enjoy it for a couple of times !
Cheers !
> add @andreasgerstmayr as maintainer

- ui/panels-plugin/src/plugins/trace-table/DataTable.tsx
TraceTable: improve readability of service name chips
Before:
After:
include:
> [ENHANCEMENT] TraceTable: improve readability of service name chips

- internal/cli/cmd/dac/setup/cue.go
- internal/cli/cmd/dac/setup/setup.go
- internal/cli/cmd/dac/setup/setup_test.go
fix https://github.com/perses/perses/issues/2247
> [BUGFIX] Fix dac cue setup and upgrade min version

- ui/core/src/schema/panel.ts
> [BUGFIX] Panel name must be provided

- ui/package-lock.json
- ui/panels-plugin/package.json
- ui/panels-plugin/src/plugins/trace-table/DataTable.tsx
- ui/panels-plugin/src/plugins/trace-table/TraceTablePanel.test.tsx
TraceTable: switch to Material UI DataGrid to enable common table functionality like sorting and resizing of columns.
include:
> [ENHANCEMENT] TraceTable: use MUI DataGrid to support sorting

- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/DetailPane/Attributes.tsx
TracingGanttChart: sort span attributes alphabetically
include:
> [ENHANCEMENT] TracingGanttChart: sort span attributes alphabetically

- docs/user-guides/embedding-panels.md
This updates the docs on embedding panels using the latest interfaces from `@perses-dev/core`.
It also formats the code markdown section using the [default prettier settings](https://github.com/perses/perses/blob/main/ui/.prettierrc.json).
> [DOC] Use latest interfaces in docs

- docs/tooling/cli.md
> [DOC] Add links in the CLI doc

- cue/dac-utils/prometheus/variable/labelnames/labelnames.cue
- cue/dac-utils/prometheus/variable/labelvalues/labelvalues.cue
- cue/dac-utils/prometheus/variable/promql/promql.cue
- cue/dac-utils/prometheus/variable/variable.cue
- cue/dac-utils/variable/list/list.cue
> [IGNORE] DaC CUE SDK: refactor/simplify dac-utils code for variables

- docs/dac/go/variable.md
> [DOC] DaC Go SDK: add missing doc for Static list var

- cue/dac-utils/variable/group/group.cue
- cue/dac-utils/variable/list/list.cue
- cue/dac-utils/variable/staticlist/staticlist.cue
- cue/dac-utils/variable/text/text.cue
- cue/schemas/variables/static-list/static-list.cue
- internal/test/dac/dac_cue_test.go
This removes some constraints repetition.
Also added some comments in the cue lib & more detailed error output in unit tests.
> [IGNORE] DaC CUE SDK: avoid declaring constraints already defined

- cue/schemas/queries/prometheus/query.cue
> [BUGFIX] Prevent saving empty PromQL strings

- docs/user-guides/configuration.md
- pkg/client/config/config.go
use TLS config when configuring the oauth client in `pkg/client`
> [ENHANCEMENT] Use TLS config in oauth client config

- cue/schemas/panels/gauge/migrate.cue
- cue/schemas/panels/stat/migrate.cue
- cue/schemas/queries/prometheus/query.cue
- docs/user-guides/configuration.md
- internal/api/impl/auth/auth.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- internal/api/migrate/mapping.cuepart
- internal/api/migrate/migrate_test.go
- internal/api/migrate/testdata/stat_calc_undefined_grafana_dashboard.json
- internal/api/migrate/testdata/stat_calc_undefined_perses_dashboard.json
- pkg/client/config/config.go
- pkg/client/perseshttp/client.go
- pkg/model/api/config/authentication.go
cherry pick some bugfixes and required enhancement for oauth
> Release update from main

- docs/prologue/introduction.md
In this PR, 
The contact information of the project team has been updated. 
include:
> [DOC] Update Contact information

- docs/user-guides/dashboard-as-code.md
- internal/cli/cmd/dac/build/build.go
- internal/cli/cmd/dac/diff/diff.go
- internal/cli/cmd/dac/preview/preview.go
- internal/cli/cmd/dac/setup/setup.go
> [DOC] better wording for `percli dac`'s commands helpers

- ui/prometheus-plugin/src/model/prometheus-client.ts
> [BUGFIX] Add http headers for GET requests of prometheus client

- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/DetailPane/Attributes.tsx
TracingGanttChart: print `<empty string>` if a string value is empty. Previously there was a blank space, which looked like an UI bug.
include:
> [ENHANCEMENT] TracingGanttChart: print '<empty string>' if value is empty

- dev/data/6-project.json
- internal/api/database/file/file.go
> [BUGFIX] support YAML extension in database configuration

- cue/schemas/panels/gauge/migrate.cue
- cue/schemas/panels/markdown/migrate.cue
- cue/schemas/panels/stat/migrate.cue
- cue/schemas/panels/table/migrate.cue
- cue/schemas/panels/time-series/migrate.cue
- cue/schemas/queries/prometheus/migrate.cue
- cue/schemas/variables/prometheus-label-values/migrate.cue
- cue/schemas/variables/prometheus-promql/migrate.cue
- cue/schemas/variables/static-list/migrate.cue
- internal/cli/cmd/dac/build/build_test.go
> [IGNORE] format migration files + fix test failing on windows

- ui/tempo-plugin/src/index.ts
- ui/tempo-plugin/src/model/index.ts
tempo-plugin: export all models (including TempoTraceQuerySpec)
no UI changes
include:
> [ENHANCEMENT] tempo-plugin: export all models (including TempoTraceQuerySpec)

- cue/schemas/panels/bar/migrate.cue
- cue/schemas/panels/gauge/migrate.cue
- cue/schemas/panels/stat/migrate.cue
- cue/schemas/panels/time-series/migrate.cue
- internal/api/migrate/migrate_test.go
- internal/api/migrate/testdata/barchart_grafana_dashboard.json
- internal/api/migrate/testdata/barchart_perses_dashboard.json
- internal/api/migrate/testdata/simple_grafana_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
This adds bargauge->barchart migration and decimal places migration.
> [ENHANCEMENT] Add decimal migrations; Add barchart migration

- docs/user-guides/dashboard-as-code.md
Fix links raising warnings when used from the mkdoc-generated website.
> [IGNORE] Fix links broken in website

- docs/user-guides/dashboard-as-code.md
> [IGNORE] small fix in DaC doc

- ui/components/package.json
- ui/components/src/DragAndDrop/DragAndDropList.tsx
- ui/components/src/DragAndDrop/DragButton.tsx
- ui/components/src/DragAndDrop/DropIndicator.tsx
- ui/components/src/DragAndDrop/index.ts
- ui/components/src/DragAndDrop/model.ts
- ui/components/src/index.ts
- ui/package-lock.json
- ui/panels-plugin/package.json
- ui/panels-plugin/src/plugins/table/CellsEditor/CellsEditor.tsx
- ui/panels-plugin/src/plugins/table/ColumnsEditor/ColumnEditorContainer.tsx
- ui/panels-plugin/src/plugins/table/ColumnsEditor/ColumnsEditor.tsx
- ui/panels-plugin/src/plugins/table/TableColumnsEditor.test.tsx
- ui/panels-plugin/src/plugins/table/TablePanel.tsx
Allow user to reorder columns in the table panel. It's based on the index of the column settings. If a column doesn't have a column setting, it will be use default ordering afters columns with columns settings. Closes #2353
Drag and drop support:
include:
> [FEATURE] Table panel: columns can be reordered

- internal/api/impl/v1/globalrolebinding/service.go
- internal/api/impl/v1/rolebinding/service.go
- internal/api/rbac/utils.go
fix https://github.com/perses/perses/issues/2428
fix https://github.com/perses/perses/issues/2270
> [ENHANCEMENT] RoleBinding prechecking if user and role exist has been removed

- cue/schemas/panels/bar/migrate.cue
- cue/schemas/panels/gauge/migrate.cue
- cue/schemas/panels/markdown/migrate.cue
- cue/schemas/panels/stat/migrate.cue
- cue/schemas/panels/table/migrate.cue
- cue/schemas/panels/time-series/migrate.cue
- cue/schemas/queries/prometheus/migrate.cue
- internal/api/migrate/testdata/old_grafana_panels_perses_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
\+ some refactoring in most migration files to simplify the code
> [BUGFIX] TimeSeriesChart: fix migration for the format attribute

- pkg/model/api/config/frontend.go
Enhance validation annotations for TimeRange and Frontend structures to ensure correct data types and formats.
Follow up for https://github.com/perses/perses/pull/2433. 
cc: @jgbernalp
> [ENHANCEMENT] Update kubebuilder validation

- ui/components/package.json
- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/Table/VirtualizedTable.tsx
- ui/explore/package.json
- ui/package-lock.json
- ui/panels-plugin/src/plugins/pie-chart/PieChartPanel.tsx
> [IGNORE] Upgrade react-table and react-virtuoso + remove some sx prop leaks

- ui/core/.eslintrc.js
- ui/core/src/model/calculations.ts
- ui/core/src/model/legend.ts
- ui/core/src/model/time.ts
- ui/core/src/model/units/bytes.ts
- ui/core/src/model/units/utils.ts
- ui/core/src/model/variables.ts
- ui/core/src/utils/fetch.ts
- ui/core/src/utils/is-empty-object.ts
- ui/core/src/utils/memo.ts
- ui/core/src/utils/panel-refs.ts
- ui/core/src/utils/time-series-data.ts
- ui/core/src/utils/transform-data.ts
> [IGNORE] Add function type check on core package

- ui/components/src/Table/index.ts
- ui/panels-plugin/src/plugins/table/TablePanel.tsx
Looks like I forgot to implem the sorting logic when a column is sortable...
include:
> [ENHANCEMENT] Table: add column sorting

- cue/schemas/panels/pie/migrate.cue
- internal/api/migrate/migrate_test.go
- internal/api/migrate/testdata/piechart_grafana_dashboard.json
- internal/api/migrate/testdata/piechart_perses_dashboard.json
Add simple piechart migration. Resolves #2315 .
> [ENHANCEMENT] Add piechart migration

- ui/plugin-system/src/components/PanelSpecEditor/PanelSpecEditor.tsx
Validation was not happy because I forgot to parse data to object 😓 
Know issue: metadata fields are not updated, need to check why...
Initial:
Title changed:
> [BUGFIX] Fix Panel JSON tab validation

- internal/cli/cmd/dac/preview/preview.go
fix https://github.com/perses/perses/issues/2457
> [ENHANCEMENT] Prefix dashboard display name when using dac preview command

- internal/cli/cmd/dac/diff/diff.go
After talking with @Syldinn about the diff command in the CLI, it appears it would be nice to return a success message saying the command write a diff file.
> [ENHANCEMENT] CLI/DAC: return a success message after writing a diff files

- cue/schemas/panels/stat/migrate.cue
- internal/api/migrate/testdata/simple_perses_dashboard.json
- internal/api/migrate/testdata/stat_calc_undefined_perses_dashboard.json
Adds sparkline migration to StatChart.
> [ENHANCEMENT] Add sparkline migration

- ui/app/src/components/Header/SearchBar/SearchBar.tsx
- ui/explore/package.json
- ui/explore/src/components/PrometheusMetricsFinder/PrometheusMetricsFinder.tsx
- ui/explore/src/components/PrometheusMetricsFinder/display/list/MetricList.tsx
- ui/explore/src/components/PrometheusMetricsFinder/overview/MetricOverview.tsx
- ui/explore/src/components/PrometheusMetricsFinder/types.ts
- ui/package-lock.json
Add a new search bar for filtering metric names in the metric finder using fuzzy search.
Add new setting for hiding time series chart, can be useful if there are too much timeseries
Hide "Similar metrics" tab if there is no filters.
> [ENHANCEMENT] Add search in metric finder + new option for hiding panel

- cue/schemas/panels/table/migrate.cue
- internal/api/migrate/migrate_test.go
- internal/api/migrate/testdata/simple_grafana_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
- internal/api/migrate/testdata/tables_perses_dashboard.json
Add support to "Organize" transformation to table panel + reduce column settings replicas
> [ENHANCEMENT] Table panel: migrate custom column ordering via "organize" transformation

- .mdox.validate.yaml
GitHub IPs from GitHub actions are probably flagged as spam/noise in a lot of firewalls...
> [IGNORE] Ignore more flaky links checks

- docs/tooling/cli.md
> [DOC] Adjustments in CLI doc

- ui/explore/.eslintrc.js
- ui/explore/src/components/ExploreManager/ExploreManager.tsx
- ui/explore/src/components/ExploreManager/ExplorerManagerProvider.tsx
- ui/explore/src/components/ExploreManager/ExplorerManagerProviderWithQueryParams.tsx
- ui/explore/src/components/ExploreManager/MetricsExplorer.tsx
- ui/explore/src/components/ExploreManager/TracesExplorer.tsx
- ui/explore/src/components/ExploreToolbar/ExploreToolbar.tsx
- ui/explore/src/components/PrometheusMetricsFinder/PrometheusMetricsFinder.tsx
- ui/explore/src/components/PrometheusMetricsFinder/display/MetricChip.tsx
- ui/explore/src/components/PrometheusMetricsFinder/display/list/MetricList.test.tsx
- ui/explore/src/components/PrometheusMetricsFinder/display/list/MetricList.tsx
- ui/explore/src/components/PrometheusMetricsFinder/filter/FilterInputs.test.tsx
- ui/explore/src/components/PrometheusMetricsFinder/filter/FilterInputs.tsx
- ui/explore/src/components/PrometheusMetricsFinder/filter/FinderFilters.tsx
- ui/explore/src/components/PrometheusMetricsFinder/overview/MetricOverview.tsx
- ui/explore/src/components/PrometheusMetricsFinder/overview/tabs/JobTab.tsx
- ui/explore/src/components/PrometheusMetricsFinder/overview/tabs/OverviewTab.tsx
- ui/explore/src/components/PrometheusMetricsFinder/overview/tabs/SimilarTab.tsx
- ui/explore/src/components/PrometheusMetricsFinder/utils.ts
- ui/explore/src/views/ViewExplore/ViewExplore.tsx
- ui/explore/src/views/ViewExplore/ViewExploreApp.tsx
https://github.com/perses/perses/issues/2444 enforce type for explore package
> [IGNORE] Enforce typing for explore package

- ui/tempo-plugin/.eslintrc.js
- ui/tempo-plugin/src/components/TraceQLEditor.tsx
- ui/tempo-plugin/src/components/TraceQLExtension.ts
- ui/tempo-plugin/src/components/complete.ts
- ui/tempo-plugin/src/model/tempo-client.ts
- ui/tempo-plugin/src/model/tempo-selectors.ts
- ui/tempo-plugin/src/plugins/tempo-trace-query/TempoTraceQuery.ts
- ui/tempo-plugin/src/plugins/tempo-trace-query/TempoTraceQueryEditor.tsx
- ui/tempo-plugin/src/plugins/tempo-trace-query/get-trace-data.ts
- ui/tempo-plugin/src/plugins/tempo-trace-query/query-editor-model.ts
- ui/tempo-plugin/src/test/mock-data.ts
#2444 enforce type for tempo-plugin package
> [IGNORE] Enforce typing for tempo-plugin package

- ui/storybook/.eslintrc.js
- ui/storybook/src/components/StorySection/StorySection.tsx
- ui/storybook/src/config/DocsContainer.tsx
- ui/storybook/src/config/decorators/WithBackground.tsx
- ui/storybook/src/config/decorators/WithThemes.tsx
- ui/storybook/src/config/decorators/WithTimeZone.tsx
- ui/storybook/src/decorators/WithErrorSnackbar.tsx
- ui/storybook/src/decorators/WithQueryClient.tsx
- ui/storybook/src/decorators/WithQueryParams.tsx
- ui/storybook/src/utils/happo/canvasUtils.ts
#2444 enforce type for plugin-system package
> [IGNORE] Enforce typing for storybook package

- ui/e2e/.eslintrc.js
- ui/e2e/src/fixtures/dashboardTest.ts
- ui/e2e/src/pages/AppHomePage.ts
- ui/e2e/src/pages/AppProjectPage.ts
- ui/e2e/src/pages/DashboardPage.ts
- ui/e2e/src/pages/DatasourceEditor.ts
- ui/e2e/src/pages/Panel.ts
- ui/e2e/src/pages/PanelEditor.ts
- ui/e2e/src/pages/PanelGroup.ts
- ui/e2e/src/pages/SecretEditor.ts
- ui/e2e/src/pages/VariableEditor.ts
- ui/e2e/src/tests/gaugeChartPanel.spec.ts
- ui/e2e/src/tests/statChartPanel.spec.ts
- ui/e2e/src/utils/animationUtils.ts
- ui/e2e/src/utils/canvasUtils.ts
- ui/e2e/src/utils/formUtils.ts
#2444 enforce type for plugin-system package
> [IGNORE] Enforce typing for e2e package

- ui/explore/src/components/PrometheusMetricsFinder/filter/FilterInputs.tsx
- ui/package-lock.json
- ui/package.json
Upgrading TypeScript to v5.4, upgrading to a higher version will need to update storybook deps. Checking, but not sure it will as fast/easy as this update 😄
> [IGNORE] Upgrade TypeScript to v5.4

- go.mod
- go.sum
- internal/api/archive/archive.go
- internal/api/plugin/archive.go
- internal/api/plugin/plugin.go
Just updating the way to extract the archive as the previous way was using a dependency that is deprecated since November
> [ENHANCEMENT] Use archive deps instead of archiver

- docs/images/perses_logo_cropped_animated.svg
- ui/app/src/App.tsx
- ui/app/src/components/PersesLoader.tsx
- ui/app/src/context/Config.tsx
- ui/app/src/index.html
- ui/app/src/render-app.tsx
Use animated logo as loader for the application instead of the 3 dots. And use the same loader design for config loading.
> [ENHANCEMENT] Use Perses logo for the app loader

- ui/app/src/model/admin-client.ts
- ui/app/src/model/config-client.ts
- ui/app/src/model/dashboard-client.ts
- ui/app/src/model/datasource-client.ts
- ui/app/src/model/ephemeral-dashboard-client.ts
- ui/app/src/model/fetch.ts
- ui/app/src/model/global-role-client.ts
- ui/app/src/model/global-rolebinding-client.ts
- ui/app/src/model/global-secret-client.ts
- ui/app/src/model/global-variable-client.ts
- ui/app/src/model/health-client.ts
- ui/app/src/model/migrate-client.ts
- ui/app/src/model/project-client.ts
- ui/app/src/model/role-client.ts
- ui/app/src/model/rolebinding-client.ts
- ui/app/src/model/secret-client.ts
- ui/app/src/model/user-client.ts
- ui/app/src/model/variable-client.ts
- ui/core/src/utils/fetch.ts
- ui/explore/src/components/PrometheusMetricsFinder/PrometheusMetricsFinder.tsx
- ui/explore/src/components/PrometheusMetricsFinder/overview/MetricOverview.tsx
- ui/explore/src/components/PrometheusMetricsFinder/utils.ts
- ui/plugin-system/src/context/ProjectStoreProvider.tsx
- ui/prometheus-plugin/src/components/PromQLEditor.tsx
- ui/prometheus-plugin/src/components/parse.ts
Almost all fetch hooks are based on fetchJson which is returning an error including the status code. Will be easier to use it now 😄 
> [IGNORE] Correctly type useQuery fetch hooks error

- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
Show "No data" instead of "null" when the Gauge has no data.
Before:
After:
include:
> [BUGFIX] GaugeChartPanel: fix empty state

- ui/.cjs.swcrc
- ui/.swcrc
- ui/app/webpack.prod.ts
- ui/tsconfig.base.json
Upgrading ECMAScript version to 2022
> [IGNORE] Upgrade to es2022

- README.md
- docs/overview.md
- Rendered preview of [README](https://github.com/perses/perses/blob/antoinethebaud/doc-new-intro/README.md)
- Rendered preview of [overview.md](https://github.com/perses/perses/blob/antoinethebaud/doc-new-intro/docs/overview.md)
> [DOC] Rework project overview + dedicated file for it

- README.md
- docs/cli.md
- docs/dac/cue/README.md
- docs/dac/getting-started.md
- docs/dac/go/README.md
- docs/dac/introduction.md
Preliminary step to be able to list DaC in the "concepts" on the website ;)
[See rendered](https://github.com/perses/perses/blob/antoinethebaud/doc-intro-dac/docs/dac/introduction.md)
> [DOC] enrich DaC intro + extract to dedicated file

- ROADMAP.md
I am updating the roadmap as it doesn't reflect anymore what is currently happening in Perses.
As I am in FOSDEM, I am just opening the PR to let members looking at it and see if what they think about it.
Please Perses' members, let me know what subject should be put in this Roadmap.
> [ignore] update roadmap

- ui/plugin-system/src/components/MultiQueryEditor/MultiQueryEditor.tsx
Not waiting for plugins to be loaded causes the following issue:
this PR waits for plugins to be loaded before addingdefault queries.
no UI Changes
> [BUGFIX] wait until plugins are loaded to avoid invalid default queries for explore components

- docs/examples/config.archive.yaml
- docs/examples/config.docker.yaml
- pkg/model/api/config/plugins.go
I am proposing to detect if Perses is used in a container, so we can inject the default value where the plugins are stored
> [ENHANCEMENT] detect if Perses is used in container to add default path

- Dockerfile
- distroless-debug.Dockerfile
- docs/configuration/configuration.md
- internal/api/e2e/framework/server.go
- pkg/client/fake/api/client.go
- pkg/model/api/config/config.go
- pkg/model/api/config/config_test.go
- scripts/generate-goreleaser/.goreleaser.base.yaml
- scripts/generate-goreleaser/generate-goreleaser.go
I have also removed any references / usages to this part of the config
> [ENHANCEMENT] Deprecate the schema config

- cue/model/api/v1/secret/tls_config_go_gen.cue
- docs/configuration/configuration.md
- pkg/model/api/v1/secret/tls_config.go
As we don't get any update from @Labiote, the initial author of the PR https://github.com/perses/perses/pull/2329, I am opening this PR to taking back the changes initially proposed and associated fixed we were requesting.
> [ENHANCEMENT] Support min/max TLS version

- .mdox.validate.yaml
> [IGNORE] mdox: ignore blocking domains

- .github/workflows/go.yml
- internal/api/e2e/api/dashboard_test.go
- internal/api/e2e/api/proxy_test.go
- internal/api/e2e/api/testdata/dashboard.json
- internal/api/impl/proxy/proxy.go
close https://github.com/perses/perses/issues/2640
> [ignore] add tests on the proxy

- docs/proxy.md
I am adding a doc explaining how the proxy is working. I guess it's a concept documentation
> [doc] add documentation about the proxy

- GOVERNANCE.md
congrats @nicolastakashi and thank you for being part of Perses 🙏
> [ignore] add @nicolastakashi as owner of perses

- ui/dashboards/src/components/Variables/Variable.tsx
Regression from #2554 😅 
Closes #2669
include:
> [BUGIFX] ListVariable: do not clear input value when selecting a value

- Makefile
- cue/common/proxy/http.cue
- cue/cue.mod/module.cue
- cue/dac-utils/dashboard/dashboard.cue
- cue/dac-utils/panelgroup/panelgroup.cue
- cue/dac-utils/panelgroups/panelgroups.cue
- cue/dac-utils/variable/group/group.cue
- cue/dac-utils/variable/list/list.cue
- cue/dac-utils/variable/text/text.cue
- cue/dac-utils/variable/variable.cue
- cue/model/api/v1/dashboard/layout_patch.cue
- cue/model/api/v1/dashboard/variable_patch.cue
- cue/model/api/v1/dashboard_go_gen.cue
- cue/model/api/v1/dashboard_patch.cue
- cue/model/api/v1/datasource_go_gen.cue
- cue/model/api/v1/plugin/plugin_go_gen.cue
- cue/model/api/v1/plugin_go_gen.cue
- cue/model/api/v1/project_go_gen.cue
- cue/model/api/v1/public_secret_go_gen.cue
- cue/model/api/v1/public_user_go_gen.cue
- cue/model/api/v1/role_go_gen.cue
- cue/model/api/v1/variable/list_patch.cue
- cue/model/api/v1/variable_patch.cue
- internal/cli/cmd/dac/build/testdata/cue/cue.mod/module.cue
- internal/cli/cmd/dac/build/testdata/cue/valid/dac.cue
- internal/test/dac/cue.mod/module.cue
- internal/test/dac/input.cue
Ref https://github.com/perses/perses/issues/1984
Change module name `github.com/perses/perses/cuelang` back to `github.com/perses/perses/cue`
> [IGNORE] change back module name to the right name

- docs/concepts/ephemeral-dashboards.md
> [DOC] New user documentation for ephemeral dashboard

- cue/model/api/v1/metadata_patch.cue
- pkg/model/api/v1/metadata.go
Adding the tags in the medata struct like described in #1733
> [FEATURE] Add tags in metadata

- docs/migration.md
> [DOC] Improve migration doc

- docs/api/variable.md
Fix typo in `ListVariable` spec docs
N/A
> [DOC] Fix typo in ListVariable spec

- pkg/model/api/config/config_test.go
> [IGNORE] Remove deprecated usage of `ephemeral_dashboards_cleanup_interval` in some tests

- .github/workflows/go.yml
- .gitignore
- internal/api/database/file/query_test.go
- scripts/download-prometheus.sh
- scripts/run-prometheus.sh
It's been a while there are issues raised time to time on windows. I think it's time to run the tests to see if Perses is really working on windows
> [IGNORE] run all tests on windows

- internal/api/discovery/cuetils/cuetils_test.go
that should fix the windows tests as a side effect.
> [ignore] move datasource discovery test to the new plugin system

- internal/api/discovery/http/http.go
- internal/api/discovery/kubernetes/kubernetes.go
somehow the interface `task.SimpleTask` is not well implemented.
This PR aims to fix that.
We really need integration / e2e tests on this feature. 
close #2711 
/cc @ibakshay
> [BUGFIX] Fix the interface impl of the datasource discovery

- internal/api/discovery/cuetils/cuetils_test.go
- internal/api/discovery/cuetils/node.go
- internal/api/discovery/kubernetes/kubernetes.go
- internal/api/discovery/kubernetes/kubernetes_test.go
- internal/api/discovery/kubernetes/service.go
- internal/api/discovery/kubernetes/service_test.go
- internal/api/discovery/kubernetes/testdata/service.json
- internal/api/plugin/migrate_test.go
- internal/api/plugin/plugin.go
- internal/test/test.go
- scripts/cue-test/cue-test.go
This PR aims to tackle the various issues raised in https://github.com/perses/perses/issues/2711.
I am adding more unit tests also to covering more use case.
One mistake I did when writing the discovery was to think an empty string and a nil value is the same for a string in Cuelang. And obviously it's not the case.
So I think the safest way to avoid the case raised in the last comment of the PR is to avoid to set a concrete value if the string is empty.
> [BUGFIX] Discovery: Fix label selector builder and empty value in cuelang

- README.md
- docs/installation/from-source.md
The pre-requisites are quite outdated
> [DOC] Update requirement when building perses

- docs/dac/cue/README.md
- docs/dac/cue/variable/list.md
- docs/dac/go/variable.md
> [DOC] DaC: document the base List variable + Remove static list variable (moved to perses/plugins)

- docs/materials.md
no idea where it will be displayed in the website 🤔
> [DOC] Referencing various materials talking about Perses

- .github/workflows/cue.yaml
- internal/cli/cmd/plugin/build/build.go
Publish the CUE module of this repository (`github.com/perses/perses/cue`) to the [Central Registry](https://registry.cue.works/) in an automated way, on every releases.
Ref https://github.com/perses/perses/issues/1984.
> [FEATURE] Publish CUE module to Central Registry

- internal/cli/cmd/dac/setup/setup.go
There was 2 issues with the current content:
- of course having a wrapping "test" object would make validation against dashboard datamodel to fail
- had to provide project info as a flag to the build command, otherwise it would fail as project is required
> [IGNORE] `dac setup`: improve example .cue file generated

- ui/components/package.json
- ui/package-lock.json
- ui/package.json
The `package.json`/`package-lock.json` were in a weird state as it was missing `react-refresh` as de dev dependency. Also you weren't able to run `npm update` because of `notistack` which I had to update to a new major version
Related https://github.com/perses/perses/pull/2730
N/A
N/A
> [IGNORE] Update package-lock.json

- ui/plugin-system/src/runtime/plugin-registry.ts
Fix the following warning in the JS console:
```
[QueriesObserver]: Duplicate Queries found. This might result in unexpected behavior. Error Component Stack
at DataQueriesProvider (DataQueriesProvider.tsx:63:1)
at div (<anonymous>)
at emotion-element-7a1343fa.browser.development.esm.js:48:1
at Box (createBox.js:20:1)
at GridItemContent (GridItemContent.tsx:32:1)
```
The root cause was that `usePlugins()` called `useQueries()` with potentially duplicate query keys, which is not supported:
https://github.com/TanStack/query/issues/8224#issuecomment-2523554831
https://github.com/TanStack/query/issues/4187#issuecomment-1256336901
To fix this, I de-duplicated the requested plugin kinds before calling `useQueries()`.
no UI changes
following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, …
> [BUGFIX] Fix duplicate query keys in useQueries()

- ui/components/src/EChart/EChart.tsx
Workaround for https://github.com/perses/plugins/issues/83
See https://github.com/perses/plugins/issues/83
> [BUGFIX] Implement workaround to fix ScatterPlot plugin

- cue/model/api/v1/secret/tls_config_go_gen.cue
- pkg/model/api/v1/secret/tls_config.go
- ui/core/src/model/secrets.ts
This PR makes `insecureSkipVerify` optional as it already defaults to false.
> [ENHANCEMENT] allow insecureSkipVerify to be optional

- docs/dac/cue/README.md
> [DOC] Mention plugin builders in CUE SDK doc

- .mdox.validate.yaml
- cue/common/datasource.cue
- cue/common/legend.cue
- cue/common/variable.cue
Add new schemas in common lib, to be reused by plugins (https://github.com/perses/plugins/pull/102)
> [IGNORE] Add new schemas in common lib

- ui/components/src/Table/Table.tsx
- ui/components/src/Table/TableFoot.tsx
- ui/components/src/Table/VirtualizedTable.tsx
- ui/components/src/Table/model/table-model.ts
Table: add optional pagination
> [FEATURE] Table: add optional pagination

- docs/plugins/cue.md
This PR fixes a [wrong merge resolution](https://github.com/perses/perses/commit/a923659a2dc399b697e9b61126a668fd2e26aeba#diff-cb880769de58f4abf35cd4a24b6efaa9a00bf6191a47781f6081f16c0e67dd09R82-R102) ;) 
> [DOC] Remove duplicated section

- dev/docker-compose.yaml
- dev/extra/prometheus.yaml
Add avalanche for generating fake metrics data for prometheus, with all type of metrics including native histograms
> [IGNORE] Add avalanche in dev env

- ui/core/src/model/time-series-data.ts
- ui/core/src/model/time-series-queries.ts
Histograms were not typed and in case of histograms, value can be undefined
> [ENHANCEMENT] Add histograms typing

- ui/components/src/EChart/EChart.tsx
Same issue as ScatterPlot (https://github.com/perses/plugins/issues/83) for EChart CustomChart, needed for PR: https://github.com/perses/plugins/pull/106
> [IGNORE] Implement workaround for timeseriestable plugin

- docs/materials.md
> [DOC] Add KubeCon pres to the list of materials

- README.md
Let's reuse the sexy gif in the main README, + some patches.
> [IGNORE] Update README

- ui/components/src/TimeSeriesTooltip/tooltip-model.ts
When embedding Perses in a NextJS app (https://github.com/sjcobb/perses-embed-example), `navigator is not defined` errors prevent building the app (related to SSR). To help, we can fallback to plotCanvas when zrender coordinates are not available (plotCanvas works fine in Edge, zrX and zrY fix a bug in Firefox). Follow up to PR #2547
Tooltip still working in Edge: 
- Does it have loading states? You need to wait for loading …
> [BUGFIX] Adjust mousemove listener to fix navigator undef error

- docs/embedding-panels.md
Update guide with breaking changes, latest recommendations now that perses/plugins packages are published: https://perses.dev/perses/docs/embedding-panels/
I tested this in repo here:
- https://github.com/sjcobb/perses-embed-panel/blob/main/src/App.tsx
- https://sjcobb.github.io/perses-embed-panel/
See [Slack thread](https://cloud-native.slack.com/archives/C07KQR95WBE/p1746041915293459?thread_ts=1746036198.712719&cid=C07KQR95WBE).
> [DOC] Update embedding panels guide with latest recommendations

- GOVERNANCE.md
- MAINTAINERS.md
> [ignore] add @ibakshay as a team member

- internal/cli/cmd/dac/build/testdata/cue/cue.mod/module.cue
- internal/cli/cmd/plugin/build/cue_test.go
- internal/cli/cmd/plugin/build/testdata/barchart/cue.mod/module.cue
- internal/cli/cmd/plugin/build/testdata/tempo/cue.mod/module.cue
- internal/test/dac/cue.mod/module.cue
Update deps to plugins modules to stable / automatically-published versions.
> [IGNORE] update plugin deps in test cue modules

- .github/workflows/cue.yaml
> [IGNORE] Fix CUE module publish

- docs/dac/go/panel-group.md
- go-sdk/panel-group/panel-group.go
* Adjusted the default `PanelHeight` from 6 to 8 as most of the panels in community dashboards are using `8` as panelheight. 
Signed-off-by: Akshay Iyyadurai Balasundaram <akshay.iyyadurai.balasundaram@sap.com>
> [ENHANCEMENT]  🐛 update default PanelHeight

- Dockerfile.dev
- docs/installation/in-a-container.md
Add a development dockerfile that can be used outside the CI to build perses
> [IGNORE] add dev dockerfile

- internal/api/plugin/migrate/testdata/old_grafana_panels_perses_dashboard.json
- internal/api/plugin/migrate/testdata/old_grafana_query_perses_dashboard.json
This should fix the tests after PR #2956 has been merged
> [IGNORE] Fix migrate tests after DatasourceVariable has been added

- ui/app/package.json
- ui/package-lock.json
- ui/package.json
- ui/plugin-system/package.json
- ui/plugin-system/src/remote/PluginRuntime.tsx
Upgrade vulnerable dependencies
> [IGNORE] Fix vulnerable dependencies

- ui/package.json
> [IGNORE] fix turbo cache clear command

- docs/configuration/load-plugin.md
I am just updating the instruction to load a plugin from a dev environment
> [DOC] Update doc about how to load a plugin in dev environment

- go-sdk/dashboard/options.go
- go-sdk/test/dashboard_test.go
- internal/test/dac/expected_output.json
- pkg/model/api/v1/common/validate.go
> [ENHANCEMENT] Go SDK: Allow passing description as dashboard option

- docs/concepts/datasources.md
> [DOC] Improve datasources concept doc

- internal/api/plugin/plugin.go
related to #3021.
It won't fix the issue, but at least it will avoid the error 500.
> [BUGFIX] Plugin: Fix internal error returned when the plugin list is empty

- scripts/plugin/plugin.yaml
[Release note](https://github.com/perses/plugins/releases/tag/table%2Fv0.7.1)
> [IGNORE] Bump table plugin to v0.7.1

- ui/app/src/model/global-datasource-client.ts
- ui/app/src/model/global-role-client.ts
> [IGNORE] Fix typo

- .mdox.validate.yaml
eslint.org is working but failing on tests
> [IGNORE] format: skip elsint.org domain check

- docs/materials.md
I have also updated the timecode of the poadcast I did with Dotan as suggested by him. The idea is to start the video when we are talking about Perses as before this moment we are talking about PromCon.
> [doc] update materials with the Rawkode live

- scripts/plugin/plugin.yaml
Add heatmap panel for Prometheus histograms, more info at: https://github.com/perses/plugins/pull/145
> [FEATURE] Add HeatMap plugin

- dev/config.yaml
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelActions.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
- ui/plugin-system/src/model/panels.ts
This PR adds CSV export functionality to time series panels, enabling users to download time series data in CSV format. The implementation includes core changes to support CSV export capabilities and integrates with the CSV export plugin functionality. 
An "Export as CSV" button appears in the top right of any panel that holds appropriate time series charts/data and when clicked downloads a file on your computer with the name "panelName_data.csv". The first line of the CSV holds labels for the data columns and if the graph has legends then those labels are used. Under that are all the rows of the actual data.
* This PR is to be used to create a snapshot branch
* Related plugin PR: TBD
* Branch: TimeSeriesFixed2 contains updated changes
* Added core CSV export functionality for time series …
> [FEATURE] - TimeSeries Export Functionality w/ Plugins

- ui/app/src/components/dialogs/CreateDashboardDialog.tsx
- ui/app/src/validation/dashboard.ts
Closes #1526 
Details of the bug can be found here #1526 
There was a small bug with the `useDashboardValidationSchema` function. 
1. The bug was resolved
2. The function was improved a bit to handle corner cases including error and loading states
> [BUGFIX] Avoid dashboard name duplication from the front-end side

- ui/plugin-system/src/runtime/variables.test.ts
- ui/plugin-system/src/runtime/variables.ts
Add a simple wrapper around `replaceVariables()` with support for extra string variables.
no UI changes
> [IGNORE] add replaceVariablesInString utility function

- README.md
Signed-off-by: Akshay Iyyadurai Balasundaram <akshay.iyyadurai.balasundaram@sap.com>
> [DOCS]: update plugin architecture description in README

- docs/concepts/variable.md
> [DOC] add variable interpolation format docs

- internal/api/interface/error.go
fix https://github.com/perses/perses/issues/3236
> [bugfix] Fix typo in error message

- docs/concepts/variable.md
> [IGNORE] Adjust variable doc

- docs/concepts/plugin.md
NB: need to publish [Prometheus doc](https://github.com/perses/plugins/pull/319) first to make the build pass
> [DOC] Add some hyperlinks in Plugin concept doc

- README.md
- docs/concepts/dashboard-as-code.md
- docs/concepts/variable.md
> [IGNORE] doc patches

- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariablePreview.tsx
> ⚠️ SHOULD BE REVIEW WITH AND MERGED IMMIDIATELY AFTER https://github.com/perses/plugins/pull/326
> [BUGFIX] Remove Variable Preview refresh button

- scripts/plugin/plugin.yaml
BUMP Prometheus Version to v0.53.2
> [IGNORE] Bump Prometheus version

- ui/app/src/App.tsx
This provider has been [removed by my refactor](https://github.com/perses/perses/pull/3268/files#diff-36280aea869f6c25b2cd282164c1569ccc49337a1cd20f4f7f343585a155ca54) and I forgot to reput it with the new mode 😓 
> [BUGFIX] Readd ReactRouterProvider

- internal/api/plugin/dev.go
> [IGNORE] add server-side logs for dev plugin load/unload

- .mdox.validate.yaml
- ui/dashboards/src/components/DashboardStickyToolbar/DashboardStickyToolbar.tsx
- ui/dashboards/src/components/Variables/ListVariableListBox.tsx
- ui/dashboards/src/components/Variables/Variable.tsx
- ui/dashboards/src/components/Variables/index.tsx
Closes https://github.com/perses/perses/issues/1512.
Improve ListVariable selection:
- global select for options (only when multiple value are allowed)
- indication of item selected (only when multiple value are allowed)
- checkbox on the left side
And fix height issue when there is a lot of values selected
> [FEATURE] dasboards - ListVariable Select: add checkbox and global checkbox for options

- ui/app/src/components/Header/SearchBar/SearchBar.tsx
- ui/app/src/components/Header/SearchBar/SearchList.tsx
- ui/app/src/model/dashboard-client.ts
- ui/app/src/views/home/ImportantDashboards.tsx
As explained in #3413 the important dashboards should be highlighted.
> [ENHANCEMENT] Highlight the important dashboards
