perses/perses

- cmd/perses/main.go
- dev/config.yaml
- internal/api/e2e/project_test.go
- internal/api/generate.go
- internal/api/impl/v1/dashboard/persistence.go
- internal/api/impl/v1/dashboard/service.go
- internal/api/impl/v1/datasource/persistence.go
- internal/api/impl/v1/project/persistence.go
- internal/api/impl/v1/prometheusrule/persistence.go
- internal/api/impl/v1/user/persistence.go
- internal/api/shared/database/dao.go
- internal/api/shared/dependency/persistence_manager.go
- internal/config/config.go
- internal/config/database.go
- utils/test.go
It doesn't change so many things, it just use the filesystem instead of etcd.
Not sure about the flags yet. But at least for the moment it's enough.
Supporting filesystem as a database will ease the " As code" and it will provide a local web editor of the prometheusRules / Dashboard.
Basically a developer that is going to change his dashboard in his git repository, he will be able to launch the `perses` binary and use the UI + API to modify locally his dashboard.
/cc @celian-garcia and @AntoineThebaud. I don't expect it impacts something on your side, it's more to let you know about it.
> support database as file

- internal/api/front/perses/package-lock.json
- internal/api/front/perses/package.json
This PR is increasing the version of codemirror-promql and lezer-promql.
It provides the following interesting (for Prometheus) fixes and enhancements:
* Autocomplete `NaN` and `Inf`
* Fetch series using the HTTP POST method. (The switch was done because some users are reaching the URL limit, which I thought wasn't really possible in the context of this lib)
* Fix the parsing of metric names starting with `Inf` / `NaN` like `infra`
Complete release note is available [here](https://github.com/prometheus-community/codemirror-promql/releases/tag/0.16.0)
> bump codemirror-promql to v0.16.0

- dev/data/dashboard.json
- docs/dashboard.md
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard_layout.go
- pkg/model/api/v1/dashboard_layout_test.go
- pkg/model/api/v1/dashboard_test.go
- pkg/model/api/v1/jsonref.go
- pkg/model/api/v1/jsonref_test.go
this PR adds the datamodel for the Dashboard Layout on the backend side. (related to #55)
It checks that the json references are pointing to an existing object.
Note: I'm not sure it will be useful in the future to set the pointer in the JSONRef. I did it today, probably this set won't be useful at all
> Implement the layout on the backend side

- cmd/perses/main.go
- internal/api/core/middleware/proxy.go
For the moment it redirects all request to the datasource.
HTTP method whitelist will come later when redoing the datamodel of the  datasource.
* standard usage, target a known datasource and used correctly the api of the datasource
```bash
curl -XGET http://localhost:8080/proxy/datasources/PrometheusDemo/api/v1/labels
{
"status": "success",
"data": [
"__name__",
"action",
"address",
"alertmanager"
]
}
```
* target a not known datasource
```bash
curl -XGET http://localhost:8080/proxy/datasources/test/api/v1/labels
{
"message": "unable to forward the request to the datasource 'test', datasource doesn't exist"
}
```
it returns the 502 error (bad gateway)
* target a known datasource, but with a wrong usage of the API. It returns the error from the datasource
```bash
curl -XGET …
```
> implement a proxy middleware that redirect requests to the datasource

- ui/app/src/App.tsx
The import line change in
https://github.com/perses/perses/commit/bcb29c7b98aa880ce662ee842eed53a9e013866f
breaks the app for some reason ("Uncaught TypeError: Cannot read property
'useChartQuery' of undefined"), although there is an index.ts that exports
everything. Let's just revert that change for now to make things run again.
> Fix import / TypeScript error issues

- ui/app/src/Footer.tsx
- ui/app/src/components/Toast.tsx
- ui/app/src/health-client.ts
- ui/app/webpack.dev.ts
This PR introduced the dev proxy required to query the backend from the frontend and fetch the `health` endpoint that contain the version of Perses.
I'm wondering if we should display the commit ID. What do you think ?
> Fetch the version from the server

- ui/app/sample-data/dashboard.ts
- ui/app/sample-data/datasource.ts
- ui/app/src/context/DataSourceRegistry.tsx
- ui/app/src/model/perses-client.ts
- ui/app/src/model/url-builder.test.ts
- ui/app/src/model/url-builder.ts
- ui/core/src/model/dashboard.ts
- ui/core/src/model/datasource.ts
- ui/core/src/model/resource.ts
I started to converge to the current datamodel served by the backend. I started by the metadata.
This PR also includes a refactoring of the `URLBuilder` to avoid to use a new object each time you want to build an URL to contact the API.
this PR should be merged after #104 as it contains the changes from there and so it will depend on the outcome of #104
> reviewing the metadata datamodel 

- .github/dependabot.yml
> dependabot is checking weekly the deps + increase the max number of PR that can be opened

- ui/app/sample-data/cadvisorDashboard.ts
- ui/app/sample-data/nodeExporterDashboard.ts
- ui/app/src/App.tsx
This is very losely based on https://grafana.com/grafana/dashboards/6014, but
we don't have all necessary features yet (like different legend strings for
different queries in the same graph).
This also adds a quick URL parameter hack to be able to choose from one of
multiple checked-in sample-data dashboards.
> Add simple Node Exporter dashboard

- internal/api/core/server.go
- internal/api/doc.go
- internal/api/impl/v1/folder/persistence.go
- internal/api/impl/v1/folder/service.go
- internal/api/interface/v1/folder/interface.go
- internal/api/shared/dependency/persistence_manager.go
- internal/api/shared/dependency/service_manager.go
- internal/api/shared/utils.go
- pkg/client/api/v1/folder.go
- pkg/model/api/v1/folder.go
- pkg/model/api/v1/folder_test.go
- pkg/model/api/v1/kind.go
This PR is adding a way to manage a sub-folder system in the backend. In the backend it's just a document that describes a folder tree with some references to the dashboard.
It will be used by the frontend to sort the dashboard in the different folders defined.
Note: related to the issue #183 
FYI: @LukeTillman @sjcobb 
> API: add folder management

- ui/panels-plugin/src/plugins/line-chart/tooltip/SeriesInfo.tsx
- ui/panels-plugin/src/plugins/line-chart/tooltip/Tooltip.tsx
- ui/panels-plugin/src/plugins/line-chart/tooltip/TooltipContent.tsx
Adds prop to wrap labels in `Tooltip`
> Add prop to wrap tooltip labels

- cmd/percli/main.go
- internal/cli/utils/config.go
- internal/cli/utils/test/test.go
this PR introduced the usage of global flags to be able to set the path to the config file and the level of the log.
This PR must be merged after #314
> CLI: manage config path and log level with global flags

- cmd/percli/main.go
- internal/cli/cmd/apply/apply.go
- internal/cli/cmd/apply/apply_test.go
- internal/cli/cmd/apply/test/multiple_resources.json
- internal/cli/cmd/apply/test/single_resource.json
- internal/cli/cmd/apply/test/unknown_resource.json
- internal/cli/cmd/describe/describe.go
- internal/cli/cmd/describe/describe_test.go
- internal/cli/utils/file/file.go
- internal/cli/utils/file/read.go
- internal/cli/utils/service/dashboard.go
- internal/cli/utils/service/datasource.go
- internal/cli/utils/service/folder.go
- internal/cli/utils/service/globaldatasource.go
- internal/cli/utils/service/project.go
- internal/cli/utils/service/service.go
- pkg/model/api/entity.go
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/datasource.go
- pkg/model/api/v1/folder.go
- pkg/model/api/v1/kind.go
- pkg/model/api/v1/metadata.go
- pkg/model/api/v1/project.go
- pkg/model/api/v1/user.go
This PR is implementing a new command in the CLI called `apply`. This command is taking a file as parameter or is reading the stdin.
Every known objects read will be created or updated with this command.
The file or the data format from stdin can be a JSON/YAML array of object or a JSON/YAML object.
I'm wondering if we should use this command to populate the database, that should probably simplify the script `dev/populate.sh`.
Description of the command itself: 
```bash
./bin/percli apply --help
Create or update resources through a file. JSON or YAML format supported
Usage:
percli apply -f [FILENAME] [flags]
Examples:
percli apply -f ./resources.json
cat ./resources.json | percli apply -f -
Flags:
-f, --file string      Path to the file that contains the resources to create/update.
-h, …
```
> CLI: implement apply cmd

- .gitpod.yml
- CONTRIBUTING.md
- Makefile
Like that when you just want to build the whole project you just to do : 
`make` or `make build`. It wasn't coherent that `make build` was just building the API and not the UI or the CLI.
> define a build-all directive in Makefile

- Makefile
- RELEASE.md
- npm-deps.sh
As part of #331, I'm creating this documentation that is indicating how to release Perses. I took some inspirations from the Prometheus release process.
Probably we can still improve it and automatise some steps.
~~I would be interested if there is some magic command to upgrade the npm dependencies when you are using a monorepo. Would be great to know for Prometheus too.~~
> add the release documentation

- .github/workflows/release.yaml
The `setup-node` action writes an `.npmrc` file with `NODE_AUTH_TOKEN` as a placeholder for use when doing things like publishing packages. See https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm for an example. Let's see if this fixes the auth issue in the libs release.
> Try setting env var that setup-node writes to .npmrc

- .github/workflows/build.yaml
- .github/workflows/release.yaml
Set the download path for UI artifacts so that they don't lose the `ui` folder when they're downloaded.
> Add path when downloading artifacts

- ui/plugin-system/src/components/PluginLoadingBoundary/PluginLoader.tsx
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
This is a small improvement to plugin loading that allows the `PluginRegistry` component to render its children while it's waiting on the list of available plugins to load. This way we don't have to block the rendering of a screen (e.g. a Dashboard) while that list is still being fetched.
> Fix plugin registry to render children while waiting on plugin list load

- ui/app/src/render-app.tsx
- ui/components/package.json
- ui/dashboards/package.json
- ui/package-lock.json
- ui/panels-plugin/package.json
- ui/plugin-system/package.json
- ui/plugin-system/src/components/PluginLoadingBoundary/PluginLoadingBoundary.tsx
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
- ui/plugin-system/src/components/PluginRegistry/registry-state.ts
- ui/prometheus-plugin/package.json
This makes a couple very minor improvements for consumers of the NPM packages:
1. Removes our reliance on Map/Set in the `immer` library. This means someone using `@perses-dev/plugin-system` doesn't have to know to call `enableMapSet()` somewhere (nor do they need to add `immer` as a dependency to their app to do that).
2. Moves `@mui/material` and `react-query` from `dependencies` to `peerDependencies` so that folks can bring their own compatible version if they already have one. Since both of these rely on React context (the theme context in MUI's case and the query client context in react-query's case), it makes sense to have these be peers so that the context works properly in apps that already have these libraries.
A "TIL" side note on number 2: In `npm` versions > 7, it now …
> Minor improvements for NPM package consumers

- ui/components/src/LineChart.tsx
Fix overlooked dataZoomEnabled eslint issue from my previous sjcobb/components/reorg-line [PR 403](https://github.com/perses/perses/pull/403)
> fix eslint issue after adding new LineChart prop

- ui/components/src/model/units.ts
- ui/package-lock.json
- ui/panels-plugin/package.json
In release v0.3.0, units.ts moved from perses-dev/panels-plugin to perses-dev/components, but I forgot to update each package.json with the @formatjs/intl-numberformat dependency that moved (formatjs was added in prev StatChart [PR 307](https://github.com/perses/perses/pull/307)).
To simplify things, I've decided to remove the @formatjs/intl-numberformat dependency since it was only being used for one function.
Commits:
- remove @formatjs/intl-numberformat dependency
- copy IsSanctionedSingleUnitIdentifier util that checks against SANCTIONED_UNITS from: https://tc39.es/ecma402/#table-sanctioned-simple-unit-identifiers
> remove @formatjs/intl-numberformat dependency

- ui/components/src/tooltip/SeriesInfo.tsx
- ui/components/src/tooltip/TooltipContent.tsx
Temporary bugfix for unreadable date and value tooltp label colors when inheriting an app's theme. 
Changed the date and value labels to white until I figure out how to get theme colors to be inherited correctly. 
Planning to add proper theme support in v0.4
> temp bugfix for tooltip label colors readability

- .github/workflows/build_and_release.yaml
- ui/components/package.json
- ui/components/tsconfig.cjs.json
- ui/core/package.json
- ui/core/tsconfig.cjs.json
- ui/dashboards/package.json
- ui/dashboards/tsconfig.cjs.json
- ui/package.json
- ui/panels-plugin/package.json
- ui/panels-plugin/tsconfig.cjs.json
- ui/plugin-system/package.json
- ui/plugin-system/tsconfig.cjs.json
- ui/prometheus-plugin/package.json
- ui/prometheus-plugin/tsconfig.cjs.json
- ui/tsconfig.cjs.json
This adds CommonJS versions/output for all packages that we publish to NPM. This is for a couple reasons:
1. Some common tooling (e.g. Jest) still doesn't support ES Modules, so if someone is trying to use Jest to test things where our packages are imported, it's currently not possible. (Jest basically fails with an error that it can't import from the packages).
2. Some folks (although I suspect not many?) may still not be using ESM in their applications and want to embed Perses components, so this will allow them to do that without needing to switch their entire applications to ESM first.
I think the first reason is probably the more common/primary reason to do this.
In order to do this, I added some compiler configs for doing CJS builds and scripts for running a CJS build with that …
> Add CommonJS version of all packages we publish

- .github/workflows/build_and_release.yaml
- .github/workflows/go.yml
This PR is upgrading go to the last version (v1.18).
In the changes, it says to `goreleaser` to not build the different binaries in parallel. It's because in a Github action, it totally fails and I have no idea why. I'm not able to reproduce it locally and I have even tried in other CI/CD and other docker images with memory and cpu limitation (like less than 1GB of memory) same result.
So until it is magically fixed or someone has an explanation, we will remain like that. The build is a bit slower (1min more), so it's not a huge issue to remove the parallel build.
> upgrade to go v1.18

- ui/app/webpack.common.ts
I'm an idiot and left the wrong bundle output directory in webpack from when I added all the `@perses-dev` packages in #315. 😂   Sorry for breaking this!
> Switch bundle output directory back

- .github/workflows/build_and_release.yaml
This PR should fix back the build of the binaries for the release
> fix go build: set parallelism build to 1

- ui/components/package.json
- ui/core/package.json
- ui/package-lock.json
This PR fixes issue noted in #perses-dev chat that core is currently is dependency of itself. Both package.json files are updated so now the components package instead pulls from core.
Issue was introduced by me in [PR 425](https://github.com/perses/perses/pull/425)
> fix package.json so core is dependency of components

- ui/components/src/tooltip/SeriesInfo.tsx
Currently, tooltips with only one focused series has a bug with how keys are displayed. Sometimes a colon is shown after the key even when there is no value following it.
In this PR, a check is added to make sure the value is populated before adding `:`
> fix tooltip key formatting in line chart

- ui/components/src/LineChart.tsx
- ui/components/src/model/graph-model.ts
- ui/panels-plugin/src/plugins/line-chart/LineChartContainer.tsx
LineChart xAxis labels now show days / seconds when applicable instead of only hours / minutes.
**Screenshot**:
> fix line chart xAxis date formatting

- .goreleaser.yml
this time it's the right one. I wished Goreleaser wasn't case sensitive :(.
> Fix tag usage in goreleaser

- ui/components/src/LineChart.tsx
- ui/components/src/model/graph-model.ts
This PR fixes a bug where xAxis date formatting for LineChart shows 12:30 AM as 24:30. Now Intl.DateTimeFormat params have been updated to instead show it as 0:30
More info about fix: https://stackoverflow.com/questions/65604554/intl-datetimeformat-returns-an-hour-over-24/65604634#65604634
An optional prop to customize xAxis.max is also added for more control when switching query duration.
> fix line chart shows time beyond 24 hours, add max prop

- ui/components/README.md
Added a README.md to the ui/components folder that links to new LineChart import example: 
https://codesandbox.io/s/perses-line-chart-component-using-echarts-1tg92v?file=/src/App.js
> components package readme with LineChart import example

- ui/panels-plugin/src/plugins/line-chart/LineChartContainer.tsx
Throw error when a query fails in LineChart panels instead of hanging in loading state.
Note: `throw error` is added inside timeScale undef condition so if any query is successful the graph will still show.
Screenshot:
> bugfix line-chart panel query error handling

- ui/app/src/App.tsx
- ui/components/src/GaugeChart/GaugeChart.tsx
- ui/components/src/model/theme.ts
- ui/components/src/utils/theme-gen.test.ts
- ui/components/src/utils/theme-gen.ts
Fix remaining [feedback comment from Luke](https://github.com/perses/perses/pull/462#discussion_r907471583) on PR [462](https://github.com/perses/perses/pull/462). Simplify previous useGenerateChartsTheme to pass theme as param into new generateChartsTheme function. Also, fixes invalid gauge series theme property and add unit test (theme-gen.test.ts).
> refactor mui to echarts theme generate function

- ui/app/sample-data/demoDashboard.ts
- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/Tooltip/Tooltip.tsx
- ui/components/src/Tooltip/focused-series.ts
- ui/components/src/Tooltip/tooltip-model.ts
- ui/components/src/Tooltip/utils.ts
We noticed performance issues when using Perses on dashboard with many charts, where multiple queries returned thousands of series. The way the tooltip is implemented is the main cause, this PR doesn't fix the issue completely but has a few improvements. I'm planning to look into additional tooltip fixes and adding lazy loading [using IntersectionObserver](https://stackoverflow.com/questions/53757229/reactjs-how-to-render-a-component-only-when-scroll-down-and-reach-it-on-the-page/65628717#65628717)
- add React.memo in Tooltip.tsx
- remove an unnecessary prop
- add check in Tooltip.tsx for if the cursor is over a canvas element (using mousePos.target)
- there is already a check in getFocusedSeriesData for whether the current target is a chart, but adding the condition in Tooltip.tsx allows …
> line chart tooltip performance improvement

- ui/app/src/theme/common.ts
- ui/app/src/views/ViewDashboard.tsx
- ui/components/src/EChart.tsx
- ui/dashboards/package.json
- ui/dashboards/src/components/DashboardToolbar.tsx
- ui/dashboards/src/components/GridLayout/GridLayout.tsx
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/context/DashboardProvider.tsx
- ui/dashboards/src/context/index.ts
- ui/dashboards/src/test/testDashboard.ts
- ui/dashboards/src/views/ViewDashboard.tsx
- ui/package-lock.json
When edit button is clicked, dashboard is in edit mode. You can then reposition and resize panels. 
Added [zustand](https://github.com/pmndrs/zustand) for state management and [react-grid-layout](https://github.com/react-grid-layout/react-grid-layout) for drag and drop.
> Implemented edit mode and added react-grid-layout

- CONTRIBUTING.md
- ui/README.md
Some updates to the setup docs
* Add links to the download pages for Go and Docker
* Add instruction to download `jq`, a dependency used by the `populate.sh` script
* Remove ambiguity about which directory to be in when running a command 
* Add note in `ui/README` to run backend server before running the frontend server
> Update CONTRIBUTING and ui/README

- ui/components/src/model/units.ts
We noticed a bug where bytes were sometimes formatted incorrectly:
Turns out, it happens when the number of byes is very small -- between -1 and 1. 
With the fix, we see the correct value and correct unit for bytes:
First, we have an array of units like `['Bytes', 'KB', 'MB', ...]`.
Then, we have a function for getting the index of the unit to use based on the number of bytes. 
When the number of bytes is between -1 and 1, our function returns -1. 
-1 is not an index, and so we get `undefined` as the unit. 
I did a little Wolfram Alpha graphing of this function to see this edge case too:
> Fix bug where bytes would be formatted with 'undefined' as unit

- ui/app/src/App.tsx
- ui/app/src/components/Footer.tsx
- ui/app/src/views/ViewDashboard.tsx
* Move footer component from `ViewDashboard.tsx` to `App.tsx`
* Add semantic tags for `main` and `footer`
* Add constant for the default dashboard ID
> [app] Move footer component into App vs. ViewDashboard

- GOVERNANCE.md
- MAINTAINERS.md
Here is a PR with an initial governance proposal for Perses. I've kept this very simple and short with the idea that we can build on it as the project grows. We can make changes to any of this - please let me know what you do or do not like about this proposal.
I've also suggested that we prune the list of "maintainers" or people who have access to make changes within the Perses org, since based on issue https://github.com/perses/perses/issues/429, a lot of people have access who are no longer active in the project. I've proposed the following 5 people as maintainers based on the feedback from issue https://github.com/perses/perses/issues/429 and my review of existing contributions:
- Antoine Thebaud (@AntoineThebaud)
- Augustin Husson (@Nexucis)
- Luke Tillman (@LukeTillman)
- Steven …
> Governance Proposal

- MAINTAINERS.md
This PR adds Eunice Wong in our MAINTAINERS.md file as [discussed here](https://matrix.to/#/!XNmgYIAndZOkEvQAbb:matrix.org/$UeokPXrYaDpNhQlnnGOuGt2oOtpuiHaPoOQocntaMaM?via=matrix.org)
See [governance proposal](https://github.com/perses/perses/pull/431) for context.
> add Eunice (eunicorn) in MAINTAINERS.md

- ui/dashboards/src/components/GridLayout/GridLayout.tsx
- ui/dashboards/src/css/styles.tsx
```
import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';
```
We needed to import the two css files in order for react-grid-layout to work. This meant that users consuming the dashboard library would also need to import these files in order for dashboard to work or have css loader in webpack
This PR fixed this issue by passing the css to MUI Global Styles.
> Removed react-grid-layout and react-resizable css imports

- GOVERNANCE.md
Update table in GOVERNANCE.md to match MAINTAINERS.md. 
@Nexucis are both of these tables with info about team members needed? Seems like the one in MAINTAINERS.md will be easier to remember to update
> governance doc table update

- ui/plugin-system/src/components/PluginLoadingBoundary/PluginLoadingBoundary.tsx
- ui/plugin-system/src/model/graph-queries.ts
- ui/plugin-system/src/model/panels.tsx
- ui/plugin-system/src/model/variables.ts
When using a plugin (i.e. the `usePlugin` hook), you really only need the plugin type and kind, not a full-blown definition object. This just updates that API to reflect that. This will be particularly important when you _don't_ have a definition object yet, for example, when you're adding a panel and you need to get the plugin in order to create the initial options for the panel (which ultimately results in a definition object).
> Update usePlugin to only need kind, not definition

- ui/dashboards/src/components/AddPanel/AddPanel.tsx
- ui/dashboards/src/components/AddPanel/PanelOptionsEditor.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelContent.tsx
- ui/dashboards/src/components/Panel/index.ts
- ui/plugin-system/src/model/panels.tsx
This shows off basic integration of the new Panel plugin APIs in #528 with the existing panel editing UI. Obviously this isn't at all what the final version will look like, but just wanted to show the new APIs being used. I've opened this PR against the other one (i.e. I want to merge it into the branch for #528) and then I'll commit all the changes together there.
Here's a quick look at it in action:
https://user-images.githubusercontent.com/428023/189772752-5f1f4cfd-77fd-41e4-986e-b892305e55a7.mov
> Basic integration of options editor for panel plugins

- ui/app/src/model/bundled-plugins.ts
- ui/dashboards/src/test/plugin-registry.ts
- ui/panels-plugin/package.json
- ui/panels-plugin/plugin.json
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
- ui/plugin-system/src/components/PluginRegistry/registry-state.ts
- ui/plugin-system/src/model/plugins.ts
- ui/prometheus-plugin/package.json
- ui/prometheus-plugin/plugin.json
Up until now, we've kept some very basic metadata about plugin modules (i.e. packages) in the `package.json` for each package under the `perses` key. This PR does three things to that:
1. Removes that metadata from `package.json` and into its own `plugin.json` file in each package (which will be distributed along with the package when it's published).
2. Changes the format of plugin module metadata so that individual plugins inside the module can have their own metadata. This is so that we can (eventually) show that metadata in the UI to the user (e.g. when selecting a panel type, we should be able to display a list of friendly names for each panel plugin).
3. Updates the `PluginRegistry` to work with the new format.
At some point in the near future, I'll be adding some APIs to the plugin …
> Use external file for plugin module resources, add metadata for individual plugins

- ui/dashboards/src/components/AddPanel/AddPanel.tsx
- ui/dashboards/src/components/AddPanel/PanelOptionsEditor.tsx
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelContent.tsx
- ui/dashboards/src/components/Panel/index.ts
- ui/panels-plugin/src/index.ts
- ui/panels-plugin/src/plugins/empty-chart/EmptyChart.tsx
- ui/panels-plugin/src/plugins/empty-chart/EmptyChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/empty-chart/empty-chart-model.ts
- ui/panels-plugin/src/plugins/empty-chart/index.ts
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
- ui/panels-plugin/src/plugins/gauge-chart/gauge-chart-model.ts
- ui/panels-plugin/src/plugins/gauge-chart/index.ts
- ui/panels-plugin/src/plugins/line-chart/LineChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/line-chart/LineChartPanel.tsx
- ui/panels-plugin/src/plugins/line-chart/index.ts
- ui/panels-plugin/src/plugins/line-chart/line-chart-model.ts
- ui/panels-plugin/src/plugins/stat-chart/StatChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
- ui/panels-plugin/src/plugins/stat-chart/index.ts
- ui/panels-plugin/src/plugins/stat-chart/stat-chart-model.ts
- ui/plugin-system/src/model/panels.tsx
- ui/plugin-system/src/model/visual-editing.ts
This extends panel plugins to add placeholders for what I _think_ are going to be the APIs needed for visual editing. Basically, it extends the definition of a `PanelPlugin` to add:
- `createInitialOptions`: a callback to create the initial/empty options object for a panel
- `PanelOptionsEditor`: a React component for visually editing the Options object
I went ahead and put some "stub" implementations in for our existing panel plugins. Since this was already a decent-sized PR, I didn't try integrating this with the visual editing functionality that's there yet. I'll try and do that in a follow-up PR shortly.
> Extend panel plugins to add placeholders for visual editing

- ui/app/sample-data/benchmarkDashboard.ts
- ui/panels-plugin/src/index.ts
- ui/panels-plugin/src/plugins/markdown/MarkdownPanel.tsx
- ui/panels-plugin/src/plugins/markdown/MarkdownPanelOptionsEditor.tsx
- ui/panels-plugin/src/plugins/markdown/index.ts
- ui/panels-plugin/src/plugins/markdown/markdown-panel-model.ts
Adds a component, but it's doesn't do anything yet:
> Create the skeleton of the Markdown panel

- ui/app/src/model/bundled-plugins.ts
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/VariableList/VariableList.test.tsx
- ui/dashboards/src/test/plugin-registry.ts
- ui/panels-plugin/plugin.json
- ui/panels-plugin/src/index.ts
- ui/panels-plugin/src/plugins/empty-chart/EmptyChart.ts
- ui/panels-plugin/src/plugins/empty-chart/EmptyChartPanel.tsx
- ui/panels-plugin/src/plugins/empty-chart/index.ts
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChart.ts
- ui/panels-plugin/src/plugins/gauge-chart/index.ts
- ui/panels-plugin/src/plugins/line-chart/LineChart.ts
- ui/panels-plugin/src/plugins/line-chart/index.ts
- ui/panels-plugin/src/plugins/markdown/Markdown.ts
- ui/panels-plugin/src/plugins/markdown/index.ts
- ui/panels-plugin/src/plugins/stat-chart/StatChart.ts
- ui/panels-plugin/src/plugins/stat-chart/index.ts
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
- ui/plugin-system/src/components/PluginRegistry/registry-state.ts
- ui/plugin-system/src/model/plugins.ts
- ui/prometheus-plugin/src/index.ts
- ui/prometheus-plugin/src/plugins/graph-query.ts
- ui/prometheus-plugin/src/plugins/interval-variable.ts
- ui/prometheus-plugin/src/plugins/label-names-variable.ts
- ui/prometheus-plugin/src/plugins/label-values-variable.ts
My ultimate goal is to simplify the plugin loading code a bunch, but the first step in doing that is to simplify the module format used in plugins. Before this PR, the format for plugin modules was to export a `setup` function, that then used a `register` callback in that function to register plugins. There were a few downsides to that:
1. It was more complicated than it needed to be. There was nothing stopping someone from registering plugins that weren't in the metadata.
2. We were duplicating information in those register calls (like the plugin type and kind that a plugin handles) that was already in the plugin metadata.
3. We weren't doing any sort of validation that the plugin metadata was correct (i.e. all the plugins the metadata said were in the module, were actually in the module …
> Simplify plugin module format, use metadata to drive plugin loading

- ui/dashboards/src/components/GridLayout/GridLayout.tsx
- ui/dashboards/src/css/styles.tsx
**Bug**
`'-webkit-user-select': 'none',`
Using kebab-case for css properties in objects is not supported. 
**Enhancement**
before the placeholder color used to be red, now it'll use the theme primary color.
> Updated React Grid Layout placeholder to use the theme color and fixed no kebab case error

- ui/README.md
- ui/package.json
This PR adds a new npm script, `npm run reinstall` that wipes all dist and node_modules folders for each perses-dev package. A section in the ui/README is also added describing when to use this command.
> reinstall cmd to wipe all dist and node_modules folders

- ui/app/sample-data/benchmarkDashboard.ts
- ui/package-lock.json
- ui/panels-plugin/package.json
- ui/panels-plugin/src/plugins/markdown/MarkdownPanel.tsx
Not a lot of code, but a lot of thought 🤔 
I tried a number of the major markdown parsing libraries in Javascript. I started off trying the libraries that Luke had surfaced, then tried some others. 
Main requirements are: 
- make sure to sanitize the HTML (i.e. convert text to HTML, _then_ sanitize) 
- make sure we can support Github Flavored Markdown (GFM adds support for tables and code-blocks and is also what most developers will be used to)
- lastly, general checks like "is this library well-maintained?" and "is this library a reasonable size?"
The best options came out as:
* `react-markdown`, wrapper for chaining a bunch of plugins in the `remark` ecosystem
* `micromark`, the markdown parser in the `remark` ecosystem
* `marked`, popular markdown parser that's been around for awhile …
> Add markdown parser and HTML sanitizer to markdown panel

- scripts/ui_release.sh
This just swaps the order of the `sed` and `npm version` calls when bumping the UI package versions so that when `npm version` runs, the dependencies are already updated and don't try to resolve package dependencies against the old verison. (This was causing peer dependency conflicts in the latest attempt at a release because we upgraded the React peer dependency.)
> Swap sed and npm version calls when bumping version

- internal/cli/cmd/remove/remove.go
- internal/cli/cmd/remove/remove_test.go
This PR should fix the unit tests that failed randomly like in https://github.com/perses/perses/actions/runs/3101521684/jobs/5022971774
The tests failed because the order is not guarantee with a map. Moving to an array and sort it will definitely guarantee the order.
I took the opportunity to refactor a bit the command. I find it a bit clearer like that.
> refactor the code of the cmd remove and fix the unit tests that failed randomly

- ui/plugin-system/src/model/graph-queries.ts
- ui/prometheus-plugin/src/model/prometheus-client.ts
- ui/prometheus-plugin/src/model/time.ts
- ui/prometheus-plugin/src/plugins/graph-query.ts
Similar to what we've done with variable plugins already, this switches up the GraphQuery plugin API to be Promise-based rather than a React hook which we have trouble with loading dynamically. This should make it possible to get rid of the legacy `PluginRegistry` and start using the new implementation I created in #542.
> Switch GraphQuery plugin API to be Promise-based

- ui/panels-plugin/src/plugins/markdown/MarkdownPanel.tsx
Showed some screenshots to Mohit, he reminded me to check dark mode, which made me see that the links looked weird.
* For links, get the color from `theme`
* For code blocks, the border-radius is fixed instead of coming from `theme.borderRadius` 
* Even if people are theme-ing their buttons/containers to have a certain border-radius, I don't think this should apply to the code formatting
* For code blocks + tables, the padding depends on font-size instead of `theme.spacing()`
* theme.spacing() can defined be in terms of `px`, I think the padding for this formatting should be set to always scale with the font-size
> Update styles for markdown panel links

- ui/.eslintrc.base.js
- ui/app/src/utils/browser-storage.ts
- ui/components/src/model/units.ts
- ui/dashboards/src/context/TemplateVariableProvider.tsx
- ui/prometheus-plugin/src/model/parse-sample-values.ts
- ui/prometheus-plugin/src/model/utils.ts
- ui/tsconfig.base.json
This just makes two minor tweaks to our dev tool configs:
1. Turns on `eslint:recommended` which was somehow missing (definitely my fault 😂 )
2. Set `pretty: true` in `tsconfig` so that the Typescript compiler outputs colors for compile errors, making that more obvious in our log output
> Add eslint:recommended, enable pretty output from Typescript

- ui/app/sample-data/benchmarkDashboard.ts
- ui/app/sample-data/convert/convert-panels.ts
- ui/app/sample-data/demoDashboard.ts
- ui/core/src/model/index.ts
- ui/core/src/model/time-series-queries.ts
- ui/dashboards/src/test/plugin-registry.tsx
- ui/dashboards/src/test/testDashboard.ts
- ui/panels-plugin/src/model/calculations.ts
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
- ui/panels-plugin/src/plugins/gauge-chart/gauge-chart-model.ts
- ui/panels-plugin/src/plugins/line-chart/LineChartContainer.tsx
- ui/panels-plugin/src/plugins/line-chart/LineChartPanel.tsx
- ui/panels-plugin/src/plugins/line-chart/TimeSeriesQueryRunner.tsx
- ui/panels-plugin/src/plugins/line-chart/line-chart-model.ts
- ui/panels-plugin/src/plugins/line-chart/utils/data-transform.ts
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
- ui/panels-plugin/src/plugins/stat-chart/stat-chart-model.ts
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.test.tsx
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
- ui/plugin-system/src/components/PluginRegistry/plugin-registry-model.ts
- ui/plugin-system/src/model/index.ts
- ui/plugin-system/src/model/plugins.ts
- ui/plugin-system/src/model/time-series-queries.ts
- ui/plugin-system/src/runtime/graph-queries.ts
- ui/plugin-system/src/runtime/plugins.ts
- ui/prometheus-plugin/plugin.json
- ui/prometheus-plugin/src/index.ts
- ui/prometheus-plugin/src/plugins/graph-query.ts
- ui/prometheus-plugin/src/plugins/time-series-query.ts
As discussed in chat, this renames the very generic `GraphQuery` to the more descriptive `TimeSeriesQuery` which better reflects the output format. I tried to also rename all the related types, but I may have missed a few which we can clean-up as we find them. There are [a few lines of refactoring](https://github.com/perses/perses/pull/573/commits/8b08c2461ce9be760188df7239a07796928fbc16) in here to plugin-related types that just simplified a few of the generics that aren't helpful at runtime, but most of this is just renames.
> Rename GraphQuery to TimeSeriesQuery

- ui/app/package.json
- ui/app/src/model/health-client.ts
- ui/app/src/model/project-client.ts
- ui/app/src/render-app.tsx
- ui/components/src/test/render.tsx
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.test.tsx
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.tsx
- ui/dashboards/src/components/PanelDrawer/PanelTypeSelect.tsx
- ui/dashboards/src/test/render.tsx
- ui/package-lock.json
- ui/plugin-system/package.json
- ui/plugin-system/src/runtime/graph-queries.ts
- ui/plugin-system/src/runtime/plugins.ts
- ui/plugin-system/src/test/render.tsx
- ui/plugin-system/src/test/setup-tests.ts
- ui/prometheus-plugin/package.json
This updates our `react-query` dependency to the latest major version (v4) which helps clean-up our Jest test logs in the dashboards package where we were getting some console error messages related to that package. I also cleaned up one other warning that was getting logged by MUI due to the panel types being loaded dynamically.
> Upgrade to react-query v4, clean-up test logs

- Makefile
After trying to use promu to improve our CI, when you are cross-building the binary, the code generation should use the host arch and host os and shouldn't depend on the cross build variable.
This PR is fixing that, so the code generation doesn't depend on the cross build variable.
> use GOHOSTARCH and GOHOSTOS for code generation

- ui/app/src/model/datasource-api.ts
- ui/plugin-system/src/model/time-series-queries.ts
- ui/plugin-system/src/runtime/time-series-queries.ts
- ui/prometheus-plugin/plugin.json
- ui/prometheus-plugin/src/model/prometheus-client.ts
- ui/prometheus-plugin/src/plugins/prometheus-datasource.ts
- ui/prometheus-plugin/src/plugins/prometheus-variables.ts
- ui/prometheus-plugin/src/plugins/time-series-query.ts
This just adds an optional datasource selector to both the Prometheus variable and time series query specs. I also switched up the time series query plugins to just take the spec object and not the entire definition when fetching time series data.
> Add optional datasource selector to spec for Prom variables and time series queries

- ui/app/sample-data/demoDashboard.ts
- ui/app/sample-data/templateVariableDemo.ts
- ui/core/src/model/variables.ts
- ui/dashboards/src/components/Variables/Variable.tsx
- ui/dashboards/src/context/TemplateVariableProvider.tsx
Renaming:
- `defaultValue` -> `default_value`
- `allowMultiple` -> `allow_multiple`
- `allowAllValue` -> `allow_all_value`
> Use snake_case in spec definitions

- ui/core/src/utils/panel-refs.ts
- ui/dashboards/src/components/Dashboard.tsx
- ui/dashboards/src/components/DashboardToolbar.tsx
- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/dashboards/src/components/GridLayout/GridLayout.tsx
- ui/dashboards/src/components/GridLayout/GridTitle.tsx
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.test.tsx
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.tsx
- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/dashboards/src/components/PanelDrawer/panel-editor-model.ts
- ui/dashboards/src/context/DashboardProvider/DashboardAppSlice.tsx
- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
- ui/dashboards/src/context/DashboardProvider/dashboard-provider-api.ts
- ui/dashboards/src/context/DashboardProvider/layout-editing.ts
- ui/dashboards/src/context/DashboardProvider/panel-editing.ts
This builds on #590 (so look at that PR first) and moves the more complicated panel editing logic into a `PanelEditingSlice` into the store. The initial editor state is now in the store, making sure you can't (for example) edit a panel that doesn't exist. It also adds support for editing a panel and having it move between groups. This is what that looks like:
https://user-images.githubusercontent.com/428023/193431778-e9201073-c1b7-42ec-a7af-3b8ae1d2c75a.mov
> Move more complicated panel editing logic into dashboard state store

- ui/turbo.json
Add `npm run clean` as dependency of build in turbo.json to hopefully help with errors after switching branches caused by:
- Old build output is still around
- You pull latest code
- You run npm run start which runs a new build and moves files, but leaves old build output intact so some files from the old build are still around
See turbo docs here: https://turborepo.org/docs/core-concepts/running-tasks
> add clean as dep of build in turbo.json

- ui/dashboards/src/components/Dashboard.tsx
- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/dashboards/src/components/GridLayout/GridLayout.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx
- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
- ui/dashboards/src/context/DashboardProvider/dashboard-provider-api.ts
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
This just removes the `useDashboard` hook and some of the weird state flow where I screwed up and told Eunice we should be passing the dashboard spec around everywhere. 😂  Instead, it just uses the `layouts` and `panels` state already in the store for both view and edit modes. I haven't tried to do anything "smart" yet (like more granular selectors to help with re-rendering), just simplified the mess I made so we can start doing that.
> Use dashboard store in view mode also

- ui/app/src/model/datasource-api.ts
- ui/dashboards/src/context/DatasourceStoreProvider.tsx
- ui/plugin-system/src/runtime/datasources.ts
- ui/prometheus-plugin/src/model/index.ts
- ui/prometheus-plugin/src/model/prometheus-client.ts
- ui/prometheus-plugin/src/model/prometheus-selectors.ts
- ui/prometheus-plugin/src/plugins/prometheus-datasource.ts
- ui/prometheus-plugin/src/plugins/prometheus-variables.ts
- ui/prometheus-plugin/src/plugins/time-series-query.ts
This adds a `createClient` property to Datasource plugins. What is a client you might ask? Well, right now, it's whatever kind of object a plugin wants it to be, just so long as it takes a datasource spec and turns it into something useful. In our Prometheus plugin, we have a `PrometheusClient` object which just has methods for communicating with a Prometheus API.  Other future Datasource plugins might have their own client objects, perhaps using some well-known Javascript library for communicating with a server.
There might come a time when we decide a Datasource's client needs to implement some kind of common functionality (maybe like a health check?) but we'll see how it evolves. This also gives some flexibility to people embedding to, for example, use their own Prometheus client with …
> Add client concept to Datasource plugins

- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
Add hard-coded options to TimeSeriesChart panel as first step in chart options editing. Static panel can now be previewed in edit drawer and added to dashboards, but _nothing is editable yet_ (adding form controls is next).
> add static panel options for TimeSeriesChart

- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelContent.tsx
- ui/panels-plugin/src/plugins/empty-chart/EmptyChartPanel.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
- ui/panels-plugin/src/plugins/markdown/MarkdownPanel.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/plugin-system/src/model/panels.ts
This just simplifies Panel plugins to only take the plugin's `spec` as props, rather than the entire `PanelDefinition` object. This is consistent with what we've already done in variable and time series query plugins where we've found that the plugin code doesn't really care about the stuff in the full-blown definition at this point. It should also make building panel previews for visual editing a little easier. (See some of the discussion in #596)
> Pass spec only to panel plugins, rather than definition

- ui/components/src/StatChart/StatChart.tsx
Remove second 'No data' message, instead only use noDataOption (will be easier to keep consistent with other charts)
> bugfix redundant no data message in StatChart

- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
Follow up to discussion in #599, name can be removed completely now. Before it was an optional prop to show the name above the calculated value-- I since refactored StatChart in #462 but forgot to remove it from StatChartPanel
> remove unused panel name in StatChartPanel

- ui/app/src/model/datasource-api.ts
- ui/dashboards/src/context/DatasourceStoreProvider.tsx
- ui/plugin-system/src/runtime/datasources.ts
This adds functionality to the `DatasourceStoreProvider` to enable us to list all the datasources of a specific plugin kind (i.e. "give me all the `PrometheusDatasource` instances available"). This is so that while visually editing a time series query or variable definition, we can present the user with a list of datasources to select from. I added a hook to the plugin runtime called `useListDatasources` that should hopefully be helpful when someone is ready to build that UI.
> Allow listing datasources for a given datasource plugin kind

- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/dashboards/src/components/PanelDrawer/PanelPreview.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
Follow up to #596 
- move preview out of TimeSeriesChartOptionsEditor
- add PanelPreview.tsx component
- currently it is pulled into PanelEditorForm above PanelSpecEditor
- _I tried a few places and this seemed to work the best but open to other ideas!_
- static height was needed since by default you could only see the panel header
> create initial panel preview component

- ui/core/src/model/datasource.ts
- ui/core/src/model/definitions.ts
- ui/core/src/model/panels.ts
- ui/core/src/model/time-series-queries.ts
- ui/core/src/model/variables.ts
- ui/dashboards/src/components/Panel/PanelContent.tsx
- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/dashboards/src/components/PanelDrawer/PanelSpecEditor.tsx
- ui/dashboards/src/components/PanelDrawer/panel-editor-model.ts
- ui/dashboards/src/context/DashboardProvider/panel-editing-slice.ts
- ui/plugin-system/src/model/datasource.ts
- ui/plugin-system/src/model/panels.ts
- ui/plugin-system/src/model/time-series-queries.ts
- ui/plugin-system/src/model/variables.ts
This is a follow-up to something I noticed in #604 and adds an `UnknownSpec` type we can use at runtime, rather than using `unknown` from Typescript. Why? Because this lets us distinguish between "some unknown object" and something like `undefined` (i.e. "I don't have an object yet"). This is sometimes useful when, for example, a plugin is loading and hasn't created a spec yet and we need to tell the difference.
> Add an UnknownSpec type for framework code at runtime

- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/package-lock.json
- ui/panels-plugin/package.json
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
- ui/plugin-system/src/model/time-series-queries.ts
- ui/plugin-system/src/runtime/PluginSpecEditor.tsx
- ui/plugin-system/src/runtime/index.ts
- ui/prometheus-plugin/package.json
- ui/prometheus-plugin/src/plugins/PrometheusTimeSeriesQueryEditor.tsx
- ui/prometheus-plugin/src/plugins/time-series-query.ts
The goal of this PR is to add a query input to the panel editor.
Originally, I tried to implement this entirely inside of TimeSeriesChartOptionsEditor alone, but that didn't work.
The reason is that the TimeSeriesChart is a panel plugin that is using other plugins -- namely, query plugins. 
Each query plugins need to tell the code that uses it how to edit it, since each query plugin can have different specs. In this PR, we're achieving this by adding `OptionsEditorComponent` and `createInitialOptions()` to the query plugins. 
Additionally, this PR:
* Converted `PanelSpecEditor` to a more generic `PluginSpecEditor` that can be used for editing panel plugins AND query plugins.
* Used `PluginSpecEditor` in both `PanelEditorForm` and `TimeSeriesChartOptionsEditor` to implement the query …
> Add PluginSpecEditor to support a query input for TimeSeriesChart

- ui/dashboards/src/test/plugin-registry.tsx
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
- ui/plugin-system/src/components/PluginRegistry/test-plugins/ernie/index.ts
- ui/plugin-system/src/model/datasource.ts
- ui/plugin-system/src/model/index.ts
- ui/plugin-system/src/model/panels.ts
- ui/plugin-system/src/model/plugin-base.ts
- ui/plugin-system/src/model/plugins.ts
- ui/plugin-system/src/model/time-series-queries.ts
- ui/plugin-system/src/model/variables.ts
- ui/plugin-system/src/runtime/PluginSpecEditor.tsx
- ui/prometheus-plugin/src/plugins/prometheus-variables.ts
- ui/prometheus-plugin/src/plugins/variable.ts
At this point, we know all plugins are going to have at least two props for visual editing (`OptionsEditorComponent` and `createInitialOptions`). This just moves those props into a `Plugin` type and makes all the plugins extend from that type. Variable plugins were the ones that hadn't been updated yet with placeholder values, so I also went ahead and added those placeholders in the `prometheus-plugin` package.
> Add visual editing props to all plugins

- ui/plugin-system/src/components/PluginRegistry/plugin-indexes.ts
- ui/plugin-system/src/model/plugin-base.ts
- ui/plugin-system/src/model/plugins.ts
- ui/plugin-system/src/runtime/PluginSpecEditor.tsx
- ui/plugin-system/src/runtime/plugins.ts
This is a small follow-up to #615. In that PR, I added a `Plugin` base type that is meant to be the common props for all plugins in the `plugin-system`. The only thing missing was some kind of "enforcement mechanism" in the type system that ensured that all plugins use it. I tried out a bunch of different ways to do this, but the most straightforward way to add this enforcement mechanism was to change `PluginType` to only include plugin implementations that extend from `Plugin`.
I also realized that this basically means that consumers can now extend the plugin system with their own plugin types. For example, if in my Perses-based application I wanted to add a new plugin type, I could do something like this:
```ts
import { UnknownSpec } from '@perses-dev/core';
import { usePlugin } from …
```
> Constrain plugin types to those that use Plugin base

- CHANGELOG.md
- RELEASE.md
I just realised that the script we are using to generate the changelog that has to be pushed in the github release is catching everything between two title starting with two `#`.
This PR aims to aligne the different release title in the changelog, and to add a template title in the release documentation
> Fix release title and propose a template title in the release documentation

- ui/dashboards/src/components/DashboardToolbar.tsx
- ui/dashboards/src/components/GridLayout/GridTitle.tsx
- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupDialog.test.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupDialog.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupEditorForm.tsx
- ui/dashboards/src/context/DashboardProvider/dashboard-provider-api.ts
- ui/dashboards/src/context/DashboardProvider/index.ts
- ui/dashboards/src/context/DashboardProvider/layout-slice.tsx
- ui/dashboards/src/context/DashboardProvider/panel-group-slice.tsx
Following up on #633, this continues refactoring panel groups. This time it's the dialog so it basically follows the same pattern as the `PanelDrawer` where it exposes all the state the editor needs on open (including how to save or close without making changes). This was basically trying to make it so the editor dialog didn't need the state of _all_ panel groups just to do its work, as well as to try and be specific about what it _could_ edit (since that editor wasn't editing things like the items in the group). Hiding the "items in the group" from the editor is going to be more important as I go to split a group's items out so that drag and drop state is separate from the rest of the group's state.
Again, I left a few TODOs in here because there's more to come! 🥳 🙃 
Signed-off-by: Luke …
> PanelGroupDialog refactor to need less state, look more like PanelDrawer

- internal/cli/cmd/lint/lint.go
- internal/cli/opt/opt.go
With this PR, maybe you will more understand the need of the package `validate` @AntoineThebaud :).
I'm also wondering if we should provide an endpoint in the API to be able to download the different schemas.
WDYT @AntoineThebaud @chucknthem @LukeTillman ? 
> improve linter by supporting datasources schema and online validation

- cmd/perses/main.go
- dev/config.yaml
- internal/api/config/config.go
- internal/api/core/server.go
- internal/api/generate.go
- utils/test.go
By configuration, you are now able to deactivate any HTTP endpoint that would modify the database.
Quite useful when you are in "as code" mode and you want to provide the datasource / dashboard via a file
> Provide a way to pass the API in a readonly mode by config

- ui/dashboards/src/components/PanelDrawer/PanelPreview.tsx
- add condition to fix empty panel preview showing when no `kind` is selected
- TODO: in future, should we select TimeSeriesChart by default?
> fix panel preview unselected condition

- .gitignore
- CONTRIBUTING.md
- dev/config.yaml
- dev/data/globaldatasource.json
- dev/populate.sh
I'm modifying the script `populate.sh` so it can generate a local DB.
That will allow us to modify on the fly the DB without requiring docker, or restarting the backend.
It will be easier like that when we want to modify a dashboard and see the result in the UI. It would be painful to run the script `populate.sh` in order to modify ETCD everytime we want to test new parameters on a dashboard.
/cc @LukeTillman @eunicorn @sjcobb @saminzadeh @cndonovan 
> modify script populate to generate a local db

- ui/dashboards/src/components/DashboardToolbar.tsx
When you are on mobile, I think it's fair you cannot edit the dashboard.
Let me know what you think about :)
It's part of the issue #643 
> remove edit button on mobile

- internal/api/shared/validate/validate.go
- pkg/model/api/v1/common/reflect.go
- pkg/model/api/v1/dashboard/variable_build_order.go
- pkg/model/api/v1/dashboard/variable_build_order_test.go
With this PR, the server is now able to determinate the build order of the variables, whatever the format of the variable would be and whatever the plugin is.
As a side effect, it can detect circular dependencies and if a not defined variable is used in another variable definition.
Perhaps this build order could be exposed through an HTTP endpoint so the UI can use it. I'm not sure this calcul is already done in the front end.
/cc @saminzadeh 
> provide a way to determinate the build order of the variables

- internal/api/impl/v1/datasource/service.go
- internal/api/impl/v1/globaldatasource/service.go
- internal/api/interface/v1/datasource/interface.go
- internal/api/interface/v1/globaldatasource/interface.go
- pkg/model/api/v1/datasource.go
I'm adding two new query parameters `kind` and `default` when getting the list of datasources or global datasources.
For example:
```bash
curl -XGET http://localhost:8080/api/v1/globaldatasources?kind=PrometheusDatasource&default=true
```
This kind of request will return at most one element in the array.
/cc @LukeTillman 
> provide kind and default query parameter to filter the list of datasources

- ui/plugin-system/src/components/PluginEditor/PluginEditor.tsx
- ui/prometheus-plugin/src/plugins/MatcherEditor.tsx
- ui/prometheus-plugin/src/plugins/prometheus-variables.tsx
- ui/prometheus-plugin/src/plugins/types.ts
- ui/prometheus-plugin/src/plugins/variable.tsx
Loom demo: https://www.loom.com/share/0dfd6ccf99ce419d9e270d2ab5c7010a
This adds in the Variable plugin editors for 3 plugin types: StaticList, PromLabelValues, PromLabelNames
Eventually, the Series Selectors will be replaced with [CodeMirror](https://codemirror.net/) for syntax highlighting and autocomplete.
> Add variable plugin editors

- ui/dashboards/src/components/Variables/VariableEditor.tsx
Demo: https://www.loom.com/share/6478791cda074913936271a57480f16d
This PR allows you to change the variable order through the UI. Until we land on a drag and drop solution, we can use up and down arrows.
> Ability to change variable order

- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/dashboards/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/prometheus-plugin/src/plugins/MatcherEditor.tsx
The changes made in #668 caused the variable editor styles to be wonky. This was fixed by adding the `fullWidth` property on the inputs.
> Fix variable editor styling

- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
Now queries have nice borders that match the designs!
Also, updated the names of the handler functions to be more consistent in this file (Steven lemme know what you think)
> Add border to each query in time series chart editor

- internal/api/shared/toolbox.go
- internal/api/shared/utils.go
- pkg/model/api/v1/common/jsonref.go
- pkg/model/api/v1/common/validate.go
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard/variable.go
All resource name, variable name and panel name follow the same rule:
- more than 2 characters
- less than 75 characters
- cannot contain any space or special characters 
/cc @saminzadeh @LukeTillman 
> align the format of the different ID used

- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/dashboards/src/components/GridLayout/GridLayout.tsx
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.test.tsx
- ui/dashboards/src/components/PanelDrawer/PanelPreview.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupDialog.test.tsx
- ui/dashboards/src/context/DashboardProvider/dashboard-provider-api.ts
- ui/dashboards/src/context/DashboardProvider/delete-panel-group-slice.ts
- ui/dashboards/src/context/DashboardProvider/delete-panel-slice.ts
- ui/dashboards/src/context/DashboardProvider/index.ts
- ui/dashboards/src/context/DashboardProvider/panel-editor-slice.ts
- ui/dashboards/src/context/DashboardProvider/panel-group-editor-slice.ts
- ui/dashboards/src/context/DashboardProvider/panel-group-slice.ts
- ui/dashboards/src/context/useDashboardSpec.tsx
For each panel group, this PR splits the item state inside that panel group into two separate pieces of state:
- `itemLayouts`: an array of the layout information (`x`, `y`, `w`, `h`, and a unique ID `i`) which corresponds 1:1 with the model that `react-grid-layout` expects
- `itemPanelKeys`: a map of the unique ID of the item in `itemLayouts` -> the panel key referenced by that panel
By splitting this state up, I was then able to connect `react-grid-layout` with the store in a pretty straightforward manner. Its `onLayoutChange` handler can now just overwrite the `itemLayouts` property on a panel group every time a move/resize happens, while the content reference (i.e. panel key) remains stable. This also means that drag and drop actions should now be reflected in the object that's output …
> Connect react-grid-layout changes with dashboard store

- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
- ui/dashboards/src/components/PanelDrawer/PanelPreview.tsx
- ui/dashboards/src/context/DashboardProvider/index.ts
- ui/dashboards/src/test/plugin-registry.tsx
- ui/dashboards/src/utils/component-ids.ts
This decouples the `Panel` from dashboard store's edit state, allowing `PanelPreview` to be rendered in "view mode" when used in the panel editor. Here's what it looks like in action now (you'll see the "edit buttons" are gone in the preview component now):
https://user-images.githubusercontent.com/428023/198093684-87765333-8743-416f-a51b-1c799459051c.mov
I also tried to add a bunch of tests to `Panel` and improved some of the ARIA attributes in the process. This should start to make dashboard tests a little easier to write and (for example) look for individual panels.
> Decouple PanelPreview from edit state

- cmd/perses/main.go
- internal/api/config/config.go
- internal/api/config/database.go
- internal/api/config/schemas.go
- internal/api/core/server.go
- internal/api/e2e/framework/server.go
- internal/api/impl/config/config.go
This PR is adding a new endpoint `/api/config` that will provide the current config of the server. Ideally every secrets will be hidden. This will be address in a later PR.
Getting the config can be used by the UI to change its behaviour. For example, the config value `Readonly` can be used by the UI to hide the button `Edit`
> add an endpoint to get the backend config

- ui/dashboards/src/components/Variables/Variable.tsx
This fixes some regression that happened in #690. This ensures the default value is an empty array when the value allows for multiple. This is a good reminder to come up with some good comprehensive tests after the autocomplete refactor.
> Fix select multi value bug when options arent present

- ui/prometheus-plugin/src/index.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQuery.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQueryEditor.tsx
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/get-time-series-data.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/index.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/query-editor-model.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/time-series-query-model.ts
This fixes an issue in the panel editor where every time a user types into the query editor, the state change propagates up to the `PanelPreview` and it re-runs the Prom query. With this change, we keep a local copy of the state in the editor and then only propagate those changes once the query editor input is blurred. Here's what that looks like in action:
https://user-images.githubusercontent.com/428023/198675185-150c89b4-32b8-4987-aa83-8099004a8767.mov
Once we get a "proper" query editor in (i.e. CodeMirror), we may want to consider adding something like a "Run Query" button to make the interaction more obvious to the user.
> Run queries in editor on input blur

- internal/api/shared/schemas/loader.go
For some reason https://github.com/perses/perses/commit/44282beb66ca14735ecf9754ce8428886a51f1ba#diff-88358bf82ecc8c2771379b628ade8c9769b02abc1f8f39f3b81112e7c0854c35 broke the detection of plugin addition, as adding a new file/folder in the watched folder produces a CREATE event and not a WRITE.
> Fix file watching that was no longer detecting plugin addition

- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.test.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupDialog.test.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.test.tsx
- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
- ui/dashboards/src/context/DashboardProvider/dashboard-provider-api.ts
- ui/dashboards/src/context/DashboardProvider/panel-group-slice.ts
- ui/dashboards/src/context/DashboardProvider/panel-slice.ts
- ui/dashboards/src/context/index.ts
- ui/dashboards/src/context/useDashboard.tsx
- ui/dashboards/src/context/useDashboardResource.tsx
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
- ui/dashboards/src/views/ViewDashboard/tests/panelGroups.test.tsx
- useDashboardSpec (renamed to useDashboardResource) now returns the dashboard resource, which makes it easier for save/export to work.  
- rather than saving previous state in the store, reset function now takes in dashboard resource (similar to how setVariables works)
- prevent calling createDashboardStore every time DashboardProvider renders
> Refactor DashboardProvider and useDashboardSpec

- ui/components/src/GaugeChart/GaugeChart.tsx
Prior to this fix, the gauge chart would sometimes be clipped on the horizontal edges depending on the size of the chart.
- This change was made previously to try to fit more tightly in small screens, but led to inconsistencies with clipping.
- This PR provides a quick fix to address the gauges looking broken in some cases.
- A better long-term fix for the tighter fit on small screens will be to change how padding within panel components is managed to move it from a constant in `Panel` to being handled by individual panel components, so we can potentially do things like hide the padding on gauges based on the size. This will be done in a follow-up by the team at some point in the future.
Gauges looked fine at some sizes:
But would …
> Adjust gauge chart radius to avoid clipping

- ui/components/src/Drawer/Drawer.tsx
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.tsx
- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
This adjustment:
- Brings the UI more in line with the designs.
- Allows the scrollbar for the panel to sit on the right side of the
screen (instead of floating ~16 pixels from the right).
- Panel content fully fills the space not used by the header (instead
of sometimes having some extra whitespace).
<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td><img width="902" alt="image" src="https://user-images.githubusercontent.com/396962/199352028-a162388c-4806-4d15-ab8f-e72637bdc0ad.png"></td>
<td><img width="902" alt="image" src="https://user-images.githubusercontent.com/396962/199351937-ca0bf605-979b-4732-9a60-c6c9635a338b.png"><td>
</tr>
</table>
> Adjust panel editor padding

- GOVERNANCE.md
- MAINTAINERS.md
With the agreement of @juliusv I'm removing him from the Perses org. Thank you for your help at the beginning of Perses Julius :).
Hope you will be around to try it :).
Signed-off-by: Augustin Husson <augustin.husson@amadeus.com>
> removing Julius Volz from the Perses org

- ui/.eslintrc.base.js
- ui/app/src/Router.tsx
- ui/app/src/context/DarkMode.tsx
- ui/app/src/render-app.tsx
- ui/app/src/views/ViewDashboard.tsx
- ui/app/src/views/ViewDashboardList.tsx
- ui/app/src/views/ViewProject.tsx
- ui/components/package.json
- ui/components/src/StatChart/StatChart.test.tsx
- ui/components/src/context/ChartsThemeProvider.tsx
- ui/components/src/model/units.ts
- ui/components/src/test-utils/index.ts
- ui/components/src/test-utils/theme.ts
- ui/components/src/test/index.ts
- ui/components/src/utils/mathjs.ts
- ui/core/package.json
- ui/dashboards/package.json
- ui/dashboards/src/context/DashboardProvider/common.ts
- ui/dashboards/src/utils/component-ids.ts
- ui/panels-plugin/package.json
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
- ui/panels-plugin/src/utils/mathjs.ts
- ui/plugin-system/package.json
- ui/prometheus-plugin/package.json
While looking into some bundle size issues internally, I noticed that there were a lot of third party libraries coming from Perses packages that probably shouldn't be. This made me go an take a look at our JavaScript bundles for the Perses app (i.e. `npm run analyze -w app`). This was what it looked like when I started:
You can see we have 2.7 MB of Javascript total (before gzipping which would happen on the wire). After doing some digging around and cleaning up a bunch of things, including adding a bit of code splitting to the app, this is what things look like now:
This ended up cutting almost 800 KB of JavaScript from our bundles. This should also help folks using the Perses packages in their own bundles. I'll add a few comments inline about a few of the more interesting changes.
> Clean up imports and exports to help with package and bundle size

- ui/app/src/context/DarkMode.tsx
- ui/app/src/views/ViewDashboard.tsx
- ui/components/src/GaugeChart/GaugeChart.tsx
- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/StatChart/StatChart.test.tsx
- ui/components/src/StatChart/StatChart.tsx
- ui/components/src/context/ChartsThemeProvider.tsx
- ui/components/src/model/theme.ts
- ui/components/src/test-utils/theme.ts
- ui/components/src/utils/theme-gen.test.ts
- ui/components/src/utils/theme-gen.ts
- ui/dashboards/src/test/render.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.test.tsx
Performance bugfix to remove using registerTheme to share an ECharts theme between charts and instead pass the generated theme obj directly into our echarts wrapper component.
> perf fix to pass echarts theme directly into chart init

- ui/app/webpack.dev.ts
Just gets rid of the deprecation warning from `webpack-dev-server` about the old configuration property we were using.
> Get rid of deprecation warning from webpack dev server

- internal/api/core/middleware/proxy.go
- pkg/model/api/v1/datasource/http/http.go
- ui/app/src/model/datasource-api.ts
- ui/app/src/model/datasource-client.ts
- ui/app/src/model/url-builder.test.ts
- ui/app/src/model/url-builder.ts
With this PR, the datasources are now coming from the backend.
As a side not, it spams a lot the server. I guess every panels and variables are asking for the datasources and there is no cache (not really know how to add one in a simple way)
Here a list of query performed to get the datasources for the `Benchmark` dashboard:
```bash
INFO[2022-11-03T12:55:45+01:00]    method=GET status=200 uri="/api/v1/projects/IncredibleProject/datasources?kind=PrometheusDatasource&default=true"
INFO[2022-11-03T12:55:45+01:00]    method=GET status=200 uri="/api/v1/projects/IncredibleProject/datasources?kind=PrometheusDatasource&default=true"
INFO[2022-11-03T12:55:45+01:00]    method=GET status=200 uri="/api/v1/globaldatasources?kind=PrometheusDatasource&default=true"
INFO[2022-11-03T12:55:45+01:00] …
```
> Use the datasource coming from the backend

- ui/app/src/views/ViewDashboard.tsx
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
I'm adding a little button to be able to remove the sticky header at runtime. I'm thinking sometimes you want the full space to see the dashboard.
https://user-images.githubusercontent.com/4548045/199757533-4442f495-5952-4ee0-a346-5d2b741a1123.mov
> add a button to stick the variable header

- CHANGELOG.md
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
This PR makes it possible for a user to expand/collapse queries in the panel editor.
Things that could make this implementation easier:
- if we had IDs on queries
- if we wanted to persist the "collapsed/not collapsed" state to the backend, because then I could just attach a field to the queries themselves
Curious if anyone has thoughts on either of these things (i.e. does that sound nice / do you think it makes sense) 
> Make it possible to expand/collapse queries

- ui/panels-plugin/src/components/OptionsEditorTabs/OptionsEditorTabs.test.tsx
- ui/panels-plugin/src/components/OptionsEditorTabs/OptionsEditorTabs.tsx
- ui/panels-plugin/src/components/OptionsEditorTabs/TabPanel.tsx
- ui/panels-plugin/src/components/OptionsEditorTabs/index.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
This component will be used across a variety of plugin options to organize configuration like queries and settings into tabs.
- I'm temporarily including the changes to the time series options in this PR, but I think it should probably be done in a quick follow-up to avoid some merge issues, since many people are touching that file.
- Similarly, I am intentionally not fixing how the content inside the tabs looks to more closely match the mocks. I think that should be done in a separate task.
- The tab configuration mixes two types based on a zoom conversation with Steven and Mohit about the future of the tabs. This enables us to both manage consistency where it makes sense while still enabling customization.
- **common** tabs: …
> Add options editor tabs component

- ui/plugin-system/src/model/time-series-queries.ts
- ui/plugin-system/src/runtime/plugin-registry.ts
- ui/plugin-system/src/runtime/time-series-queries.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQuery.ts
This is a follow up to the draft PR #719 
> This addresses the problem that TimeSeries queries are run every time any variable value state is changed. This does the following:
> 
> Only load TS queries when the variables it depends on are loaded or changed.
> This requires an additional hook into the plugin dependsOn to define which variables a TS query depends on
Video demo: https://www.loom.com/share/211f502fef3c44f5977888dff44d5292
> Update TimeSeriesQuery plugins to load based on variable state

- CHANGELOG.md
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
<table>
<tr>
<th>query</th>
<td><img width="896" alt="image" src="https://user-images.githubusercontent.com/396962/200625765-2479b044-9539-4c14-81ee-ad1675fea9a0.png">
</td>
</tr>
<tr>
<th>settings</th>
<td><img width="896" alt="image" src="https://user-images.githubusercontent.com/396962/200625788-ab6fabbd-6c29-4425-9571-7591f3ef5396.png">
</td>
</tr>
<tr>
<th>json</th>
<td>
</td>
</tr>
</table>
> Organize time series options in tabs

- ui/dashboards/src/components/Panel/PanelHeader.tsx
- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
Right now `setDashboard` does not actually reset metadata, so there is no way to edit dashboard name/version/others fields.
This also fixes an issue where the panel icons are missing if panel is too small
> Update setDashboard to also set metadata

- ui/dashboards/src/components/Variables/Variable.tsx
- ui/plugin-system/src/model/variables.ts
- ui/prometheus-plugin/src/plugins/prometheus-variables.tsx
- ui/prometheus-plugin/src/plugins/variable.tsx
This updates the `dependsOn` API in the VariablePlugin to be consistent with TimeSeriesQuery plugin (see #732 for more info)
> Update VariablePlugin dependsOn API

- CHANGELOG.md
- ui/dashboards/src/components/GridLayout/GridTitle.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
- ui/dashboards/src/views/ViewDashboard/tests/panelGroups.test.tsx
When the user enters edit mode, we want to always show the panel edit icons, instead of only showing them when the user is hovering over the panel. 
In view mode, nothing changes (the user only sees the description icon when they hover over a panel).
> Always show the edit icons in edit mode (instead of on hover)

- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.test.tsx
This fixes a test unnecessarily emitting a console error like this: "Warning: An update to unstable_HistoryRouter inside a test was not wrapped in act"
Fixing this while I was poking at the jest console errors/warnings I mentioned in the matrix chat. This is the one that is fixable. I think the rest are related to https://github.com/remix-run/react-router/issues/8809.
> Wrap browser navigation in act

- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartOptionsEditor.tsx
This just adds the query editor to both stat and gauge charts while leaving the raw JSON editor in a separate tab for now to allow editing the other options we haven't built editors for yet. For example, in Stat Chart:
And in Gauge Chart:
> Add query editor to stat and gauge charts

- schemas/variables/prometheus-promql/prometheus-promql.cue
- schemas/variables/prometheus-promql/prometheus-promql.json
- ui/prometheus-plugin/plugin.json
- ui/prometheus-plugin/src/index.ts
- ui/prometheus-plugin/src/plugins/prometheus-variables.tsx
- ui/prometheus-plugin/src/plugins/types.ts
This PR is adding a new Variable plugin named `PrometheusPromQLVariable`. It allows user to enter a PromQL expression and then to select a `label_name` that will finally give the value for the variable.
https://user-images.githubusercontent.com/4548045/201677724-d31b951b-2329-4678-abd4-6b6e227e0ed4.mov
Side Note: Pretty cool to see it tooks me only 2h to implement a new simple variable plugin from scratch (aka without not so much knowledge about how it works).
> add new variable plugin: PrometheusPromQLVariable

- CHANGELOG.md
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditorSettings.test.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditorSettings.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
- ui/panels-plugin/src/plugins/gauge-chart/gauge-chart-model.ts
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
- ui/panels-plugin/src/plugins/stat-chart/stat-chart-model.ts
- ui/plugin-system/src/components/CalculationSelector/CalculationSelector.test.tsx
- ui/plugin-system/src/components/CalculationSelector/CalculationSelector.tsx
- ui/plugin-system/src/components/CalculationSelector/index.ts
- ui/plugin-system/src/model/calculations.ts
- ui/plugin-system/src/model/index.ts
This commit also includes the following changes as side effects:
- Add CalculationSelector component for configuring the `calculation` option for a panel plugin.
- Moved `calculations.ts` model to avoid circular dependencies.
- I am starting with the gauge chart to keep this PR relatively small. I'll do something similar with the stat chart in a follow-up PR.
- The `CalculationSelector` fit best in `plugin-system` based on various dependencies and preexisting models. `UnitSelector` was put in `components` because of where the `units` model was, but I wonder if `UnitSelector` should also go in `plugin-system`. It seems like a more appropriate location and would be more consistent. Thoughts?
- The units not always behaving as …
> Add UI for configuring gauge panel options

- ui/dashboards/src/components/Panel/Panel.tsx
This should address the issue mentioned in #770 where a 400 (or any JS error via the TimeSeriesQuery plugin) causes the Panel to be stuck in an error state. 
Since some of our panel plugins [throw uncaught errors,](https://github.com/perses/perses/blob/9b5263a29b07a3bc1a537d095c740d9a68eaebbb/ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx#L48) we need a way to reset the wrapping ErrorBoundary when the spec (query) changes.
Demo: https://www.loom.com/share/02b0651e45e340d89bd02edbd2ca557a
> Reset error boundary on spec change

- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditorSettings.tsx
PR is to move TimeSeriesChart panel options tab content into a separate component similar to GaugeChart and StatChart. Did this while working on new y_axis controls PR that will come later, but want to go ahead and merge this first so working in TimeSeriesChartOptionsEditor is easier for others
> separate settings editor component in time series panel

- CHANGELOG.md
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/DownloadButton/DownloadButton.tsx
- ui/dashboards/src/components/DownloadButton/index.ts
- ui/dashboards/src/components/index.ts
- Creates a blob url each time the dashboard changes (and deletes the previous blob url)
- Renders a hidden link
- When user clicks on the download button, we programmatically click on the hidden link with the download attribute and the correct blob url (the download attribute is the API that triggers putting the file into the downloads folder)
credits to @cndonovan for original implementation :)
> Export json button for dashboard 

- CHANGELOG.md
- ui/dashboards/src/components/PanelDrawer/PanelDrawer.test.tsx
- ui/dashboards/src/context/DashboardProvider/panel-editor-slice.ts
**Bug**
If you add two panels with the same name, then they reference the same panel. When you edit one panel, you'll also see the changes in the other panel
**Fix**
Create a unique panel key for each panel
> Fix duplicate panel keys

- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
- ui/plugin-system/src/components/PluginEditor/PluginEditor.tsx
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQueryEditor.tsx
> Even out the spacing between query options

- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/dashboards/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
Perses Drawer:
- has default right position
- has a default width
- requires a prop that tells it how to close when someone clicks outside the drawer 
> Use Perses Drawer component for variable editor 

- CHANGELOG.md
- ui/dashboards/src/components/GridLayout/GridLayout.tsx
Before this fix, the contents of the grid would stay small and look strange after making the browser window small and then large again.
After the fix, the grid behaves responsively, as expected.
- Open a dashboard.
- Make your browser window small to trigger the responsive behavior.
- Maker your browser window wider to go back to the larger responsive size. 
- See a dashboard with very scrunched up charts that looks odd and is hard to use.
This appears to be related to https://github.com/react-grid-layout/react-grid-layout/issues/1663.
After following the steps to reproduce the bug:
After following the steps to reproduce the bug:
> Fix bug with grid layout responsive behavior

- ui/dashboards/src/components/GridLayout/GridTitle.tsx
Mohit updated the designs for these two icons! (looks so great now)
> Update the expanded/collapsed icons for panel groups

- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
This fixes the issue where you cannot download json when in edit mode
> Add Download Button in Edit Mode

- CHANGELOG.md
- internal/api/impl/migrate/mapping.cuepart
- internal/api/impl/migrate/testdata/perses_dashboard.json
Before migrating the node exporter dashboard (as an example) would lead to having an error from the server when going to create the dashboard migrated because the name contains space.
This PR tackles this issue by removing any space in the dashboard title. The title is used in the display object.
> Fix dashboard.name when migrating from a Grafana dashboard

- CHANGELOG.md
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.test.tsx
- ui/dashboards/src/context/TemplateVariableProvider/query-params.ts
- ui/plugin-system/src/runtime/TimeRangeProvider/query-params.ts
Pressing browser back button removes each query param individually instead actually navigating to the previous page
**Before**
**After**
> Fix pressing back button removes query param individually

- CHANGELOG.md
- Dockerfile
- distroless-debug.Dockerfile
When using the docker image, it appears that the workdir `/perses` doesn't have the right usergroup which ends up by not being able to use it.
This PR is hopefully fixing this issue.
> fix the permission on the workdir perses in the docker images

- CHANGELOG.md
- go.mod
- go.sum
- internal/api/e2e/framework/data.go
- internal/cli/file/file.go
- pkg/client/perseshttp/request.go
This PR proposed to use [jsoniter](https://github.com/json-iterator/go) instead of using `encoding/json` to marshal / unmarshal data.
Using this lib is fixing the issue that you can have when using the CLI to migrate a dashboard in a yaml format.
The conversion between yaml and json doesn't work with the standard library (`encoding/json`) and result with the following error : 
```bash
Error: json: unsupported type: map[interface {}]interface {}
```
This new lib is able to manage this kind of type and as a side effect it seems more optimised. 
Let's see if in a long term we encounter some issues with this new lib.
> replace encoding/json by jsoniter

- CHANGELOG.md
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
This gets us to a better place (no crashes), but there are probably ways to improve.
We we have been seeing that the browser can freeze/crash when we open the panel editor AND the panel has multiple queries: https://github.com/perses/perses/issues/819
When we render a time series chart, we load data from the backend, then we use this data to compute `graphData`, and then pass `graphData` into `LineChart` for rendering. But computing `graphData` involves looping over every data point -- so this is the part where we can cause the browser to freeze.
The computation of `graphData` is memoized, with the main dependency being the results from the backend. 
When we open the editor, it looks like we trigger fetching data, which changes the `fetchStatus` of each query result. When there are …
> Fix panel editor crash by reducing number of expensive loops

- CHANGELOG.md
- ui/components/src/LineChart/LineChart.tsx
This PR removes an unnecessary optimization in LineChart. Now that Christine improved TimeSeriesChart panel performance in #828,  this useDeepMemo is not needed. It also contributes to the unit selector not always updating the panel preview component
> Fix panel preview shows stale properties 

- CHANGELOG.md
- schemas/common/unit.cue
- ui/components/src/StatChart/StatChart.test.tsx
- ui/components/src/UnitSelector/UnitSelector.test.tsx
- ui/components/src/model/units/time.ts
This PR improves time unit display, before the formatTime function found the largest whole time unit that could be shown. This was counterintuitive when switching between units, especially when applied to y axis formatting.  Commits include:
- Fix time units inconsistencies--instead of a custom function, [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) is now used ([more info](https://dev.to/jordanfinners/never-use-a-number-or-currency-formatting-library-again-mhb))
- _Existing properties include: 'Milliseconds', 'Seconds', 'Minutes', 'Hours', 'Days', 'Weeks', 'Months', 'Years'_
- allow `decimal_places` to be used with time units
> Fix time units display, allow decimal_places to be used

- CHANGELOG.md
- ui/components/src/DateTimeRangePicker/DateTimeRangePicker.tsx
- ui/components/src/DateTimeRangePicker/TimeRangeSelector.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx
In our app, the time range controls (the time range picker and the refresh button) appear next to some buttons, but these controls don't have the same height as the buttons. It looks broken.
Looked into the custom variants idea (julie), the make components grow to fill the container idea (luke), and the pass along specific styles to components idea (luke).
It would be cool to be able to do the fill-the-container idea, but `MUI Select` gave me a hard time on this. I wasn't able to find a way to apply styles to the underlying elements that would make them grow to fill the container. 
So, in the end, changed the external prop to `height` and use the `height` prop to (1) set the `height` of the refresh button and (2) set the vertical padding on the element that represents the time range …
> [ENHANCEMENT] Make it possible to adjust the height of the time range controls

- schemas/panels/time-series/time-series.cue
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditorSettings.tsx
- ui/panels-plugin/src/plugins/time-series-chart/VisualOptionsEditor.test.tsx
- ui/panels-plugin/src/plugins/time-series-chart/VisualOptionsEditor.tsx
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
UX feedback from @foxbat07  in time series panel for visual options and reset button text:
- step increment in sliders is now 0.25 instead of 0.5
- max is reduced for both point_radius and line_width
- reset button text now reads "Reset to Default" and icon is removed
> [ENHANCEMENT] visual options and reset btn ux feedback

- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditor.tsx
When opening + closing panel groups, we use "ChevronRight" and "ChevronDown".
This updates the query editor so that we use the same icons when opening and closing queries.
> [ENHANCEMENT] Update query editor collapse/expand chevrons to match the rest of dashboard

- ui/components/src/InfoTooltip/InfoTooltip.tsx
- ui/dashboards/src/components/GridLayout/GridTitle.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
These tooltips will show up after 0.5 sec
> [FEATURE] Add tooltips to icons in panel and panel group header

- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditorSettings.tsx
Fixes time series panel reset button in dark mode when Perses is embedded, see example of bug:
> [BUGFIX] reset btn dark mode font color

- ui/app/src/model/dashboard-client.ts
- ui/app/src/model/http.ts
- ui/app/src/model/migrate-client.ts
- ui/app/src/views/ViewDashboard.tsx
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
This PR allowed the UI to send a request to the backend to persist the modified dashboard.
Success or error message are displayed using the `Snackbar`
This PR fixes #807 
> [FEATURE] Persist dashboard modification when clicking on save button

- internal/api/core/server.go
- internal/api/impl/validate/validate.go
- internal/cli/cmd/lint/lint.go
- pkg/client/api/client.go
- pkg/client/api/validate.go
This PR add three new endpoints : 
- `/api/validate/dashboards`
- `/api/validate/datasources`
- `/api/validate/globaldatasources`
these endpoints are used by the CLI to validate dashboard and datasources using the remote server.
> [FEATURE] Add new endpoints to validate dashboard and datasource

- .github/workflows/ci.yaml
- .gitignore
- CONTRIBUTING.md
- Makefile
- RELEASE.md
- scripts/extract-changelog/extract-changelog.go
- scripts/generate-changelog/generate-changelog.go
- scripts/generate-changelog/generate-changelog_test.go
This PR is going to tackle the points raised in #838
It provides a new Go script called `generate-changelog` that create a first list of changelog entries in the file `CHANGELOG.md` based on the git history.
The script will select any logs in the git history that contains the pattern `[<catalog_entry>]` where `catalog_entry` can be `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`.
The catalog entry can be placed anywhere in the commit message and it's not case sensitive. For example: 
`legend.position now required in time series panel [BreakingChange] (#848)` will be selected
`Support snaphost UI releases (#844)` wont be selected by the script.
As a side note, if a PR contains multiple different clean commit containing a catalog entry, this PR should be merged and not squashed to …
> [IGNORE] Generate Changelog

- ui/components/src/LineChart/LineChart.tsx
- Add back OPTIMIZED_MODE_SERIES_LIMIT condition in LineChart.tsx, 
- Revert changes from PR #821
- specifically [this commit](https://github.com/perses/perses/pull/821/commits/24ab048c1e8d2c80d803ea5ac7e9837694528f1e)
- See thread here: https://github.com/perses/perses/pull/821#discussion_r1036168943
> [BUGFIX] add back optimized mode to LineChart

- pkg/model/api/v1/dashboard/variable.go
- pkg/model/api/v1/dashboard/variable_build_order.go
- pkg/model/api/v1/dashboard/variable_build_order_test.go
This PR fixed #859 
We are going to forbid the possibility to name a variable with just a number. It's not a meaningful name anyway, so it's not that bad to do that.
That should be a way to mitigate the issue #859 and to avoid to detect additional variable coming from different language.
> [BUGFIX] Fix variable collisions with promQL function

- pkg/model/api/v1/dashboard/variable.go
- ui/core/src/model/variables.ts
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
As talked on matrix sometimes ago, we figured out having a default value doesn't make sense for `TextVariable`. So default value move to be specific to `ListVariable` only
> [BreakingChange] Remove default value for TextVariable

- scripts/generate-changelog/generate-changelog.go
This PR proposed to ignore the `bump` commits that are created by `dependabot`. 
> [IGNORE] Ignore bump commit in the changelog

- pkg/model/api/v1/dashboard/variable.go
- pkg/model/api/v1/dashboard/variable_test.go
Regarding the field `default_value` available in the `ListVariable` It was possible to use an array of string or a string in the frontend, but the backend would have blocked that.
This PR aligned the type of `default_value` between the frontend and the backend.
> [BUGFIX] default_value is accepted by the backend to be a string or an array

- internal/api/shared/schemas/schemas_test.go
- pkg/model/api/v1/dashboard/variable.go
- pkg/model/api/v1/dashboard/variable_test.go
When you inline your a struct in another and both override the json unmarshal method, actually it is used the one coming from the inline struct. So whatever you are putting in addition of the inline struct will be ignored during the unmarshal step.
For the moment, I just copy and past the field coming from the struct `common.Display` to the struct `VariableDisplay`. I don't have better solution for the moment.
> [BUGFIX] Fix Unmarshal variable display

- ui/components/src/Legend/Legend.tsx
When a Mac user has the setting `Show scrollbars: "Always"`, we see a horizontal scrollbar in the legend for a time series chart. The legend text wraps to the next line, so we don't need a horizontal scrollbar. 
This PR hides the horizontal scrollbar.
> [ENHANCEMENT] Hide horizontal scrollbar in Legend

- docs/cue.md
- internal/api/impl/migrate/mapping.cuepart
- internal/api/impl/migrate/migrate.go
- internal/api/impl/migrate/testdata/old_format_grafana_dashboard.json
- internal/api/impl/migrate/testdata/old_format_perses_dashboard.json
- internal/api/impl/migrate/testdata/simple_grafana_dashboard.json
- internal/api/impl/migrate/testdata/simple_perses_dashboard.json
- schemas/panels/gauge/mig.cuepart
- schemas/panels/markdown/mig.cuepart
- schemas/panels/stat/mig.cuepart
- schemas/panels/time-series/mig.cuepart
- schemas/queries/prometheus/mig.cuepart
- schemas/variables/prometheus-label-names/mig.cuepart
- schemas/variables/prometheus-label-values/mig.cuepart
- schemas/variables/prometheus-promql/mig.cuepart
- schemas/variables/static-list/mig.cuepart
This PR brings several improvements to the migrate feature.
- Preload the mapping engine instead of building it at each and every request. -> /!\\ refresh on plugin changes (filewatch) is required due to this change, missing at the moment.
- Move the different mappings used for unit, calc.. conversion to the common file + document these, as they are now available to any plugin.
- Added migration file for PrometheusPromQLVariable.
- Support more attributes in the conversion: variable show/hide, description...
- Fix several default values that were wrongly taking the priority.
- Fix several cases where the migration was failing because of missing expected attribute.
- Fix an issue with the Hidden attribute that was getting ignored by the default json unmarshal.
Signed-off-by: AntoineThebaud …
> [ENHANCEMENT] Improvements to the migrate feature

- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/DownloadButton/DownloadButton.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx
- ui/dashboards/src/components/ToolbarIconButton/ToolbarIconButton.tsx
- ui/dashboards/src/components/ToolbarIconButton/index.ts
Addresses some issues around inconsistencies in the dashboard toolbar around inputs, buttons, icon buttons, and MUI theming.
- We were doing a little too much hardcoding in some of these components, which meant that things weren't matching up properly moving around between themes in perses and other projects. These changes attempt to simplify those changes, so that they rely more heavily on the MUI theme.
<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Was able to test this out with snapshots!
<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Was able to …
> [BUGFIX] Toolbar inputs and icons are consistent

- ui/app/src/views/ViewMigrate.tsx
- ui/components/src/JSONEditor.tsx
By default, codemirror doesn't have a maximum height. That can be ok for tiny JSON. It's less ok when you have thousand line (like in the migration page).
Also Codemirror doesn't seem to be well constraint by the width of the container like `Stack`. So I wrapped it around a `Box` and allow user to give a pre-determine `width` if necessary
> Wrape codemirror around a box and set a default height

- .github/workflows/ci.yaml
- .github/workflows/go.yml
- .github/workflows/react.yml
Prior to this change, the github actions in `ci.yaml` would run on pull request and push events. This means that when maintainers work in branches, they trigger these actions twice when working in pull requests. This is an unnecessary use of actions resources and can slow down getting work done (e.g. slowed down getting #868 done to unblock a release).
After this change, the github actions in `ci.yaml` will continue to run on pull request events. It will modify the behavior to only run on push events when they match one of the following:
- `main` branch: default project branch
- `release/*` branch: branches used to prepare releases
- `snapshot/*` branch: branches used to release one-off snapshots for testing
- `v*` tag: release tags.
Signed-off-by: Julie Pagano …
> [IGNORE] Reduce duplicate github actions

- ui/components/src/GaugeChart/GaugeChart.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditorSettings.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
- ui/panels-plugin/src/plugins/gauge-chart/gauge-chart-model.ts
Currently, `decimal_places` in GaugeChart is hard-coded to 0 and abbreviate is not respected. This PR ensures the full `unit` object is passed into the formatValue function. 
DEFAULT_UNIT is also updated so when adding a new GaugeChart panel to PercentDecimal is used instead of Percent (I've noticed that PercentDecimal gets used more often, but I'm open to reverting this change based on feedback).
Note: this is a follow up to PR #891
> [BUGFIX] GaugeChart do not ignore unit decimal_places and abbreviate

- internal/api/impl/migrate/migrate.go
- internal/api/shared/migrate/migrate.go
- internal/cli/cmd/migrate/migrate.go
This PR is adding an offline mode on the command `migrate` command in the CLI.
Like the command `lint`, user can choose to use a remote Perses serveror he can choose to use local plugin to perform the command 
> [FEATURE] Add offline mode for the migrate command in the CLI

- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/Variables/EditVariablesButton.tsx
- ui/dashboards/src/components/Variables/VariableEditButton.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/dashboards/src/components/Variables/index.tsx
* Created the `EditVariablesButton` component, so that it's possible to move the button to a different location, as designs call for.  `EditVariablesButton` contains both the button itself and the drawer for editing variables. 
* When we have many variables, they will stack on top of each other nicely (and the margins will be correct)
* The buttons saying "Add panel" and "Add panel group" are shortened to "Panel" and "Panel group" to save space (the icon and tooltip still tell the user that these buttons are for adding things). 
> [ENHANCEMENT] Move edit variables button and make variables wrap to next line

- ui/dashboards/src/components/DownloadButton/DownloadButton.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx
Similar to the `TimeRangeControls`, we want to be able to adjust the height of the `DownloadButton`.
This change will enable us to use the `DownloadButton` from the perses package, instead of using the local version of the `DownloadButton` in our app.
> [ENHANCEMENT] Add prop for adjusting the height of the DownloadButton

- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
Multiple queries crash bug - try setting lowest possible min step interval to 10 ms (this is what Grafana uses in their rounding function). Not sure this will actually fix the issue we're seeing with the page crashing after new query is Applied, but maybe it will help somewhat until we can refactor the gcd approach.
Future TODO: make “Min Interval” configurable from query editor fields
> [BUGFIX] reduce calculated min step interval in TimeSeriesPanel

- ui/core/src/model/time.ts
Follow up to #911, this PR refactors our approach for how suggestedStepMs is calculated by rounding the step values to whole numbers like: 1s, 15s, 1m, 15m, etc.
This will especially help with `getCommonTimeScale`, which was having performance issues when multiple queries were set in TimeSeriesChart.
> [BUGFIX] round suggested stepMs to improve multi query performance

- ui/dashboards/src/components/AddGroupButton/AddGroupButton.tsx
- ui/dashboards/src/components/AddGroupButton/index.ts
- ui/dashboards/src/components/AddPanelButton/AddPanelButton.tsx
- ui/dashboards/src/components/AddPanelButton/index.ts
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
With this PR: 
* When the screen size is tablet or bigger, the toolbar buttons will take up one row (existing behavior). 
* When the screen size is smaller, the toolbar buttons will be split into two rows to save space
> [ENHANCEMENT] Toolbar uses two rows for small screens

- dev/data/dashboard.json
- internal/api/shared/migrate/testdata/old_format_perses_dashboard.json
- internal/api/shared/migrate/testdata/simple_perses_dashboard.json
- schemas/panels/time-series/mig.cuepart
- schemas/panels/time-series/time-series.cue
- schemas/panels/time-series/time-series.json
- ui/components/src/Legend/Legend.tsx
- ui/components/src/LegendOptionsEditor/LegendOptionsEditor.test.tsx
- ui/components/src/LegendOptionsEditor/LegendOptionsEditor.tsx
- ui/components/src/model/graph.ts
- ui/components/src/model/legend.test.ts
- ui/components/src/model/legend.ts
- ui/components/src/theme/theme.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.test.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
This PR includes:
- [BREAKINGCHANGE] change legend position values to PascalCase
- [BUGFIX] chart resize glitch when changing legend position 
The `legend.position` change to use PascalCase for dashboard values that are string unions/enums was made for consistency with other properties like `kind` and `calculation`. I also took a quick stab at FE validation for the legend spec when inside the panel edit drawer, but this isn't meant to be a long term solution.
See Matrix chat discussion about snake_case for keys in dashboard JSON and PascalCase for values: 
https://matrix.to/#/!XNmgYIAndZOkEvQAbb:matrix.org/$1yAfafCLxONIoBfj83jN0ul2v8AhHBPXpG2QZfwHJUk?via=matrix.org&via=herail.net
> [BREAKINGCHANGE] change legend position values to PascalCase, fix resize glitch

- ui/dashboards/src/components/Variables/VariableList.tsx
Two style tweaks:
* AppBar has a background color that shows up in dark mode. It's subtle, but different from the other background color (see screenshot).
* Added a negative margin to make sure the variables don't have unnecessary padding (I added the margins in previous PR so that the variables will have margins when they wrap to next line).
> [ENHANCEMENT] Remove variable list background color

- ui/dashboards/src/components/DeletePanelDialog/DeletePanelDialog.tsx
- ui/dashboards/src/components/DeletePanelGroupDialog/DeletePanelGroupDialog.tsx
- ui/dashboards/src/components/DiscardChangesConfirmationDialog/DiscardChangesConfirmationDialog.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupDialog.tsx
For time being, we need to make sure that any Button with `variant=outlined` also has `color=secondary`
> [BUGFIX] Fix the text color for buttons with outlined variant

- dev/data/dashboard.json
- schemas/panels/time-series/time-series.cue
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
Follow up to #767 (see [comments here](https://github.com/perses/perses/pull/767#issuecomment-1316307642)), in that PR we essentially deprecated the top level `unit` in TimeSeriesChart panels. Now that most dashboards have been converted to using the preferred `y_axis.unit`, I'm removing the top level unit completely (see CUE schema update). This also makes visual editing more intuitive, because sometimes the unit you would see in our panel edit form controls would not always match what was set in the JSON (since there was no way to edit the top level unit). 
Example Demo and Benchmark dashboards are updated to pass BE validation, as well as some minor changes to options / layout as I was testing locally.
Panel editing of `y_axis.unit`
Ensure schema validation works when setting top level …
> [BREAKINGCHANGE] remove deprecated top-level `unit` in time series panel

- internal/api/core/middleware/verification.go
- internal/api/e2e/framework/scenario.go
- internal/api/shared/utils.go
When calling the endpoint `/api/v1/dashboards`, it will trigger a middleware that is decoding the body to find the what project shall be used to perform the request.
It appears it's not possible to decode multiple times the body when we are using the method `bind` from the framework `echo`.
This PR is fixing that, assuring we don't modify the request body so it can be decoded later by the business code.
> [BUGFIX] Fix API error EOF that happens when decoding multiple times the body from a middleware

- .mdox.validate.yaml
- Makefile
I'm ignoring the link to the google group email.
Randomly it returns an error and it makes the CI failed which is annoying.
> [IGNORE] ignore google email link with mdox

- ui/dashboards/src/components/DiscardChangesConfirmationDialog/DiscardChangesConfirmationDialog.tsx
- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
- ui/dashboards/src/context/DashboardProvider/panel-editor-slice.ts
- ui/e2e/src/pages/DashboardPage.ts
- ui/e2e/src/pages/PanelEditor.ts
- ui/e2e/src/tests/panelEditor.spec.ts
- ui/e2e/src/tests/panels.spec.ts
**BEFORE**
The discard changes confirmation dialog appears even when you don't make any changes 
**AFTER**
> [BUGFIX] Fix discard changes confirmation dialog showing up even when there is no change

- internal/api/shared/migrate/testdata/old_format_perses_dashboard.json
- internal/api/shared/migrate/testdata/simple_perses_dashboard.json
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard_test.go
- pkg/model/api/v1/datasource.go
- pkg/model/api/v1/metadata.go
Before this PR, this kind of JSON was accepted:
```json
{
"kind": "Dashboard",
"metadata": {
"name": "test",
"project": "perses"
}
}
```
that's not something that should be allowed. `Spec` must be defined.
> [BUGFIX] Fix empty dashboard spec that wasn't rejected

- ui/app/package.json
- ui/components/package.json
- ui/package-lock.json
- ui/package.json
- ui/panels-plugin/package.json
I'm just upgrading some dev-dependencies to be up to date.
I'm also taking the opportunity to upgrade `echarts` just to have back some fixes that might useful for us.
I have also fixed the critical issues raised by npm when you run `npm install`. I basically just run `npm audit fix`. Nothing super smart here
> [IGNORE] upgrade various dependencies

- dev/data/dashboard.json
- ui/package-lock.json
- ui/panels-plugin/package.json
- ui/panels-plugin/src/plugins/markdown/MarkdownPanel.tsx
- ui/panels-plugin/src/plugins/markdown/MarkdownPanelOptionsEditor.tsx
* Change markdown reference from https://www.markdownguide.org/cheat-sheet/ to https://commonmark.org/help/
* Update test data to have more overlap with https://commonmark.org/help/
* Update `marked` library
* Fix bug where h2 was bigger than h1
> [ENHANCEMENT] Update markdown library

- ui/e2e/src/fixtures/dashboardTest.ts
I noticed a rare flaky test run related to this in another PR ([example failure](https://github.com/perses/perses/actions/runs/4027288537/jobs/6922828092)). We have retry logic set up to catch a rare issue in a test and try again. When a retry runs on a test set that mutates dashboards, we can hit a case where the backend throws an error because we try to create a duplicate dashboard name.
This fix includes the `retry` number in the dashboard name to ensure it is unique.
> [IGNORE] Include retry in dashboard name for tests

- ui/components/src/model/units/decimal.ts
- ui/components/src/model/units/units.test.ts
In certain cases, when a custom unit such as `"unit": { "kind": "Decimal", "decimal_places": 2, "abbreviate": true }` is used, the value is not rounded. This is most noticeable for smaller values in the tooltip. Now the abbreviateLargeNumber function is only called when a value is 1000 or greater, otherwise decimalFormatter.format is called like normal.
> [BUGFIX] round small decimal values when abbreviate is set

- ui/e2e/package.json
Prior to this fix, the visual tests were not using the correct font because the happo asset uploader only caught relative asset links and our fonts use a full link including localhost.
The addition of the `HAPPO_DOWNLOAD_ALL=true` env var forces the happo asset uploader to grab all assets, which will grab the fonts. This is the easiest short-term fix. Their support team will take a look at adjusting the script to support non-relative asset links with localhost in them, and we can hopefully pull down and get a fix in the near future. We have very few external assets, so the side effects of using this env var should be minimal even if we need it for a longer period of time.
> [IGNORE] Short-term fix for visual test fonts

- ui/components/src/GaugeChart/GaugeChart.tsx
- ui/components/src/StatChart/StatChart.tsx
- ui/components/src/model/theme.ts
- ui/components/src/test-utils/theme.ts
- ui/components/src/utils/theme-gen.test.ts
- ui/components/src/utils/theme-gen.ts
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
- ui/panels-plugin/src/plugins/markdown/MarkdownPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
Previously, the panel content always added padding. This would lead to some annoying workarounds in plugins where the visualization wanted to have less or no padding.
After this fix, the panel content adds no padding and any spacing needs have moved down into the individual plugins.
This commit also adjusts some minor spacing and alignment issues in the plugins.
BREAKINGCHANGE: Panel plugins external to the perses repository can no longer depend on the container providing padding and will likely need to make some styling adjustments after this change.
Click the "details" link for happo in the status checks to see our visual tests in action! Note that there are some issues related to font loading that are being addressed in …
> [BREAKINGCHANGE] Move panel padding to plugins

- ui/e2e/src/tests/statChartPanel.spec.ts
- ui/e2e/src/tests/timeSeriesChartPanel.spec.ts
Occasionally noticing some flakiness with the loading state around echarts-based visual tests. Adding the wait for a stable canvas to all of them to see if that helps.
> [IGNORE] Wait for stable canvas in tests

- ui/components/src/Dialog/Dialog.tsx
- ui/components/src/Dialog/index.tsx
- ui/components/src/index.ts
- ui/dashboards/src/components/DeletePanelDialog/DeletePanelDialog.tsx
https://github.com/perses/perses/discussions/935
Based on the discussion, we want generic dialog components that include common UX patterns:
1. Close icon button at the top right corner
2. Dividers for dialog content
3. For dialog actions, we always want primary button with contained variant on the left and secondary button (usually Cancel) with outlined variant on the right
> [FEATURE] Generic Dialog Components

- ui/app/src/Router.tsx
- ui/app/src/components/CreateDashboardDialog/CreateDashboardDialog.tsx
- ui/app/src/components/DashboardList.tsx
- ui/app/src/components/DeleteDashboardDialog/DeleteDashboardDialog.tsx
- ui/app/src/components/RenameDashboardDialog/RenameDashboardDialog.tsx
- ui/app/src/model/action.ts
- ui/app/src/model/dashboard-client.ts
- ui/app/src/views/ViewDashboard.tsx
- ui/app/src/views/ViewMigrate.tsx
- ui/app/src/views/ViewProject.tsx
- ui/core/src/utils/text.ts
- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
- ui/dashboards/src/context/useDashboard.tsx
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
Signed-off-by: Guillaume LADORME <guillaume.ladorme@amadeus.com>
This PR initiates the dashboard CRUD. It includes:
This PR fixes #818 and  #823
> [FEATURE] UI - Add dashboard CRUD

- ui/app/src/Router.tsx
- ui/app/src/views/ViewDashboardList.tsx
Quick routing updates after testing #916 Project CRUD changes locally. 
- Add `/projects` route
- Make project names clickable
> [ENHANCEMENT] project routing and list view links

- schemas/panels/time-series/mig.cuepart
Follow up to unit breaking changes in #920. This PR fixes TimeSeriesChart migration by updating mig.cuepart file so unit is added inside `y_axis`. Now importing migrated dashboard into a project does not throw errors.
> [BUGFIX] time series migration add unit inside y_axis

- ui/e2e/src/config/base.playwright.config.ts
Previously, a global viewport was set, but would be overridden in the chrome config, so we weren't using the intended value. After this fix, the intended viewport is used.
> [IGNORE] Use specified playwright viewport

- dev/data/dashboard.json
- ui/app/src/components/Footer.tsx
- ui/dashboards/src/components/GridLayout/GridLayout.tsx
- ui/dashboards/src/constants/grid-layout-config.ts
- ui/dashboards/src/constants/index.ts
- ui/dashboards/src/context/DashboardProvider/duplicate-panel-slice.ts
- ui/dashboards/src/utils/panelUtils.test.ts
- ui/dashboards/src/utils/panelUtils.ts
- ui/e2e/src/pages/AppHomePage.ts
- ui/e2e/src/pages/DashboardPage.ts
- ui/e2e/src/pages/PanelGroup.ts
- ui/e2e/src/tests/duplicatePanels.spec.ts
- ui/e2e/src/tests/gaugeChartPanel.spec.ts
- ui/e2e/src/tests/markdownPanel.spec.ts
- ui/e2e/src/tests/panels.spec.ts
- ui/e2e/src/tests/statChartPanel.spec.ts
- ui/e2e/src/tests/timeSeriesChartPanel.spec.ts
Prior to this change, duplicate panels would always be placed on the
far left in a new row at the bottom of the dashboard.
After this change, duplicate panels are placed as follows:
- If there is space directly to the right of the panel being duplicated,
the duplicate will be placed there.
- Otherwise, the duplicate panel is placed directly below the panel
being duplicated, pushing down any panels below it.
This approach to placement of duplicate panels balances the following
considerations:
- Making it easy for the user to find a duplicate by initially placing
it close to the original panel.
- Minimizing rework for the user that may be caused if we move other
panels to make place for the duplicate panel. The grid compacts
vertically, so moving other panels downward while retaining their …
> [ENHANCEMENT] Modify placement of duplicate panels

- ui/components/src/DateTimeRangePicker/AbsoluteTimePicker.tsx
- ui/components/src/DateTimeRangePicker/DateTimeRangePicker.tsx
- ui/components/src/DateTimeRangePicker/TimeRangeSelector.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.test.tsx
- ui/e2e/src/pages/DashboardPage.ts
- ui/e2e/src/tests/timePicker.spec.ts
- ui/e2e/src/utils/index.ts
- ui/e2e/src/utils/timeUtils.ts
Prior to this fix, the text inputs for setting a custom time range attempted to turn the content of the text input into a `Date` and apply the changes on `change`. This prevented the user from modifying the input to adjust the value and would prematurely complete the time range editing interaction.
After this fix, the text inputs are treated as text while being changed. They are evaluated as dates on blur. This fix also introduces an "apply" button that must be clicked to submit the changes in the text inputs, so that the user has control of when the time range editing interaction completes using text inputs.
This change also fixes a bug where the end time minutes value selected using the clock face interface was not being saved.
- This PR is a little tricky because I'm trying to fix the …
> [BUGFIX] Allow editing of time range using inputs

- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx
This fixes the TimeRangeControls to wrap the component in a flex component with a spacing of 1. Without a wrapper, the component did not look great standalone. It also adds the ability to hide the refresh button.
TODO:
There is still some work to make this TimeRangeControls component composable for a majority of usec cases. Some examples:
- ability to pass custom time ranges
- Remove dependency of DashboardContext
> [ENHANCEMENT ] Fix styling of TimeRangeControls

- ui/components/src/Legend/Legend.tsx
Shan found a bug where a random semicolon shows below our legend when inspecting the DOM or in certain cases like shown here:
> [BUGFIX] remove semicolon below legend

- dev/data/dashboard.json
- ui/e2e/src/tests/timeSeriesChartPanel.spec.ts
Follow up to `area_opacity` PR #962 with visual regression tests for the new TimeSeriesChart panel option.
> [IGNORE] add visual options test for time series panel

- ui/components/src/model/graph.ts
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.test.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/plugin-system/src/model/time-series-queries.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/get-time-series-data.ts
Change TimeSeries results types to regular Array instead of Iterable. We had plans to leverage Iterables early on when these types were defined that haven't really materialized. Changing to a regular Array so we can remove `Array.from` calls in many files and makes working with our packages a little easier.
> [BREAKINGCHANGE] TimeSeries and TimeSeriesValueTuple Iterable type change

- pkg/client/api/v1/project_test.go
Somehow the test that is checking the number of element of the project list is flacky with MySQL. Until we figure out what's going one, the test is disable to avoid noisy fake failure in the CI.
> [IGNORE] Disable integration test that is flacky

- ui/core/src/model/http.ts
- ui/prometheus-plugin/src/model/prometheus-client.ts
- ui/prometheus-plugin/src/plugins/prometheus-datasource.ts
As discussed in original datasource proposal, passing custom `headers` are supported. This PR implements this in the context of our PrometheusDatasource. This required updates in createClient as well as the fetchWithPost function.
> [ENHANCEMENT] Pass headers in Prometheus datasource createClient

- dev/data/dashboard.json
- ui/e2e/src/tests/timeSeriesChartPanel.spec.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
We got feedback that our legend is too scrunched up when using `position: 'Bottom'`. This PR increases our time series panel's legend size when panels reach a certain height (breakpoint currently set to 300 but this can be adjusted).
> [ENHANCEMENT] Legend height increased for tall panels

- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
If a dashboard passed into the DashboardProvider has `layouts` or `panels` that are `undefined`/`null` for some reason, this guarantees that they are initialized to `[]` or `{}`.
> [BUGFIX] Add null checks for layouts and panels in DashboardProvider

- ui/core/src/model/time-series-queries.ts
- ui/plugin-system/src/model/time-series-queries.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/get-time-series-data.ts
`TimeSeriesData` now supports optional `Labels`. This is helpful when consumers of TimeSeriesData need to know which labels are associated to a time series.
Here is an example:
> [ENHANCEMENT] TimeSeriesData now supports labels

- ui/e2e/src/pages/Panel.ts
Some of the flakiness was likely related to the panel being moused over as a result of the "trial click" workaround to wait for a stable panel. Trying out replacing that with a `scrollIntoViewIfNeeded`, which also checks for a stable element, but does not mouseover, and as an added benefit, it will make sure the panel is scrolled into view.
https://playwright.dev/docs/actionability
This led to a bunch of changes in the visual diffs for panels because the mouse is no longer sitting over the panel. I think this should lead to less flakiness going forward. If we have cases where we want to test the mouseover, we should do that explicitly with an explicit location, so there is not flakiness.
> [IGNORE] reduce visual test flakiness

- internal/api/e2e/dashboard_test.go
- internal/api/e2e/framework/data.go
- internal/api/e2e/framework/scenario.go
- internal/api/shared/database/file/file.go
- internal/api/shared/database/file/query.go
- internal/api/shared/database/file/query_test.go
this PR is here to fix #959
I'm adding a dedicated e2e tests to cover the use case described by the opened issue.
The issue was only when the FileDB were used. After a couple time to figure out what's happening, I entirely review the way we are building the query for the FileDB. It wasn't really coherent but no I think it's far better and also cover other use cases like doing this query : `curl -XGET http://perses.dev/api/v1/dashboards?name=perses`.
In the use case above I think the query parameter `name` was ignored.
> [BUGFIX] Fix getting dashboard from an empty project

- ui/dashboards/src/components/EditJsonButton/EditJsonButton.tsx
- ui/dashboards/src/components/ToolbarIconButton/ToolbarIconButton.tsx
There are two react warnings displayed in the console.
> [BUGFIX] Fix React Warnings

- ui/components/src/Legend/Legend.stories.tsx
- ui/components/src/Legend/Legend.tsx
- Marking this as BUGFIX because of the change to export `LegendProps`.
- I thought this would be a good example to help with debugging the Legend performance issues when we're ready to dig into that.
I show the reasoning for the scalability story and how it works in this loom.
https://www.loom.com/share/f4efa85e867742d993c0cd59d506c9f2
> [BUGFIX] Add story for Legend and export LegendProps

- internal/api/e2e/project_test.go
- internal/api/impl/v1/dashboard/persistence.go
- internal/api/impl/v1/datasource/persistence.go
- internal/api/impl/v1/folder/persistence.go
- internal/api/impl/v1/project/service.go
- internal/api/interface/v1/dashboard/interface.go
- internal/api/interface/v1/datasource/interface.go
- internal/api/interface/v1/folder/interface.go
- internal/api/shared/database/file/file.go
- internal/api/shared/database/model/dao.go
- internal/api/shared/database/sql/query.go
- internal/api/shared/database/sql/query_test.go
- internal/api/shared/database/sql/sql.go
- internal/api/shared/dependency/service_manager.go
Before this PR, when you remove a project, the related dashboards, folders and datasources were not removed as well. So when you re-created the project with the same name, you were seeing again the old dashboard / folders / datasources
> [BUGFIX] Fix the deletion of a project that didn't remove the related dashboards

- ui/dashboards/src/components/EmptyDashboard/EmptyDashboard.stories.tsx
- ui/dashboards/src/components/EmptyDashboard/EmptyDashboard.tsx
- ui/turbo.json
Commit also includes a tweak to the turbo.json for storybook that I noticed was needed while working on this change.
> [ENHANCEMENT] Empty state can include image

- internal/api/core/middleware/verification.go
- internal/api/impl/v1/dashboard/service.go
- internal/api/impl/v1/datasource/service.go
- internal/api/impl/v1/folder/service.go
- internal/api/impl/v1/globaldatasource/service.go
- internal/api/impl/v1/project/service.go
- internal/api/shared/error.go
By adding the management of database error in the method `HandleError` called in a HTTP middleware, we can simplify a lot the error management in the different services
> [IGNORE] simplify the error management

- ui/app/webpack.prod.ts
When we are building the UI for the production, we don't need anymore to generate the source map.
It also reduced the binary from 22 MB to 19 MB.
> [IGNORE] don't generate source map when building the ui

- ui/package-lock.json
- ui/prometheus-plugin/package.json
This PR update the dependence `@prometheus-io/codemirror-promql` to the last version and remove the dependency to `@prometheus-dev/lezer-promql` which is already brought by `codemirror-promql`
> [IGNORE] bumps @prometheus-io/codemirror-promql to v0.43.0

- internal/api/shared/migrate/migrate.go
- ui/app/src/views/ViewMigrate.tsx
We have currently 2 issues with expanded rows when attempting dashboard migration: 
1. When a row is expanded in Grafana, its children panels are no longer considered its children but instead put as siblings into the same list. For instance, if you have this dashboard with collapsed rows:
```
{ 
...
panels: [
{
type: "row"
panels: [
A,
B,
C,
]
},
{
type: "row"
panels: [
D,
E,
F,
]
},
]
}
```
If the first row is expanded, this is how the datamodel would look like:
```
{ 
...
panels: [
{
type: "row"
panels: []
},
A,
B,
C,
{
type: "row"
panels: [
D,
E,
F,
]
},
]
}
```
Due to our current (too simplistic) way of processing the panels, any panel contained in an expanded row will get put at the top of the Perses dashboard without any parent row.
2. [Library …
> [IGNORE] Migrate screen: add recommendation about keeping rows collapsed

- ui/.eslintrc.base.js
- ui/app/src/context/DarkMode.tsx
- ui/e2e/src/config/base.playwright.config.ts
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditorSettings.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
- ui/plugin-system/src/runtime/time-series-queries.ts
- ui/storybook/src/config/decorators/WithBackground.tsx
- ui/storybook/src/config/decorators/WithThemes.tsx
Commit also fixes any duplicate imports caught by the rule.
I ran into this while working on the refactor for https://github.com/perses/perses/pull/1053. Removing duplicate imports makes these sorts of refactors easier and makes the code a little cleaner. I'm hoping this is a non-controversial eslint rule, but please let me know if you disagree with adding it!
> [IGNORE] add eslint rule to avoid duplicate imports

- ui/e2e/src/tests/persesApp.spec.ts
There is a small edge case where the page doesn't finish reloading the empty state when switching themes. Moving the check for the page content into the theme check loop should fix this.
> [IGNORE] Fix flaky visual test

- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
Prior to this change, the info icon was only shown when the user was hovering over the panel, which significantly reduces discoverability of the description information, especially on larger dashboards.
After this change, the info icon is always shown in "view" mode when a panel has a description. The hover over the icon to show the description in a tooltip continues to behave as before.
Making this change based on a request from @foxbat07  to improve usability.
> [ENHANCEMENT] always show info icon when panel has a description

- ui/app/package.json
- ui/app/src/model/datasource-api.ts
- ui/app/src/views/ViewDashboard.tsx
- ui/package-lock.json
This PR is another proposition to fix #806.
The idea here is to proposed two implementations of the interface `DatasourceAPI`. 
* The first one `HTTPDatasourceAPI` is the regular implementation that is simply contacting the backend like it is done currently on the `main` branch.
* The second one is using a LRU cache in order to save temporary the list of the datasources used by the dashboard.
Finally, the cache is warming up before the dashboard is loaded, so each panel is actually using the cache to get their datasource and doesn't contact the backend anymore.
With this PR for the dashboard `Benchmark`, it contacts the backend 6 times instead of 20.
> [BUGFIX] Fix datasource spamming by using a cache

- internal/api/shared/migrate/migrate.go
- internal/api/shared/migrate/migrate_test.go
- internal/api/shared/migrate/testdata/expanded_rows_after.json
- internal/api/shared/migrate/testdata/expanded_rows_before.json
- ui/app/src/views/ViewMigrate.tsx
This PR fixes an issue with children panels that were getting wrongly positioned in the translated Perses dashboard, in case their parent row was expanded. This issue came from a (weird) behavior of Grafana that I explained in previous PR #1044 (also detailed in code comments).
> [BUGFIX] Migrate feature: fix issue with children panels wrongly positionned

- ui/components/src/LineChart/LineChart.tsx
Follow up to PR #1023 to add an undefined check when using __experimentalEChartsOptionsOverride to hide the custom TimeSeriesTooltip
> [BUGFIX] Add undef check to fix add panel showContent error

- ui/app/src/components/DashboardList.tsx
- ui/components/src/InfoTooltip/InfoTooltip.tsx
- ui/components/src/ThresholdsEditor/ThresholdInput.tsx
- ui/dashboards/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/e2e/README.md
- ui/e2e/src/fixtures/dashboardTest.ts
Adding e2e test failures on console errors because it would have caught the bug found in https://github.com/perses/perses/pull/1067.
*Saving this for future me when I squash this PR*
This commit introduces functionality that fails Playwright-based e2e tests if console errors
are seen during the test because this is often a sign of a subtle bug we would not catch
otherwise. 
As part of introducing this, we need to fix some of the underlying console errors from 
libraries we use (e.g. MUI, React). In one case, we ignore an emotion error because it is
tricky to fix and focused on a use case we are not currently focused on (SSR). Fixes include:
- Fixing React errors related to a text input changing from uncontrolled to controlled because a
text input could sometimes be `undefined`. These now …
> [BUGFIX] miscellaneous fixes to address console errors

- .github/workflows/ci.yaml
- ui/.gitignore
- ui/components/package.json
- ui/core/package.json
- ui/dashboards/package.json
- ui/package-lock.json
- ui/package.json
- ui/panels-plugin/package.json
- ui/plugin-system/package.json
- ui/prometheus-plugin/package.json
- ui/typedoc.json
I have been struggling to keep track of what Perses exports from the various UI packages, which can make it tricky to figure out breaking changes when things are refactored. Typedoc does a nice job evaluating the entry point and creating documentation, so that seemed like a low effort way to get this information.
In the short term, storing these as artifacts in github actions runs. Longer-term, we could potentially publish these in github pages alongside storybook (which is only good at documenting React components) to provide documentation for the non-component utilities, types, etc. that Perses provides.
It is notable that typedoc isn't great at handling cross-package dependencies at this time, so there are some limitations to what we're getting. We can watch this issue to see when this …
> [IGNORE] Add simple typedoc setup

- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/TimeSeriesTooltip/SeriesInfo.tsx
- ui/components/src/TimeSeriesTooltip/TimeSeriesTooltip.tsx
- ui/components/src/TimeSeriesTooltip/TooltipContent.test.tsx
- ui/components/src/TimeSeriesTooltip/TooltipContent.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
Revert `showQuery` prop addition in LineChart's tooltipConfig, always use series name instead of trying to be smart about parsing out metric name in certain cases.
> [BUGFIX] Revert tooltip prop to show full query and always show resolved series name

- ui/components/src/TimeSeriesTooltip/tooltip-model.ts
- ui/components/src/TimeSeriesTooltip/utils.ts
Fixes the following tooltip positioning issue where on longer pages with lots of panels, there are certain cases where the tooltip shows way too high on the page, this PR adjust which x and y mouse coordinates are used to position the tooltip
> [BUGFIX] Fix tooltip position on long dashboards

- internal/api/e2e/dashboard_test.go
- internal/api/e2e/framework/data.go
- internal/api/e2e/framework/server.go
- internal/api/e2e/migrate_test.go
- internal/api/shared/migrate/migrate_test.go
- internal/api/shared/validate/testdata/variable_with_regex_dashboard.json
- internal/api/shared/validate/validate_test.go
- internal/cli/cmd/describe/describe_test.go
- internal/cli/cmd/get/get_test.go
- internal/cli/test/test.go
- internal/test/test.go
- pkg/model/api/v1/dashboard/variable_build_order.go
When migrating/validating a dashboard with such variable query expr:
`thanos_build_info{stack=~"$iaas_loc.*"}`
we would encounter such validation issue (notice the trailing dot):
`bad request: variable "iaas_loc." is used in the variable "stack" but not defined`
So the easiest & pragmatic solution for now is simply to not authorize characters like `.` in variables name that could conflict with regexp syntax, which was basically the case before [last change](https://github.com/perses/perses/commit/ba17e4d2e073f766b41d7d9ae7819c36bf424d0f#diff-5fee94bdc9b5e8bf134768e6f062f3379a78da68cefa3f3ecf9690c72b3ed9efL24).
⚠️ Also there was a misalignment with the regexp used on the frontend side
https://github.com/perses/perses/blob/main/ui/dashboards/src/components/Variables/VariableEditorForm/Variab …
> [BUGFIX] Dashboard validation: fix issue with variable parsing when the query embeds a regexp

- ui/components/package.json
- ui/components/src/Legend/CompactLegend.tsx
- ui/components/src/Legend/Legend.stories.tsx
- ui/components/src/Legend/Legend.tsx
- ui/components/src/Legend/ListLegend.tsx
- ui/components/src/Legend/ListLegendItem.tsx
- ui/components/src/model/legend.ts
- ui/package-lock.json
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.test.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
Prior to this fix, the entire legend would be rendered. This causes browser performance issues when there are a lot of items.
This fix modifies the legend to do the following:
- Virtualize the list variation of the legend.
- The `Right` positioned legend will always be virtualized because it always uses the list variation of the legend. The UX is consistent with prior behavior.
- The `Bottom` positioned legend will continue to use the compact, non-virtualized varation of the legend when it has a relative small (<500) items. When it has a larger (>= 500) items, it will instead be rendered with the list variation of the legend, so it can be virtualized. This is necessary because it would be very difficult to virtualize the compact view. The UX of skimming hundreds of items is much harder …
> [ENHANCEMENT] Virtualize legend to fix perf issues

- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/dashboards/src/components/Variables/index.tsx
Prior to this fix, the list variable used the variable's display name for the accessible input label and the variable's name for the `label` field on the select, which is turned into a `fieldset` that is used to leave space for the label in MUI. When these values have mismatched sizes, this can lead to unexpected rendering of the label.
You can reproduce this bug by giving a list-based template variable a short name and a long display name. This bug does not happen in text-based template variables.
> [BUGFIX] List variable input label should match fieldset

- ui/components/package.json
- ui/components/src/model/units/bytes.test.ts
- ui/components/src/model/units/bytes.ts
- ui/components/src/model/units/units.test.ts
- ui/package-lock.json
* Add `numbro` package
* Use `numbro` with `base: decimal` to get units that are powers of 1000
* Use `Intl.NumberFormat` with `{ style: 'unit', unit: 'byte' }` instead of `{ style: 'decimal' }`
* Add a bunch of unit tests
> [ENHANCEMENT] Format bytes with units that are powers of 1000

- ui/components/src/OptionsEditorLayout/OptionsEditorControl.tsx
- ui/components/src/StatChart/StatChart.tsx
- ui/components/src/ThresholdsEditor/ThresholdInput.tsx
- ui/components/src/ThresholdsEditor/ThresholdsEditor.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
- ui/panels-plugin/src/plugins/stat-chart/utils/data-transform.test.ts
- ui/panels-plugin/src/plugins/stat-chart/utils/data-transform.ts
Stat chart value wasn't using threshold color, so if sparkline was disabled, you could not tell if the chart met the threshold or not.
**BEFORE**
**AFTER**
Also updated the look of Thresholds Editor:
> [BUGFIX] Stat chart value to use threshold color

- ui/dashboards/src/components/Dashboard/Dashboard.stories.tsx
- ui/storybook/src/utils/requests/queryRangeRequests.ts
I stabilized the data, but NOT the time range in my previous commit, leading to some flaky visual tests. This commit stabilized the time range.
> [IGNORE] stabilize time range in story

- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/utils/palette-gen.ts
When testing with a migrated Node Exporter dashboard locally ([JSON here](https://grafana.com/grafana/dashboards/1860-node-exporter-full/)), I saw this warning in the console related to our legend:
This PR ensures that the keys will always been unique.
> [IGNORE] Ensure unique ids are used in legend

- ui/dashboards/src/components/Dashboard/Dashboard.stories.tsx
- ui/storybook/src/utils/happo/canvasUtils.ts
If we do not wait, you can end up with flaky diffs where a loading state is still shown.
This commit also modifies the `waitForStableCanvas` utility to support multiple canvases, which is common when testing a dashboard with multiple panels.
> [IGNORE] Wait for canvases in storybook visual test

- ui/components/src/TimeSeriesTooltip/tooltip-model.ts
Show more focused series in our TimeSeriesTooltip by default. 
Pin tooltip feature is not very discoverable and users think there isn't a way to get inside our tooltip and scroll. Until we address this, increasing the height is best workaround.
> [ENHANCEMENT] Increase tooltip max height to fit more series w/o scrolling

- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
Very slight improvement to TimeSeriesChart hover / focused series emphasis behavior. Tried adjusting non-focused series line opacity on blur. Removed the line width increase on emphasis and added: 
- https://echarts.apache.org/en/option.html#series-line.emphasis.focus
- https://echarts.apache.org/en/option.html#series-line.emphasis.blurScope
https://user-images.githubusercontent.com/9369625/232081609-d278b38e-8137-49d1-9ed0-62b32498507a.mp4
https://user-images.githubusercontent.com/9369625/232081659-e19e83aa-eab4-4c99-b80c-1102e959ece5.mp4
https://user-images.githubusercontent.com/9369625/232084265-ab546f15-82a0-4561-bc8e-948f513cde11.mp4
> [ENHANCEMENT] Highlight behavior slight improvement using opacity blur

- ui/components/src/YAxisLabel.tsx
- ui/e2e/src/tests/panelEditor.spec.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartOptionsEditorSettings.tsx
- ui/panels-plugin/src/plugins/time-series-chart/YAxisOptionsEditor.tsx
Feedback from Mohit so that it's more clear that the Reset button is for all panel options and not just related to the thresholds controls above it.
Added an e2e test that open add panel drawer, clicks settings tab, types a y_axis.label of "Memory" and then clicks the Reset button to check whether the axis label in the chart preview is hidden.
> [ENHANCEMENT] Move time series panel reset button

- scripts/api_backend_dev.sh
you can now use it like that:
```bash
./scripts/api_backend_dev.sh --override
```
In case the folder `loca_db` doesn't exist when running this script whatever the flag is used, it will generate the DB.
But in case it already exists, then you need to use the flag `--override` to re-generate it
> [IGNORE] add override flag that would reset the local DB

- ui/dashboards/src/stories/decorators/WithPluginRegistry.tsx
- ui/plugin-system/src/components/PluginEditor/PluginEditor.test.tsx
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
- ui/plugin-system/src/model/plugins.ts
- ui/plugin-system/src/runtime/plugin-registry.ts
- ui/plugin-system/src/test-utils/mock-plugin-registry.tsx
- ui/plugin-system/src/test/render.tsx
Because of the changes in #1032, if `TimeSeriesQuery` isn't defined in DefaultPluginKinds, it will have weird/unexpected behaviors in the query editor. 
**BEFORE** 
```
export interface PluginRegistryProps {
children?: React.ReactNode;
pluginLoader: PluginLoader;
defaultPluginKinds?: DefaultPluginKinds; // optional before
}
```
```
export type DefaultPluginKinds = Partial<Record<PluginType, string>>; // all plugin types were optional
```
**AFTER**
```
export interface PluginRegistryProps {
children?: React.ReactNode;
pluginLoader: PluginLoader;
defaultPluginKinds: DefaultPluginKinds; // this is now required
}
```
```
type PluginKinds = Partial<Record<PluginType, string>>;
export type DefaultPluginKinds = 
Required<Pick<PluginKinds, 'TimeSeriesQuery'>> // "TimeSeriesQuery" is now required …
```
> [BREAKINGCHANGE] Make "TimeSeriesQuery" required in DefaultPluginKinds

- ui/components/src/model/units/bytes.test.ts
- ui/components/src/model/units/decimal.test.ts
- ui/components/src/model/units/percent.test.ts
- ui/components/src/model/units/percent.ts
- ui/components/src/model/units/units.test.ts
This PR updates the formatting for the percent values. 
Right now, if the user picks `Percent` as the unit but the `decimal_places` option is undefined, and the value is`100`, then it would be automatically formatted as `100.00%`. We don't want those extra decimal places. 
This PR updates the logic so that if `decimal_places` is undefined, then we format based on significant digits instead of decimal places. 
See tests for how different values will be handled!
> [ENHANCEMENT] Improve formatting for percent values 

- internal/api/shared/error.go
When the API is in a readonly mode, if you try to delete an object it currently returns an HTTP error 500 "internal server error" instead of saying that the method or the route doesn't exist.
This PR is fixing that
> [BUGFIX] Fix http method not allowed not handled

- internal/api/config/database.go
- internal/api/shared/database/database.go
This PR add a ``sql.tls_config`` configuration that will allow TLS configuration foe database connections exactly with the same configuration as in prometheus.
None
> [FEATURE] Allow TLS configuration for mysql database

- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQueryEditor.tsx
Add context when using our Prom query editor so that users know how to use the `series_name_format` input, open to feedback on the wording!
https://user-images.githubusercontent.com/9369625/231636902-d2e2a5d4-abd7-4de7-a76d-9784d392347a.mp4
> [ENHANCEMENT] Add help text and placeholder for series_name_format control

- ui/prometheus-plugin/src/utils/utils.test.ts
- ui/prometheus-plugin/src/utils/utils.ts
When a label_name token inside the double curly braces (aka handlebars syntax) for our `series_name_format` field in the query editor tab has no corresponding label values or is unintentionally set to value that isn't reflected in the query results, our formatter function used to show the token itself. Now instead, an empty string is returned, which makes more sense and is a better fallback for new users who might not 100% understand how this somewhat confusing field actually works under the hood (hopefully in the future, this will only be exposed to power users and we come up with a higher level, more intuitive way to format series names automatically and tie it to the legend more visibly).
- Does the time change? You need to use …
> [BUGFIX] Series name formatter return empty string when no resolved label value

- ui/components/src/EChart/EChart.tsx
- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/StatChart/StatChart.tsx
Every usage of our echarts wrapper component `EChart.tsx` ends up setting an sx prop to control width and height resize behavior. This PR allows `width: '100%', height: '100%'` to be set by default. It is not a breaking change since combineSx is added and explicitly defining will not break anything, but those lines can be removed now if a user prefers to rely on defaults.
Building on PR #1112 to avoid merge conflicts and that PR will be merged first (legend highlight PR will be next in this PR stack).
> [ENHANCEMENT] Allow echarts wrapper to default to fluid width and height 

- ui/app/src/components/CreateDashboardDialog/CreateDashboardDialog.tsx
- ui/app/src/views/home/HomeView.tsx
We shouldn't be able to create dashboard without creating a project before + fix a issue when there was only one dashboard 😅 
> [BUGFIX] Fix dashboard creation dialog when there is one or less dashboards

- ui/app/src/views/home/ProjectsAndDashboards.tsx
This PR is improving the search in the home page.
Before when you were searching for a particular dashboard, it didn't returned the dashboard that matched the search. But it returned the project with every dashboards including the one that is matching.
Result with this PR:
> [ENHANCEMENT] improve search in the home page

- ui/.eslintrc.base.js
- ui/app/src/views/home/ProjectsAndDashboards.tsx
- ui/app/webpack.dev.ts
- ui/ui-guidelines.md
We previously [ran into some issues](https://github.com/perses/perses/pull/1127) where the webpack overlay caused
problems with e2e tests because there was an eslint warning that
triggered the webpack overlay. This commit will help minimize that
recurring in the future by doing the following:
- Change the webpack overlay to be off by default and opt-in using an
env var.
- Change eslint rules to all be "error" (instead of "warn"). This makes
it clearer to developers when they broke an eslint rule in the PR
checks.
- We could consider looking into having the e2e tests run against prod webpack, but if we do that, I think we'd lose throwing errors on those dev mode console errors we get from react/mui/etc., which can help us catch subtle bugs. Let me know if you feel strongly about one vs. …
> [IGNORE] Make webpack overlay opt in and use error for eslint rules

- ui/components/src/UnitSelector/UnitSelector.test.tsx
- ui/components/src/UnitSelector/UnitSelector.tsx
- ui/components/src/model/units/bytes.test.ts
- ui/components/src/model/units/bytes.ts
- ui/components/src/model/units/constants.ts
- ui/components/src/model/units/decimal.test.ts
- ui/components/src/model/units/decimal.ts
- ui/components/src/model/units/percent.ts
- ui/components/src/model/units/time.ts
- ui/components/src/model/units/units.ts
- ui/components/src/model/units/utils.ts
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditorSettings.test.tsx
- ui/panels-plugin/src/plugins/gauge-chart/gauge-chart-model.ts
- ui/panels-plugin/src/plugins/stat-chart/StatChartOptionsEditorSettings.test.tsx
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
This PR makes it possible to set `decimal_places` as `undefined` in the UI.
~To do this, I had to change the "Decimals" input from a dropdown to an input with `type="number"`.~
This allows the default behavior to kick in: When `decimal_places` is undefined, we can fall back to using significant figures to format numbers.
> [ENHANCEMENT] Make it possible to set decimal_places as undefined in UI

- Dockerfile
- distroless-debug.Dockerfile
Fixing favicon & font requests returning 500 (seeker can't seek) inside distroless container.
Found the issue and the fix thanks to: https://github.com/jaegertracing/jaeger/pull/3569
- net/http depends on mime-type to set the Content-Type for a http response (https://github.com/golang/go/blob/master/src/net/http/fs.go#L173-L176)
- mime-type is calculated using https://pkg.go.dev/mime#TypeByExtension (https://github.com/golang/go/blob/master/src/net/http/fs.go#L235)
- In distroless, there is no default installation of mime-type library hence net/http was setting application/text for favicon.ico which was leading to 500. Adding mailcap package will install /etc/mime.types (https://pkgs.alpinelinux.org/contents?branch=edge&name=mailcap&arch=x86_64&repo=main) and fix the issue by setting the …
> [BUGFIX] Fix favicon returning 500 inside container

- ui/panels-plugin/src/plugins/time-series-chart/VisualOptionsEditor.tsx
This was meant to be removed in #1124 (I messed up a rebase at some point 😞 since it was deleted at one point)
Mohit had asked for visual editing of palette to be removed, it also doesn't 100% work now that we automatically change the palette based on total series.
> [BUGFIX] Remove palette edit buttons after merge issue

- ui/dashboards/src/components/EditJsonDialog/EditJsonDialog.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx
- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
- ui/dashboards/src/context/DashboardProvider/dashboard-provider-api.ts
- ui/dashboards/src/context/useDashboard.tsx
Now that a JSON editor was added in #1012, this PR allows saving a new `duration` from the editor. 
This is just the first PR of multiple that will allow users to pick if they want to save the selected time range as default and/or the selected variables as default.
https://user-images.githubusercontent.com/9369625/236255218-cfdd270f-4a0a-4ff2-beac-55b055abd169.mp4
> [BREAKINGCHANGE] Allow saving `duration` from JSON editor, useDefaultTimeRange renamed to useDashboardDuration

- ui/plugin-system/src/stories/shared-utils/decorators/WithPluginRegistry.tsx
- ui/storybook/src/config/main.ts
This PR helps address https://github.com/perses/perses/pull/1121#discussion_r1181679790. 
> [IGNORE] stories can directly import plugin.json files

- ui/dashboards/src/components/DashboardStickyToolbar/DashboardStickyToolbar.tsx
- ui/dashboards/src/components/DashboardStickyToolbar/index.ts
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/dashboards/src/components/index.ts
Add time range and refresh buttons to the sticky toolbar (fix: #797).
> [ENHANCEMENT] Add timerange and refresh buttons on the sticky toolbar

- ui/components/src/StatChart/StatChart.tsx
While playing around with the Stat Chart, I noticed there was extra padding around the text when the chart doesn't have a sparkline. 
I figure this helps center the text a bit more.
> [ENHANCEMENT] Improve centering for stat chart

- ui/components/src/UnitSelector/UnitSelector.test.tsx
- ui/components/src/UnitSelector/UnitSelector.tsx
- ui/components/src/model/units/bytes.test.ts
- ui/components/src/model/units/bytes.ts
- ui/components/src/model/units/decimal.test.ts
- ui/components/src/model/units/decimal.ts
- ui/components/src/model/units/percent.test.ts
- ui/components/src/model/units/percent.ts
- ui/components/src/model/units/time.ts
This is a follow-up to a bunch of number formatting work.
We noticed we had a lot of numbers with unnecessary decimal places like 100.00, 400.00, etc.
We changed "Decimals" and made it so that when "Decimals" is set to X, use _at maximum_ X decimal places. That solved the problem but wasn't quite complete.
Now, we've added the ability to set "Decimals" to undefined. Using this, we can avoid having numbers like 100.00. This means we can go back to being explicit: When "Decimals" is set to X, use exactly X decimal places.
> [ENHANCEMENT] Update formatting to use exact decimal places

- ui/components/src/EChart/EChart.tsx
- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/StatChart/StatChart.tsx
Reverts perses/perses#1115
Previous PR doesn't work since the sx prop is needed in the dependency array [here](https://github.com/perses/perses/blob/v0.29.1/ui/components/src/EChart/EChart.tsx#L178-L184)
> [BUGFIX] Revert allow echarts wrapper to default to fluid width and height

- ui/components/src/TimeSeriesTooltip/TimeSeriesTooltip.tsx
- ui/components/src/TimeSeriesTooltip/tooltip-model.ts
- ui/components/src/TimeSeriesTooltip/utils.ts
This PR fixes the vertical positioning of the time series tooltip on a dashboard with several panels.
Issue:
https://github.com/perses/perses/assets/5461414/ef274d99-6696-4331-8ba1-9ef082a5b025
Fix:
https://github.com/perses/perses/assets/5461414/ad9da70f-0641-487a-86b6-e79f6d8f185a
> [BUGFIX] fix time series vertical positioning

- MAINTAINERS.md
I'm proposing Guillaume Gladorme (@Gladorme) as maintainer for Perses. He did some wonderful contributions on the application and he is eager to continue. So I think it really makes sense to add him :).
> [IGNORE] Add Guillaume Gladorme as a maintainer

- ui/panels-plugin/src/index.ts
- ui/panels-plugin/src/plugins/gauge-chart/gauge-chart-model.ts
- ui/panels-plugin/src/plugins/gauge-chart/index.ts
- ui/panels-plugin/src/plugins/markdown/index.ts
- ui/panels-plugin/src/plugins/markdown/markdown-panel-model.ts
- ui/panels-plugin/src/plugins/stat-chart/index.ts
- ui/panels-plugin/src/plugins/stat-chart/stat-chart-model.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.test.tsx
- ui/panels-plugin/src/plugins/time-series-chart/index.ts
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
This PR adds an `interface` that represents the schema for each type of panel (`TimeSeriesChart`, `GaugeChart`, `StatChart`, and `MarkdownPanel`).
The goal is to use these in the converter code.
Removes `spec.unit` from the TimeSeriesDefinition, because we actually use `spec.y_axis.unit`.  
To fix a broken dashboard, either move the data in `spec.unit` to `spec.y_axis.unit` OR remove `spec.unit` if `spec.y_axis.unit` is already defined.
> [BREAKINGCHANGE] Add interfaces for each panel's definition

- ui/app/src/views/ViewDashboard.tsx
- ui/core/src/model/resource.ts
Make certain metadata fields optional (see PR #939) and comment [here](https://github.com/perses/perses/pull/939#discussion_r1094774589) about using `unknown`. 
created_at, updated_at, and version are now optional 
These fields are set by the BE and shouldn't be required, this allows us to use the DashboardResource from @perses-dev/core without using type assertion as a workaround.  
> [BREAKINGCHANGE] Optional metadata, remove `unknown` DashboardResource type assertion

- ui/components/src/LineChart/LineChart.stories.tsx
- ui/components/src/LineChart/LineChart.tsx
This new optional prop enables the user to choose one of two displays when the line chart does not have data:
- `message` (default): renders a simple "no data" message to the user. This was the prior behavior before the addition of this prop.
- `chart`: renders a very simple chart with the available information (e.g. x axis).
- This is yet another small PR in prep for the table legend. We want to show an empty chart (instead of a "no data" message) when the user unselects all the items in a table legend using the checkboxes.
This is only in storybook right now. Screenshot …
> [ENHANCEMENT] Add `noDataVariant` to `LineChart`

- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
This commit refactors the time series chart panel selection mechanisms in the following ways:
- Switch from tracking selected items using `name` to using a unique `id` to avoid unintentionally setting multiple items if they have the same label.
- Switch from storing selected items using an array of names to a record of ids and booleans. This should make some operations more performant with large data sets and is more aligned with how we'll want to manage checkbox-based selection with the in progress table legend work.
- This is another refactor in service to the in flight work I'm doing on the table legend to avoid that initial PR being super large and nasty to review. 
- I played around with some larger refactoring while doing this that I think would benefit the time series chart panel, …
> [ENHANCEMENT] Refactor time series chart panel selection

- ui/components/src/Legend/CompactLegend.tsx
- ui/components/src/Legend/Legend.stories.tsx
- ui/components/src/Legend/Legend.test.tsx
- ui/components/src/Legend/Legend.tsx
- ui/components/src/Legend/ListLegend.tsx
- ui/components/src/Legend/ListLegendItem.tsx
- ui/components/src/model/legend.test.ts
- ui/components/src/model/legend.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
Prior to this change, much of the legend selection interactions were managed inside `TimeSeriesChartPanel`, requiring consumers to duplicate this logic when using the legend in other use cases.
After this change, the legend selection interactions are managed inside `Legend` and its child components, so that it can be used wherever the legend is. The selection state remains "controlled."
BREAKINGCHANGE: Refactoring `Legend` to manage legend interactions includes the following breaking changes:
- The `Legend` component now requires the following props to control the selected state of the items: `selectedItems`, `onSelectedItemsChange`.
- The `LegendItem` type no longer allows the `isSelected` property. The selected state of items are now managed by the `selectedItems` prop on the `Legend` …
> [BREAKINGCHANGE]: move legend interactions to legend

- ui/dashboards/src/components/GridLayout/GridTitle.tsx
This is a proposal for (imho) better usability of panel groups.
Currently to toggle/expand a panel group, you have to click on the (little) chevron button at the left:
This PR makes the whole panel group clickable instead:
Let me know if you agree or not with this change. Also this is my first attempt at doing some React so don't hesitate to point anything wrong/dirty in the code.
> [ENHANCEMENT] make the whole panel group clickable for toggle/expand

- .github/workflows/ci.yaml
It's causing issues that aren't a super-quick fix, and it is not a mission critical part of the project at this time. Temporarily disabling it in CI to avoid confusion with the intent to re-enable after we fix those issues.
> [IGNORE] Temporarily disable typedoc in CI

- ui/components/src/StatChart/StatChart.tsx
Right now y-axis min is calculated by echart, which causes the sparkline in stat chart to be rather flat in some cases. 
To fix this, we are now setting y-axis min to the minimum value of the data.
**BEFORE**
**AFTER**
> [ENHANCEMENT] Set y-axis min relative to data in stat chart

- ui/app/src/components/Header.tsx
- ui/app/src/context/DarkMode.tsx
- ui/e2e/src/pages/DashboardPage.ts
- ui/e2e/src/pages/PanelEditor.ts
- ui/e2e/src/tests/gaugeChartPanel.spec.ts
Changing the Theme Provider to not reload the entire screen when switch between themes.
This PR will fix https://github.com/perses/perses/issues/1173
- Does it have loading states? You need to wait for the loading to complete.
https://github.com/perses/perses/assets/8205546/d7eb91b6-c717-43cc-9d7a-0318b5bd2f12
> [BUGFIX] avoiding screen reload on theme toggle

- ui/e2e/src/tests/statChartPanel.spec.ts
Follow up to #1198 (see issue #1173) to fix unrelated e2e failures
> [IGNORE] StatChart add threshold e2e fix

- ui/core/src/model/dashboard.ts
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/SaveDashboardButton/SaveDashboardButton.tsx
- ui/dashboards/src/context/DashboardProvider/common.ts
- ui/dashboards/src/context/DashboardProvider/index.ts
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
Not all embed users implement saving dashboards using REST, this type change will allow `SaveDashboardButton` to be used in cases where our consumers use GraphQL
> [BREAKINGCHANGE] Save dashboard type change for embed gql users

- ui/app/package.json
- ui/dashboards/package.json
- ui/dashboards/src/test/render.tsx
- ui/package-lock.json
Temp branch to hopefully upgrade react router without breaking a bunch of stuff 🤞 
Follow up to closed PR #1153 - I think this is safe to upgrade now, finally got RTL tests to pass again
> [IGNORE] Upgrade react-router from 6.3.0 to 6.11.2 

- ui/dashboards/src/components/PanelDrawer/PanelDrawer.test.tsx
- ui/dashboards/src/components/SaveChangesConfirmationDialog/SaveChangesConfirmationDialog.tsx
- ui/dashboards/src/components/SaveDashboardButton/SaveDashboardButton.tsx
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
- ui/dashboards/src/context/TemplateVariableProvider/utils.test.ts
- ui/dashboards/src/context/TemplateVariableProvider/utils.ts
- ui/dashboards/src/test/render.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.stories.tsx
- ui/e2e/src/tests/variables.spec.ts
- ui/storybook/src/decorators/WithErrorSnackbar.tsx
- Fixes issue where empty StaticListVariable was triggering save default dialog unnecessarily
- Refactor error handling in SaveDashboardButton and change to async await
- RTL test setup adjustments to include SnackbarProvider
- Reduce Jest warnings in dashboards package by adding TimeRangeProvider in PanelDrawer.test.tsx (still a decent number of warnings though)
> [BUGFIX] Saving defaults error adjustments and account for Empty StaticListVariable

- .github/workflows/ci.yaml
- ui/components/package.json
- ui/components/typedoc.json
- ui/core/package.json
- ui/core/typedoc.json
- ui/dashboards/package.json
- ui/dashboards/typedoc.json
- ui/package-lock.json
- ui/package.json
- ui/panels-plugin/package.json
- ui/panels-plugin/typedoc.json
- ui/plugin-system/package.json
- ui/plugin-system/typedoc.json
- ui/prometheus-plugin/package.json
- ui/prometheus-plugin/typedoc.json
- ui/typedoc.base.json
- ui/typedoc.json
This commit:
- Upgrades typedoc to the latest release. I think they've fixed some of the issues that may have led to the OOM errors we saw before, but we'll need to keep an eye on it.
- Handles some breaking changes in the latest typedoc release related to generating docs for monorepos.
- Re-enables typedoc generation in CI.
Fixes https://github.com/perses/perses/issues/1200.
Typedoc assets again available after the CI run, which did not throw any memory errors.
Examples of what the docs look like now. They've changed the layout a little, but it's still very similar.
> [IGNORE] upgrade and fix typedoc generation

- ui/dashboards/src/components/SaveChangesConfirmationDialog/SaveChangesConfirmationDialog.tsx
- ui/dashboards/src/components/SaveDashboardButton/SaveDashboardButton.tsx
- ui/dashboards/src/context/DashboardProvider/save-changes-dialog-slice.tsx
- Fix console warnings when saving using gql (these warnings were not shown in Perses app) 
- Disable saveDefaultTimeRange checkbox when saved default duration is not modified
**After** isSavedDurationModified fix:
**Before** console error fix:
> [BUGFIX] Fix save dashboard console warning and saved duration checkbox

- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQuery.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/get-time-series-data.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/plugin.test.ts
Variables are now supported in the Prometheus legend formatter
> [FEATURE] Resolve variables in prometheus legend formatter

- ui/panels-plugin/src/index.ts
Follow up to #1189, I didn't actually export what I wanted in that PR 
Each barrel file is already scoped down to export only what we want, so this shouldn't be exporting too much hopefully, ex) 
- ui/panels-plugin/src/plugins/time-series-chart/[TimeSeriesChart.ts](https://github.com/perses/perses/blob/17529cf70b5c03b8b77807b338e26eee20362001/ui/panels-plugin/src/plugins/time-series-chart/index.ts)
Fixes import error:
> [ENHANCEMENT] Export from each core panel plugin barrel file

- ui/components/src/EChart/EChart.tsx
- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/TimeSeriesTooltip/nearby-series.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
Support shared crosshair for all charts on a dashboard. This is only on for panel use-cases where `syncGroup` is set explicitly. Embed users of LineChart.tsx or EChart.tsx will have to explicitly set a `syncGroup` to opt-in to this feature.
See ECharts docs:
- https://echarts.apache.org/en/api.html#echarts.connect
https://github.com/perses/perses/assets/9369625/b9c46df3-2306-4521-990c-e3c31cdf31da
> [FEATURE] Shared crosshair for all time series panels on a dashboard

- ui/dashboards/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/dashboards/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
This fixes ListVariables to use `spec.custom_all_value` if present when the All value (`$__all`) is selected
Demo:
https://www.loom.com/share/8f87895829dc469f983f1d95cfeaba24
> [FEATURE] Respect custom all value in list variables

- ui/components/src/YAxisLabel.tsx
Fix positioning of y axis label so that it doesn't overlap with the legend.
Before:
After:
https://github.com/perses/perses/assets/22085207/188ee3ee-f201-449c-9814-bd3f7ff846db
> [BUGFIX] Fix y axis label positioning

- ui/components/src/SettingsAutocomplete/SettingsAutocomplete.stories.tsx
- ui/components/src/SettingsAutocomplete/SettingsAutocomplete.test.tsx
- ui/components/src/SettingsAutocomplete/SettingsAutocomplete.tsx
- ui/components/src/SettingsAutocomplete/index.ts
- ui/components/src/UnitSelector/UnitSelector.tsx
- ui/components/src/index.ts
- ui/core/src/model/calculations.ts
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditorSettings.test.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanelOptionsEditor.stories.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartOptionsEditorSettings.test.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanelOptionsEditor.stories.tsx
- ui/panels-plugin/src/plugins/time-series-chart/VisualOptionsEditor.tsx
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
- ui/plugin-system/src/components/CalculationSelector/CalculationSelector.test.tsx
- ui/plugin-system/src/components/CalculationSelector/CalculationSelector.tsx
- ui/plugin-system/src/components/LegendOptionsEditor/LegendOptionsEditor.tsx
The purpose of this component is to normalize the rendering of settings within the panel options editors and other similar use cases.
This is a first draft of this component to make incremental progress. It is very likely the designs and some behaviors may change after syncing with designers
- I know we have some more work to do on the designs for this component. I have some time scheduled with design to work on that. However, I don't want to block incremental progress on this component (in service of getting table legend to have values) on those design adjustments, especially since this isn't making anything worse than it was before and in some cases is making an incremental improvement.
- Marking the component as "experimental" until the designs are more finalized.
- I'm writing pretty …
> [FEATURE]: SettingsAutocomplete component

- ui/components/src/TimeSeriesTooltip/TimeSeriesTooltip.tsx
Pinned tooltip fixed to not show above edit panel drawer and sticky header.
> [BUGFIX] Ensure pinned tooltip shows behind modals / sticky header

- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/LineChart/utils.ts
- ui/components/src/TimeSeriesTooltip/nearby-series.ts
Move clear highlighted series function to onMouseLeave so it works even when cursor is moved quickly.
Before it could stay like this when leaving panel:
> [BUGFIX] Highlighted series not always cleared when cursor moved quickly

- schemas/panels/time-series/time-series.cue
- ui/components/src/ContentWithLegend/ContentWithLegend.stories.tsx
- ui/components/src/ContentWithLegend/ContentWithLegend.tsx
- ui/components/src/ContentWithLegend/model/content-with-legend-model.test.ts
- ui/components/src/ContentWithLegend/model/content-with-legend-model.ts
- ui/core/src/model/legend.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/plugin-system/src/components/LegendOptionsEditor/LegendOptionsEditor.tsx
- ui/plugin-system/src/model/legend.ts
This change impacts the following:
- `ContentWithLegend` component.
- `TimeSeriesChartPanel` panel plugin.
Sizes currently include: small and medium.
This change also includes an adjustment to the sized height of bottom positioned table legends to be smaller if there are not enough legend items to fill the specified space.
I'm intentionally not tackling the grafana migration piece in this PR because this one is a trickier case because there's not a 1:1 mapping between the two, and I don't want to block the basic behavior on the complex migration logic. …
> [ENHANCEMENT] Add size option for content with legend

- ui/components/src/Legend/ListLegend.tsx
- ui/components/src/Table/InnerTable.tsx
Previously, the table and legend didn't properly account for spacing for the scrollbar causing unnecessary horizontal scroll, which is distracting when scrollbars are visible. It's easy to miss use cases like this as a mac user with a trackpad, because it hides the scrollbars by default. 😢 
This change should address cases where there is an unnecessary horizontal scroll in the table and legend caused by this. It does not address all cases of unwanted horizontal scrollbars.
All screenshots taken with my mac configured to always show scrollbars to make it very clear what the …
> [BUGFIX] avoid unnecessary horizontal scroll with table & legend

- ui/core/src/model/variables.ts
- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
- ui/dashboards/src/context/TemplateVariableProvider/hydrationUtils.test.ts
- ui/dashboards/src/context/TemplateVariableProvider/hydrationUtils.ts
- ui/plugin-system/src/runtime/template-variables.ts
Move `DEFAULT_ALL_VALUE` const to core from plugin-system. Similar to #1265, in an effort to move helpful types and utils to `@perses-dev/core` this is a BREAKINGCHANGE, but will allow consumers to utilize this type without requiring the entire plugin-system (avoids the consumer having to install MUI)
> [BREAKINGCHANGE] Move DEFAULT_ALL_VALUE to core since plugin-system requires MUI

- ui/plugin-system/src/runtime/time-series-queries.ts
This PR fixes a type error `Type unknown is not assignable to type TimeSeriesData` by removing the type cast to `QueryObserverOptions` in useTimeSeriesQueries
> [BUGFIX] Fix useTimeSeriesQueries return type

- scripts/cue-test/cue-test.go
There is probably a better way to fix this, but this PR is my quick attempt to fix an error I see when using `make cue-test`
```bash
sjcobb@Stevens-MacBook-Pro perses % make cue-test
>> test cue schemas with json data
go run ./scripts/cue-test/cue-test.go
WARN[0000] Plugin .DS_Store will not be loaded: it is not a folder 
INFO[0001] validate schemas under "schemas/panels"      
FATA[0001] open schemas/panels/.DS_Store/.DS_Store.json: not a directory 
exit status 1
make: *** [cue-test] Error 1
```
> [IGNORE] Mac specific error fix for cmd: make cue-test

- schemas/panels/time-series/time-series.cue
- schemas/panels/time-series/time-series.json
- ui/components/src/TimeChart/TimeChart.tsx
- ui/components/src/model/graph.ts
- ui/panels-plugin/src/plugins/time-series-chart/VisualOptionsEditor.tsx
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
Adds ability to have a time series bar chart type using existing TimeSeriesChart panel.
The new optional property added to the spec is `visual.display: 'line' | 'bar'` (with the default being 'line' if undefined)
> [FEATURE] Time series bar support using `visual.display` in TimeSeriesChart spec

- ui/components/src/TimeChart/TimeChart.tsx
- ui/components/src/TimeSeriesTooltip/TooltipHeader.test.tsx
- ui/components/src/TimeSeriesTooltip/TooltipHeader.tsx
- TimeChart rewrite follow up to fix clicking on 'Unpin' icon 
- prev PR #1268
- Adjust help text based on user feedback
https://github.com/perses/perses/assets/9369625/0a897baf-1772-4afa-84cb-71ea1cccc301
> [BUGFIX] Fix unpin tooltip icon click, adjust help text

- ui/components/src/TimeChart/TimeChart.stories.tsx
Test is flaky so disabling for now
Examples:
- https://happo.io/a/1009/p/1516/compare/1796e508aa670adfe27250c06ea6da821e72c8ae/bd0fd009daa7a6bbffc1890a4ecd93d0f648164e
- https://happo.io/a/1009/p/1516/compare/fe88431e44589e17f3443325523d912064a6fd29/1796e508aa670adfe27250c06ea6da821e72c8ae
> [IGNORE] Disable flaky noData TimeChart visual regression test

- ui/core/src/utils/time-series-data.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
http://localhost:3000/projects/perses/dashboards/TimeChart_vs_LineChart?start=1689236880000&refresh=0s&end=1689240690000
http://localhost:3000/projects/perses/dashboards/TimeChart_vs_LineChart?start=1689236880000&refresh=0s&end=1689240690000
> [BUGFIX] Time chart fix for incorrect connected values 

- ui/components/src/TimeSeriesTooltip/TimeChartTooltip.tsx
- ui/components/src/TimeSeriesTooltip/tooltip-model.ts
- ui/components/src/TimeSeriesTooltip/utils.ts
This PR fixes 2 bugs:
1. The position of tooltip is recalculated every time it renders, causing the tooltip to move even after it is pinned. To fix this, we need to store the position of tooltip in a ref. 
3. Tooltip is cut off if it is attached to a different element other than document.body. To fix this, we have to make sure the tooltip stays within the element boundaries. 
More info about using `tooltipPortalContainerId` in PR #1289
> [BUGFIX] Fix tooltip pinning when apps set a `tooltipPortalContainerId`

- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
Adjust TimeSeriesChart panel mapping to account for selected series, before it was looping through all dataset sources regardless of which legend items were selected
No tooltip on hover when second series selected
Tooltip showing when second series selected
> [BUGFIX] Tooltip hidden when many series and legend item selected

- ui/components/src/BarChart/BarChart.tsx
- ui/components/src/TimeChart/TimeChart.tsx
- ui/components/src/utils/theme-gen.test.ts
- ui/components/src/utils/theme-gen.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
- Fix palette colors for TimeSeriesChart `visual.display: 'bar'`
- Adjust charts theme to account for vertical bar charts
- Fix stacked bar tooltip by using ECharts tooltip when visual.stack is set
https://github.com/perses/perses/assets/9369625/b6490658-eb57-43d3-a467-faecd26f9db6
> [BUGFIX] Time series stacked bar correct palette color and tooltip

- go.mod
- go.sum
- internal/api/core/server.go
- internal/api/impl/v1/dashboard/service.go
- internal/api/impl/validate/validate.go
- internal/api/interface/v1/dashboard/interface.go
- internal/api/shared/dependency/service_manager.go
- internal/api/shared/validate/validate.go
- pkg/model/api/v1/utils/variable_build_order.go
- pkg/model/api/v1/utils/variable_build_order_test.go
Backend should take in account the external variables (project/global variables) when it is verifying that the variables used by a dashboard are defined.
This is the case for all validation by endpoints (on dashboard create/update + on each call of the /validate endpoint).
The static validation done by percli lint (without --online) doesn't assume on any external variable. It may fail if somebody try to use it to validate a dashboard which uses external variables.
> No UI Changes
> [FEATURE] Consider external vars in dashboard validation

- pkg/model/api/v1/utils/variable_build_order.go
I missed something in the previous PR https://github.com/perses/perses/pull/1306
The variables names list is computed again right after to build the graph of dependencies.
> No UI Changes
> [BUGFIX] Consider external vars in dashboard validation

- ui/components/src/TimeChart/TimeChart.stories.tsx
Looking into failing jobs like this one: https://happo.io/a/1009/jobs/719894
Errors:
```
Canvas was not stable after 1 check(s). Trying again in 250.
Canvas was not stable after 2 check(s). Trying again in 250.
Canvas was not stable after 3 check(s). Trying again in 250.
Canvas was not stable after 4 check(s). Trying again in 250.
Canvas was not stable after 5 check(s). Trying again in 250.
Canvas was not stable after 6 check(s). Trying again in 250.
Canvas was not stable after 7 check(s). Trying again in 250.
Canvas was not stable after 8 check(s). Trying again in 250.
Canvas was not stable after 9 check(s). Trying again in 250.
Canvas was not stable after 10 check(s). Trying again in 250.
Canvas was not stable after 11 check(s). Trying again in 250.
Canvas was not stable after 12 …
```
> [IGNORE] Disable TimeChart happo test to debug timeout

- internal/api/shared/validate/testdata/datasource_custom.json
- internal/api/shared/validate/testdata/datasource_default.json
- internal/api/shared/validate/validate.go
- internal/api/shared/validate/validate_test.go
- ui/app/src/components/DatasourceList/DatasourceDataGrid.tsx
- ui/app/src/components/DatasourceList/DatasourceDrawer.tsx
- ui/app/src/components/DatasourceList/DatasourceEditorForm.tsx
- ui/app/src/components/DatasourceList/DatasourceList.tsx
- ui/app/src/components/dialogs/DeleteDatasourceDialog.tsx
- ui/app/src/model/project-client.ts
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/tabs/ProjectDatasources.tsx
- ui/core/src/model/datasource.ts
- ui/core/src/utils/text.ts
- ui/e2e/src/pages/AppProjectPage.ts
- ui/e2e/src/pages/DatasourceEditor.ts
- ui/e2e/src/tests/projectView.spec.ts
- ui/plugin-system/src/components/OptionsEditorRadios/OptionsEditorRadios.tsx
- ui/plugin-system/src/components/OptionsEditorRadios/index.ts
- ui/plugin-system/src/components/OptionsEditorTabPanel/OptionsEditorTabPanel.tsx
- ui/plugin-system/src/components/OptionsEditorTabPanel/index.ts
- ui/plugin-system/src/components/OptionsEditorTabs/OptionsEditorTabs.tsx
- ui/prometheus-plugin/src/plugins/PrometheusDatasourceEditor/PrometheusDatasourceEditor.tsx
- ui/prometheus-plugin/src/plugins/PrometheusDatasourceEditor/index.ts
- ui/prometheus-plugin/src/plugins/PrometheusDatasourceEditor/types.ts
- ui/prometheus-plugin/src/plugins/prometheus-datasource.tsx
Issue ref: https://github.com/perses/perses/issues/1033
This PR adds project datasources CRUD, leveraging on the tab layout from #1267. It also comes with:
- A bugfix on backend side: updating the already-defined-as-default datasource was causing unwanted request rejection (_"cannot set A as default since there's already a default datasource set (A)"_).
- New reusable component `OptionsEditorRadio` for RadioGroup-based options.
_NB: contrary to what was done for variables, here you have no action button in the list view: clicking on a row opens the drawer form for this datasource and it's there that you can act on it. We agreed with @Gladorme to have this divergence between variables & datasources UX temporarily: since we were not able to identify which one is better, the goal is to have …
> [FEATURE] Add project datasources CRUD

- ui/app/src/model/variables.ts
- ui/app/src/utils/variables.ts
- ui/app/src/views/ViewDashboard.tsx
- ui/dashboards/src/components/SaveDashboardButton/SaveDashboardButton.tsx
- ui/dashboards/src/components/Variables/EditVariablesButton.tsx
- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
- ui/dashboards/src/context/TemplateVariableProvider/hydrationUtils.test.ts
- ui/dashboards/src/context/TemplateVariableProvider/hydrationUtils.ts
- ui/dashboards/src/context/TemplateVariableProvider/utils.test.ts
- ui/dashboards/src/context/TemplateVariableProvider/utils.ts
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
- ui/plugin-system/src/runtime/template-variable.test.ts
- ui/plugin-system/src/runtime/template-variables.ts
This PR introduce the logic to take into account a new type of variables into the dashboards. I call them here "external" and they contains all the variables that are not defined inside the Dashboard itself. 
Spoiler alert, in the Perses UI, it would describe the new "project scope" and "global scope" variables. 
The idea here is to include them as specific variables in the store, so they would be taken in account into the view, but not in the backend requests. 
> **Disclaimer from a react newbie**
> Despite the fact that it works well, I am not sure I'm using the store as I should. In particular, I put the ``overridden``/``overriding`` booleans inside the state object(s) of the store, but I need to recompute them in the drawer (see VariableEditor.tsx) as the store is not used there while …
> [FEATURE] Injection of external variables

- ui/components/src/TimeChart/TimeChart.stories.tsx
- ui/components/src/TimeChart/TimeChart.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- Add stacked bar story
- Fix dep array after #1313 
- adjust panel conditions to ensure tooltip pinning is off when isStackedBar
> [IGNORE] Add stacked bar story to debug Happo errors

- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
Include an optional `panelDefinition` and `panelGroupItemId` in the panel props: See https://github.com/perses/perses/pull/1315#discussion_r1270969119
> [ENHANCEMENT] Include panel definition in extra panel props

- ui/core/src/model/query.ts
- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/dashboards/src/components/PanelDrawer/PanelPreview.tsx
- ui/panels-plugin/src/plugins/bar-chart/BarChartPanel.tsx
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartPanel.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
- ui/plugin-system/src/runtime/DataQueriesProvider/DataQueriesProvider.test.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/DataQueriesProvider.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/model.ts
- ui/plugin-system/src/test/index.ts
- ui/plugin-system/src/test/mock-data.ts
Currently our DataQueriesProvider serves as the core component for data querying. It decouples the visualization layer from the data source layer. This separation allows users to update queries easily without affecting the visualization. 
However, our current implementation is limited to supporting time series queries only. We want to expand the capabilities of the DataQueriesProvider to support other data types, such as traces and logs. This improvement will  provide developers more versatility and flexibility when running queries.
**Changes**
- Modify the `DataQueriesProvider` to filter the definitions into different query types, returning a mix of data types
- Update `useDataQueries` hook to accept a `queryType` prop and return results specifically related to that query type.
**Usage** …
> [BREAKINGCHANGE] Update DataQueriesProvider to support other data types

- ui/core/src/model/units/time.test.ts
- ui/core/src/model/units/time.ts
- ui/core/src/model/units/units.ts
The goal of this work is to produce y-axis values that are easier to understand. In the code, we pick the largest time unit that still produces natural numbers (numbers > 1). 
| We currently say 3000ms | We want to say 3s |
| -- | -- |
| <img width="292" alt="Screenshot 2023-07-25 at 11 51 12 AM" src="https://github.com/perses/perses/assets/2584129/a2e7076b-7a1f-4f09-b502-a564ccbf0ccb"> | <img width="243" alt="Screenshot 2023-07-25 at 11 51 22 AM" src="https://github.com/perses/perses/assets/2584129/83144002-67bf-48e8-a25f-bc2e0d0cde7e"> |
| -- | -- |
| <img width="602" alt="Screenshot 2023-07-25 at 11 58 18 AM" src="https://github.com/perses/perses/assets/2584129/20e1a929-7dab-4347-b8fb-a6069bba18e5"> | <img width="658" alt="Screenshot 2023-07-25 at 12 02 09 PM" …
> [ENHANCEMENT] Choose largest time unit that produces natural numbers

- ui/components/src/BarChart/BarChart.tsx
- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/TimeChart/TimeChart.tsx
- ui/components/src/utils/axis.ts
- ui/core/src/model/calculations.ts
- ui/panels-plugin/src/plugins/bar-chart/BarChartOptionsEditorSettings.test.tsx
- ui/panels-plugin/src/plugins/bar-chart/BarChartOptionsEditorSettings.tsx
- ui/panels-plugin/src/plugins/bar-chart/bar-chart-model.ts
- ui/panels-plugin/src/plugins/bar-chart/utils.ts
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChartOptionsEditorSettings.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartOptionsEditorSettings.tsx
- Updates formatting of x axis values
- Adds a "Reset to Defaults" button to the bar chart settings
- Fixes empty state so that "No data" message is shown when appropriate
- Prevents y axis labels from getting cut off
X axis before:
X axis after:
Reset to Defaults button:
Empty state:
> [ENHANCEMENT] Bar chart updates

- ui/components/src/TimeChart/TimeChart.tsx
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
In order to fix zIndex issues when clicking to pin on a dashboard, changes were made in #1258 that break tooltip pinning once inside a Drawer. Since pinning isn't as useful in PanelPreview.tsx, this PR disables tooltip pinning by adding a nested `<ChartsProvider chartsTheme={chartsTheme} enablePinning={false}>`
This is follow up to #1317, that branch will be merged first
> [BUGFIX] Disable tooltip pinning in panel preview

- ui/components/src/TimeSeriesTooltip/nearby-series.ts
- ui/components/src/utils/chart-actions.test.ts
- ui/components/src/utils/chart-actions.ts
- ui/core/src/utils/time-series-data.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
Rely on `getCommonTimeScale` and `getTimeSeriesValues` to ensure consistent xAxis intervals. We don't need to manually check every series.
> [ENHANCEMENT] Improve performance in `checkforNearbyTimeSeries`

- ui/dashboards/src/test/render.tsx
Add DatasourceStoreProvider in dashboards package test context helper to fix all the warnings in console when running unit tests
> [IGNORE] Cleanup jest warnings in dashboards package

- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/e2e/.happo.js
- ui/e2e/src/config/base.playwright.config.ts
- ui/e2e/src/pages/Panel.ts
- ui/plugin-system/src/runtime/DataQueriesProvider/DataQueriesProvider.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/model.ts
- ui/plugin-system/src/runtime/time-series-queries.ts
There is a regression where lazy loading isn't working after introducing `DataQueriesProvider`.
This is because `DataQueryProvider` wraps the component only renders if it is in view port, resulting in all queries running when the page loads. 
This PR adds a new prop called enabled in DataQueriesProvider to provide the capability to disable running the query automatically
> [BUGFIX] Fix no lazy loading after adding DataQueriesProvider 

- ui/app/src/components/DatasourceList/DatasourceDataGrid.tsx
- ui/app/src/components/DatasourceList/DatasourceDrawer.tsx
- ui/app/src/components/DatasourceList/DatasourceEditorForm.tsx
- ui/app/src/components/DatasourceList/DatasourceList.tsx
- ui/app/src/components/VariableList/VariablesList.tsx
- ui/app/src/components/dialogs/DeleteDatasourceDialog.tsx
- ui/app/src/model/admin-client.ts
- ui/app/src/model/datasource-api.ts
- ui/app/src/model/datasource-client.ts
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/admin/tabs/GlobalDatasources.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/tabs/ProjectDatasources.tsx
- ui/core/src/model/datasource.ts
- ui/core/src/model/resource.ts
- ui/core/src/utils/text.ts
- ui/core/src/utils/types.ts
- ui/dashboards/src/context/DatasourceStoreProvider.tsx
Refactoring on top of the global datasource CRUD PR #1319  to use generics like we do for the global/project variables.
Ref #1033 
Closes #1319 (Let's see if we can automatically close a PR but I'm not sure)
> [FEATURE] Global Datasource CRUD + DRY refactoring

- ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts
- ui/prometheus-plugin/src/model/prometheus-client.ts
- closes #1291 ?
- This PR resolve also another bug not filed. When we use a prometheus label value source for the variable list, if we don´t set the label name, it makes a query giving a 404 and a strange json message. Now it is just not querying if the label name is empty.  
> [BUGFIX] Hanging preview state when adding a new list variable before Source selected

- internal/api/e2e/api/dashboard_test.go
- internal/api/e2e/api/datasource_test.go
- internal/api/e2e/api/doc.go
- internal/api/e2e/api/globaldatasource_test.go
- internal/api/e2e/api/globalvariable_test.go
- internal/api/e2e/api/migrate_test.go
- internal/api/e2e/api/project_test.go
- internal/api/e2e/api/variable_test.go
- internal/api/e2e/client/datasource_test.go
- internal/api/e2e/client/doc.go
- internal/api/e2e/client/project_test.go
- internal/api/e2e/client/test_utils.go
This PR is moving the integration in the internal package.
This is following the conversation from #1190. Moving them outside of `pkg` will reduce the number of indirect dependencies you have in the go.mod when you are importing perses.
> move pkg integration test outside

- ui/app/src/components/DatasourceList/DatasourceDrawer.tsx
- ui/app/src/components/DatasourceList/DatasourceEditorForm.tsx
- ui/app/src/components/DatasourceList/DatasourceList.tsx
- ui/app/src/components/VariableList/VariableFormDrawer.tsx
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/admin/tabs/GlobalDatasources.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/tabs/ProjectDatasources.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
fixes https://github.com/perses/perses/issues/1356.
This PR brings small changes to the datasource creation/edit form:
- it makes the datasource name attribute readonly after creation. This fixes the bug raised with #1356. The decision to remove this feature comes from other reasons than just this fix, see the comments in this issue to have more context.
- it fixes some wrong titles/names in readonly mode.
- it also aligns variable & datasource forms behaviors when clicking out of the drawer: it's now doing nothing for both - until we find a proper solution to have closure with discard confirmation modal showing up in this situation.
- Does it …
> [BUGFIX] datasource form: make name readonly after creation + fix wrong titles/names in readonly mode

- ui/core/src/model/time.ts
- ui/core/src/model/units/time.test.ts
- ui/core/src/model/units/time.ts
- ui/core/src/model/units/types.ts
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
- ui/plugin-system/src/utils/variables.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/get-time-series-data.ts
- Add builtin variables:
- `$__range`: The range for the current dashboard in "human" readable format (1y 1w 1d 1h 1m 1s)
- `$__range_s`: The range for the current dashboard in second
- `$__range_ms`: The range for the current dashboard in millisecond
- Add support for curly bracket variables: `$varName` can also be written `${varName}`
- Fix prefixed variables by other variable name, before `$__range_ms` was parsed `3600_ms` instead of `3600000`. Because `$__range` was applied before `$__range_ms`. Now variables with longer names are applied first.
Closes #1345
> [FEATURE] Add $__range(_ms/_s) builtin variables + add support for curly bracket variables + fix prefixed variables by other variable name

- ui/app/src/components/datasource/DatasourceDrawer.tsx
- ui/app/src/components/datasource/DatasourceList.tsx
- ui/app/src/components/dialogs/index.ts
- ui/app/src/components/variable/VariableDrawer.tsx
- ui/app/src/components/variable/VariableList.tsx
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/admin/tabs/GlobalDatasources.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/tabs/ProjectDatasources.tsx
- ui/app/src/views/projects/tabs/ProjectVariables.tsx
- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/e2e/src/pages/DatasourceEditor.ts
- ui/e2e/src/pages/VariableEditor.ts
- ui/e2e/src/tests/projectView.spec.ts
- ui/e2e/src/tests/variables.spec.ts
- ui/plugin-system/src/components/DatasourceEditorForm/DatasourceEditorForm.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/plugin-system/src/utils/action.ts
Resolves #1390.
This PR unifies the user experience when dealing with variables & datasources CRUD. Basically it consists in:
- adding action buttons in the list view for datasources
- adding action buttons in the form view for variables
It also fixes a minor issue with some snackbar messages showing "global \<resource\> updated" while it's a project one.
- **External resources forms:**
- **Local resources forms:**
> [ENHANCEMENT] Reconcile variables & datasources CRUD

- schemas/panels/time-series/time-series.cue
- ui/components/src/ThresholdsEditor/ThresholdInput.tsx
- ui/components/src/ThresholdsEditor/ThresholdsEditor.test.tsx
- ui/components/src/ThresholdsEditor/ThresholdsEditor.tsx
- ui/core/src/model/thresholds.ts
- ui/e2e/src/pages/PanelEditor.ts
- ui/e2e/src/tests/gaugeChartPanel.spec.ts
- ui/e2e/src/tests/timeSeriesChartPanel.spec.ts
- ui/panels-plugin/src/model/thresholds.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
Changed casing for thresholds mode to kebab-case on frontend side, to align with the backend datamodel. (This was basically missed in https://github.com/perses/perses/pull/1262).
This fixes #1389.
> [BUGFIX] Fix BE/FE misalignement on threshold datamodel #1389

- dev/data/dashboard.json
- dev/data/projectdatasource.json
- dev/populate.sh
- internal/api/core/core.go
- internal/api/core/middleware/proxy.go
- internal/api/shared/schemas/base_def_query.cue
- scripts/cue-test/cue-test.go
- ui/app/src/model/datasource-api.test.ts
- ui/app/src/model/datasource-api.ts
- ui/core/src/model/datasource.ts
- ui/dashboards/src/context/DatasourceStoreProvider.test.tsx
- ui/dashboards/src/context/DatasourceStoreProvider.tsx
- ui/dashboards/src/test/datasource-provider.tsx
- ui/plugin-system/src/components/DatasourceSelect.tsx
- ui/plugin-system/src/runtime/datasources.ts
- ui/plugin-system/src/stories/shared-utils/decorators/WithPluginSystemDatasourceStore.tsx
- ui/prometheus-plugin/src/model/prometheus-selectors.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/plugin.test.ts
Currently the datasource selection when we use it in a panel or variable is quite limited. It is not displaying the eventually overridden datasource (e.g a global datasource when a project datasource exist with the same name)
I'm proposing to keep this well split by group (default VS local VS project VS global datasource ) so the user understand better from where the datasource selected comes from. 
As a bonus, it continues on the implementation of the local datasources. Specially the part that computes the proxy url on the fly + related proxy middleware in the backend.
- ``DatasourceApi``: Moved build of proxy url to dedidated optional method
- ``DatasourceStore``: Modified the datasource "metadata" to a list of selection items, grouped by group
- internal
- relates #1033 
- react
- …
> [BREAKINGCHANGE] Datasource selection by group

- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard_test.go
- ui/components/package.json
- ui/core/package.json
- ui/dashboards/package.json
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.test.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx
- ui/panels-plugin/package.json
- ui/plugin-system/package.json
- ui/plugin-system/src/runtime/TimeRangeProvider/query-params.ts
- ui/prometheus-plugin/package.json
Fixes https://github.com/perses/perses/issues/1337.
There were 2 underlying issues here:
- `refreshInterval` didn't exist in the backend datamodel
- changing refresh interval via the dropdown was not triggering dashboard context update
> [BUGFIX] Fix saved changes to refresh interval not preserved

- dev/data/dashboard.json
- docs/cli.md
- docs/dashboard.md
- internal/api/shared/migrate/mapping.cuepart
- internal/api/shared/migrate/testdata/old_grafana_panels_perses_dashboard.json
- internal/api/shared/migrate/testdata/simple_perses_dashboard.json
- internal/api/shared/validate/testdata/variable_with_regex_dashboard.json
- pkg/model/api/v1/dashboard/variable_test.go
- pkg/model/api/v1/dashboard_test.go
- pkg/model/api/v1/variable/list.go
- ui/core/src/model/variables.ts
- ui/dashboards/src/components/Dashboard/Dashboard.stories.tsx
- ui/dashboards/src/components/Variables/TemplateVariable.test.ts
- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
- ui/dashboards/src/context/TemplateVariableProvider/hydrationUtils.test.ts
- ui/dashboards/src/context/TemplateVariableProvider/hydrationUtils.ts
- ui/dashboards/src/context/TemplateVariableProvider/utils.test.ts
- ui/dashboards/src/context/TemplateVariableProvider/utils.ts
- ui/e2e/src/data/updatedDefaultsDashboard.json
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts
- ui/plugin-system/src/components/Variables/variable-model.test.ts
- ui/plugin-system/src/components/Variables/variable-model.ts
- ui/plugin-system/src/runtime/template-variables.ts
[BREAKINGCHANGE] snake_case -> camelCase in variable spec
- `allow_multiple` -> `allowMultiple`
- `allow_all_value` -> `allowAllValue`
- `capturing_regexp` -> `capturingRegexp`
- `default_value` -> `defaultValue`
For the context see discussion #1243 - [Antoine comment](https://github.com/perses/perses/discussions/1243#discussioncomment-6316495). To be consistent with Kubernetes naming conventions, proposed change is convert snake_case JSON properties to camelCase, see: 
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-conventions 
- _"Go field names must be PascalCase. JSON field names must be camelCase. Other than capitalization of the initial letter, the two should almost always match. No underscores or dashes in …
> [BREAKINGCHANGE] Variables spec snake_case -> camelCase 

- pkg/model/api/v1/common/display.go
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard_test.go
- pkg/model/api/v1/variable/variable.go
- ui/core/src/model/display.ts
- ui/core/src/model/panels.ts
- ui/plugin-system/src/components/DatasourceEditorForm/DatasourceEditorForm.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts
You can't set a description without having a display name for variables & datasources. This requirement is removed with this PR. 
Closes #1384
> [FEATURE] Display name is optional for variables

- ui/dashboards/src/components/Panel/Panel.tsx
Fixes https://github.com/perses/perses/issues/1342.
Fixes https://github.com/perses/perses/issues/1402.
This bug was most probably introduced with https://github.com/perses/perses/pull/1032, since before this the queries definition was located within the panel's plugin spec, thus relying on `plugin.spec` as resetKeys for the ErrorBoundary component was fine at this time.
https://github.com/perses/perses/assets/7058693/38e7dc56-ee16-478e-81fd-be9126201b31
> [BUGFIX] Fix panel preview unresponsive after query error

- pkg/model/api/v1/public_secret.go
- pkg/model/api/v1/secret.go
- pkg/model/api/v1/secret/basic_auth.go
- pkg/model/api/v1/secret/tls_config.go
I'm just applying the camelCase convention we choose for the json key. It has been missed for the secret.
> [BUGFIX] Align camelCase json key in secret

- ui/dashboards/src/components/EditJsonDialog/EditJsonDialog.tsx
Before:
After:
NB: A 2nd scrollbar may still appear on smaller screen sizes, but it's much less tall & annoying than before.
> [ENHANCEMENT] Remove annoying double scroll on Edit JSON dialog

- internal/api/shared/migrate/loader.go
- internal/api/shared/migrate/migrate.go
- internal/api/shared/schemas/loader.go
- internal/api/shared/schemas/schemas.go
This PR fixed #1440 
We are loading every 5min the cuelang schema. And we never reset the cue schema during this reload. The cue context is tracking every loaded instances of the schema, which made the memory increasing during every loop.
Even if we don't want to keep a cue context forever, we still need to keep one that would have in memory the different schema loaded. The cue context is then used during the validation phase.
It also removed the usage of the sync map. 
Explanations are described here: https://teivah.medium.com/maps-and-memory-leaks-in-go-a85ebe6e7e69
> [BUGFIX] Fix memory leak caused by a cue context kept during the load of the schemas

- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx
- ui/dashboards/src/constants/user-interface-text.ts
Add a tooltip to the auto refresh select, it will be easier for users to understand what this select is doing 😄 
> [ENHANCEMENT] Add tooltip to auto refresh dashboard select

- ui/components/src/RefreshIntervalPicker/RefreshIntervalPicker.tsx
Display properly custom auto refresh interval. Previously when the auto refresh interval wasn't using a suggested timerange, the field was empty
> [ENHANCEMENT] Display properly custom auto refresh interval

- schemas/common/proxy/http.cue
- schemas/common/url.cue
- schemas/datasources/prometheus/prometheus.cue
- schemas/datasources/prometheus/prometheus.json
- ui/e2e/src/pages/DatasourceEditor.ts
- ui/e2e/src/tests/projectView.spec.ts
This PR brings changes to the PrometheusDatasource cuelang schema:
- XOR condition to ensure either `directUrl` or `proxy` is present. It's not supposed to be able to provide either both or none of them.
- format validation for the url fields.
_NB: this is the error you'd now see if you try to create a datasource without direct URL or proxy config set:_
_So the cue validation is working as expected but the error message is not very intelligible. Imho this is not a problem since we also want field validation on the frontend side, which would prevent submitting the form with no or wrongly-formatted URL provided. The latter is not tackled by this PR but instead should come with https://github.com/perses/perses/pull/1438._
ℹ️ This change is technically a breaking change, however I don't …
> [BUGFIX] Prom DS: change to XOR between `directUrl` and `proxy`

- schemas/datasources/prometheus/prometheus.cue
- ui/prometheus-plugin/src/plugins/PrometheusDatasourceEditor.tsx
This PR is to allow users to provide a custom set of allowed endpoints when creating/editing a Prometheus data source, instead of being forced to an hard-coded set like previously.
The previously-enforced list is still available as a suggestion/default value when creating a new datasource.
https://github.com/perses/perses/assets/7058693/7bcf7cf0-1b69-4224-bb8f-75c2f1586430
> [FEATURE] Prom DS: allow providing custom allowed endpoints

- internal/api/core/middleware/proxy.go
This was causing wrong behavior & nil pointer exception as one may expect..
> [BUGFIX] Fix wrong error check in proxy

- internal/api/shared/migrate/migrate_test.go
- internal/api/shared/migrate/testdata/library_panel_grafana_dashboard.json
- internal/api/shared/migrate/testdata/library_panel_perses_dashboard.json
- internal/api/shared/migrate/testdata/old_grafana_query_grafana_dashboard.json
- internal/api/shared/migrate/testdata/old_grafana_query_perses_dashboard.json
- internal/api/shared/migrate/testdata/simple_perses_dashboard.json
- schemas/panels/gauge/mig.cuepart
- schemas/panels/markdown/mig.cuepart
- schemas/panels/stat/mig.cuepart
- schemas/panels/time-series/mig.cuepart
- schemas/queries/prometheus/mig.cuepart
- schemas/variables/prometheus-label-names/mig.cuepart
- schemas/variables/prometheus-label-values/mig.cuepart
- schemas/variables/prometheus-promql/mig.cuepart
- ui/app/src/views/MigrateView.tsx
2 different issues were making the grafana migration fail:
- Library panels: looks like "collapse them to make it work" is no longer valid, so we were trying to access a `type` attribute that doesn't exist in their case. It's now properly tackled (placeholder panel gets applied). Warning on the Migrate UI removed accordingly.
- Old query datamodel: nowadays the `query` attribute from the prometheus template variables is a struct and no longer a string. Grafana is not automatically doing the conversion so we have to support both here.
This also comes with some improvements for PromQL variables migration: stronger checks + no more replacement of builtin vars like `$__range` since we properly support them now.
> [BUGFIX] Fix grafana migration failing in some corner cases

- internal/api/shared/schemas/base_def_query.cue
- ui/core/src/model/datasource.ts
- ui/plugin-system/src/components/DatasourceSelect.tsx
- ui/plugin-system/src/runtime/datasources.ts
- ui/prometheus-plugin/src/model/prometheus-selectors.ts
In a [previous PR](https://github.com/perses/perses/pull/1360), we allowed the frontend to choose between global/project/local datasources. In this context, we reused the same classes for backend requests datamodel and datasource selection in the frontend, which introduced the group field, not interpreted in the backend.
With that code, we split the datamodels:
- The ``DatasourceSelectItemSelector`` is used by the frontend only in the datasource selection form. With group field to know by advance which one would be used by the frontend at T time.
- The ``DatasourceSelector`` remains the one used in the backend requests. Without group field as the backend does not have this notion.
- Does the time change? You need to use consistent …
> [REFACTOR] Separate the datasource selector frontend from backend

- internal/api/shared/migrate/testdata/old_grafana_query_perses_dashboard.json
- internal/api/shared/migrate/testdata/simple_perses_dashboard.json
- schemas/panels/stat/migrate.cue
- schemas/panels/time-series/migrate.cue
Since Grafana is putting some thresholds by default on timeseries panels in hidden mode & that we don't have such hidden mode for thresholds, the best way to avoid having unwanted thresholds showing on many graphs is to not migrate them when they are hidden.
> [BUGFIX] Fix unwanted thresholds when migrating timeseries panels

- schemas/common/format.cue
- ui/core/src/model/units/throughput.test.ts
- ui/core/src/model/units/throughput.ts
- ui/core/src/model/units/types.ts
- ui/core/src/model/units/units.ts
Adding some throughput units. I wonder if it's not better to have a custom string unit and the user set whatever he wants 🤔 
> [ENHANCEMENT] Add some throughput units

- ui/app/src/components/AppBreadcrumbs.tsx
- ui/app/src/components/Header.tsx
- ui/app/src/components/PersesLogo.tsx
- ui/dashboards/src/components/DashboardStickyToolbar/DashboardStickyToolbar.tsx
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
Reduce the size of the various navbars (top one, the one with breadcrumb & timerange controls in read mode, the one with variables dropdowns & timerange controls in edit mode, also the sticky version of the latter) to spare vertical space for the dashboard content.
before/after comparison:
> [ENHANCEMENT] Reduce navbars size

- ui/app/src/Router.tsx
- ui/app/src/components/AppBreadcrumbs.tsx
- ui/app/src/components/Header.tsx
- ui/app/src/components/ProjectBreadcrumbs.tsx
- ui/app/src/model/config-client.ts
- ui/app/src/views/admin/AdminView.tsx
- ui/app/src/views/config/ConfigView.tsx
- ui/app/src/views/home/HomeView.tsx
- ui/app/src/views/projects/ProjectView.tsx
- ui/app/src/views/projects/dashboards/HelperDashboardView.tsx
- ui/endpoint.go
This PR is adding a new page to display the backend config.
Maybe we should put every button in a menu on the right corner.
I took the opportunity to split the breadcrumbs wrapper we have in two different components. I changed also the icon for the admin panel
> [FEATURE] display the server config

- ui/app/src/views/projects/RecentlyViewedDashboards.tsx
Align recently dash view table with left side table.
> [ENHANCEMENT] align recently dash view table

- .github/workflows/ci.yaml
- Makefile
- scripts/generate-goreleaser/generate-goreleaser.go
- scripts/push-main-docker-image/push-main-docker-image.go
This PR is enabling the possibility to push the docker image built on the main branch.
With that we can try any commit available on the upstream.
I refactor a bit the script `generate-goreleaser` to have something a bit cleaner and easier to test.
The idea here is to generate the docker image with the tag `main-<date>-<short_commit_id>-<distrib>-<arch>`
For example: `docker.io/persesdev/perses:main-2023-10-23-8b1f5d3f-distroless-debug-arm64`
Then since we are generating different image depending on the architecture (arm, amd), we need to create and push the manifest so we can pull the docker image easily
> [IGNORE] push docker image on the main branch

- .github/workflows/ci.yaml
- scripts/override_version.sh
As we are pushing a docker image on the branch `main`, it would be nice it is reflected in the version displayed in the footer.
A simple way to do it, is to override the environment variable `VERSION` created in the makefile.
> [IGNORE] override VERSION on the main branch

- .github/dependabot.yml
Configure dependabot to rely on ui/api labels instead of go/javascript.
This is to avoid having these 2 sets of redundant labels coexisting.
> [IGNORE] Configure dependabot to rely on ui/api labels instead of go/javascript

- dev/data/dashboard.json
- internal/api/shared/migrate/mapping.cuepart
- internal/api/shared/migrate/testdata/library_panel_perses_dashboard.json
- internal/api/shared/migrate/testdata/old_grafana_panels_perses_dashboard.json
- internal/api/shared/migrate/testdata/simple_grafana_dashboard.json
- internal/api/shared/migrate/testdata/simple_perses_dashboard.json
- schemas/queries/prometheus/migrate.cue
This PR tackles many corner cases that were causing the grafana migration to fail:
- `target.datasource.type` not present when migrating queries
- `datasource` field not present when migrating queries
- empty panel title when migrating panels
- row with targets defined (should be ignored)
It also comes with:
- an improvement to stop appending an empty grid when migrating dashboards without standalone panels (this empty grid was consuming vertical space on the screen for no purpose),
- some refactoring in mapping.cuepart to reduce code duplication by using [function pattern](https://cuetorials.com/patterns/functions/).
> [BUGFIX] Avoid failing grafana migration in multiple cases

- internal/api/shared/migrate/mapping.cuepart
Use CUE alias syntax in mapping.cuepart to avoid dirty variable naming.
> [IGNORE] Use CUE alias syntax in mapping.cuepart to avoid dirty variable naming

- docs/embedded-panels.md
- ui/app/src/components/variable/VariableDrawer.tsx
- ui/dashboards/src/components/Panel/Panel.test.tsx
- ui/dashboards/src/components/PanelGroupDialog/PanelGroupDialog.test.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.test.tsx
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
- ui/dashboards/src/views/ViewDashboard/tests/panelGroups.test.tsx
- ui/package-lock.json
- ui/plugin-system/package.json
- ui/plugin-system/src/runtime/TimeRangeProvider/TimeRangeProvider.tsx
- ui/plugin-system/src/runtime/TimeRangeProvider/TimeRangeProviderWithQueryParams.tsx
- ui/plugin-system/src/runtime/TimeRangeProvider/query-params.ts
- ui/plugin-system/src/runtime/TimeRangeProvider/refresh-interval.ts
- ui/plugin-system/src/stories/shared-utils/decorators/WithTimeRange.tsx
This PR comes from the experience of creating an embedded panel in a separate UI. 
This requires for sure a `TimeRangeProvider`, but even if we set `enabledURLParams` property to `false`, it still requires to define a `QueryParamsProvider` upper, which leads to this kind of non-sense:
```tsx
<BrowserRouter>
<QueryParamProvider adapter={ReactRouter6Adapter} options={{ params: {} }}>
<TimeRangeProvider
initialRefreshInterval="0s"
initialTimeRange={{ pastDuration: '30m' }}
enabledURLParams={false}
>
<TemplateVariableProvider>
...
```
With this PR this PR you can fully decide to use or not query params
- If you don´t want to use them
```tsx
<TimeRangeProvider
refreshInterval="0s"
timeRange={{ pastDuration: '30m' }}
>
<TemplateVariableProvider>
...
```
- If you want to use them
```tsx …
```
> [BREAKINGCHANGE] Allow TimeRangeProvider and TemplateVariableProvider to live without QueryParamsProvider

- internal/api/shared/migrate/mapping.cuepart
- internal/api/shared/migrate/testdata/old_grafana_panels_perses_dashboard.json
- internal/api/shared/migrate/testdata/old_grafana_query_grafana_dashboard.json
- internal/api/shared/migrate/testdata/old_grafana_query_perses_dashboard.json
- internal/api/shared/migrate/testdata/simple_grafana_dashboard.json
- internal/api/shared/migrate/testdata/simple_perses_dashboard.json
- schemas/panels/time-series/migrate.cue
- schemas/queries/prometheus/migrate.cue
Closes https://github.com/perses/perses/issues/1520.
New fields supported when migrating a dashboard from Grafana:
**For List variables:**
- custom All value
**For Timeseries panel:**
- "stacked" property
- show/hide legend
- line width
- fill opacity
- connected nulls
- line vs bar display
**For Prom ts queries:**
- custom legend text
- min step
> [ENHANCEMENT] Support more attributes in Grafana migration

- ui/plugin-system/src/components/PanelSpecEditor/PanelSpecEditor.tsx
Limit the height just enough to always keep the tabs in sight.
This also avoids having to scroll at the very bottom to be able to scroll horizontally for long lines (e.g query expression).
> [ENHANCEMENT] Panel json view: add maxheight for better UX

- ui/app/src/model/migrate-client.ts
- ui/app/src/views/MigrateView.tsx
- ui/components/src/JSONEditor.tsx
- ui/dashboards/src/components/EditJsonDialog/EditJsonDialog.tsx
- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/plugin-system/src/components/PanelSpecEditor/PanelSpecEditor.tsx
All JSON views:
- find & replace interface is now showing up correctly. Fixes https://github.com/perses/perses/issues/1518.
Migrate screen:
- Grafana input: changed from **TextField** to **JSONEditor**. No more weird behavior when trying to modify things after initial copy-paste, & better UX overall.
- Migrate button: stronger checks for enabling (JSON parse should succeed).
- Migration output: it's now readonly. Fixes https://github.com/perses/perses/issues/1551.
> [BUGFIX] Fix several issues with JSON views

- ui/app/src/guard/GuardedAuthRoute.tsx
- ui/app/src/model/auth-client.ts
When the token expired, the cookies are removed since we set `maxAge` in the previous PR.
The redirection is currently broken because the cookies are removed when expire.
I think it's cleaner to remove the cookies when they expire and I think it is simpler to check if the cookies exist rather than trying to know if the token has been decoded and if it is expired (for the redirection I mean)
> [IGNORE] Fix redirection when token expired

- internal/api/config/database.go
By adding this default choice, we are able to run `Perses` with no configuration now.
> [ENHANCEMENT] File DB is the default choice if no db configuration is provided

- ui/app/src/components/Header.tsx
- ui/app/src/components/logo/PersesLogoCropped.tsx
- ui/app/src/utils/browser-size.ts
- ui/app/src/views/auth/SignWrapper.tsx
Here is a proposition to reorder the different button when you are on mobile.
- Logo is cropped
- Admin, config and migration button are available in a menu
https://github.com/perses/perses/assets/4548045/2cf46e2d-a763-4f88-8ec3-c6b92bfaf171
The swap of the theme will go in a user menu I think. A bit like GitHub.
> [ENHANCEMENT] Reorder navbar button on mobile

- ui/dashboards/src/components/Variables/TemplateVariable.test.ts
- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/e2e/src/pages/DashboardPage.ts
- ui/e2e/src/tests/jsonEditor.spec.ts
- ui/e2e/src/tests/saveDefaults.spec.ts
- ui/e2e/src/tests/variables.spec.ts
This PR changes ListVariable to rely on MUI's Autocomplete, in order to provide autocomplete & filtering.
https://github.com/perses/perses/assets/7058693/c3a3b4df-40ab-4ec0-b22b-2e83844c6b07
Making the display fit well & adapt to the content as much as possible was not easy.. a remaining pain point is that the input grows vertically with the content (especially annoying in case of long variable values for which `limitTags={3}` is not enough, eg:
Besides there's an annoying bug with the Autocomplete, the scroll goes to the top each time you click a value. This should be solved by upgrading the MUI dependency (see https://github.com/mui/material-ui/issues/29508). I'm planning to tackle this in a next PR.
- Does the time change? You …
> [ENHANCEMENT] Autocomplete & filtering for ListVariable

- ui/app/src/context/DarkMode.tsx
- ui/components/src/test-utils/theme.ts
- ui/components/src/utils/theme-gen.test.ts
- ui/components/src/utils/theme-gen.ts
``generateChartsTheme`` function is very practical, but I would like to propose the ability to override a bit more fields. This is a breaking change as the function is exposed and potentially used by users? @jgbernalp are you using it in Redhat?
> [BREAKINGCHANGE] generateChartsTheme can override any value

- ui/plugin-system/src/components/TimeSeriesQueryEditor/TimeSeriesQueryEditor.tsx
Move the Add Query button in the Panel editor from top-right to bottom-left. It doesn't change much when you have 1 query defined or 2, but avoids lots of scrolling when you start to have more.
> [ENHANCEMENT] Panel editor: reposition Add Query button for better UX

- ui/app/src/views/auth/SignInView.tsx
- ui/app/src/views/auth/SignUpView.tsx
This PR adds the ability for users to sign in and sign up by hitting the `Enter` key after entering their username & password.
Before this a user has to switch from the keyboard to the mouse and click the "Sign in" / "Register" button, which is inconvenient.
IMPORTANT: Currently this is only my idea how to do it as I'm not very familiar in React. Any feedback is appreciated. I also tried using an HTML `<form>` but it breaks the design, hence this a bit more complex approach.
> [ENHANCEMENT] Submit sign-in & sign-up forms on pressing Enter key

- ui/app/src/components/DashboardCard/DashboardCard.tsx
- ui/app/src/components/Header.tsx
- ui/app/src/components/breadcrumbs/AppBreadcrumbs.tsx
- ui/app/src/components/breadcrumbs/ProjectBreadcrumbs.tsx
- ui/app/src/components/breadcrumbs/breadcrumbs.tsx
- ui/app/src/components/tabs.tsx
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/config/ConfigView.tsx
- ui/app/src/views/home/HomeView.tsx
- ui/app/src/views/home/ProjectsAndDashboards.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/ProjectView.tsx
- ui/app/src/views/projects/RecentlyViewedDashboards.tsx
- ui/app/src/views/projects/dashboards/HelperDashboardView.tsx
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
This PR:
- merges the section title with the breadcrumb on all pages (Admin, Project etc.) to save some vertical space
- reduces the tabs size on the project & admin page (see above screenshots)
- changes the project icon from "folder" to archive" (see above screenshots)
- adds icons in the dashboard breadcrumb
- brings back the delete project button on the Project page, which was unintentionally removed by https://github.com/perses/perses/pull/1267
> [ENHANCEMENT] several display improvements + bring back delete project button

- ui/app/src/views/projects/explore/ExploreView.tsx
- ui/explore/src/components/ExploreToolbar/ExploreToolbar.tsx
- ui/explore/src/components/PanelEditor/PanelEditorForm.tsx
- ui/explore/src/components/TimeSeriesQueryEditor/TimeSeriesQueryEditor.tsx
- ui/explore/src/views/ViewExplore/ViewExploreApp.tsx
This build issue arrived on the main branch because https://github.com/perses/perses/pull/1590 was not rebased on latest main state after https://github.com/perses/perses/pull/1477 was merged..
I also did some adjustments to the Explore page layout at the same time (align breadcrumb & base margin with the other pages + move Add Query button down).
> [BUGFIX] Fix broken import on Explore view + some display adjustments

- ui/app/src/components/datasource/DatasourceList.tsx
In the `onSave` for the DataSourceDrawer in the DatasourceList, we call `handleDatasourceUpdate`, which calls `setDatasourceDrawerOpened` https://github.com/perses/perses/blob/1e889c657e2fba79b0ba2563e4aa972ed1d747c5/ui/app/src/components/datasource/DatasourceList.tsx#L80-L86, but we then call it again in the callback. This removes the extra call.
> [BUGFIX] Remove extra call to `setDatasourceDrawerOpened` in DatasourceList

- internal/api/config/authorization.go
- internal/api/config/config_test.go
Marshalling of the config didn't work well for the interval of the authorisation config. The interval wasn't marshall with the proper format (aka "10m0s")
> [BUGFIX] Fix marshalling authorisation config in json

- ui/prometheus-plugin/src/model/prometheus-client.ts
- ui/prometheus-plugin/src/plugins/prometheus-datasource.tsx
As a first step towards #1542 (and as my first PR, so feedback appreciated), this implements a healthcheck on Prometheus Datasources.
The `DatasourceClient` interface defines a `healthcheck` method, which
hasn't actually been implemented. This implements it for the `PrometheusDatasourceClient`
as a first step towards being able to test the health of a datasource.
The actual implementation calls the [/-/healthy](https://prometheus.io/docs/prometheus/latest/management_api/#health-check)
endpoint in the Prometheus API, rather than running a query. I figured
this was a better way to test the health rather than running a dummy
query and checking the result, as running a query is a more expensive
and subjects us to the vagaries of PromQL, and potential
query timeouts which aren't directly …
> [ENHANCEMENT] Implement the `healthcheck` method for Prometheus datasources

- ui/app/src/components/CRUDButton/CRUDButton.tsx
- ui/app/src/components/DashboardList/DashboardList.tsx
- ui/app/src/components/DashboardList/RecentDashboardList.tsx
- ui/app/src/components/datasource/DatasourceList.tsx
- ui/app/src/components/secret/SecretList.tsx
- ui/app/src/components/variable/VariableList.tsx
- ui/app/src/context/Config.tsx
- ui/app/src/guard/GuardedAuthRoute.tsx
- ui/app/src/model/config-client.ts
- ui/app/src/model/dashboard-client.ts
- ui/app/src/render-app.tsx
- ui/app/src/views/MigrateView.tsx
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/config/ConfigView.tsx
- ui/app/src/views/home/InformationSection.tsx
- ui/app/src/views/home/ProjectsAndDashboards.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/dashboards/DashboardView.tsx
This PR is just refactoring the way to access the config. I'm introducing a context so the different component can have access to the config without having to deal with async and network issue.
Today the config is already heavily use and I think it makes sense to simplify the usage and its access of it.
I find the code cleaner with this way (but perhaps it's just matter of test ;))
> [ENHANCEMENT] Use a context for the config to share it across the whole app

- docs/configuration.md
- internal/api/config/security.go
This PR is adding a default encryption key. I'm doing it that to avoid the situation when you are trying Perses and you reload the instance the encryption key is changing and you need to dumb the database because the backend cannot read it anymore.
> [ENHANCEMENT] add a default encryption key

- ui/app/src/components/rolebindings/RoleBindingDrawer.tsx
- ui/app/src/components/rolebindings/RoleBindingEditorForm.tsx
- ui/app/src/components/rolebindings/RoleBindingList.tsx
- ui/app/src/components/roles/RoleEditorForm.tsx
- ui/app/src/model/global-role-client.ts
- ui/app/src/model/global-rolebinding-client.ts
- ui/app/src/utils/role.ts
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/admin/tabs/GlobalRoleBindings.tsx
- ui/app/src/views/admin/tabs/GlobalRoles.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
This PR contains the following:
- Add CRUD for Global Role and Role Bindings at global level. Similar to PR #1601 for project level
- Improve RoleBinding listing
- Improve RoleBinding form with autocomplete for Role name
> [FEATURE] UI - Add CRUD for GlobalRoles and GlobalRoleBindings resources

- ui/dashboards/src/components/Datasources/EditDatasourcesButton.tsx
- ui/dashboards/src/context/DatasourceStoreProvider.test.tsx
- ui/dashboards/src/context/DatasourceStoreProvider.tsx
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
- ui/plugin-system/src/components/DatasourceSelect.tsx
- ui/plugin-system/src/runtime/datasources.ts
- ui/plugin-system/src/stories/shared-utils/decorators/WithPluginSystemDatasourceStore.tsx
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/plugin.test.ts
Previously, when a dashboard level datasource is added to a dashboard, it is immediately available for use in the dashboard. This causes an error because the server side (e.g. the proxy endpoints) isn't created until the dashboard is saved.
Here we introduce the idea of "saved" datasources, which are the datasources that are available for use in the dashboard because they have been created through a dashboard save.
We then use this list of saved datasources to disable entries in the datasource select dropdown, with an indication that the dashboard needs to be saved before the datasource can be used.
https://github.com/perses/perses/assets/4386405/63a71f53-1636-41fb-8e46-e036bca62643
- Does the time change? You need to use …
> [ENHANCEMENT] Prevent using dashboard datasources before they're saved

- ui/endpoint.go
When you are using the binary `perses` and going to the explore page with the URL, the page is not loaded.
This PR is fixing that.
> [BUGFIX] Fix reaching directly the page explorer without using the react router

- ui/tempo-plugin/src/plugins/plugin.test.ts
Fix broken `type-check` step on main branch that happened because of merging https://github.com/perses/perses/pull/1603 right after https://github.com/perses/perses/pull/1561 (thus main branch from #1603 PoV didn't have the changes from #1561).
We might think of adding branch protection or builds triggered automatically after target branch update in order to avoid this to happen again..
> [BUGFIX] fix broken type-check on main branch

- docs/configuration.md
- internal/api/config/config_test.go
- internal/api/config/security.go
- internal/api/core/server.go
- internal/api/impl/v1/user/endpoint.go
- ui/app/src/Router.tsx
- ui/app/src/model/auth-client.ts
- ui/app/src/model/config-client.ts
- ui/app/src/views/auth/SignInView.tsx
I'm adding a new entry in the authentication config: `deactivate_sign_up`. With this config we can deactivate the `SignUp` page and the possibility to create a new user.
That should be useful once we are supporting OIDC.
As a side effect, when a route is not known, it is now redirecting to the home page.
Also if there is a valid access token in the cookies, it is not possible to reach the `SignIn` page
> [ENHANCEMENT] SignUp page can be deactivated and sign-in page cannot be reached if token exists

- .github/workflows/ci.yaml
- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/react.yml
that's the config required to trigger the CI in the merge queue: https://github.com/perses/perses/queue/main
More info: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
> [IGNORE] Support merge group in the ci

- ui/prometheus-plugin/src/plugins/PrometheusDatasourceEditor.tsx
Previously, the fields created with the PrometheusDatasourceEditor weren't wired into the form infrastructure. This means that, among other things, if you edit the URL of the datasource, the form doesn't know that the datasource has changed and doesn't allow you to save.
This change wraps the PrometheusDatasourceEditor inputs with react-hook-form Controllers, which means that the form is now aware of changes.
Before: (Editing the URL doesn't allow you to save)
https://github.com/perses/perses/assets/4386405/1d4602f6-b913-40e3-8e8f-c9513623c01c
After:
https://github.com/perses/perses/assets/4386405/fd146205-53b4-4a6c-b492-5fe6818953b7
- Does it …
> [BUGFIX] Wrap PrometheusDatasourceEditor with react-hook-form Controllers

- .github/pull_request_template.md
- README.md
- docs/design-docs/authorization.md
Adding screenshot of a Perses dashboard in the readme. Because visitors can't see what Perses look like without running it or going to the demo instance. Fixed by adding the screenshot of a migrated dashboard about node exporter metrics
> [DOC] Add the screenshot of a Perses dashboard in the README

- ui/app/src/model/fetch.ts
When the access token expired, you may have noticed that the token is indeed refreshed but there is still an error saying the token is malformed and so you don't have access to the API.
That's because the retry of the query is performed before getting the new token. This is now done with this PR
> [BUGFIX] Fix the token refresh that required a complete refresh of the page to be considered

- ui/app/src/components/breadcrumbs/ProjectBreadcrumbs.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/variable-editor-form-model.ts
- ui/plugin-system/src/validation/variable.ts
Similar to PR #1621: all inputs are wrapped around controller and will update the state of the form + validation.
It still not at role / rolebinding form editor level, because of setState stuff (could be removed if all fields have controller associated to, but it will be tricky with the PluginEditor)
No change on UI side
include:
- Does it have …
> [ENHANCEMENT] Improve variable editor form state update

- ui/dashboards/src/components/AddGroupButton/AddGroupButton.tsx
- ui/dashboards/src/components/AddPanelButton/AddPanelButton.tsx
- ui/dashboards/src/components/DashboardStickyToolbar/DashboardStickyToolbar.tsx
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/Datasources/EditDatasourcesButton.tsx
- ui/dashboards/src/components/Variables/EditVariablesButton.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/dashboards/src/constants/styles.ts
Improve the dashboard toolbar UX by:
- repositioning the buttons to have less difference between read & edit modes,
- improving its responsiveness: variables take more advantage of the space available + put some limit to the vertical space used when there are many of them, by adding scrolling (basically vertical when not sticky, horizontal when sticky).
_FYI I'm planning to make the JSON view available in the read mode too in a future PR, this is also going to reduce the visual difference between the two modes._ 
Buttons position:
:-------------------------:|:-------------------------:
Responsiveness:
https://github.com/perses/perses/assets/7058693/bdb22e34-d6cf-44da-9fb4-9469ed9f86de
⚠️ something I didn't take time to improve in this PR is the space used by the edit …
> [ENHANCEMENT] Improve dashboard toolbar UX

- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/EditJsonButton/EditJsonButton.tsx
- ui/dashboards/src/components/EditJsonDialog/EditJsonDialog.tsx
- ui/dashboards/src/constants/user-interface-text.ts
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
The button to access the dashboard's JSON in the toolbar is now accessible in read mode too, allowing the users to view the JSON definition of the dashboard without being able to edit it.
https://github.com/perses/perses/assets/7058693/c2eb8c44-81d6-432c-9632-aa5e4cde023b
include:
- Does it have loading states? You need to wait for loading to …
> [FEATURE] Allow visualizing the dashboard's JSON in read mode

- ui/plugin-system/src/components/DatasourceEditorForm/DatasourceEditorForm.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
Fixes https://github.com/perses/perses/issues/1653.
Empty strings for desc attributes are no longer kept when applying/saving.
include:
> [BUGFIX] Fix missing tooltip on updated variables

- .github/workflows/ci.yaml
Reverts perses/perses#1656
It looks like there is a breaking change on how to upload/download an artifact in the github action version and the documentation is not obvious on how to fix it: https://github.com/actions/toolkit/tree/main/packages/artifact#breaking-changes
The Github documentation is not yet updated about the new way to upload the files
> Revert "Bump actions/download-artifact from 3 to 4"

- internal/api/core/server.go
- internal/api/impl/proxy/proxy.go
- internal/api/shared/utils/utils.go
Add ability to proxy unsaved datasources
This adds the ability to proxy unsaved datasources. This is effectively
the same as the existing proxy functionality, but loading the datasource
from a spec in the request body rather than from the database. This is useful
for testing datasources before saving them, and for using local datasources
before the dashboard has been saved.
In order to not make this an open proxy, we authenticate calls to the
proxy endpoint, ensuring that users have create datasource permissions.
This is a bit awkward to do in the proxy, because it required another middleware
to extract the claims, but it seems to work - I'd appreciate any comments
on making that cleaner.
following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, `BREAKINGCHANGE`, …
> [ENHANCEMENT] Add in a proxy for unsaved datasources

- ui/dashboards/src/components/Datasources/DatasourceEditor.tsx
- ui/plugin-system/src/components/DatasourceEditorForm/DatasourceEditorForm.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
Closes #1652.
https://github.com/perses/perses/assets/7058693/c1e85d86-8fd5-4d3a-a328-d2a5a68b53a1
include:
> [ENHANCEMENT] Allow editing the name of the local resources

- .github/workflows/ci.yaml
I'm deactivating the push of the storybook to happo to have a diff.
At least we will finally have a green status for the CI. And we can still work on it once we have time to do it
> [IGNORE] deactivate happo storybook visual

- docs/user-guides/installing-perses-in-a-container.md
I'm adding a little description about the different tags we are provided. Maybe it can help a bit to understand which one you should use depending on the context.
I'm also taking the opportunity to cleanup and rewording a bit the rest of the documentations.
For example, I have removed the section `Note: What to do with failures?`. Someone that knows how to use docker/podman is already aware about how to destroy a container.
/cc @eschabell
> [DOC] Add a section about the different container tags provided

- schemas/common/calculation.cue
'Doing this as we already have such "last as default" behavior on the UI, and it would make sense to have this as part of the schemas too (useful e.g to mimic the same behavior with the dashboard as code use case).
> [IGNORE] Make `last` the default value for the `calculation` attribute

- internal/cli/config/config.go
Currently when you run the command login twice (when starting from scratch), the second time it didn't write in the config file the new token received. Which makes the command login failed successfully 😄
> [BUGFIX] Fix login command that didn't rewrite the token after a second connection

- CONTRIBUTING.md
- scripts/api_backend_dev.sh
Just submitting this as a quick proposal.
We've had a couple of cases in the chat where folks have been confused about how to log in to the backend dev server. This adds a echo to the script that tells them how to do it.
> [IGNORE] Add authentication details to backend dev script

- cmd/percli/main.go
- internal/cli/cmd/login/login.go
- internal/cli/cmd/project/project.go
- internal/cli/cmd/refresh/refresh.go
- internal/cli/config/config.go
- pkg/client/api/auth.go
when the authentication is enabled, it's quite annoying to login every 15min. 
Since we have a refresh token mecanism, I'm proposing a new command `refresh` that will contact the API to get a new access token
That's a beginning, perhaps for long term we want an automatic way to refresh the token like the UI has.
> [FEATURE] CLI: add a new command  to refresh the access token

- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/dashboards/src/components/Variables/VariableList.tsx
- ui/dashboards/src/constants/styles.ts
Implement dynamic input resize for Text variables, as it was done for List variables in https://github.com/perses/perses/pull/1576.
_As in this past PR, the computed input size doesn't perfectly fit the text content due to the approximation done to consider that each character = 8px. It's still better than before but could for sure be improved._
https://github.com/perses/perses/assets/7058693/57bcbf30-e479-405d-b600-bfa1bc464de2
include:
- Is the data inconsistent? You need to mock API …
> [ENHANCEMENT] Auto input resize for text variables

- go.mod
- internal/api/e2e/framework/server.go
- pkg/model/api/config/config_test.go
- pkg/model/api/config/database.go
- pkg/model/api/config/security.go
- pkg/model/api/v1/common/url.go
- pkg/model/api/v1/common/url_test.go
- pkg/model/api/v1/secret/secret.go
- pkg/model/api/v1/secret/secret_test.go
- One new URL type supporting any deserialization/serialization.
- Hidden type augmented to support MarshalText
These two types will be designed to be used in configuration, to simplify some url treatment and secure sensitive strings.
include:
> [ENHANCEMENT] New type for URL and Secret suitable for configuration

- docs/user-guides/configuration.md
- internal/api/impl/auth/native.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- internal/api/impl/auth/userinfo.go
- pkg/model/api/config/authentication.go
- pkg/model/api/config/authentication_test.go
- pkg/model/api/config/security.go
- pkg/model/api/v1/common/url.go
- pkg/model/api/v1/common/url_test.go
This PR comes after having tested several external OIDC provider.
So far I tested Azure, Google, Gitlab, Linkedin as OIDC providers. 
This last one seems to not support all the features like the others.
That's why this PR allow more fine grain in configuration:
Set a custom Discovery URL (the famous "/.well-known/openid-configuration" where all the config can be accessed)
With linkedin the problem is that the lib we use expected the discovery url to be {issuer}/.well-known/openid-configuration, which is not the case
```
// 20240102161055
// https://www.linkedin.com/oauth/.well-known/openid-configuration
{
"issuer": "https://www.linkedin.com",
```
By default my first implementatio assumed that PKCE verification is supported by all the OIDC providers, which is not the case. 
So we can now …
> [ENHANCEMENT]: Some improvements around OIDC/OAuth provider configuration

- dev/data/user.json
- docs/api/user.md
- internal/api/e2e/api/auth_test.go
- internal/api/e2e/api/rbac_test.go
- internal/api/e2e/framework/data.go
- internal/api/impl/auth/auth.go
- internal/api/impl/auth/native.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- internal/api/impl/auth/service.go
- internal/api/impl/auth/service_test.go
- internal/api/impl/auth/userinfo.go
- internal/api/impl/v1/user/service.go
- pkg/model/api/v1/public_user.go
- pkg/model/api/v1/user.go
- ui/app/src/model/auth-client.ts
- ui/app/src/model/user-client.ts
- ui/app/src/views/auth/SignUpView.tsx
- ui/app/src/views/auth/SignWrapper.tsx
This PR add the last important missing brick which consist in saving the user once logged in. 
It allows then to add some permissions to that user. 
include:
> [BREAKING CHANGE] Sync external user with database at login time

- .github/workflows/ci.yaml
- .github/workflows/delete-snapshot.yml
- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/react.yml
- docs/user-guides/configuration.md
- internal/api/impl/auth/auth.go
- internal/api/impl/auth/auth_test.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- pkg/model/api/config/authentication.go
In some companies you may be under different proxy when you run your perses instance. 
This PR is make it possible to replace the redirect_uri hardly defined in oauth config to something computed dynamically
include:
> [ENHANCEMENT] OAuth/OIDC possibly get redirect_uri from request

- .github/workflows/go.yml
> [IGNORE] new github action to ensure CUE gen files are up to date with Go datamodel

- cue/model/api/v1/metadata_go_gen.cue
- cue/model/api/v1/metadata_patch.cue
- internal/api/e2e/framework/data.go
- internal/api/shared/schemas/schemas_test.go
- internal/api/shared/utils/utils.go
- internal/cli/cmd/dac/build/testdata/invalid_dac.cue
- internal/cli/cmd/dac/build/testdata/working_dac.cue
- internal/cli/cmd/describe/describe_test.go
- internal/test/dac/expected_output.json
- internal/test/dac/input.cue
- pkg/client/fake/api/v1/folder.go
- pkg/client/fake/api/v1/folder_test.go
- pkg/model/api/v1/dashboard_test.go
- pkg/model/api/v1/metadata.go
- pkg/model/api/v1/metadata_test.go
- pkg/model/api/v1/utils/default.go
- pkg/model/api/v1/utils/variable_build_order_test.go
Run `ValidateID()` as part of the v1.Metadata unmarshalling, so the constraints apply consistently for any kind of resource having metadata.
This solves some validation discrepancies (e.g DaC unit tests, unmarshalling was working but trying to apply the dashboard to a Perses server was failing).
> [ENHANCEMENT] Run ID validation on Metadata.Name in all cases to avoid discrepancies

- schemas/queries/prometheus/query.cue
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/get-time-series-data.ts
Closes https://github.com/perses/perses/issues/1724.
include:
> [ENHANCEMENT] Support referencing variables in 'Min step' field

- pkg/client/api/auth.go
I think I broke the refresh when I implemented the external auth 
Here is where it was broken 
Refresh was calling the /auth/providers/native/login/refresh endpoint instead of /auth/refresh
include:
> [BUGFIX] Fix the refresh token client in the CLI

- pkg/model/api/v1/common/plugin.go
- pkg/model/api/v1/dashboard/layout.go
- pkg/model/api/v1/dashboard/variable.go
This PR adds kubebuilder annotations to interface types that are resolved at runtime, this allows that the CRD schema can store these dynamic fields
no UI changes
> [ENHANCEMENT] add kubebuilder annotations to runtime types

- internal/api/core/core.go
- internal/api/shared/dependency/service_manager.go
- internal/api/shared/provisioning/provisioning.go
I think it makes more sense to have the provisioning to not be included in the `service_manager`. It's not a service but just a cron task, so no reason to let the `service_manager` returning an instance of the provisioning.
> [IGNORE] Move provisioning to a dedicated package

- dev/config.yaml
- docs/user-guides/configuration.md
- internal/api/core/core.go
- internal/api/shared/dashboard/cleaner.go
- internal/api/shared/dashboard/cleaner_test.go
- pkg/model/api/config/config.go
- pkg/model/api/config/config_test.go
Ephemeral dashboards are automatically removed once expiration delay has passed.
New config param added to tune the interval.
> [FEATURE] Ephemeral dashboards are automatically removed once expiration delay has passed

- ui/components/src/LineChart/LineChart.tsx
- ui/components/src/TimeChart/TimeChart.tsx
- ui/components/src/TimeSeriesTooltip/LineChartTooltip.tsx
- ui/components/src/TimeSeriesTooltip/TimeChartTooltip.tsx
- ui/components/src/TimeSeriesTooltip/nearby-series.ts
- ui/components/src/TimeSeriesTooltip/tooltip-model.ts
- ui/components/src/TimeSeriesTooltip/utils.ts
- ui/components/src/utils/chart-actions.ts
- ui/panels-plugin/src/plugins/scatterplot/Scatterplot.tsx
Fixes #1396
Tooltip is broken in Firefox, fix up the mousemove logic (offsetX and offsetY have subtle differences with Chrome)
zrender is the canvas/svg graphics lib that ECharts is built on, main change is to always use their mousemove coords that [handle browser inconsistencies](https://github.com/ecomfe/zrender/blob/5.5.0/src/core/event.ts#L46-L120) for us
https://github.com/perses/perses/assets/9369625/f8d9433e-4147-47fc-bae7-87ccf86242b1
Also see recording in #1396
https://github.com/perses/perses/assets/9369625/a346979d-e143-452f-a3fc-e4f3b065ca57
https://github.com/perses/perses/assets/9369625/8f7ec20a-1d7e-4f13-b99f-31f37f1b4ab3
See …
> [BUGFIX] Tooltip positioning broken in Firefox

- go-sdk/dashboard/dashboard.go
- go-sdk/dashboard/dashboard_test.go
- go-sdk/dashboard/options.go
- go-sdk/group/options.go
- go-sdk/group/variable.go
- go-sdk/prometheus/variable/label-names/label-names.go
- go-sdk/prometheus/variable/label-names/options.go
- go-sdk/prometheus/variable/label-values/label-values.go
- go-sdk/prometheus/variable/label-values/options.go
- go-sdk/prometheus/variable/promql/promql.go
- go-sdk/variable/list-variable/list-variable.go
- go-sdk/variable/list-variable/options.go
- go-sdk/variable/options.go
- go-sdk/variable/plugin/static-list/static-list.go
- go-sdk/variable/text-variable/options.go
- go-sdk/variable/text-variable/text-variable.go
- go-sdk/variable/variable.go
Align Go SDK with Cue feature, you can create grouped variables. Grouped variables will be filtered by their parent variables. For now, it only applied automatically to label values and label names variables matchers.
Prev:
```golang
dashboard.AddVariable("stack",
listVar.List(
labelValuesVar.PrometheusLabelValues("stack",
labelValuesVar.Matchers("thanos_build_info{}"),
labelValuesVar.Datasource("promDemo"),
),
listVar.DisplayName("PaaS"),
),
),
dashboard.AddVariable("namespace", listVar.List(
labelValuesVar.PrometheusLabelValues("namespace",
labelValuesVar.Matchers("kube_namespace_labels{\"stack\"=\"$stack\"}"),
labelValuesVar.Datasource("promDemo"),
),
)),
dashboard.AddVariable("namespaceLabels", listVar.List(
labelNamesVar.PrometheusLabelNames( …
```
> [ENHANCEMENT] Add grouped variable helper in Go SDK

- internal/cli/cmd/dac/setup/setup.go
Just a simple addition to avoid further manual steps to the DaC users.
This step is skipped if the .gitignore file is not already present.
> [ENHANCEMENT] `percli dac setup` adds output dir to .gitignore

- ui/dashboards/src/components/DashboardStickyToolbar/DashboardStickyToolbar.tsx
- ui/dashboards/src/components/Variables/TemplateVariable.tsx
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
- ui/plugin-system/src/components/Variables/variable-model.ts
- ui/plugin-system/src/runtime/template-variables.ts
Fixing promql variables loading indefinitely when using builtin variables in the expr. Closes #1552.
The issue come from Object.assign ...
On the way I did small improvements
> [BUGFIX] Fixing variable loading indefinitely

- ui/app/src/components/datasource/DatasourceDataGrid.tsx
- ui/app/src/components/datasource/DatasourceList.tsx
Add a column for displaying if a datasource is a default datasource or not
Before:
After:
include:
> [ENHANCEMENT] Make default datasources more visible

- .gitignore
- ui/plugin-system/src/runtime/TimeRangeProvider/TimeRangeProvider.tsx
When using embedded dashboard on our app, we saw that the refreshing button in timerange control was not updating the "relative" time range and queries/panels were not updated. It's fixed with this new dependency on the useEffect.
And added a pattern for easily ignoring files 😄 
> [BUGFIX] Update relative timerange value when refreshing

- ui/app/src/components/CRUDButton/CRUDGridActionsCellItem.tsx
- ui/app/src/components/DashboardList/DashboardList.tsx
- ui/app/src/components/datasource/DatasourceList.tsx
- ui/app/src/components/dialogs/CreateDashboardDialog.tsx
- ui/app/src/components/rolebindings/RoleBindingList.tsx
- ui/app/src/components/roles/RoleList.tsx
- ui/app/src/components/secrets/SecretList.tsx
- ui/app/src/components/variable/VariableList.tsx
- ui/app/src/views/admin/tabs/GlobalDatasources.tsx
- ui/app/src/views/admin/tabs/GlobalRoleBindings.tsx
- ui/app/src/views/admin/tabs/GlobalRoles.tsx
- ui/app/src/views/admin/tabs/GlobalSecret.tsx
- ui/app/src/views/admin/tabs/GlobalVariables.tsx
- ui/app/src/views/home/HomeView.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/app/src/views/projects/dashboards/CreateDashboardView.tsx
- ui/app/src/views/projects/tabs/ProjectDatasources.tsx
- ui/app/src/views/projects/tabs/ProjectRoleBindings.tsx
- ui/app/src/views/projects/tabs/ProjectRoles.tsx
- ui/app/src/views/projects/tabs/ProjectSecrets.tsx
- ui/app/src/views/projects/tabs/ProjectVariables.tsx
Add duplicate button on resource lists for global and project resources. Closes: https://github.com/perses/perses/issues/1383
include:
> [FEATURE] Add duplicate button for global and project resources

- ui/app/src/components/datasource/DatasourceDrawer.tsx
- ui/app/src/components/variable/VariableDrawer.tsx
- ui/app/src/views/projects/explore/ProjectExploreView.tsx
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
- ui/plugin-system/src/runtime/plugin-registry.ts
PluginRegistry no longer need a default plugin kind. Remove some unnecessary code and dep on prometheus plugin.
> [ENHANCEMENT] Make defaultPluginKinds of PluginRegistry provider optionnal

- internal/cli/cmd/apply/apply.go
- internal/cli/cmd/dac/build/build.go
- internal/cli/cmd/dac/dac.go
- internal/cli/cmd/dac/preview/preview.go
- internal/cli/cmd/dac/preview/preview_test.go
- internal/cli/cmd/lint/lint.go
- internal/cli/service/service.go
- pkg/client/fake/api/client.go
- pkg/client/fake/api/v1/client.go
- pkg/client/fake/api/v1/ephemeraldashboard.go
I'm adding a new command that would help for the preview of the dashboard in the context of the `dashboard as code`.
```bash
percli dac preview -d ./built
```
The command will give a give of URLs for the previews. For example:
```yaml
- project: perses
dashboard: Demo
preview: http://localhost:8080/api/v1/projects/perses/ephemeraldashboards/pr-1664-Demo
- project: perses
dashboard: Benchmark
preview: http://localhost:8080/api/v1/projects/perses/ephemeraldashboards/pr-1664-Benchmark
```
Today through flags provided by the command, you can add two prefixes: the repository name & the pull request name.
I'm wondering if we should add another flags for generic prefix or it's fine like that.
Note: result can be printed in JSON too
> [FEATURE] Add dac preview command

- cmd/percli/main.go
- internal/cli/cmd/dac/dac.go
I'm adding a global flag for all `dac` sub command so we can set the output folder at any moment.
> [ENHANCEMENT] add persistant flag to set the output folder for dac

- ui/app/src/views/projects/ProjectTabs.tsx
Ephemeral dashboards would be created either via DaC or via temporary copy of existing dashboards (https://github.com/perses/perses/pull/1818)
include:
> [IGNORE] Remove Add dashboard button for ephemeral dashboards

- internal/api/provisioning/provisioning.go
This is mainly to stop considering `unable to retrieve the service associated to \"EphemeralDashboard\"" error="resource \"EphemeralDashboard\" not supported by the provisioning service` as an error, as it's an acknowledged decision to not support ephemeral dasboards via provisioning.
> [IGNORE] change provisionning failure log from error to warning

- docs/user-guides/configuration.md
- internal/api/impl/auth/auth.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- internal/api/impl/auth/service.go
- internal/cli/cmd/login/login.go
- pkg/client/api/auth.go
- pkg/model/api/auth.go
- pkg/model/api/config/authentication.go
Implement the client credentials flow. It will allow to authenticate in Perses through CLI or API using a robotic access like it would be needed in scripted pipeline for example. 
A specification documentation with a sequence diagram is coming, but the logic is the same as the auth code/device code flow, we send a query to /providers/{oidc|oauth}/{slug_id}/token, it asks a token to the provider and generate a Perses access token from it. 
It performs also a user synchronization to save a user using a ``metadata.name`` as good as we can. The decision of what to take as ``metadata.name`` is not easy but the ``GetLogin`` of both oauth and oidc are well encapsulated and quite explicit. We can improve but for now it is good enough in my opinion.
following `catalog_entry` values: `FEATURE`, …
> [FEATURE] Client Credentials authentication flow

- ui/app/src/App.tsx
- ui/app/src/Router.tsx
- ui/app/src/components/Header.tsx
- ui/app/src/context/Authorization.tsx
- ui/app/src/context/Config.tsx
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
Disabling tabs if user do not have enough permission. Hiding is a little more tricky: what do we do if all tab are hidden. 
Bonus: admin menu hidden if user don't have read permission on at least one admin resource.
Related to  #1844 
include:
> [ENHANCEMENT] Tab disabled if user do not have read permission

- pkg/model/api/v1/dashboard/variable_test.go
- pkg/model/api/v1/variable/text.go
Allow empty value for non-constant TextVariables. This is especially useful for the Grafana migrate use case, for which the non-empty value constraint is currently preventing to migrate dashboards that define Textbox variables without default value. 
The constraint is kept for constants, as empty constants don't really make sense.
> [ENHANCEMENT] Allow empty value for non-constant TextVariables (= textbox use case)

- internal/api/migrate/mapping.cuepart
A Grafana variable can have a custom All value defined even if the "include All" option is not ticked. On our side we have backend validation that forbids this, thus this PR patches the migration logic to avoid migrating the custom All value if "include All" is not ticked.
This avoids the migration to fail with this error: 
> [ENHANCEMENT] Grafana migrate: avoid error when variable defines a "ghost" All value

- ui/app/src/views/import/PersesFlow.tsx
When importing dashboards we fail to set the project correctly. This causes dashboards to be imported into the project set in the JSON, rather than the project the user has selected.
This fixes this by setting the project in the `PersesFlow` component when the user selects a project.
Solves #1833
include:
- Does it have loading states? You need to …
> BUGFIX: Fix setting projects when importing Perses dashboards

- ui/app/src/components/Header.tsx
- ui/app/src/context/Authorization.tsx
- ui/app/src/model/auth-client.ts
Authorization Provider data is reset when token expire, this PR keep the data even if the TTL is passed.
> [BUGFIX] Don't reset token data when expired

- ui/dashboards/src/components/GridLayout/GridTitle.tsx
In the optic to keep more place for useful data (panels), I propose to reduce panel group header height. Thanks for the idea @lalooose 😄 
Before:
After:
include:
> [ENHANCEMENT] Reduce panel group header height

- ui/app/src/views/projects/explore/ExploreView.tsx
- ui/app/src/views/projects/explore/ProjectExploreView.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.test.tsx
- ui/dashboards/src/components/TimeRangeControls/TimeRangeControls.tsx
- ui/dashboards/src/constants/user-interface-text.ts
- ui/e2e/src/tests/saveDefaults.spec.ts
- ui/explore/src/views/ViewExplore/ViewExplore.tsx
- ui/explore/src/views/ViewExplore/ViewExploreApp.tsx
This PR aims to eliminate the dependency of ``TimeRangeControl`` on dashboard package.
It remains in dashboard package to make the move inanother PR.
The only dependency remaining is the ToolbarIconButton, but this component is isolated as well, so it can be also moved.
Now the next question will be: **where do we put them?** Knowing that ``TimeRangeControls`` have now dep on ``components``, ``core``, and ``plugin-system``. :question: :question: :question: 
include:
- Is the data inconsistent? …
> [REFACTOR] Free TimeRangeControls from dashboard dep

- internal/api/migrate/mapping.cuepart
- internal/api/migrate/migrate.go
- internal/api/migrate/migrate_test.go
- internal/api/migrate/testdata/empty_panels_list_grafana_dashboard.json
- internal/api/migrate/testdata/empty_panels_list_perses_dashboard.json
- pkg/model/api/v1/dashboard.go
- pkg/model/api/v1/dashboard_test.go
- pkg/model/api/v1/ephemeraldashboard_test.go
Hi folks, I am first time contributor of this repo, not sure we are aligned the fix on this ticket https://github.com/perses/perses/issues/1536. This PR intent to allow migration of empty panels dashboard from Grafana, and remove the panels check in the schema of dashboard v1. 
- na Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- na Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- na Visual tests are stable and unlikely to be flaky.
and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) …
> [ENHANCEMENT] Allow migration of empty panel dashboard

- internal/api/migrate/migrate.go
- ui/app/src/views/import/GrafanaFlow.tsx
- [BUGFIX] Grafana migrate: fix issue with inputs containing double quotes
- [ENHANCEMENT] Grafana migrate: set current input value as default suggestion
For the enhancement part:
Before, current values of constants were lost in the process:
Now, current values are provided as default values. You can always change them.
include:
- Does it have …
> [BUGFIX] Grafana migrate: fix issue with inputs containing double quotes

- docs/user-guides/dashboard-as-code.md
Website is back online https://cuetorials.com.
Partial revert of https://github.com/perses/perses/pull/1862.
> [IGNORE] DaC CUE SDK documentation: bring back link to Cuetorials

- internal/cli/cmd/login/device_code.go
- internal/cli/cmd/login/login.go
- internal/cli/cmd/login/login_test.go
- internal/cli/cmd/login/native.go
- internal/cli/cmd/login/robotic.go
This PR is refactoring the way we are managing the different provider in the CLI cmd `login`.
Like that each login flows are isolated from each other and we cannot execute a default flow if nothing is entered.
> [ignore] refactor the way different provider are managed in the login 

- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/dashboards/src/context/DatasourceStoreProvider.tsx
- ui/dashboards/src/validation/panel.ts
- ui/plugin-system/src/components/DatasourceEditorForm/DatasourceEditorForm.tsx
- ui/plugin-system/src/components/PluginEditor/PluginEditor.test.tsx
- ui/plugin-system/src/components/PluginEditor/PluginEditor.tsx
- ui/plugin-system/src/components/PluginEditor/plugin-editor-api.ts
- ui/plugin-system/src/components/PluginKindSelect/PluginKindSelect.test.tsx
- ui/plugin-system/src/components/PluginKindSelect/PluginKindSelect.tsx
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.test.tsx
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
- ui/plugin-system/src/components/PluginSpecEditor/PluginSpecEditor.test.tsx
- ui/plugin-system/src/components/PluginSpecEditor/PluginSpecEditor.tsx
- ui/plugin-system/src/components/TimeSeriesQueryEditor/TimeSeriesQueryEditor.tsx
- ui/plugin-system/src/components/TimeSeriesQueryEditor/TimeSeriesQueryInput.tsx
- ui/plugin-system/src/components/TraceQueryEditor/TraceQueryInput.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/model.ts
- ui/plugin-system/src/runtime/plugin-registry.ts
linked with #1303 
First step of a set of PR with end goal of being able to associate with a panel several type of queries.
This is only touching the ``PluginEditor`` for now so functionally nothing happen differently than before as we always give a list of one plugin type.
The idea would be then to call the ``PluginEditor`` giving several ``PluginType``. 
e.g: Would help for a future Table Panel that would support giving `TimeSeriesQuery` and `TraceQuery` result.
Example of screenshot tweaking a bit the ``BarChart`` Panel to support ``TraceQuery`` and ``TimeSeriesQuery`` (not included in that PR that concern only the ``PluginEditor``)
> [!IMPORTANT]
> Depending on the output of the plugin improvements discussion #1543, the  three `TimeSeriesQuery`, `TraceQuery`, `LogQuery` plugin types …
> [BREAKINGCHANGE] PluginEditor takes multiple plugin types as input

- internal/cli/cmd/apply/apply.go
- internal/cli/cmd/dac/preview/preview.go
- internal/cli/service/service.go
- pkg/client/perseshttp/request.go
To fix #1904, I simplify the way the command `apply` is working. Instead of checking if the resource exists which required a read permission on it, I'm trying to create it first. Then based on the HTTP code result, the code will try to update it or stop.
Like that we are also saving one additional request to the database.
> [BUGFIX] Fix CLI cmd apply that wasn't able to create a resource with no read permission

- internal/api/e2e/api/rbac_test.go
- internal/api/impl/v1/user/endpoint.go
- internal/api/toolbox/toolbox.go
Move from the HTTP error 401 to 403 when user doesn't have enough permission to make the request.
> [BUGFIX] Fix HTTP error returned when access permission is missing

- ui/panels-plugin/src/plugins/bar-chart/BarChart.ts
- ui/panels-plugin/src/plugins/gauge-chart/GaugeChart.ts
- ui/panels-plugin/src/plugins/markdown/Markdown.ts
- ui/panels-plugin/src/plugins/scatterplot/ScatterChart.ts
- ui/panels-plugin/src/plugins/stat-chart/StatChart.ts
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChart.ts
- ui/plugin-system/src/components/PanelSpecEditor/PanelSpecEditor.tsx
- ui/plugin-system/src/model/panels.ts
fixes #1303 
> [!NOTE]
Depends on new multi query editor https://github.com/perses/perses/pull/1898
(If you want to review this PR only, check only the latest commit diff)
Last implementation of this thread ^^' 
Thanks to this PR, a panel have to declare the query types that it supports.
- clarify the contract between a panel and the queries that it can support. Nothing is guessed or under the hood. 
- fully ready to create panel supporting multiple query types
=> **this PR is clearly an enabler for the ``Table`` panel implementation.**
Before that, the ``PanelSpecEditor`` had to guess the query type taking the first of the existing queries. 
As you can see, at creation, when queries was empty this was leading to some problem (`default:` case, the `ScatterChart` is hardly mentioned …
> [FEATURE] Add `supportedQueryTypes` to the panel plugins definition

- go.mod
- internal/api/core/server.go
- internal/api/dependency/service_manager.go
- internal/api/impl/v1/view/endpoint.go
- internal/api/impl/v1/view/endpoint_test.go
- internal/api/impl/v1/view/service.go
- internal/api/interface/v1/view/interface.go
- internal/api/utils/utils.go
- pkg/model/api/v1/view.go
Linked with #1170
Here we add the backend side of usage tracking. We introduce a new view service that will be used to
track the usage of the API, bound to the /api/v1/view endpoint.
We then add a new implementation of that service
that tracks views in Prometheus metrics, with the
flexibility to swap out the implementation later.
> [FEATURE] Backend work for usage tracking

- cue/schemas/variables/static-list/migrate.cue
- cue/schemas/variables/static-list/static-list.json
- docs/plugin/cue.md
- internal/api/migrate/testdata/simple_grafana_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
Rework the migration logic of StaticListVariable to avoid migration failure: relying on the `options` field was causing the following error when migrating dashboards retrieved directly from the Grafana database (not from UI):
```
error="something wrong happened with the request to the API.  Message: bad request: unable to convert to Perses dashboard: spec.variables.0.spec.plugin.spec.values: undefined field: options (and 1 more errors) StatusCode: 400"
```
This was happening because the `options` field is actually made-up by the frontend from the `query` field, it doesn't get saved in db.
Also I took advantage of this fix to enhance the StaticListVariable migration logic, to no longer lose the "key" when the `key : value` syntax is used.
following `catalog_entry` values: `FEATURE`, …
> [BUGFIX] Fix grafana migration failing for "custom" template variables

- internal/api/migrate/mapping.cuepart
- internal/api/migrate/testdata/old_grafana_panels_perses_dashboard.json
- internal/api/migrate/testdata/old_grafana_query_perses_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
See comment.
Basically undoes https://github.com/perses/perses/pull/1848.
This is related to https://github.com/perses/perses/issues/1930: if ever we decide `labelName` is optional, then `capturingRegexp` should apply to the full query result, thus we'd be able to undo this PR.
> [BUGFIX] Grafana migration: best-effort solution to not migrate irrelevant regexps

- cmd/perses/main.go
- internal/api/core/core.go
- internal/api/e2e/framework/server.go
- internal/api/schemas/loader.go
Would avoid to modify and compile the code when trying to profile the application.
> [FEATURE] Activate pprof by flag

- internal/api/e2e/api/auth_test.go
- internal/api/e2e/api/dashboard_test.go
- internal/api/e2e/api/rbac_test.go
- internal/api/e2e/framework/server.go
- internal/api/impl/v1/dashboard/service.go
- internal/api/impl/v1/datasource/service.go
- internal/api/impl/v1/ephemeraldashboard/service.go
- internal/api/impl/v1/folder/service.go
- internal/api/impl/v1/role/service.go
- internal/api/impl/v1/rolebinding/service.go
- internal/api/impl/v1/secret/service.go
- internal/api/impl/v1/variable/service.go
- internal/api/rbac/cache.go
- internal/api/toolbox/toolbox.go
Currently API is returning wrong data for `List` project requests. It's fixing the issue
> [BUGFIX] Fix project list endpoints returning wrong data

- internal/api/core/core.go
- internal/api/schemas/schemas_test.go
Following the issue #1923 regarding the memory leaks we have when calling frequently the package cuelang to reload the schemas, I'm proposing to deactivate these cron.
As it's not possible to add at runtime a new plugin, likely we won't need to change the schemas at runtime as well. So there is no need to frequently reloading the schemas for the moment.
Besides we still have a file watching on the schema folder. So the functionality is partially degraded.
Once we have a proper plugin flow, these crons will be reactivated.
Monitoring is showing the memory leak is mitigated with this PR:
(for the same range of time (30min))
Before:
After:
> [BREAKINGCHANGE] Deactivate cron task that reloads the cue schemas

- cmd/percli/main.go
- docs/tooling/cli.md
- internal/cli/cmd/whoami/whoami.go
can be used as follow:
```bash
./bin/percli whoami --show-token --show-url
Token used: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcxMzI3OTg3MiwibmJmIjoxNzEzMjc4OTcyfQ.mecrHuc4FVMLLNcOfc_2IEPlZ85BZJrtO8FAWFKieZV4rg_b32iiLLcfcOEv36h6QL5EVizSg7XLA5UxCk-m2Q
Authenticated to the server: http://localhost:8080
User used: admin
```
> [FEATURE] CLI: add cmd whoami

- internal/api/e2e/api/dashboard_test.go
- ui/app/src/model/dashboard-client.ts
- ui/app/src/model/project-client.ts
Reverting changes of PR #1928, the API should have returned empty list. The issue was a side effect of #1932 issue.
Tests added for checking empty project with auth 😄 
> [IGNORE] Revert PR #1928

- docs/user-guides/dashboard-as-code.md
> [DOC] Fix wrong usage of `dac build` command in user guide

- ui/app/src/components/users/UserEditorForm.tsx
- ui/app/src/context/Config.tsx
Fixing external provider warning in user form (missing negation) + moving to config context
> [BUGIFX] Fix external provider warning in user form

- go-sdk/common/thresholds.go
- go-sdk/panel/gauge/gauge.go
- go-sdk/panel/gauge/options.go
- go-sdk/panel/stat/stat.go
- go-sdk/panel/time-series/time-series.go
Some `int` in the Go SDK should be `float`
> [BUGFIX] Go SDK move some int to float

- cue/dac-utils/dashboard/dashboard.cue
- go-sdk/dashboard/dashboard_test.go
- internal/test/dac/expected_output.json
- internal/test/dac/input.cue
(Also fixes a small issue where variables field was mandatory for the builder while it's optional for the final dashboard).
> [ENHANCEMENT] DaC CUE SDK: support passing datasources in dashboard builder

- cue/dac-utils/dashboard/dashboard.cue
- cue/model/api/v1/dashboard_patch.cue
- go-sdk/dashboard/dashboard_test.go
- internal/test/dac/dac_cue_test.go
- internal/test/dac/expected_output.json
- internal/test/dac/input.cue
Before you could already pass values to these fields via the base datamodel like the following:
```cue
dashboardBuilder & {
#name: "ContainersMonitoring"
#display: name: "Containers monitoring"
// ...
} & {spec: {
duration:        "3h"
refreshInterval: "30s"
}}
```
But it's a bit easier & aligns the UX with the other fields to just support these in the dashboard builder, so that you can do:
```cue
dashboardBuilder & {
#name: "ContainersMonitoring"
#display: name: "Containers monitoring"
// ...
#duration:        "3h"
#refreshInterval: "30s"
}
```
> [ENHANCEMENT] DaC CUE SDK: support time fields in dashboard builder

- internal/api/provisioning/provisioning.go
- internal/cli/service/service.go
Following the issue raised #1960, there is an issue in the provisionner that actually update user while there is none in the database.
The logic in the provisionner and in the `apply` command in the CLI is wrong. This PR aims to fix that.
For the moment it is also coherent with another fix coming from the pending PR #1961
/cc @sinkingpoint
> [BUGFIX] Fix upsert function in provisioner and in the `apply`  cmd

- internal/api/impl/v1/datasource/service.go
Suddenly the datasources query from the frontend didn't return the accurate datasource (specially when we want to get the default datasource).
This is a regression introduced in https://github.com/perses/perses/pull/1932
> [BUGFIX] Fix datasource query copy

- ui/plugin-system/src/model/time-series-queries.ts
- ui/plugin-system/src/runtime/TimeRangeProvider/TimeRangeProvider.tsx
- ui/plugin-system/src/runtime/time-series-queries.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/plugin.test.ts
Improving auto refresh. The actual auto refresh was only working with timeseries query. Now it will refresh all dashboard components (panels / variables /...).
We still need to improve refresh display => it's removing data, show loader and put it again, it should keep previous data  visible and only replace it when it's ready
> [BUGFIX] Fix auto refresh

- dev/config-mariadb.yaml
- dev/config.yaml
- internal/api/core/core.go
- internal/cli/cmd/conf/conf_test.go
- pkg/client/fake/api/client.go
- pkg/model/api/config/config.go
- pkg/model/api/config/config_test.go
- pkg/model/api/config/frontend.go
- ui/app/src/context/Config.tsx
- ui/app/src/model/config-client.ts
- ui/app/src/views/home/ImportantDashboards.tsx
I'm introducing a dedicated config for the frontend.
Later it will be interesting as we want to provide a way to configure the au-refresh period value.
It's a breaking change as the config `info` and `important_dashboard` are moving under the new field `frontend`
> [BREAKINGCHANGE] Introduce a dedicated config for the frontend

- README.md
- docs/user-guides/oauth-configuration-helpers.md
so we can have in the repo description the link to the website (https://perses.dev) and not anymore the demo.
> add demo links in the readme

- ui/plugin-system/src/components/MultiQueryEditor/MultiQueryEditor.tsx
Was not that harmful but clearly bring confusion
include:
> [BUGFIX] Remove TimeSeriesQuery type from MultiQueryEditor

- ui/app/src/model/project-client.ts
In the current home page, for each project listed we are getting one by one the list of dashboards by project. That's something that cannot scale as we will have a lot of queries when a lot of projects are created.
This PR aims to simplify this process by getting all dashboards at once and them map it to the list of dashboard.
> [ENHANCEMENT] Optimize query to get dashboards on the home page

- internal/api/toolbox/list.go
- internal/api/toolbox/toolbox.go
I am refactoring a bit the list method from `toolbox`. 
Here it simply return the response in a single place while before the HTTP response returned was everywhere.
It will help on a later PR when sending only the metadata.
> [ignore] small refactor on the toolbox list method

- cue/schemas/panels/time-series-table/time-series-table.cue
- cue/schemas/panels/time-series-table/time-series-table.json
- ui/.eslintrc.base.js
- ui/core/src/model/time-series-data.ts
- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/PanelDrawer/PanelPreview.tsx
- ui/explore/src/components/ExploreManager/MetricsExplorer.tsx
- ui/panels-plugin/plugin.json
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.test.tsx
- ui/panels-plugin/src/plugins/time-series-table/DataTable.tsx
- ui/panels-plugin/src/plugins/time-series-table/TimeSeriesTable.ts
- ui/panels-plugin/src/plugins/time-series-table/TimeSeriesTablePanel.test.tsx
- ui/panels-plugin/src/plugins/time-series-table/TimeSeriesTablePanel.tsx
- ui/panels-plugin/src/plugins/time-series-table/index.ts
- ui/panels-plugin/src/test/mock-query-results.ts
- ui/plugin-system/src/model/panels.ts
- ui/plugin-system/src/model/time-series-queries.ts
- ui/plugin-system/src/runtime/DataQueriesProvider/DataQueriesProvider.test.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/DataQueriesProvider.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/model.ts
- ui/plugin-system/src/runtime/time-series-queries.ts
- ui/prometheus-plugin/plugin.json
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/get-time-series-data.ts
ref #1456 (not fix as it's not addressing all the problems. Only the explorer one)
Introduction of the ``TimeSeriesTable`` panel. It allow users to display "prometheus like" table results as a panel in a dashboard. It is also used in TimeSeries explorer.
This led to the creation of several new fields but no **breaking change**. 
The new mode field is used to tell the DataQueriesProvider to execute the time series queries in `instant` mode (e.g /query endpoint used for prometheus)  or `range` mode (e.g /range endpoint used for prometheus)
Default mode is ``range``.
```html
<DataQueriesProvider definitions={definitions} options={{ mode: 'instant' }}>
```
This allow to declare the mode at panel plugin level. Basically for now only the timeseries table panel will tell the queries to be done …
> [FEATURE] Instant query table view

- ui/dashboards/src/components/Variables/VariableList.tsx
Doing a quick fix for issue #1954, I think there's still room for improvements. Lot of useEffects to remove in TemplateVariable.tsx + we should have a method returning all variables def a dashboard can use and remove variables definitions overrode. I will check when I have time 😄 
fixes #1954 
include:
- Does it have loading states? You need to wait …
> [BUGFIX] Fixing external ListVariable overriding dashboard ListVariable in query param

- ui/components/src/StatChart/StatChart.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartOptionsEditorSettings.tsx
Align with gauge chart code 😄 
Fixes #1938
include:
> [BUGFIX] Fix StatChart 'no  defined' in Setting tab

- internal/api/toolbox/list.go
I'm just parallelising the query when we get a full list of data per project. 
This drop again a bit the time it takes to get a response from the backend. When querying the metadata for the dashboard list we are around 50ms now for 1k dashboards
PR must be merged after #1994
> [ENHANCEMENT] on the backend side, query are parallelised when getting the list of resources

- ui/explore/src/components/ExploreManager/ExplorerManagerProvider.tsx
- ui/explore/src/components/ExploreManager/ExplorerManagerProviderWithQueryParams.tsx
Data is kept when switching tabs on the explorer, you don't lose data anymore 😄 
Note: the url will only track params of the current displayed tab
include:
> [ENHANCEMENT] Keep data when switching explorer tabs

- cue/schemas/common/format.cue
- go-sdk/common/format.go
- internal/api/migrate/mapping.cuepart
- internal/api/migrate/testdata/simple_grafana_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
- ui/core/src/model/units/throughput.ts
Add `bytes/sec` unit for Y axis to the Throughput category.
include:
> [ENHANCEMENT] add `bytes/sec` format

- ui/dashboards/src/context/DashboardProvider/DashboardProvider.tsx
- ui/dashboards/src/context/TemplateVariableProvider/TemplateVariableProvider.tsx
use `useStoreWithEqualityFn()` instead of `useStore()` with `equalityFn`, because `useStore()` with `equalityFn` is deprecated:
https://github.com/pmndrs/zustand/discussions/1937
https://github.com/pmndrs/zustand/pull/1945
no UI changes
include:
> [IGNORE] use useStoreWithEqualityFn() instead of useStore() with equalityFn

- internal/api/core/core.go
- internal/api/discovery/discovery.go
- internal/api/discovery/http/http.go
- internal/api/discovery/service/service.go
- internal/cli/cmd/dac/build/testdata/go/go.mod
- pkg/client/perseshttp/request.go
- pkg/client/perseshttp/request_test.go
- pkg/model/api/config/config.go
- pkg/model/api/config/datasourcediscovery.go
This PR introduces the notion of datasource discovery.
I'm starting with a HTTP discovery so we have something generic. The idea is that you can expose an endpoint returning a list of global datasource and Perses will fetch it and inject the data in the database.
I think for the discovery it makes to create only global datasource because that's something you are doing in the backend config. So for me it doesn't really make sense to create data in a project using the discovery. But maybe I am wrong.
Linked to #74
> [FEATURE] Provide datasource discovery starting with http discovery

- ui/explore/src/components/ExploreManager/ExplorerManagerProvider.tsx
When explorer is not set in query params, it will use the default one by default (tab: 0).
include:
> [BUGFIX] Fix explorer failing to load query params when explorer is not set

- ui/dashboards/src/components/GridLayout/GridLayout.tsx
Fixing some issue with panel full size:
- when you are sharing a panel in full size and the panel group is collapsed by default, the panel is collapsed => now it is opened
- when you are scrolling and expand a panel to full size, the panel height could be too high
include:
> [BUGFIX] Fix panel group collapsed + panel height in panel view mode

- ui/plugin-system/src/components/PluginKindSelect/PluginKindSelect.tsx
I'm seeing this error on the Explore page in the JS console on Firefox:
```
MUI: You have provided an out-of-range value `{"kind":"PrometheusTimeSeriesQuery","type":"TimeSeriesQuery"}` for the select component.
Consider providing a value that matches one of the available options or ''.
The available values are `{"type":"TimeSeriesQuery","kind":"PrometheusTimeSeriesQuery"}`.
```
This is because the order of keys in Objects is undefined, therefore the output of JSON.stringify() is not guaranteed to be the same for two objects with the same keys and values.
I followed the same approach as for DatasourceSelect: https://github.com/perses/perses/blob/cf87ec4b6bd474f2d58c01709a36ff37bcde9512/ui/plugin-system/src/components/DatasourceSelect.tsx#L139-L167
no visible UI changes
following …
> [BUGFIX] replace unstable JSON.stringify() with custom string in <PluginKindSelect>

- ui/explore/src/components/ExploreManager/constants.ts
- ui/panels-plugin/src/plugins/time-series-table/DataTable.tsx
- ui/panels-plugin/src/plugins/time-series-table/SeriesName.tsx
- ui/prometheus-plugin/src/utils/utils.test.ts
- ui/prometheus-plugin/src/utils/utils.ts
Importing Prometheus series name formating to Perses explorer.
You can click on the label="value" for copying in the clipboard
Using same limit, if there is more than 1000 series, only show plain text time series name.
Use MUI Table + increase panel height
include:
> [ENHANCEMENT] Add formating to series name in explorer and use MUI Table

- docs/api/dashboard.md
> [DOC] fix wrong type in API doc

- cue/dac-utils/prometheus/filter/filter.cue
- go-sdk/dashboard/dashboard_test.go
- go-sdk/prometheus/variable/label-names/label-names.go
- go-sdk/prometheus/variable/label-values/label-values.go
- internal/test/dac/expected_output.json
- internal/test/dac/input.cue
We might think of adding a parameter later to give the user the ability to tune the equality operator, but for now putting `=~` ensures that it will work in all cases.
> [BUGFIX] DaC SDKs: fix generated label matchers not compatible with multi-select variables

- docs/dac/go/README.md
- go-sdk/datasource/datasource.go
- go-sdk/http/proxy.go
- go-sdk/link/link.go
- go-sdk/panel-group/panel-group.go
- go-sdk/panel/bar/bar.go
- go-sdk/panel/gauge/gauge.go
- go-sdk/panel/markdown/markdown.go
- go-sdk/panel/panel.go
- go-sdk/panel/stat/stat.go
- go-sdk/panel/time-series/time-series.go
- go-sdk/prometheus/datasource/datasource.go
- go-sdk/prometheus/query/query.go
YAML marshalling was causing such unexpected `pluginspec` field to appear in the final output:
```yaml
queries:
- kind: TimeSeriesQuery
spec:
plugin:
kind: PrometheusTimeSeriesQuery
spec:
pluginspec: # invalid !
query: sum by (app_name) (jvm_info_total{stack="$stack"})
```
To solve this I added an explicit `inline` marshall instruction for this field + same for any similar cases in other builders, just in case.
> [BUGFIX] DaC Go SDK: Fix unwanted intermediary field append in YAML output

- dev/config-mariadb.yaml
- dev/config.yaml
- docs/user-guides/configuration.md
- internal/api/core/core.go
- internal/api/core/server.go
- internal/api/e2e/framework/server.go
- internal/api/impl/v1/ephemeraldashboard/endpoint.go
- pkg/model/api/config/config.go
- pkg/model/api/config/config_test.go
- ui/app/src/Router.tsx
- ui/app/src/context/Config.tsx
- ui/app/src/model/config-client.ts
- ui/app/src/views/projects/ProjectTabs.tsx
Not everybody needs the ephemeral dashboard. So having a config that explicitly activate this feature let people choose what feature they would like to use.
> [FEATURE] Provide a way by config to activate the ephemeral dashboard feature

- ui/app/src/model/dashboard-client.ts
As discussed with @Nexucis, I'd find it safer to take the metadataonly into account in the querykey for the dashboards list. 
Even if we actually never use it with false when project is not set and never use it with true when project is set. This situation is either miracle, or genius, but not future proof IMHO 
Extra care ping @Gladorme I know that you struggled with that so I'd prefer to test it with you first. I did in the first place: ``queryKey=[resource, {project, metadataOnly}]`` but I think this would break the query invalidation in the project client.
and …
> [ENHANCEMENT] Dashboards lists - improve metadataOnly safety

- ui/app/src/components/DashboardList/DashboardList.tsx
- ui/components/src/Dialog/Dialog.tsx
Fixing dialogs width + fix dashboard delete dialog
BEFORE:
AFTER:
include:
> [BUGFIX] Fix dashboard delete + fix dialog width with long name

- dev/config-mariadb.yaml
- dev/config.yaml
- docs/user-guides/configuration.md
- internal/api/core/core.go
- internal/api/core/server.go
- internal/api/e2e/framework/server.go
- internal/api/impl/v1/ephemeraldashboard/endpoint.go
- pkg/model/api/config/config.go
- pkg/model/api/config/config_test.go
- pkg/model/api/config/frontend.go
- ui/app/src/Router.tsx
- ui/app/src/components/Header.tsx
- ui/app/src/context/Config.tsx
- ui/app/src/model/config-client.ts
- ui/app/src/views/projects/ProjectTabs.tsx
I am renaming all `deactivate/activate` by `disable/enable` key.
The config impacted shouldn't be an issue for end user as for most case, the default config is used
> [BREAKINGCHANGE] Rename various config to use the same wording

- ui/panels-plugin/src/plugins/time-series-table/SeriesName.tsx
Fixes the following warning created by nesting `<Typography>` (which default to `<p>` elements):
```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```
no UI changes
include:
> [IGNORE] Fix React warning in TimeSeriesTable

- ui/plugin-system/src/components/PanelSpecEditor/PanelSpecEditor.tsx
Noticed a visible semicolon under the queries when editing a panel.
include:
> [BUGFIX] Remove semicolon under queries

- ui/dashboards/src/components/EmptyDashboard/EmptyDashboard.tsx
👋 I wanted a quick PR so I could remember how to get local dev working. I thought that "panel!" in the empty dashboard message looked awkward how it wrapped to another line. Increasing the width fixes it and the text still wraps nicely on mobile automatically.
https://happo.io/a/1009/p/1488/compare/3f92d334f907c3d2042ed5d458a4005640053100/9ee4f333f69d913c4bc049689aa00782bf1e0d76
No longer wraps to another line on desktop
Still looks good on mobile
include:
- Is the data inconsistent? You need …
> [ENHANCEMENT] Adjust empty dashboard message width

- ui/panels-plugin/src/plugins/time-series-chart/time-series-chart-model.ts
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
Default line width seems large so I adjusted and tweaked the hover state (since reducing the line width made a higher opacity necessary).
https://happo.io/a/1009/p/1488/compare/3f92d334f907c3d2042ed5d458a4005640053100/7dc3820d9d773be4f172187f6790037fa4553178
include:
> [ENHANCEMENT] Reduce default line width, more subtle hover state

- cmd/perses/main.go
- internal/api/migrate/loader.go
- internal/api/migrate/migrate.go
- internal/api/schemas/loader.go
- internal/api/schemas/monitoring.go
- internal/api/schemas/schemas.go
Currently if we have e.g 10 panels plugin installed and the 4th one in alphabetical order is faulty/corrupted, the 6 following plugins wont be loaded even though they'd be valid, which is too bad..
This PR aims to change that + take advantage of changing this part of the code to add instrumentation of schemas load.
New metrics overview:
```
perses_plugin_schemas_load_attempts{load="change",schema="model",status="error"} 0
perses_plugin_schemas_load_attempts{load="change",schema="model",status="success"} 4
perses_plugin_schemas_load_attempts{load="full",schema="migration",status="error"} 0
perses_plugin_schemas_load_attempts{load="full",schema="migration",status="success"} 9
perses_plugin_schemas_load_attempts{load="full",schema="model",status="error"} 0 …
```
> [ENHANCEMENT] Schemas load: avoid breaking too early in case of error + add monitoring for it

- ui/core/src/model/trace-data.ts
- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.tsx
- ui/panels-plugin/src/plugins/trace-table/DataTable.tsx
- ui/panels-plugin/src/plugins/trace-table/TraceTablePanel.tsx
- ui/panels-plugin/src/test/mock-trace-query-results.ts
- ui/plugin-system/src/test/mock-data.ts
- ui/tempo-plugin/src/model/api-types.ts
- ui/tempo-plugin/src/model/tempo-client.ts
- ui/tempo-plugin/src/plugins/plugin.test.ts
- ui/tempo-plugin/src/plugins/tempo-trace-query/get-trace-data.ts
- ui/tempo-plugin/src/test/mock-data.ts
* rename partial trace (returned by search endpoint) to `TraceSearchResult`
* add `Trace` data model to core
* execute either a search query or fetch trace by id, depending on query
* build span tree in Tempo client
* prerequisite of #2047
no UI changes
include:
> [IGNORE] support fetching entire trace

- ui/prometheus-plugin/src/model/time.test.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/get-time-series-data.ts
Closes https://github.com/perses/perses/issues/2086.
include:
> [BUGFIX] Fix `$__interval` not taking datasource scrape interval as lower bound

- ui/app/src/components/DashboardList/DashboardDataGrid.tsx
- ui/app/src/components/EphemeralDashboardList/EphemeralDashboardDataGrid.tsx
- ui/app/src/components/datagrid.tsx
- ui/app/src/components/datasource/DatasourceDataGrid.tsx
- ui/app/src/components/rolebindings/RoleBindingDataGrid.tsx
- ui/app/src/components/roles/RoleDataGrid.tsx
- ui/app/src/components/secrets/SecretDataGrid.tsx
- ui/app/src/components/users/UserDataGrid.tsx
- ui/app/src/components/variable/VariableDataGrid.tsx
- ui/components/src/Overlay/Overlay.tsx
- ui/components/src/Overlay/index.ts
- ui/components/src/index.ts
- ui/panels-plugin/src/plugins/bar-chart/BarChartPanel.tsx
- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.test.tsx
- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.tsx
- ui/panels-plugin/src/plugins/stat-chart/StatChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
- ui/panels-plugin/src/plugins/time-series-table/TimeSeriesTablePanel.tsx
- ui/panels-plugin/src/plugins/trace-table/TraceTablePanel.tsx
To improve consistency across components, let's move `<NoContentRowOverlay>` from `apps` to `components` package, and also use it in panels.
Additionally, add a new `<LoadingOverlay>` component, for usage in e.g. panels.
no visible UI changes
include:
> [IGNORE] move <NoContentRowOverlay> to components package, add <LoadingOverlay>

- ui/app/src/components/datasource/DatasourceList.tsx
- ui/app/src/components/secrets/SecretList.tsx
- ui/app/src/components/variable/VariableList.tsx
> [BUGFIX] Fix  misaligned in some resource datagrids

- ui/components/src/TimeRangeSelector/DateTimeRangePicker.tsx
With the upgrade to latest MUI X version, we can use MUI X DateTimeField directly (https://mui.com/x/react-date-pickers/date-time-field/)
include:
> [ENHANCEMENT] Use DateTimeField in DateTimeRangePicker

- ui/core/src/utils/fetch.ts
- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.tsx
- ui/panels-plugin/src/plugins/trace-table/TraceTablePanel.tsx
Some services (e.g. Tempo) do not return error messages in JSON format. Therefore, we cannot assume the error response is always in JSON format.
Before:
After:
include:
> [BUGFIX] check content-type header before parsing error message as JSON

- .github/workflows/ci.yaml
- .github/workflows/delete-snapshot.yml
- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/react.yml
currently CI is broken because somehow, the github actions is taking the last version of `perses/github-actions` that request to provide the path to the file `.nvmrc`.
This PR aims to fix that
> [ignore] bump perses/github-actions to v0.5.2

- ui/tempo-plugin/src/model/api-types.ts
- ui/tempo-plugin/src/model/tempo-client.test.ts
- ui/tempo-plugin/src/model/tempo-client.ts
- ui/tempo-plugin/src/plugins/tempo-datasource.tsx
- ui/tempo-plugin/src/plugins/tempo-trace-query/get-trace-data.ts
Previously, TraceQL queries with `&&` were not escaped when accessing the Tempo API. This PR refactors the client code, to use the URLSearchParams API to construct the URL and align with the Prometheus API client (`queryOptions`, support custom headers).
no UI changes
include:
> [BUGFIX] fix TraceQL query escaping

- go-sdk/panel/bar/bar.go
- go-sdk/panel/gauge/gauge.go
- go-sdk/panel/markdown/markdown.go
- go-sdk/panel/stat/stat.go
- go-sdk/panel/time-series/time-series.go
- go-sdk/prometheus/datasource/datasource.go
- go-sdk/prometheus/query/query.go
- go-sdk/prometheus/variable/label-names/label-names.go
- go-sdk/prometheus/variable/label-values/label-values.go
- go-sdk/prometheus/variable/promql/promql.go
- go-sdk/variable/list-variable/list-variable.go
- go-sdk/variable/plugin/static-list/static-list.go
- go-sdk/variable/text-variable/text-variable.go
In the different plugin supported, it was possible to create the builder for each plugin which is not the way the SDK has been thought.
On each plugin, there is only one method exposed that should be used to create the plugin. Builder is just the internal way we used to create the plugin
> [BREAKINGCHANGE] GO-SDK: remove the possibility to create the plugin builder

- internal/api/core/core.go
- internal/api/core/server.go
- pkg/model/api/config/config.go
- ui/app/src/model/route.test.ts
- ui/app/src/model/route.ts
- ui/app/src/model/url-builder.ts
- ui/app/src/render-app.tsx
- ui/endpoint.go
This PR is providing a way to prefix the API.
For the backend, you need to set the configuration entry `api_prefix` with the wanted value.
For the frontend, the prefix is deduced.
Closes #2136
> [FEATURE] Provide a way to prefix the API

- cue/schemas/panels/table/migrate.cue
- cue/schemas/panels/table/table.cue
- ui/components/src/DensitySelector/DensitySelector.tsx
- ui/components/src/Table/InnerTable.tsx
- ui/components/src/Table/model/table-model.ts
Add a new density to Table panel
Comfortable:
For reminder:
Standard:
Compact:
include:
> [ENHANCEMENT] Add 'comfortable' density for Table panel

- ui/app/package.json
- ui/app/src/components/Footer.tsx
- ui/app/src/model/admin-client.ts
- ui/app/src/model/auth-client.ts
- ui/app/src/model/config-client.ts
- ui/app/src/model/dashboard-client.ts
- ui/app/src/model/datasource-client.ts
- ui/app/src/model/ephemeral-dashboard-client.ts
- ui/app/src/model/global-role-client.ts
- ui/app/src/model/global-rolebinding-client.ts
- ui/app/src/model/global-secret-client.ts
- ui/app/src/model/global-variable-client.ts
- ui/app/src/model/health-client.ts
- ui/app/src/model/project-client.ts
- ui/app/src/model/role-client.ts
- ui/app/src/model/rolebinding-client.ts
- ui/app/src/model/secret-client.ts
- ui/app/src/model/user-client.ts
- ui/app/src/model/variable-client.ts
- ui/app/src/views/import/GrafanaFlow.tsx
- ui/app/src/views/import/PersesFlow.tsx
- ui/plugin-system/src/components/Variables/variable-model.ts
- ui/plugin-system/src/context/ProjectStoreProvider.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/model.ts
- ui/plugin-system/src/runtime/datasources.ts
- ui/plugin-system/src/runtime/plugin-registry.ts
- ui/plugin-system/src/runtime/time-series-queries.ts
- ui/plugin-system/src/test/render.tsx
I tried to upgrade @tanstack/query to v5 to fix a bug. Unfortunately the upgrade didn't resolve the issue and other stuff broke :grimacing: , so I put the upgrade on hold for now.
Instead of throwing away the progress I thought we can still merge the changes which already work in v4, to make the future (inevitable) upgrade simpler.
* move function parameters to object format (v5 doesn't support non-object function params)
* remove onError callback (removed in v5)
https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5
Related: #2020
no UI changes
and …
> [IGNORE] Prepare upgrade to @tanstack/query v5

- ui/app/src/components/Header/AccountMenu.tsx
- ui/app/src/components/Header/Header.tsx
- ui/app/src/components/Header/SearchBar/SearchBar.tsx
Vertically-center the search bar with the viewport + make it take more available space on mobile.
Before:
After:
Responsiveness:
https://github.com/user-attachments/assets/143c3c3e-74a4-46ff-a460-fc43cbfb3eca
include:
> [ENHANCEMENT] Improve searchbar display

- ui/panels-plugin/src/plugins/time-series-chart/QuerySettingsEditor.tsx
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.test.ts
- ui/panels-plugin/src/plugins/time-series-chart/utils/data-transform.ts
Fix #2126. Padding on the panel should be similar on left and right when yAxis is disabled.
include:
> [BUGFIX] Timeseries Panel should have same left/right margin when yAxis is disabled

- ui/panels-plugin/src/plugins/trace-table/TraceTable.ts
- ui/plugin-system/src/model/panels.ts
Fix access to the `traceLink` property when embedding the `TraceTable`:
```
<TraceTable.PanelComponent spec={{}} traceLink={traceDetailLink} />
```
We decided to put the `traceLink` property to the panel properties instead of the `spec`, because it must be a function and cannot be JSON serialized.
no UI changes
include:
- Does it have loading states? …
> [IGNORE] fix TraceTable type

- internal/cli/cmd/remove/remove.go
The current `percli delete` command outputs a Not Found error when a resource is not found. This is inconvenient when using a definition file that includes multiple existing resources for deletion.
For example, the command would result in the following output.
```
$ # add new resources
$ percli apply -f sandbox.json
object "Project" "project-1" has been applied
object "Role" "defaultrole" has been applied in the project "project-1"
object "User" "user1" has been applied
object "RoleBinding" "projectrolebinding" has been applied in the project "project-1"
$ # delete resources
$ percli delete -f sandbox.json
object "Project" "project-1" has been deleted
Error: something wrong happened with the request to the API.  Message: document not found StatusCode: 404
```
In this PR, I will make …
> [ENHANCEMENT] Ignore Not Found errors in percli delete command

- ui/panels-plugin/src/plugins/trace-table/TraceTablePanel.tsx
Previously, not setting the `traceLink` property always sets a link to the explore page.
However, there might be cases when developers explicitly don't want to create a link.
include:
> [ENHANCEMENT] TraceTablePanel: support disabling links to the trace

- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart.ts
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/DetailPane/Attributes.test.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/DetailPane/Attributes.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/DetailPane/DetailPane.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/TracingGanttChart.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChartPanel.tsx
TracingGanttChart: support links in the span attribute list
`net.host.name` is a link in this example:
include:
> [ENHANCEMENT] TracingGanttChart: support links in the span attribute list

- ui/panels-plugin/src/plugins/scatterplot/Scatterplot.tsx
ScatterPlot: update tooltip formatting
Before:
After:
include:
> [ENHANCEMENT] ScatterPlot: update tooltip formatting

- cue/schemas/panels/scatter/scatter.cue
- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.test.tsx
- ui/panels-plugin/src/plugins/scatterplot/ScatterChartPanel.tsx
- ui/panels-plugin/src/plugins/scatterplot/scatter-chart-model.ts
* make size configurable (min/max size), use a default range from 6-20 px
* apply linear scale of spanCount from range minSpanCount..maxSpanCount to a value from minSize..maxSize
Before:
After:
include:
> [ENHANCEMENT] make circle size configurable in ScatterPlot panel

- cue/schemas/panels/tracing-gantt-chart/tracing-gantt-chart.cue
- ui/panels-plugin/src/model/palette.test.ts
- ui/panels-plugin/src/model/palette.ts
- ui/panels-plugin/src/plugins/trace-table/DataTable.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/GanttTable.test.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/GanttTable.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/GanttTableRow.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/SpanDuration.test.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/SpanDuration.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/MiniGanttChart/Canvas.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/MiniGanttChart/MiniGanttChart.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/MiniGanttChart/draw.ts
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/TracingGanttChart.stories.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/TracingGanttChart.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/utils.ts
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChartPanel.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/gantt-chart-model.ts
Currently, the TracingGanttChart always generates consistent colors with the `ColorHash` library (same as the TimeSeriesChart): https://github.com/perses/perses/blob/0e5663c6c2111eb94bf207b512c1d20d7264ab59/ui/panels-plugin/src/model/palette.ts#L24-L29
To improve the UI when embedding the panel into other pages, it's beneficial to use a fixed color palette, i.e. from the eCharts theme: `chartsTheme.echartsTheme.color`.
Colors from MUI theme:
Default, generated colors:
include:
- Is the data …
> [FEATURE] TracingGanttChart: support categorical color palette

- ui/panels-plugin/src/plugins/scatterplot/Scatterplot.tsx
ScatterPlot panel: format time based on next best unit
Before:
After:
include:
> [ENHANCEMENT] ScatterPlot panel: format time based on next best unit

- ui/panels-plugin/src/plugins/trace-table/DataTable.tsx
TraceTable: show date in UTC in tooltip
include:
> [ENHANCEMENT] TraceTable: show date in UTC in tooltip

- internal/api/migrate/mapping.cuepart
- internal/api/migrate/testdata/simple_grafana_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
Follow-up on the issue reported in https://github.com/perses/perses/pull/2218. The migration logic is now resilient to the absence of the `hide` property for variables.
This PR also changes the migration code to stop populating the variable display name with its "technical" name. This was done at the time because of a model constraint that https://github.com/perses/perses/pull/1414 got rid of.
It also simplifies the code responsible of migrating variable's display attributes as a whole.
> [ENHANCEMENT] Avoid failing grafana migration on `hide` absence

- CONTRIBUTING.md
Part of https://github.com/cncf/toc/issues/1411 tasks
> Perses channels are moving to CNCF slack

- ui/tempo-plugin/src/model/api-types.ts
- ui/tempo-plugin/src/model/tempo-client.test.ts
- ui/tempo-plugin/src/model/tempo-client.ts
- ui/tempo-plugin/src/plugins/plugin.test.ts
- ui/tempo-plugin/src/plugins/tempo-datasource.tsx
- ui/tempo-plugin/src/plugins/tempo-trace-query/get-trace-data.ts
- ui/tempo-plugin/src/test/mock-data.ts
* name API functions after Tempo API functions
* use params dict for every API functions
* store datasourceUrl in closure
* support custom headers
* add searchTags() and searchTagsValues() API functions
no UI changes
include:
> [IGNORE] align TempoClient with PrometheusClient, add searchTags and searchTagsValues()

- ui/tempo-plugin/src/model/tempo-client.ts
tempo client: encode URL parameters in path
no UI changes
include:
> [BUGFIX] tempo client: encode URL parameters in path

- ui/tempo-plugin/src/components/TraceQLEditor.tsx
In the explore view, the input field accept either a TraceQL query or a Trace ID, and displays the trace table or the Gantt chart based on the value. Unfortunately, the lezer grammar (correctly) marks Trace IDs as invalid TraceQL queries. Therefore, let's disable syntax highlighting if the input is a Trace ID.
include:
- Does it have loading states? …
> [BUGFIX] tempo query: disable syntax highlighting if query is a trace id

- ui/package-lock.json
- ui/tempo-plugin/package.json
- ui/tempo-plugin/src/components/TraceQLExtension.ts
- ui/tempo-plugin/src/components/complete.test.ts
- ui/tempo-plugin/src/components/complete.ts
- ui/tempo-plugin/src/index.ts
TraceQL query editor: add auto-complete support
_Note: This PR requires #2228_
https://github.com/user-attachments/assets/859a27c1-0b76-4faa-acf9-8f248e96a692
include:
> [ENHANCEMENT] TraceQL query editor: add auto-complete support

- ui/components/src/theme/index.ts
- ui/components/src/theme/theme.ts
Allow passing custom parameters to the MUI `createTheme()` function
Example:
```
const muiTheme = getTheme('light', {
typography: {
...typography,
fontFamily: 'my-custom-font',
},
shape: {
borderRadius: 0,
},
});
```
no UI changes
include:
> [IGNORE] Allow passing custom parameters to the MUI `createTheme()` function

- ui/panels-plugin/src/plugins/trace-table/DataTable.tsx
TraceTable: expose service-color as CSS var
This helps with customizations when embedding this panel, for example:
```
.MuiChip-root {
background-color: var(--service-color);
}
```
Also, fix spelling of `error` chip if `count==1`.
no mentionable UI changes
include:
> [IGNORE] TraceTable: expose service-color as CSS var

- cue/schemas/panels/table/migrate.cue
- internal/api/migrate/testdata/simple_grafana_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
Small improvement to table migrations:
Special 'Value' column from Grafana should be 'value' in order to match Perses 'value' column with actual values.
old migration:
after migration:
> [ENHANCEMENT] Migrate: rename Value to value in table migrations

- ui/tempo-plugin/src/components/complete.test.ts
- ui/tempo-plugin/src/components/complete.ts
CodeMirror parses the input in the background, and sometimes didn't complete parsing the input before the tree was searched to identify the completions.
no UI changes
include:
> [BUGFIX] fix flaky TraceQL auto-completion tests

- cue/schemas/panels/table/migrate.cue
- internal/api/migrate/mapping.cuepart
- internal/api/migrate/migrate_test.go
- internal/api/migrate/testdata/simple_grafana_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
- internal/api/migrate/testdata/tables_grafana_dashboard.json
- internal/api/migrate/testdata/tables_perses_dashboard.json
This PR improves the table migration logic by supporting migrating column renames from both the "Organize" transformation & the "field overrides" options from Grafana.
NB1: this remains a best effort migration. In the new test file added, the 2 last panels are not accurately migrated, but these are tackling some corner cases that's not worth investing on imho.
NB2: the migration logic was quite heavily revamped here, hopefully the new code should allow for easier extension in the future: table panels in Grafana provides many customization capabilities, so we'll most likely have to enrich this code again later..
> [ENHANCEMENT] Table panel migration: support column rename from field overrides

- .github/workflows/ci.yaml
- .github/workflows/delete-snapshot.yml
- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/react.yml
Moving go version to v1.23.X through the upgrade of the github action.
I am also upgrading the cuelang version used in the CI
> [IGNORE] Update golang,cue and github actions version

- ui/components/src/FormatControls/FormatControls.tsx
- ui/core/src/model/calculations.ts
- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/panels-plugin/src/plugins/bar-chart/BarChartOptionsEditorSettings.test.tsx
- ui/panels-plugin/src/plugins/bar-chart/BarChartOptionsEditorSettings.tsx
- ui/plugin-system/src/components/CalculationSelector/CalculationSelector.tsx
- ui/plugin-system/src/components/PanelSpecEditor/PanelSpecEditor.tsx
Fixes #2256. When creating a panel, when the kind is changed, the initial/default spec are changed visually but not spread to react-hook-form. So when you save the panel (!= saving dashboard), default values are not applied (returning empty spec), breaking the panel display if a field is mandatory. It could occur to any panel types, not limited to Bar panel.
include:
- Does the time change? You need to use consistent time values or …
> [BUGFIX] Default panel spec not saved

- docs/plugins/panels.md
NB: I wonder if we could just somehow include/redirect to the cuelang files instead of maintaining this doc on the side, I think the CUE syntax is a bit clearer than the one we use in this doc, it basically describes the same thing & it would avoid misalignment between code & doc. 
> [DOC] Table: Add datamodel documentation

- ui/components/src/TimeChart/TimeChart.tsx
Closes #2217 
This PR addresses a bug that caused an increase in vertical page size and redundant scrolling. The issue was traced back to the native ECharts tooltip, which was attached to the body element, causing unexpected layout shifts.
include:
> [BUGFIX] Disable mounting native echats tooltip to body for timeseries chart except stacked

- docs/examples/config.archive.yaml
in the archive the database folder cannot be `perses` since it's the name of the executable.
> [BUGFIX] Fix database folder in default config file for the archives

- ui/explore/src/components/PrometheusMetricsFinder/display/list/MetricList.tsx
Should fix the flickering issue on the metric finder.
include:
> [BUGFIX] Fix metric finder list flickering

- cue/dac-utils/variable/staticlist/staticlist.cue
- cue/dac-utils/variable/text/text.cue
- cue/schemas/variables/static-list/static-list.cue
- go-sdk/dashboard/dashboard_test.go
- internal/test/dac/expected_output.json
- internal/test/dac/input.cue
Same refactor as done in https://github.com/perses/perses/pull/2289 but for TextVariable & StaticListVariable.
Also took the opportunity to cover StaticListVariable in the DaC unit tests.
> [IGNORE] DaC CUE SDK: refactor/simplify dac-utils code for variables (part 2)

- pkg/model/api/config/authentication.go
fix https://github.com/perses/perses/issues/2172
> [BREAKINGCHANGE] OIDC/OAUTH: client_secret is now optional in the perses config

- cue/dac-utils/variable/group/group.cue
- docs/dac/cue/variable/group.md
- go-sdk/dashboard/dashboard_test.go
- internal/test/dac/expected_output.json
- internal/test/dac/input.cue
Adding a new output to the existing variable-group lib to generate a query param expression from the list of variables passed. This can come in handy when you want to add links to a panel.
> [ENHANCEMENT] DaC CUE SDK: new utility to generate query params from labels

- ui/plugin-system/src/components/PluginEditor/PluginEditor.tsx
- ui/prometheus-plugin/src/components/PromQL.tsx
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQueryEditor.tsx
- Added a textfield-like like label for the promQL input + placeholder text
- Consistent spacing between elements
- Rework Legend's texts
There's still room for improvements (e.g label's background)
_EDIT: gave up on rounded corner for the CodeMirror component since, for maintainability reasons._
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/bd1d9224-abc5-463c-a9d5-e3ff3eacef1c) | ![2024-10-03_13h05_07](https://github.com/user-attachments/assets/e0ffebb0-a8c5-419c-b449-92be99cd5059) |
| ![2024-10-03_13h07_17](https://github.com/user-attachments/assets/c847f702-6c5b-4a90-bc3b-a013385405f5) | ![2024-10-03_13h08_10](https://github.com/user-attachments/assets/e2ebbaf2-b711-4a23-910a-c416a41a49cc) |
EDIT: with latest changes:
following …
> [ENHANCEMENT] Improve the query editor's look

- ui/tempo-plugin/src/model/api-types.ts
- ui/tempo-plugin/src/model/tempo-client.test.ts
- ui/tempo-plugin/src/model/tempo-client.ts
- ui/tempo-plugin/src/test/mock-data.ts
When upgrading to Tempo v2.6.0, the vParquet4 block format is the default, which includes the `serviceStats` field in the search API response.
The previously stored blocks (using vParquet3 format or older) do not contain this field yet, therefore it's possible to receive a search API response where some traces contain the `serviceStats` field and some traces don't contain this field.
no UI changes
include:
- Does the time change? You …
> [BUGFIX] tempo: support search results with mixed vParquet3 and vParquet4 blocks

- docs/user-guides/configuration.md
- internal/api/discovery/http/http.go
- internal/api/e2e/api/auth_test.go
- internal/api/e2e/api/dashboard_test.go
- internal/api/e2e/api/globalrolebinding_test.go
- internal/api/e2e/api/rbac_test.go
- internal/api/e2e/api/rolebinding_test.go
- internal/api/e2e/api/user_test.go
- internal/api/e2e/client/auth_test.go
- internal/api/e2e/client/test_utils.go
- internal/api/e2e/framework/data.go
- internal/api/impl/auth/auth.go
- internal/api/impl/auth/native.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- internal/cli/cmd/login/device_code.go
- internal/cli/cmd/login/login.go
- internal/cli/cmd/login/login_int_test.go
- internal/cli/cmd/login/native.go
- internal/cli/cmd/login/robotic.go
- internal/cli/config/config.go
- pkg/client/api/auth/auth.go
- pkg/client/api/client.go
- pkg/client/api/validate/validate.go
- pkg/client/config/config.go
- pkg/client/fake/api/client.go
- pkg/client/perseshttp/client.go
- pkg/client/transport/transport.go
- pkg/model/api/auth.go
- pkg/model/api/config/datasourcediscovery.go
This PR is changing the http client of Perses. The main goal is to handle the Oauth and native auth easily.
For that I am introducing a custom round tripper in the package `transport`. That's the part that is handling automatically the native authentification.
We are using the package `oauth2` to handle oauth authentication.
As a side effect, the login requests are now returning the object `oauth2.Token`. Doing that help a lot to handle the different cases (i.a, does the token expire, the type of the token ...etc.) 
With this PR handling configuring oauth with the perses client will be like that:
```go
client, err := config.NewFromConfig(config.RestConfigClient {
URL: "http://localhost:8080",
Auth: &config.AuthConfig {
OauthConfig: &config.OauthConfig{
ClientID:     "MyClientID", …
```
> [BREAKINGCHANGE] Refactor package pkg/client to handle native/oauth auth natively

- docs/user-guides/configuration.md
- internal/api/impl/auth/auth.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- pkg/client/perseshttp/client.go
- pkg/model/api/config/authentication.go
This PR allows us to set a timeout and various TLS configurations into the HTTP client that is used to make the various queries to external auth providers.
Hopefully fixes #2302 
It makes a little cleanup as well in the auth config documentation that was missing some elements.
> [ENHANCEMENT] Configuration of the HTTP client for oauth/oidc providers

- cue/schemas/panels/gauge/migrate.cue
- cue/schemas/panels/stat/migrate.cue
- internal/api/migrate/mapping.cuepart
- internal/api/migrate/migrate_test.go
- internal/api/migrate/testdata/stat_calc_undefined_grafana_dashboard.json
- internal/api/migrate/testdata/stat_calc_undefined_perses_dashboard.json
- [BUGFIX] Grafana migration: fix wrong default value for calculation
- [ENHANCEMENT] Stat & Gauge migration: avoid failing when there's no calc defined
> [BUGFIX] Grafana migration: fix some failing cases

- cue/schemas/panels/time-series/migrate.cue
Some of the fields are actually optional in grafana such as panel.options.legend.showLegend and panel.options.legend.placement for time series panels.
Using mixins for dashboard creation, we can get such block legend:
```
"legend": {
"calcs": [ ],
"displayMode": "list"
},
```
And it'll be valid for grafana.
These changes allow to avoid errors when we have jsons with such format.
> [ENHANCEMENT] Change timeseries panel's legend migration

- cue/schemas/panels/table/migrate.cue
Fix table migration fail when excludeByName is not present in transformation="organize".
Note: Logic is currently disable altogther.
> [BUGFIX] Migration: Fix table migration fail when excludeByName is not present in transformation="organize"

- internal/api/migrate/mapping.cuepart
Tiny patch that maps grafana durations (in seconds and ms) to seconds and milliseconds. Useful to migrate dashboards with panels showing 'Uptime'.
> [ENHANCEMENT] migration: Map durations to seconds

- cue/schemas/panels/time-series/migrate.cue
Migration could fail with grafana lineWidth < 0.25.
> [BUGFIX] Migration: Add lineWidth constraint

- internal/api/migrate/migrate.go
- internal/api/migrate/testdata/expanded_rows_before.json
Similar to #2325 , panels and collapsed attributes may be missing in rows definitions, for example, when generated. Handling such situation in migrations.
> [ENHANCEMENT] migration: Handle collapsed/panels missing in row definition

- cue/schemas/panels/gauge/migrate.cue
- cue/schemas/panels/stat/migrate.cue
- cue/schemas/panels/time-series/migrate.cue
Some of the fields are actually optional in grafana such as `fieldConfig.defaults.thresholds.steps` for stat and gauge panels.
For example,  [grafonnet](https://grafana.github.io/grafonnet/API/index.html) and [foundation-sdk](https://github.com/grafana/grafana-foundation-sdk) can generate perfectly fine grafana dashboards without those attributes. Dashboards then can be loaded to grafana and those attributes would be filled with defaults, but would fail to migrate to Perses due to migration will try to acces attributes that are missing.
This adds checks that those attributes exist before accessing them.
> [ENHANCEMENT] Migration: Don't fail on `fieldConfig.defaults.thresholds.steps` absence

- ui/core/src/schema/variable.ts
- ui/plugin-system/src/utils/variables.ts
> [ENHANCEMENT] allow variables to be empty

- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/SpanDuration.test.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/SpanDuration.tsx
TracingGanttChart: align span duration label location based on available space. Show the label on the left side if there is no space on the right side.
Additionally, set a `min-width` of `2px` for the span bar, otherwise span bars with very small durations would be invisible.
The span duration label of the pink bar is shown on the left side, because there is no space on the right side:
include:
- Does the time change? You need to use …
> [ENHANCEMENT] TracingGanttChart: align span duration label location based on available space

- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/DetailPane/DetailPane.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/DetailPane/SpanEvents.test.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/DetailPane/SpanEvents.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/GanttTable.test.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/GanttTable.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/GanttTableHeader.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/SpanDuration.test.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/SpanDuration.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/GanttTable/SpanName.test.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/MiniGanttChart/Canvas.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/MiniGanttChart/MiniGanttChart.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/MiniGanttChart/draw.ts
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/Ticks.test.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/Ticks.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/TracingGanttChart.stories.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/TracingGanttChart.tsx
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/trace.test.ts
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/trace.ts
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChart/utils.ts
- ui/panels-plugin/src/plugins/tracing-gantt-chart/TracingGanttChartPanel.tsx
- ui/panels-plugin/src/test/get-trace-data-jaeger.ts
- ui/panels-plugin/src/test/mock-trace-data.ts
In some cases, the trace start and end time does not match the start and end time of the root span (in other words, some spans are in progress or started after the root span has ended).
* compute and memoize start and end time of the trace by scanning all spans of the trace
* introduce a GanttTrace data type which holds these pre-computed fields
* update all React props `rootSpan` --> `trace` and all references `rootSpan.startTimeUnixMs` --> `trace.startTimeUnixMs` (and `.endTime`)
The trace contains spans starting after the root span has ended:
and …
> [BUGFIX] TracingGanttChart: calculate start and end time from all spans

- internal/cli/cmd/migrate/migrate.go
fix https://github.com/perses/perses/issues/2345
When using the offline migrate command, you need to provide the schemas to be able to perform it. The nil pointer sharing in the issue is occurring because the flags are not provided and then the schemas are not loaded locally.
> [BUGFIX] Fix migrate cmd by making the flag schemas.<schema_kind> mandatory when being offline

- internal/api/migrate/mapping.cuepart
**cps** unit for migration mapping list was added. This unit was in code, but was skipped in mapping list (mapping.cuepart file).
> [ENHANCEMENT] Add counts/sec unit to mapping list for migration

- ui/panels-plugin/src/plugins/trace-table/DataTable.tsx
TraceTable: expand the span count bubble in the service name chips
Before:
After:
include:
> [BUGFIX] TraceTable: expand the span count bubble in the service name chips

- go.mod
- go.sum
- internal/cli/cmd/apply/apply.go
- internal/cli/cmd/apply/apply_test.go
- internal/cli/cmd/remove/remove_test.go
- internal/cli/opt/opt.go
- internal/cli/test/sample_resources/multiple_resources.json
[ENHANCEMENT] Add --force option to allow applying resource despite project config inconsistencies
Fix: https://github.com/perses/perses/issues/1917, take a look at the problem, i am uncertain if this solution aligns with our objectives. The proposed PR addition of a force flag aims to alert users to potential project inconsistencies while still permitting them to create based on input metadata.
- na Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- na Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- na Visual tests are stable and unlikely to be flaky.
See …
> [ENHANCEMENT] Add --force option to allow applying resource despite project config inconsistencies

- .github/workflows/go.yml
- cue/dac-utils/prometheus/filter/filter.cue
- cue/dac-utils/prometheus/variable/labelnames/labelnames.cue
- cue/dac-utils/prometheus/variable/labelvalues/labelvalues.cue
- cue/dac-utils/prometheus/variable/promql/promql.cue
- cue/schemas/panels/gauge/migrate.cue
- cue/schemas/panels/stat/migrate.cue
- cue/schemas/panels/table/migrate.cue
- cue/schemas/panels/time-series/migrate.cue
- go.mod
- go.sum
- internal/api/discovery/cuetils/cuetils.go
- internal/api/discovery/cuetils/node.go
This bump to [v0.11.0-alpha.4](https://github.com/cue-lang/cue/releases/tag/v0.11.0-alpha.4) enforced to:
- fix some deprecated lib usage
- stop cheating with the switch-like statements (it can no longer deal with the 0 index when the array is empty)
> [IGNORE] CUE: bump to latest alpha

- ui/panels-plugin/src/plugins/trace-table/TraceTablePanel.tsx
TraceTable: show scrollbar only if content overflows
Before (scrollbar is always shown):
After (scrollbar is not shown because the content does not overflow):
include:
> [ENHANCEMENT] TraceTable: show scrollbar only if content overflows

- docs/user-guides/configuration.md
- internal/api/e2e/api/auth_test.go
- internal/cli/config/config.go
- pkg/client/config/config.go
- pkg/client/perseshttp/client.go
- pkg/client/perseshttp/request.go
I am breaking (again) the RestConfig for the perses http client regarding the way the authentication is managed.
I believe it will simplify a bit the config. It also simplify the way we are managing the auth in the client. Now everything is handled inside the `http.Client` and not anymore partially in the object `Request`
> [BREAKINGCHANGE] Refactor the way to manage authentication in the perses http client

- internal/api/impl/v1/view/endpoint.go
- ui/app/src/views/projects/dashboards/HelperDashboardView.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/DataQueriesProvider.tsx
- ui/plugin-system/src/runtime/UsageMetricsProvider.tsx
- ui/plugin-system/src/runtime/index.ts
This is the other half of https://github.com/perses/perses/issues/1170
This adds in a provider that tracks metrics about a dashboard that is being loaded. Each individual panel uses that provider to store the state of it's queries, and then once all the queries are finished, we
ship the metrics off to the previously created /visit api.
https://github.com/user-attachments/assets/f693294a-73ef-4dc5-a2a8-9d28ea68fdc7
include:
- Does the …
> [FEATURE] Usage Tracking Frontend Work

- internal/api/migrate/mapping.cuepart
- internal/api/migrate/testdata/old_grafana_panels_perses_dashboard.json
- internal/api/migrate/testdata/old_grafana_query_perses_dashboard.json
- internal/api/migrate/testdata/simple_perses_dashboard.json
Migrates current value to defaultValue in dashboard variables. This specifically useful for special values like `$__all` which can be set by default in Grafana.
NOTE: this is a copy of automatically closed https://github.com/perses/perses/pull/2383, but I removed the part that sets `defaultValue` to $__all if default value was missing in Grafana at all.
> [ENHANCEMENT] migrate current.value to defaultValue

- Makefile
- ui/app/src/components/datasource/DatasourceDrawer.tsx
- ui/app/src/components/datasource/DatasourceList.tsx
- ui/app/src/components/form-drawers.tsx
- ui/app/src/components/rolebindings/RoleBindingDrawer.tsx
- ui/app/src/components/rolebindings/RoleBindingEditorForm.tsx
- ui/app/src/components/rolebindings/RoleBindingList.tsx
- ui/app/src/components/roles/RoleDrawer.tsx
- ui/app/src/components/roles/RoleEditorForm.tsx
- ui/app/src/components/roles/RoleList.tsx
- ui/app/src/components/secrets/SecretDrawer.tsx
- ui/app/src/components/secrets/SecretEditorForm.tsx
- ui/app/src/components/secrets/SecretList.tsx
- ui/app/src/components/users/UserDrawer.tsx
- ui/app/src/components/users/UserEditorForm.tsx
- ui/app/src/components/users/UserList.tsx
- ui/app/src/components/variable/VariableDrawer.tsx
- ui/app/src/components/variable/VariableList.tsx
- ui/app/src/views/admin/tabs/GlobalRoleBindings.tsx
- ui/components/src/FormEditor/FormActions.tsx
- ui/components/src/FormEditor/index.ts
- ui/components/src/index.ts
- ui/dashboards/src/components/Datasources/DatasourceEditor.tsx
- ui/dashboards/src/components/Variables/VariableEditor.tsx
- ui/plugin-system/src/components/DatasourceEditorForm/DatasourceEditorForm.tsx
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
When clicking on a resource row, in order to see resource detail, when you click on the edit button, made some change and saved: the drawer is closed and nothing happened. It's now fixed.
include:
> [BUGFIX] Edit mode not working after clicking on the resource row

- ui/components/src/BarChart/BarChart.tsx
- ui/components/src/ContentWithLegend/ContentWithLegend.tsx
- ui/components/src/Legend/Legend.tsx
- ui/components/src/PieChart/PieChart.tsx
- ui/components/src/Table/TableCell.tsx
- ui/components/src/TimeChart/TimeChart.tsx
- ui/components/src/YAxisLabel.tsx
- ui/panels-plugin/src/plugins/time-series-chart/TimeSeriesChartPanel.tsx
Thanks to @andreasgerstmayr comment on one of his PR, I discovered dynamic values in SX is bad: [https://mui.com/system/getting-started/the-sx-prop/#dynamic-values](https://mui.com/system/getting-started/the-sx-prop/#dynamic-values) and should move to inline style.
It's a first pass on height / width props, but there are probably still some left. The biggest one is still on the [EChart component](https://github.com/perses/perses/blob/5a36eded73cf73b13781e40db35b829b2442d484/ui/components/src/EChart/EChart.tsx#L207) but look like it's used as a trick to re-render the component 🤔 
and …
> [BUGFIX] Remove some SX props leaking

- ui/dashboards/src/components/Variables/BuiltinVariableAccordions.tsx
- ui/prometheus-plugin/src/plugins/prometheus-datasource.tsx
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQueryEditor.tsx
Rework the description of prom built-in vars & min step parameters: start first by explaining what's their interest for the user, then provide more details about what they represent concretely.
include:
> [ENHANCEMENT] More user-friendly helpers for prometheus built-in variables

- .github/ISSUE_TEMPLATE/bug_report.yml
- internal/cli/cmd/login/login.go
- internal/cli/config/config.go
Currently if you log using the CLI in the demo and then you are waiting for the token to expire, you won't be able to log again. Instead you will the following error:
```bash
$ ./bin/percli login http://demo.perses.dev/
Error: something wrong happened with the request to the API. Error: Get “http://demo.perses.dev/api/config”: oauth2: token expired and refresh token is not set
```
Also you cannot log into a Perses instance where the auth is disabled. You will face the same issue. 
All of that is because when using the command `percli login` we are creating the Perses HTTP client based on a previous config where potentially token is expired or doesn't exist.
Creating from scratch the Perses HTTP client is fixing the issues mentioned above.
> [BUGFIX] Fix login command avoiding reusing previous config

- ui/e2e/src/fixtures/dashboardTest.ts
- ui/prometheus-plugin/src/components/PromQLEditor.tsx
- ui/prometheus-plugin/src/components/parse.ts
Change the PromQL tree view behavior to only fire the request to the parse_query endpoint if the user decided to show the Tree view.
Previous design was to prevent relevant syntax errors to be hidden by default to the user, but in the end it causes other issues / unwanted console errors so in the end 'getting rid of that.
This should also fix the issue we have with e2e tests currently.
include:
- Does the time change? You need to use …
> [BUGFIX] PromQL Tree view: stop firing the parse query before the show button gets clicked

- go-sdk/prometheus/datasource/datasource.go
- pkg/model/api/config/config.go
- pkg/model/api/config/datasourcediscovery.go
- pkg/model/api/config/frontend.go
- pkg/model/api/config/provisioning.go
- pkg/model/api/config/schemas.go
- pkg/model/api/v1/datasource/datasource.go
- pkg/model/api/v1/ephemeraldashboard.go
This PR adds Kubernetes-compatible annotations to fields of type model.Duration in the imported library for Kubernetes spec fields. The following annotations are added to relevant fields:
```yaml
// +kubebuilder:validation:Type=string
// +kubebuilder:validation:Format=duration
```
These annotations ensure that `model.Duration` fields are treated as strings with a duration format, resolving conflicts between the custom JSON serialization in prometheus/common and Kubernetes API expectations. This fix addresses validation errors in the Perses controller when updating Perses resources. 
This change ensures compatibility between the Perses and Perses Operator. 
> [ENHANCEMENT] Add Kubernetes-compatible annotations for model.Duration fields

- .gitignore
- dev/docker-compose.yaml
- dev/extra/prometheus.yaml
- dev/extra/tempo.yaml
Allow dev env to launch prometheus and tempo datasource with `--profile` arg
Example: `docker-compose --file dev/docker-compose.yaml --profile prometheus --profile tempo up --detach`
> [IGNORE] Add optional local prometheus and tempo to dev env

- go-sdk/prometheus/datasource/datasource.go
- pkg/model/api/config/authentication.go
- pkg/model/api/config/authorization.go
- pkg/model/api/config/config.go
- pkg/model/api/config/database.go
- pkg/model/api/config/datasourcediscovery.go
- pkg/model/api/config/frontend.go
- pkg/model/api/config/provisioning.go
- pkg/model/api/config/schemas.go
- pkg/model/api/v1/datasource/datasource.go
- pkg/model/api/v1/ephemeraldashboard.go
Add kubebuilder custom validations for duration all types
https://github.com/perses/perses-operator/pull/21
> [ENHANCEMENT] add kubebuilder annotations to all duration types

- ui/prometheus-plugin/src/components/PromQLEditor.tsx
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/get-time-series-data.ts
- ui/prometheus-plugin/src/plugins/prometheus-time-series-query/replace-prom-builtin-variables.ts
- ui/prometheus-plugin/src/utils/utils.ts
- ui/tempo-plugin/package.json
With https://github.com/perses/perses/pull/2344 I missed the fact that prometheus-specific builtin variables (`$__interval`, `$__rate_interval`..) aren't getting replaced by proper values with the current logic.. Thus any query containing such variable is producing an error (prometheus cannot parse this perses-specific syntax). This PR aims to fix that.
include:
- Does the time change? You need to use consistent time values or mock …
> [BUGFIX] Fix tree view broken when using prometheus built-in vars

- cue/schemas/panels/status-history/migrate.cue
- cue/schemas/panels/status-history/status-history.cue
- cue/schemas/panels/status-history/status-history.json
- ui/components/src/StatusHistoryChart/StatusHistory.md
- ui/components/src/StatusHistoryChart/StatusHistoryChart.stories.tsx
- ui/components/src/StatusHistoryChart/StatusHistoryChart.tsx
- ui/components/src/StatusHistoryChart/StatusHistoryTooltip.ts
- ui/components/src/StatusHistoryChart/get-formatted-axis-label.ts
- ui/components/src/StatusHistoryChart/index.ts
- ui/components/src/StatusHistoryChart/utils/get-color.test.ts
- ui/components/src/StatusHistoryChart/utils/get-color.ts
- ui/components/src/StatusHistoryChart/utils/get-tooltip-position.ts
- ui/components/src/TimeSeriesTooltip/TooltipHeader.tsx
- ui/components/src/index.ts
- ui/components/src/utils/format.ts
- ui/panels-plugin/plugin.json
- ui/panels-plugin/src/plugins/status-history-chart/StatusHistoryChart.ts
- ui/panels-plugin/src/plugins/status-history-chart/StatusHistoryChartOptionsEditorSettings.tsx
- ui/panels-plugin/src/plugins/status-history-chart/StatusHistoryPanel.tsx
- ui/panels-plugin/src/plugins/status-history-chart/index.ts
- ui/panels-plugin/src/plugins/status-history-chart/status-history-model.ts
- ui/panels-plugin/src/plugins/status-history-chart/utils/data-transform.test.ts
- ui/panels-plugin/src/plugins/status-history-chart/utils/data-transform.ts
- ui/panels-plugin/src/plugins/status-history-chart/utils/get-timescale.ts
- ui/plugin-system/src/components/LegendOptionsEditor/LegendOptionsEditor.tsx
Implements a new Status History panel for Perses that displays status changes over time, similar to Grafana's Status History panel.
Resolves #2268 
include:
> [FEATURE] Status History panel

- cue/schemas/panels/table/migrate.cue
- internal/api/migrate/migrate_test.go
- internal/api/migrate/testdata/simple_perses_dashboard.json
- internal/api/migrate/testdata/tables_perses_dashboard.json
Add (actually [bring back](https://github.com/perses/perses/pull/2312)) necessary logic to migrate the `fieldConfig.overrides` from Grafana to our `columnSettings`.
You may notice that the logic would inevitably generate multiple settings for the same column while Perses will only consider the first one found to customize the table rendering. At least the values are there in the JSON so users can go there to merge settings manually.
Why not trying to automatically merge settings: there's a bug on new CUE evaluator that prevents us to use maps to gather settings first. See https://github.com/perses/perses/pull/2312. I actually tried a workaround logic with many loops to replace the need for a map but the complexity went crazy (unit test evaluation went from 1s to 20s..). Keeping history …
> [ENHANCEMENT] Table: best-effort migration of fieldConfig.overrides to columnSettings

- internal/api/schemas/loader.go
- internal/cli/cmd/plugin/lint/lint.go
- internal/cli/cmd/plugin/plugin.go
I am adding a new command `percli plugin lint` that is validating the cuelang schema for a plugin. Probably in a future PR, it will run the eslint linter as well. 
It should improve the CI/CD in the repo `perses/plugins`
> [FEATURE] add plugin lint command

- cue/schemas/panels/table/table.cue
- ui/components/src/Legend/TableLegend.tsx
- ui/components/src/Table/Table.tsx
- ui/components/src/Table/VirtualizedTable.tsx
- ui/components/src/Table/model/table-model.ts
- ui/panels-plugin/src/plugins/table/TablePanel.tsx
- ui/panels-plugin/src/plugins/table/TableSettingsEditor.tsx
- ui/panels-plugin/src/plugins/table/table-model.ts
On the Table panel, allow users to set a custom default width to all columns. Column associated to a column setting can override this default value.
Auto column width will try to automatically adjust the width of columns to fit without overflowing. When there is a lot of columns, the table can be unreadable.
include:
- Does it have loading states? …
> [ENHANCEMENT] Table: add default column width setting

- internal/api/migrate/mapping.cuepart
Migratoin: Add missing color aliases from grafana pallete (yellow).
> [ENHANCEMENT] Add yellow mapping from grafana

- cue/schemas/panels/markdown/migrate.cue
It is possible to get Grafana Text panel without content field, if text panel is generated like via grafonnet library.
This small change covers it and provides empty panel in those cases.
> [ENHANCEMENT] Update Markdown migration

- internal/cli/cmd/dac/build/build.go
- internal/cli/cmd/describe/describe.go
- internal/cli/cmd/get/get.go
- internal/cli/cmd/version/version.go
- internal/cli/opt/opt.go
The removed check was redundant with the base validation behavior coming with that flag:
https://github.com/perses/perses/blob/1f0d7cc7b2ef419592df52d1bbbdcabc1e4461cc/internal/cli/output/output.go#L33-L43
(Some commands (e.g `describe`) were already fine)
> [IGNORE] `dac build`: remove useless check for output flag

- ui/panels-plugin/src/plugins/table/TablePanel.tsx
When using a cell mapping with range starting from 0, it was ignored because of the if check global
> [BUGFIX] Table: mapping with min range 0 not working

- cue/schemas/panels/table/table.cue
- ui/components/src/AlignSelector/AlignSelector.tsx
- ui/components/src/SortSelector/SortSelectorButtons.tsx
- ui/panels-plugin/src/plugins/table/ColumnsEditor/ColumnEditor.tsx
- ui/panels-plugin/src/plugins/table/TablePanel.tsx
- ui/panels-plugin/src/plugins/table/table-model.ts
Allow user to predefine column sorting in column settings
include:
> [ENHANCEMENT] Table: add default column sorting

- internal/cli/cmd/dac/build/build.go
- internal/cli/cmd/dac/diff/diff.go
Fixes this issue encountered when the output folder of dac-related commands doesn't already exists:
```
$ percli dac diff -f dashboard.json
Error: unable to write the diff file: open built/perses-dashboard.diff: The system cannot find the path specified.
```
The command now tries to create the output folder as part of its logic (just like for `build` command)
> [BUGFIX] `dac diff`: fix output folder not found

- .gitignore
- ui/.eslintrc.base.js
- ui/package-lock.json
- ui/package.json
Linter is only supporting Typescript < 5.4, when updating linter I have other error, quick fix for current issue. When your are using unsupported TS version, linter do not raise error during npm run lint 😅 
And enforce return typing, because it's not the default behaviour, weird...
> Downgrade TypeScript version to v5.3 + enforce return typing

- ui/components/src/TransformsEditor/TransformEditor.tsx
- ui/components/src/TransformsEditor/TransformsEditor.test.tsx
- ui/components/src/controls/TextField.tsx
- ui/components/src/controls/index.ts
- ui/components/src/index.ts
- ui/panels-plugin/src/plugins/table/CellsEditor/CellEditor.tsx
- ui/panels-plugin/src/plugins/table/ColumnsEditor/ColumnEditor.tsx
- ui/panels-plugin/src/plugins/table/ColumnsEditor/ColumnEditorContainer.tsx
- ui/panels-plugin/src/plugins/table/TableColumnsEditor.test.tsx
- ui/panels-plugin/src/plugins/table/TableSettingsEditor.tsx
TextField can trigger a lot of useless re-renders until the right value is typed. Debounce should reduce a little bit this issue.
include:
> [ENHANCEMENT] Table panel: editor text fields are debounced 

- cue/dac-utils/variable/group/group.cue
- docs/dac/cue/variable/group.md
- internal/test/dac/input.cue
As you can see in the unit tests it was already possible to achieve the same result with such syntax:
```cue
#input: [for i in #input {#datasourceName: "promDemo"}]
```
Still, I expect this to be such a common pattern that adding a small helper to allow providing simply `#datasourceName: "promDemo"` is worth it imho.
> [ENHANCEMENT] DaC CUE SDK: add datasource param to the var group builder

- internal/cli/cmd/dac/diff/diff.go
- **add output**: `diff` now produces an output similar to what `preview` is doing, with project + dashboard name + status (NEW/UPDATED/ERROR) + Diff file path if applicable:
```bash
$ percli dac diff -d testdata/
time="2024-12-13T22:23:11+01:00" level=info msg="No dashboard brand-new found in project perses-github-actions, skipping diff generation"
time="2024-12-13T22:23:11+01:00" level=info msg="built/perses-github-actions-empty_dashboard.diff successfully generated"
- project: perses-github-actions
dashboard: brand-new
status: NEW
- project: perses-github-actions
dashboard: empty_dashboard
status: UPDATED
diff: built/perses-github-actions-empty_dashboard.diff
```
- **avoid early return when processing a directory**: This change is needed to correctly handle the common case where a user …
> [ENHANCEMENT] `percli dac diff`: add output + avoid early return when processing a directory

- internal/cli/cmd/dac/build/testdata/go/go.mod
- internal/cli/cmd/plugin/lint/lint.go
This PR is reflecting the introduction of the plugin module from https://github.com/perses/plugins/pull/16.
The folder `schema` can contains multiple cuelang schema representing the sub plugin module. This PR is aiming to find whatever the folder struct is the different schema files. Like that we are not forcing people to have a special folder struct for their plugins.
With this change, we should be able to validate our own plugin.
> [ENHANCEMENT] : percli plugin lint: improve the way to find the schema files

- internal/cli/cmd/dac/setup/setup.go
`dac setup` (alternatively `dac setup --language cue`) shouldn't ask the user to install Golang, since it's not needed to work with the CUE SDK.
The issue was raised as part of https://github.com/perses/perses/issues/2533.
> BUGFIX: `percli dac setup`: fix useless requirement of go CLI when using CUE

- internal/api/impl/auth/auth.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- ui/app/src/Router.tsx
- ui/app/src/model/auth-client.ts
- ui/app/src/model/fetch.ts
- ui/app/src/views/auth/SignInView.tsx
- ui/app/src/views/auth/SignWrapper.tsx
This PR aims to fix #2284
This is two main changes:
Make sure that the original route is never lost, passing it everywhere. To the Perses backend and to the OIDC/Oauth providers.
The main idea is to simplify relying on cookie presence only to know if we need to redirect or not. 
=> All routes/redirections are in the Router 💪 
From what I understood, the standard way appears to be creating a guard component in the Router which will react on the cookie presence/absence. And to place all the routes component under that guard.
The main tricky point resided then in the fact that **when we refresh the access token with the refresh token, it was removing the cookie and recreated it**. The guard was then too reactive and redirected directly to signin page. 😢 
=> Solution to that is to use a …
> [BUGFIX] Redirect to the desired page after login success

- ui/components/src/TimeSeriesTooltip/tooltip-model.ts
Perses is refactoring tooltip logic from eCharts, it’s important to note that the zRender library used by eCharts handles window events differently for touch devices and browsers. Specifically, `zrX` and `zrY` properties on event objects are only available on the `PointerMove` event for Edge browsers, while other browsers use the standard `MouseEvent`. This discrepancy means we cannot rely solely on `MouseEvent` for consistent event handling.
Unfortunately, `zRender` does not provide any public API or methods to detect how it patches events, leaving us without a straightforward way to accommodate these differences.
To address this, similar logic from `zRender` has been incorporated directly into the project, with slight modifications to minimize boilerplate code and improve …
> [BUGFIX] Fixes tooltip display in EDGE / IE

- ui/dashboards/src/components/Variables/Variable.tsx
Close #2277. Found other issue when testing the fix: dropdown position changing when removing change from All to an item
include:
> [BUGFIX] ListVariable: fix autocomplete when 'All' is selected

- ui/app/src/views/home/RecentDashboards.tsx
Add an error boundary around recently view dashboard. Some user are affect by an unknown issue #2559. It will mitigate the error on the home page. But it will still throw error on dashboards, I think
> [IGNORE] Home page: Add error boundary around recently viewed dashboards

- .github/workflows/e2e.yml
Should fix this issue that appeared yesterday:
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> [IGNORE] CI: e2e: bump actions/upload-artifact to v4

- dev/config.yaml
- internal/api/core/core.go
- internal/api/plugin/dev.go
- internal/api/plugin/npm.go
- internal/api/plugin/plugin.go
- pkg/model/api/config/plugins.go
- ui/endpoint.go
Here a proposition to let the Perses server to read plugin serving by the dev server from `rsbuild`.
You just need to configure in Perses the dev environment and then it will read the schema and refresh the list of module available on `/api/v1/plugins`.
It will also forward the request to the dev server when needed. 
To be used like that: 
```yaml
plugins:
dev_environment:
url: "http://localhost:3005"
plugins:
- name: TimeSeriesChart
absolute_path: "/Users/ahusson/workspace/go/src/perses/plugins/TimeSeriesChart"
```
I am just wondering if it's a good idea to have this configuration in the global config of Perses or if we should have it in a different file.
On the other hand, if someone want to split the Perses config in different files, there are tools for that that will compute and merge …
> [FEATURE] Perses server is able to load plugin from dev environment server

- ui/app/package.json
- ui/app/src/components/DashboardList/DashboardDataGrid.tsx
- ui/app/src/components/DashboardList/DashboardList.tsx
- ui/app/src/components/DashboardList/RecentDashboardList.tsx
- ui/app/src/context/DashboardNavHistory.tsx
- ui/package-lock.json
A bug in the MUI Grid library caused loop setState https://github.com/mui/mui-x/issues/15721, the library was upgraded. Also for dashboards with the same name but in different projects there was a key collision.
Fixes: #2559
No UI changes
> [BUGFIX] add id to avoid setState loops, upgrade MUI grid

- internal/cli/cmd/dac/preview/preview.go
- internal/cli/cmd/dac/preview/preview_test.go
- pkg/client/fake/api/v1/client.go
- pkg/client/fake/api/v1/dashboard.go
Adding the URL of the existing dashboard, when applicable, corresponding to the preview helps the user to quickly see the before & after states, using "current" link + preview link.
> [ENHANCEMENT] `percli dac preview`: add current dashboard URL to the output when applicable

- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelActions.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
Solves https://github.com/perses/perses/issues/2602
- Updated the panels to show header actions only when hovering the panel or when the panel is expanded
- show drag handle only in edit mode
include:
> [ENHANCEMENT] Improve panel hover behavior and adjust header styling for better visibility

- internal/api/database/file/file.go
- internal/api/database/file/query.go
- internal/api/plugin/archive.go
- internal/api/plugin/npm.go
- internal/api/plugin/schema/schema.go
- internal/cli/cmd/dac/build/testdata/go/go.mod
- scripts/cue-test/cue-test.go
We are using in various places `path.Join` or `path.Split` while using file access path that works everywhere than on windows. 
This PR aims to fix that by using the pkg `filepath` that will handle the windows file system.
> [BUGFIX] Uses pkg filepath instead of path when manipulating file access

- cue/model/api/v1/plugin/plugin_go_gen.cue
- cue/model/api/v1/plugin/plugin_patch.cue
- internal/api/plugin/dev.go
- internal/api/plugin/migrate/migrate.go
- internal/api/plugin/plugin.go
- internal/api/plugin/schema/schema.go
- internal/api/plugin/validate.go
- internal/cli/cmd/plugin/lint/lint.go
- pkg/model/api/v1/plugin/plugin.go
Based on the plugin Kind, we are able to detect if the plugin needs a schema or not.
That should help to support and load the `explorer` plugin and latter the plugin like in the PR https://github.com/perses/perses/pull/2530
> [ENHANCEMENT] schemas are required for specific plugin kind

- internal/api/core/core.go
- internal/api/plugin/dev.go
- internal/api/plugin/plugin.go
- pkg/model/api/config/plugin.go
- ui/endpoint.go
The goal of this PR is to store the actual path where a plugin is located and associated it to it's name. Doing that allows to remove the constraint to have the folder in the archive named exactly like the plugin.
It will allow us to rename every plugin folder in `perses/plugins` and solve the issue https://github.com/perses/plugins/issues/43
As a side note, it is also fixing what URL is used for a plugin in development. Before it wasn't considering the URL written in the local config.
It is also fixing when the schema is not required, the plugins are still loaded. Before when schema was not required, the whole plugin was skipped and so not in the list of the plugin loaded.
> [ENHANCEMENT] Improve the way the plugins are loaded by considering the local path where they are stored

- docs/plugins/loading.md
as part of #2642, here a description of how Perses is able to load a plugin for the backend side. It remains the frontend side
> [DOC] Add doc explaining how the backend is loading the plugins

- internal/api/core/server.go
- internal/api/dependency/service_manager.go
- internal/api/impl/auth/auth.go
- internal/api/impl/auth/oauth.go
- internal/api/impl/auth/oidc.go
- internal/api/impl/auth/service.go
- internal/api/impl/v1/user/service.go
- With the changes in #2430, it is now possible to create roles that include users who have not yet been created.  
- This fixes an issue where permission settings were not applied when users were added to predefined roles via API, OIDC, or OAuth 2.0.
no ui changes
no ui changes
> [BUGFIX] Refresh RBAC cache when adding or removing users.

- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/plugin-system/src/model/panels.ts
For example the `Table` panel must switch between `instant` and `range` queries, depending on the cell type:
* text: `instant`, because we need a single value
* sparkline: `range`, because we need a time series
no UI changes
include:
> [ENHANCEMENT] Support conditional queryOptions for panels

- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelContent.tsx
- ui/dashboards/src/components/Panel/PanelPlugin.tsx
- ui/dashboards/src/components/Panel/PanelPluginLoader.tsx
- ui/dashboards/src/components/Panel/index.ts
This component wraps loading a panel plugin from the registry and rendering its PanelComponent. Example usage:
```
<PanelPluginLoader
kind="StatChart"
spec={{
calculation: 'last-number',
format: {
unit: 'decimal',
},
sparkline: {},
}}
contentDimensions={{ width: 300, height: 100 }}
queryResults={[
{ definition: { kind: 'TimeSeriesQuery', spec: { plugin: { kind: '', spec: {} } } }, data: tsData },
]}
/>
```
This is useful e.g. in the Table panel, when rendering Panels in a table cell.
no UI changes
and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common …
> [IGNORE] add <PanelPluginLoader> component to simplify embedding panels

- internal/api/plugin/plugin.go
- internal/api/plugin/validate.go
- internal/cli/cmd/plugin/build/build.go
- internal/cli/cmd/plugin/config/config.go
- internal/cli/cmd/plugin/lint/lint.go
When we are building the archive for a plugin, we are checking a list of mandatory files. If they are missing the error returned was not understandable.
This PR aims to improve the error returned.
> [BUGFIX] CLI/plugin: Improve error returned when files are missing in a plugin and fix loading default config file

- internal/api/plugin/migrate/variable.go
This PR addresses an issue with the migration of allValue from Grafana dashboards to Perses. Currently, Perses validation does not allow `allValue` (or `CustomAllValue` in perses) to be set when `AllowAllValue` is `false`. However, this is a valid use case in Grafana, which causes the migration of certain Grafana dashboards to fail.
include:
- Does …
> [BUGFIX] Grafana migration: Fix variable allValue migration

- scripts/generate-goreleaser/.goreleaser.base.yaml
from the logs:
```
• setting defaults
• DEPRECATED: archives.format should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
```
I am applying what is describing in the goreleaser documentation.
> [IGNORE] fix goreleaser archive format field used

- docs/configuration/load-plugin.md
- docs/plugins/structure.md
I have split the initial doc about how a plugin is loaded. I think it makes more sense like that.
> [DOC] Refactor and improve the doc about how to load a plugin

- ui/plugin-system/src/runtime/DataQueriesProvider/DataQueriesProvider.test.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/model.ts
Temporarily fix for #2697
This pull request includes a change to the `useQueryType` function in the `DataQueriesProvider` model to improve the handling of query type determination. The most important change is the modification of the function to return a combination of `isTraceQueryPluginLoading` and `isTimeSeriesQueryLoading` instead of throwing an error.
Improvements to query type determination:
* [`ui/plugin-system/src/runtime/DataQueriesProvider/model.ts`](diffhunk://#diff-762341f821e1106857e9670dc731dd98dde263e54710935a256854a850f2779cL97-R98): Modified the `useQueryType` function to return `isTraceQueryPluginLoading || isTimeSeriesQueryLoading` instead of throwing an error if the query type is not determined.
following `catalog_entry` values: `FEATURE`, `ENHANCEMENT`, `BUGFIX`, …
> [BUGFIX] Support custom query editors

- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelActions.tsx
Restore panel icon hover behavior (ref. https://github.com/perses/perses/pull/2635#discussion_r1970392400)
In non-editing, non-fullscreen mode, some panel icons are only visible on mouse hover:
* info icon (panel description)
* fullscreen icon
To be discussed:
* should the menu also be visible on hover, or always?
cc @galangel 
https://github.com/user-attachments/assets/96b7bc4c-b1be-4e1e-8ff8-3415cb1afec7
include:
- Does the time …
> [IGNORE] Restore panel icon hover behavior

- Makefile
Allow npm install flags to be passed in `make build-ui`. 
For example 
`make build-ui NPM_INSTALL_FLAGS="--ignore-scripts"`  
`cd ./ui && npm install $(NPM_INSTALL_FLAGS) && npm run build`
`cd ./ui && npm install --ignore-scripts  && npm run build`
N/A no UI changes were made. 
[-] * No UI Changes in this PR 
- [-] Changes that impact the UI include screenshots and/or screencasts of the relevant changes.
- [-] Code follows the [UI guidelines](https://github.com/perses/perses/blob/main/ui/ui-guidelines.md).
- [-] Visual tests are stable and unlikely to be flaky.
and …
> [ENHANCEMENT]: Allow npm install flags to be passed in `make build-ui` command

- ui/plugin-system/src/components/DatasourceSelect.tsx
Explicitly use `OutlinedSelectProps` as the parent interface, otherwise we cannot use the `notched` property in https://github.com/perses/plugins/pull/73.
Not 100% sure why it's required, `SelectProps` is a type union:
```
export type SelectProps<Value = unknown> =
| (FilledSelectProps & BaseSelectProps<Value>)
| (StandardSelectProps & BaseSelectProps<Value>)
| (OutlinedSelectProps & BaseSelectProps<Value>);
```
And the inheritance with `interface DatasourceSelectProps extends Omit<SelectProps<string>, OmittedMuiProps>` doesn't work otherwise.
no UI changes
and …
> [IGNORE] DatasourceSelect: support OutlinedSelectProps

- .github/workflows/cue.yaml
when `go.mod` or the list of the plugin is modified, we should run all test to be sure aspect of the code is covered and the update of dependencies doesn't break anything
> [IGNORE] Run cue tests when go.mod and plugins are modified

- ui/plugin-system/src/components/HTTPSettingsEditor/HTTPSettingsEditor.tsx
When switching between directUrl and proxy, copy all values (e.g. scrapeInterval) except for directUrl / proxy.
no UI changes
include:
> [BUGFIX] HTTPSettingsEditor: remove directUrl/proxy of previous value

- .github/dependabot.yml
I am updating the dependabot config hoping afteward it will be able to update the various go.mod files we have in perses.
The various go.mod we have are using to test the plugin and dac feature.
> [ignore] update dependabot go mod directories

- internal/cli/cmd/plugin/build/build.go
- internal/cli/cmd/plugin/build/build_test.go
- internal/cli/cmd/plugin/build/testdata/tempo/.gitignore
- internal/cli/cmd/plugin/build/testdata/tempo/cue.mod/module.cue
- internal/cli/cmd/plugin/build/testdata/tempo/package-lock.json
- internal/cli/cmd/plugin/build/testdata/tempo/package.json
- internal/cli/cmd/plugin/build/testdata/tempo/rsbuild.config.ts
- internal/cli/cmd/plugin/build/testdata/tempo/schemas/datasource/tempo.cue
- internal/cli/cmd/plugin/build/testdata/tempo/schemas/datasource/tempo.json
- internal/cli/cmd/plugin/build/testdata/tempo/schemas/tempo-trace-query/query.cue
- internal/cli/cmd/plugin/build/testdata/tempo/src/bootstrap.tsx
- internal/cli/cmd/plugin/build/testdata/tempo/src/components/TraceQLEditor.tsx
- internal/cli/cmd/plugin/build/testdata/tempo/src/components/TraceQLExtension.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/components/complete.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/components/highlight.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/components/index.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/env.d.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/index.tsx
- internal/cli/cmd/plugin/build/testdata/tempo/src/model/api-types.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/model/index.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/model/tempo-client.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/model/tempo-selectors.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/model/trace-query-model.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/plugins/tempo-datasource-types.tsx
- internal/cli/cmd/plugin/build/testdata/tempo/src/plugins/tempo-datasource.tsx
- internal/cli/cmd/plugin/build/testdata/tempo/src/plugins/tempo-trace-query/TempoTraceQuery.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/plugins/tempo-trace-query/TempoTraceQueryEditor.tsx
- internal/cli/cmd/plugin/build/testdata/tempo/src/plugins/tempo-trace-query/get-trace-data.ts
- internal/cli/cmd/plugin/build/testdata/tempo/src/plugins/tempo-trace-query/query-editor-model.ts
- internal/cli/cmd/plugin/build/testdata/tempo/tsconfig.json
that should fix the issue found in https://github.com/perses/plugins/pull/75.
I would like to add a test to cover the case when the folder `schemas` contained multiple sub-folder and nothing at the root like it is the case for the Prometheus or Tempo plugin.
> [BUGFIX] CLI: plugin build should consider all subfolder when getting the cue dependencies

- ui/app/rspack.config.ts
update rspack configuration to use the defineConfig function instead of a module. Remove not required __dirname references that might conflict with future node versions.
Fixes #2758
> [BUGFIX] update rspack configuration for future node versions compatibility

- ui/dashboards/src/context/VariableProvider/VariableProvider.tsx
Reduce unnecessary re-renders of `<DashboardApp>` component.
`DashboardApp` calls the `useDashboard()` hook, which calls `useVariableDefinitionActions()`. This function uses the store and returns **a new object every time**, invalidating the hook. By using `useShallow()`, it checks if the object actually changed or not.
However, in my opinion, it'd be best to remove this function and use `useStore(store, (s) => s.setVariableDefinitions)` instead when accessing `setVariableDefinitions` for example. What do you think?
I also updated `VariableProvider` and `VariableProviderWithQueryParams` to not create a new store every time for the initial value.
Screenshots from the React Profiler while loading the node exporter dashboard:
Before: The component was rendered 9 times.
After: The component …
> [ENHANCEMENT] Improve dashboard performance by reducing re-renders

- docs/plugins/common.md
Since the `common` package used by plugins is defined in perses/perses, its documentation should remain there (previously part of panels.md)
> [DOC] Add (back) common package doc

- ui/app/src/components/EphemeralDashboardList/EphemeralDashboardList.tsx
`expireAt` field in the Ephemeral Dashboard view is formatted as `localeString` whereas the rendering logic relies on it being in ISO format. This causes a crash while trying to view the Ephemeral dashboard. 
Fix for #2777 and #2063 
> [BUGFIX] Format expireAt with ISOString to fix EphemeralDashboard view crash

- dev/data/9-dashboard.json
Due to the size of the StatChart panel in the example dashboard, the edit button was in the action menu.
Unfortunately locating elements in the MaterialUI `<Popover>` element is unstable at times, therefore let's just increase the StatChart panel width for the e2e test, so the edit button is directly in the Panel header instead of the MUI `<Popover>` element.
- Does it have loading states? You need to wait for loading to …
> [IGNORE] Fix flaky StatChart panel e2e test

- docs/plugins/common.md
Moving HTTP proxy doc (back) to perses/perses to reference it both in prometheus & tempo docs.
> [DOC] Add HTTP Proxy documentation

- ui/app/rspack.config.mjs
Fixes the following error when starting rspack dev server on Node.js v22:
```
/home/agerstmayr/redhat/dev/perses/perses/ui/node_modules/@rspack/core/dist/index.js:12602
throw new Error(
^
Error: ./dist is neither a posix nor a windows path, and there is no 'dirname' method defined in the file system
at dirname2 (/home/agerstmayr/redhat/dev/perses/perses/ui/node_modules/@rspack/core/dist/index.js:12602:9)
at /home/agerstmayr/redhat/dev/perses/perses/ui/node_modules/@rspack/core/dist/index.js:12610:21
at Immediate.<anonymous> (/home/agerstmayr/redhat/dev/perses/perses/ui/node_modules/webpack-dev-server/node_modules/memfs/src/volume.ts:588:9)
at processImmediate (node:internal/timers:491:21)
```
Resolves: #2776
@Nexucis could you check if that change works for your env so we're not …
> [BUGFIX] fix rspack dev server on Node.js v22

- .github/workflows/cue.yaml
- internal/cli/cmd/plugin/build/build.go
- internal/cli/cmd/plugin/build/cue.go
- internal/cli/cmd/plugin/build/cue_test.go
- internal/cli/cmd/plugin/build/npm.go
- internal/cli/cmd/plugin/build/testdata/emptydeps/cue.mod/module.cue
This PR is changing the way we are vendoring the Cuelang dependency.
Before we were setting a temporary folder that was used as cache folder to download the Cuelang dependency.
Now we are not altering the default caching folder of Cuelang. The code is looking at the dependency file and then based on them, it will copy one by one the dependency from the caching folder to the vendor folder.
If one dependency is not found, then the code is calling cuelang to download it.
> [ENHANCEMENT] CLI/plugin: Improve the way to vendor cue dependencies and rely on cue default caching

- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
Solves https://github.com/perses/perses/issues/2791 
Changes made in the JSON will affect the top section of the edit drawer ( changes made on blur )
> [BUGFIX] Panel edit drawer - Update Title, description and Type on form changes

- pkg/model/api/v1/secret.go
- ui/app/src/components/secrets/SecretDataGrid.tsx
- ui/app/src/components/secrets/SecretEditorForm.tsx
- ui/app/src/components/secrets/SecretList.tsx
- ui/app/src/views/admin/AdminTabs.tsx
- ui/app/src/views/projects/ProjectTabs.tsx
- ui/e2e/src/pages/SecretEditor.ts
- ui/e2e/src/tests/projectView.spec.ts
This PR makes the authorization options for a secret optional. This will allow clients using the proxy to pass their own Authorization header in cases this Header is available from the client or is dynamic and cannot be set to a specific value.
updated the secrets table to include the "No Authorization" option
updated the secrets form to include the "No Authorization" option
> [ENHANCEMENT] make proxy authorization optional

- internal/cli/cmd/dac/build/build.go
With this PR, `percli dac build` is ignoring a list of pre-defined folder where the files to be compiled must not be stored.
it fixes https://github.com/perses/perses/issues/2533.
An idea to improve this quick win would be to use the file `.gitignore` if it exists and then ignore everything listed in this file
> [ENHANCEMENT] CLI/DAC: ignore a list of pre-defined folder when building dashboard

- internal/cli/cmd/dac/build/build.go
This pull request introduces changes to the `internal/cli/cmd` package to support passing arguments to commands in the `build` subcommand. The most important changes include adding a new method to set arguments, updating the `option` struct to store these arguments, and modifying the command execution to include the arguments.
Enhancements to argument handling:
* [`internal/cli/cmd/cmd.go`](diffhunk://#diff-ff081a1614e8adc291f4c20213d31463eb3b63cb0ea04a80dfe3626458464973R31-R38): Added the `SetArgs` method to the `Option` interface to allow setting command arguments.
Updates to the `build` command:
* [`internal/cli/cmd/dac/build/build.go`](diffhunk://#diff-97a1ca64aa554e8fc0b8b0f14879390430207a930004b32489d5191fc381e0c4R47-L53): Updated the `option` struct to include an `args` field for …
> [ENHANCEMENT] adding extra args support dac build

- cue/dac-utils/variable/group/group.cue
- cue/dac-utils/variable/list/list.cue
This fixes one of the errors we are getting in some cases with DaC following the bump to CUE [v0.12.0](https://github.com/cue-lang/cue/releases/tag/v0.12.0) that includes this:
> ⚠️ [CL 1206950](https://cuelang.org/cl/1206950) fixes an issue where incomplete errors were not being reported by `cue eval` and `cue vet`.
> [BUGFIX] CUE SDK: fix "cannot reference optional field" error

- scripts/generate-goreleaser/.goreleaser.base.yaml
following this guideline: https://goreleaser.com/deprecations/#archivesbuilds
> [ignore] update goreleaser config

- .github/workflows/cue.yaml
The job has been skipped during the the release because the event check is not the accurate one. Before it was looking for the event matching the creating of release in GitHub. But the process in Perses is to actually create a tag. The CI is then triggered when the tag is created (with a push). 
This PR is fixing it
> [ignore] fix release condition for  cue sdk

- pkg/model/api/v1/common/url.go
fix such issue..
```bash
time="2025-03-24T11:22:22Z" level=info msg="No dashboard node-exporter-simple found in project KubeConEurope2025, no current link to provide"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5bae0c]
goroutine 1 [running]:
net/url.(*URL).String(0xc00002aab0?)
/opt/hostedtoolcache/go/1.23.7/x64/src/net/url/url.go:832 +0x2c
github.com/perses/perses/internal/cli/cmd/dac/preview.(*option).buildPreviewResponse(0xc000170000, 0xc00013f860?, 0xc000386340)
/home/runner/work/perses/perses/internal/cli/cmd/dac/preview/preview.go:172 +0x3ad
github.com/perses/perses/internal/cli/cmd/dac/preview.(*option).Execute(0xc000170000)
/home/runner/work/perses/perses/internal/cli/cmd/dac/preview/preview …
```
> [BUGFIX] `dac preview`: fix nil pointer error for brand new dashboards

- ui/plugin-system/src/remote/PluginRuntime.tsx
Use a lazy singleton for plugin runtime, this avoids initializing the module federation runtime if not used. For example when embedding Perses plugins by importing the `@perses-dev/plugin-system`
> [ENHANCEMENT] use singleton and lazy initialization for plugin runtime

- docs/configuration/configuration.md
This leftover line
```
```bash
```
starts a not existing verbatim block that is not closed and hence mixes up the markdown syntax.
This line was introduced in this commit:
https://github.com/perses/perses/commit/a0707f151dc1a4246af8f3b9c14d21b2b865f0f2#diff-17f1012e0c2fbd9bcd8dff3c23b18ff4b6676eef3beca6f8a3e72e6a36633334R69
> [DOC] Fix the markdown syntax in `docs/configuration/configuration.md`

- pkg/model/api/v1/secret/oauth.go
- Updated the error messages
- Fixed a typo into the json struct tag
- Fixed the conditions to be valid client credentials (results in the table means "return an error"
> [BUGFIX] Fix OAuth struct parse errors + typo in json

- pkg/client/config/config.go
> [BUGFIX] Read clientSecretFile when configuring rest client with oauth

- ui/app/src/views/import/PersesFlow.tsx
- ui/components/src/JSONEditor.tsx
UX when importing dashboards via JSON can be laggy, I'm proposing couple changes
**Actual result**
**Expected result**
> [BUGFIX] Dashboard import: fix wrong form reset + UX improvements

- docs/configuration/configuration.md
- internal/api/core/core.go
- internal/api/core/core_test.go
- internal/api/e2e/api/cors_test.go
- internal/cli/cmd/conf/conf_test.go
- pkg/model/api/config/config_test.go
- pkg/model/api/config/security.go
CORS is needed in order to host the frontend independently from the backend. This change adds the ability to configure the [CORS middleware](https://echo.labstack.com/docs/middleware/cors) in the config file.
> [FEATURE] Allow to configure CORS

- ui/plugin-system/src/components/DatasourceSelect.tsx
- ui/plugin-system/src/components/PluginRegistry/PluginRegistry.tsx
- ui/plugin-system/src/components/PluginRegistry/plugin-indexes.ts
- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
- ui/plugin-system/src/model/trace-queries.ts
- ui/plugin-system/src/runtime/plugin-registry.ts
- ui/plugin-system/src/runtime/time-series-queries.ts
- ui/plugin-system/src/runtime/trace-queries.tsx
- ui/plugin-system/src/runtime/utils.ts
solves https://github.com/perses/perses/issues/1514
connected to https://github.com/perses/plugins/pull/110
- `DatasourceSelect` component now works with variables
- `DatasourceSelect` component returns a `DatasourceSelectValue` of type `DatasourceSelect | VariableName`
- Type fixes for `listPluginMetadata`, accepts `PluginType[]` instead of `string[]`
- TraceData now supports variables, and therefore also has `dependsOn` function
Fixes:
- `VariableEditorForm` wasn't updated properly whenever the spec was changed, watching the plugin instead of only watching the plugin.kind solves it.
Unknowns:
- We do not support for now multiple variables for prometheus and tempo datasources, need a way to manually remove the options for multi-selection whenever working with those specific datasource …
> [ENHANCEMENT] Enable Datasource Variables

- cue/model/api/v1/common/url_go_gen.cue
- pkg/model/api/v1/common/url.go
Adds annotations for kubebuilder to properly validate the common.URL type as a string instead of an object
Closes #2890 
> BUGFIX: Add Kubebuilder annotation to common.URL

- internal/cli/cmd/get/get.go
- internal/cli/cmd/plugin/list/list.go
- internal/cli/cmd/plugin/list/list_test.go
- internal/cli/cmd/plugin/plugin.go
- pkg/client/fake/api/v1/client.go
- pkg/client/fake/api/v1/plugin.go
- ui/endpoint.go
```bash
➜  perses git:(main) ✗ ./bin/percli plugin list
NAME        | VERSION |     TYPE     | LOADED | FROM DEV
---------------------+---------+--------------+--------+-----------
TracingGanttChart  | 0.5.0   | Panel        | true   | false
BarChart           | 0.5.0   | Panel        | true   | false
GaugeChart         | 0.5.0   | Panel        | true   | false
Markdown           | 0.6.0   | Panel        | true   | false
PieChart           | 0.5.0   | Panel        | true   | false
Prometheus         | 0.6.0   | PluginModule | true   | false
ScatterChart       | 0.5.0   | Panel        | true   | false
StatChart          | 0.5.0   | Panel        | true   | false
StaticListVariable | 0.2.0   | Variable     | true   | false
Table              | 0.5.0   | Panel        | true   | false
Tempo …
```
> [FEATURE] CLI: list the plugins

- internal/api/interface/error.go
- internal/api/toolbox/toolbox.go
fix https://github.com/perses/perses/issues/2919
Instead of throwing a 400 error, it returns a 415 error which seems more accurate based on the meaning of the error code.
Let me know if we need to differentiate when the header `Content-Type` is missing or wrong.
> [ENHANCEMENT] Invalid content type when it is not JSON

- ui/plugin-system/src/components/HTTPSettingsEditor/HTTPSettingsEditor.tsx
data source settings editor: use proxy mode by default
Resolves: https://github.com/perses/perses/issues/2914
no notable changes
> [ENHANCEMENT] data source settings editor: use proxy mode by default

- ui/components/src/TimeChart/TimeChart.tsx
- ui/components/src/context/ChartsProvider.tsx
- ui/components/src/test-utils/theme.ts
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
solves https://github.com/perses/perses/issues/2813
`syncGroup` property used to be available regardless if we are within the edit panel or not.
Similar solution to the `enablePinning`:
- Added another property to `ChartsProvider` called `enableSyncGrouping`.
- `TimeChart` consumes this property and accordingly syncs the group or not.
**BEFORE**
**AFTER**
- Does it have loading states? You need to wait for loading to …
> [BUGFIX] Shared Tooltip In Edit Panel Overflowing

- ui/plugin-system/src/runtime/time-series-queries.ts
`<DataQueriesProvider />` accepts a `queryOptions` prop that is intended to match the options used in `@tanstack/react-query` query hooks. 
Although it appears that all options can be passed in, only a limited subset is actually forwarded to the query configuration. This can create a false impression that all fetching options are customizable. This PR updates the implementation to pass all options using the spread operator. The spread is applied as the first argument to avoid accidentally overriding custom logic such as `enabled` or `queryFn`.
N/A
N/A
> [ENHANCEMENT] pass rest of options from queryOptions

- ui/components/package.json
- ui/package-lock.json
Adding immer as deps and remove zod (not used in this repo)
Hopefully, should remove these warnings:
```
[HistogramChart] warn    Compile Warning: 
[HistogramChart] File: /.../Projects/plugins/node_modules/@perses-dev/components/dist/Legend/Legend.js:1:1
[HistogramChart]   ⚠ No required version specified and unable to automatically determine one. Unable to find required version for "immer" in description file/s
[HistogramChart]   │ /.../Projects/plugins/node_modules/@perses-dev/components/package.json
[HistogramChart]   │ /.../Projects/plugins/package.json
[HistogramChart]   │ It need to be in dependencies, devDependencies or peerDependencies. file: shared module immer
[HistogramChart] 
[HistogramChart]  @ ../node_modules/@perses-dev/components/dist/Legend/index.js
[HistogramChart]  @ …
```
> [IGNORE] components: add missing dep immer

- internal/api/plugin/schema/schema.go
- internal/cli/cmd/plugin/lint/lint.go
Can help troubleshoot issues when updating schemas of a multi-plugin packages, e.g:
```bash
$ ../perses/bin/percli plugin lint --plugin.path prometheus --log.level trace
time="2025-06-04T21:08:36+02:00" level=trace msg="Loading model package from prometheus\\schemas\\datasource\\"
time="2025-06-04T21:08:36+02:00" level=trace msg="Loading model package from prometheus\\schemas\\prometheus-label-names\\"
Error: imported and not used: "github.com/perses/plugins/prometheus/schemas/datasource:model" as promDs (and 1 more errors)
```
> [IGNORE] Add a trace log in `schema.Load()`

- docs/installation/in-a-container.md
I am doing that as the Dockerfile is outside of the `docs` folder and the website does not have access to any other file than the one in the `docs` folder.
So when the website is building the navigation, it doesn't find the file `Dockerfile`
> [DOC] Update link to dev dockerfile in the doc

- docs/configuration/configuration.md
Finishes changes introduced in f8b3caac (#2831).
I've came across some cods inconsistencies when trying to run some plugin in dev mode. The changes in docs should match the changes in the code. In parallel, I'm sending a PR to plugins repo as well.
> [DOC] Fix docs for plugin configuration

- internal/api/impl/proxy/proxy.go
- internal/api/impl/v1/user/endpoint.go
- internal/api/impl/v1/view/endpoint.go
- internal/api/impl/v1/view/endpoint_test.go
- internal/api/interface/service.go
- internal/api/rbac/cache.go
- internal/api/rbac/disabled.go
- internal/api/rbac/rbac.go
- internal/api/toolbox/list.go
- internal/api/toolbox/toolbox.go
This PR is changing the rbac interface in order to use the Perses context instead of the login of the user.
This is a first PR to make the authorization layer more generic and later to be able to improve and accept the PR #2940.
Other PRs will follow changing step by step the authorization layer
/cc @PeterYurkovich
> [IGNORE] RBAC interface is using the perses context

- ui/dashboards/src/components/DownloadButton/DownloadButton.tsx
The namespace was not in the correct location for the perses-operator Dashboard CR while using the download feature.
> [BUGFIX] Move namespace to correct location for Dashboard CR export

- ui/explore/src/components/ExploreManager/ExploreManager.tsx
Current tab order was random based on plugin loading, now it will keep the same place based on plugin display name
> [BUGFIX] explore: Fix tabs in random order

- ui/explore/src/components/ExploreManager/ExploreManager.tsx
After looking at @iNecas [super demo](https://www.youtube.com/watch?v=-ieiplT1k5g). I found explorer tabs were using too much space to my liking on small screens. 
I remove some whitespace + adding a toggle to collapse or expand tabs (state stored in localStorage). On mobile screen button is hidden.
BEFORE:
AFTER:
> [FEATURE] Explore: allow users to collapse tabs menu

- ui/app/src/views/import/GrafanaFlow.tsx
I was importing a grafana dashboard from json. When I select a project after migrating the import button was disabled I was wondering why checked everything again and changed project still no 
Then clicked outside of the select box and suddenly it's enabled
Closes the following [issue](https://github.com/perses/perses/issues/3082)
> [BUGFIX] After selecting a project in import dashboard import button stays disabled until clicked outside

- ui/app/src/Router.tsx
- ui/app/src/components/variable/VariableDrawer.tsx
- ui/app/src/model/datasource-api.ts
- ui/app/src/model/url-builder.ts
- ui/app/src/views/explore/ExploreView.tsx
- ui/app/src/views/explore/ProjectExploreView.tsx
- ui/app/src/views/projects/dashboards/HelperDashboardView.tsx
- ui/core/src/model/datasource.ts
- ui/dashboards/src/context/DatasourceStoreProvider.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
- ui/explore/src/views/ViewExplore/ViewExplore.tsx
Relates to #3059 
This PR pulls the datasource build proxy URL logic out of the Data Source Provider properties. 
Every single data source should carry a concrete proxy URL. It means, building the proxy URL is the responsibility of the consumer.  
**_This is a refactor_**
> [FEATURE]: Decouple datasource provider from builing proxy url logic

- .mdox.validate.yaml
datatracker is the website referencing all RFC and it now returns a 403 when GitHub is checking the URL. Perphaps GitHub has been blacklisted
> [ignore] avoid checking datatracker url in doc as it returns a 403

- ui/app/src/Router.tsx
- ui/app/src/context/Authorization.tsx
- ui/app/src/model/auth-client.ts
- ui/app/src/model/fetch.ts
With #3031 fix, we are refetching access token when back returns code 401. For this we need to keep expired access token in browser to send it, else we have a 400 error. For this the access token cookie max age is equal to refresh token cookie max age.
However, if by any chance the refresh token cookie is deleted and not the access token cookie, the UI will be stuck in bad state (all fetch failing and not redirecting to login page).
This PR force the delete of the cookie in case of refresh token is failing, forcing the user to be redirected to login page.
- Is the data …
> [BUGFIX] UI: remove cookies on token refresh fail

- ui/.prettierrc.json
- ui/components/src/ContentWithLegend/ContentWithLegend.tsx
- ui/components/src/Legend/Legend.tsx
Closes #2772 
For details of the bug please take a look at the related issue
https://github.com/perses/perses/issues/2772#issue-2919900618
This fix 
1. Removes Overflow hidden behavior of the chart container, **if there is enough room for both legend and the container** (This is the improvement)
2. If there is an overlap, the legend covers the chart. **This has been the default behavior**
3. If there is no enough room for both, the legend is removed. **This also has been the default behavior** 
> :warning: If overlap happens the legend covers the chart. (This has been the default behavior). Under these circumstances, for sure the tool tip also will be covered!
See …
> [BUGFIX] Handle Piechart tooltip overlap with legend

- cue/common/format.cue
- docs/plugins/common.md
- go-sdk/common/format.go
- ui/components/src/FormatControls/FormatControls.test.tsx
- ui/components/src/FormatControls/FormatControls.tsx
- ui/core/src/model/units/currency.test.ts
- ui/core/src/model/units/currency.ts
- ui/core/src/model/units/types.ts
- ui/core/src/model/units/units.ts
Solves #2225 
The changes in this PR add "Currency" as additional Unit for formatting. Initially the [15 most traded currencies](https://en.wikipedia.org/wiki/Foreign_exchange_market#Most_traded_currencies_by_value) were added. The currency units follow the ISO 4217 currency codes, thus addition or removal of units should be trivial. 
> [FEATURE] Add currency value formatting (perses#2225)

- cmd/perses/main.go
- internal/api/core/core.go
- internal/api/core/server.go
- internal/api/dependency/dependency.go
- internal/api/dependency/persistence_manager.go
- internal/api/dependency/service_manager.go
- internal/api/e2e/api/globalrolebinding_test.go
- internal/api/e2e/api/rolebinding_test.go
- internal/api/e2e/client/test_utils.go
- internal/api/e2e/framework/data.go
- internal/api/e2e/framework/scenario.go
- internal/api/e2e/framework/server.go
- internal/api/impl/v1/project/service.go
Role, RoleBinding and user are here to make the native authorisation working. As such when a third-party authorisation service is used, we don't need to expose these resources
Edit: As a side effect, I had to rework the e2e tests. Indeed, by deactivating the possibility to create role/roleBinding when the native authorisation is not activated, then current tests were not passing anymore as we are creating the tests without any authentication.
This is not the case anymore, every standard tests scenarios are using a server with auth activated. A default user is created "alice" with default role and roleBiding to give her full right on any object provided by the API.
> [FEATURE] Enable role, rolebinding and user only when native authz is used

- ui/components/package.json
- ui/core/package.json
- ui/dashboards/package.json
- ui/explore/package.json
- ui/plugin-system/package.json
Fix swc configuration to use the root `./dist` folder as target for transpiled files. This will fix https://github.com/perses/plugins/pull/235
> [IGNORE] fix swc configuration to use the root directory for transpiled files

- ui/plugin-system/src/components/MultiQueryEditor/QueryEditorContainer.test.tsx
- ui/plugin-system/src/components/PluginEditor/PluginEditor.test.tsx
- ui/plugin-system/src/components/PluginEditor/PluginEditor.tsx
- ui/plugin-system/src/components/PluginSpecEditor/PluginSpecEditor.tsx
- ui/plugin-system/src/model/plugin-base.ts
Relates to #3187 
>  This PR and https://github.com/perses/plugins/pull/242 should be merged together to be effective, So you need to review them together.
> 🔍  Read the PR before you review anything.
> ⚠️ I would like to have @jgbernalp  and @Nexucis  approval as well. Do not merge unless they have tested and approved this fix
> ⚠️  This change will affect Explorer, Edit Panel View, (**Prometheus and Tempo**)
> 🧪  Please test before merge
> 💀   This change will not cover similar onBlur issues of Legend and Min Step. They will have their own dedicated issues
`Run Query Button` as its name suggests is responsible for running an **_updated_** query. At the moment, this button does not function properly, and the query-execution is triggered by onBlur event. 
This change is tracking the …
> [BUGFIX] Add watch_query_changes to fix run query button issue

- go.mod
- internal/api/impl/v1/plugin/endpoint.go
- internal/api/plugin/dev.go
- internal/api/plugin/migrate/migrate.go
- internal/api/plugin/plugin.go
- internal/cli/cmd/plugin/start/start.go
- pkg/client/api/v1/plugin.go
The CLI is watching any Cuelang files contained in the `schema` folder. 
Anytime a change occurred on any files watched, the CLI is calling the API to reload the schema and the migration file.
This should complete the plugin development and help to load or reload a plugin in development without having to re-start the Perses server.
> [ENHANCEMENT] CLI/PLUGIN: schema files are watched and reloaded when modified

- ui/plugin-system/src/runtime/RouterProvider.tsx
Log a warning instead of throwing an exception if `<RouterProvider>` (see https://github.com/perses/perses/pull/3140 for more details) is not present.
no UI changes
> [IGNORE] make <RouterProvider> optional

- ui/core/src/model/index.ts
- ui/core/src/model/log-data.ts
- ui/core/src/model/query.ts
- ui/plugin-system/src/model/log-queries.ts
- ui/plugin-system/src/model/plugins.ts
- ui/plugin-system/src/runtime/DataQueriesProvider/DataQueriesProvider.test.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/DataQueriesProvider.tsx
- ui/plugin-system/src/runtime/DataQueriesProvider/model.ts
- ui/plugin-system/src/runtime/log-queries.ts
- ui/plugin-system/src/test/mock-data.ts
Adds necessary models and queries for LogQuery type
We need it for [#perses/plugins/178](https://github.com/perses/plugins/pull/178)
relates to #2999 
> [FEATURE] Add LogQuery support and related data structures and queries

- ui/dashboards/src/components/GridLayout/GridItemContent.tsx
- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelActions.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
- ui/dashboards/src/constants/user-interface-text.ts
Closes #3071 
This is the Quick Query Viewer **kick-off** . 
> ⚠️ More interesting ideas can be added later on top. Let's have a scaffold first ...
1. Open a project
2. Then go to a dashboard
3. All panel headers should have an extra functionality (Query Viewer)
4. Click on the icon button
5. Do you see the queries? (It should show all quires)
6. You can also open Tree View
- Does it have loading states? You need to wait for …
> [FEATURE]: Add Quick Query Viewer

- ui/plugin-system/src/components/PluginEditor/PluginEditor.tsx
- ui/plugin-system/src/model/plugin-base.ts
Relates to #3195 
> ⚠️ Should be merged with https://github.com/perses/plugins/pull/268 to be effective 
Prometheus Time Series Query Editor gives you two options called `Legend` and `Min_Steps`. If you change the values of the mentioned fields and trigger the onBlur event the, query will be executed immediately. This is **NOT** an ideal behavior, and we prefer to have the query executed when the `Run Query Button` is pressed. 
This change adds a generic watch mechanism to the PluginEditor. This helps us to track the changes of the `UnknownSpec`. When the `Run Query Button` is pressed, the stale specs are replaced with tracked changes, and then, the query is executed. 
This is already tested by 
https://github.com/perses/perses/commit/f95c59636da1bf9142d1340dc3381b77af5ad64b
**I see some …
> [BREAKINGCHANGE] Watch the changes of the unknown specs in all Editor Plugins

- ui/plugin-system/src/components/Variables/VariableEditorForm/VariableEditorForm.tsx
Closes https://github.com/perses/perses/issues/3234
There is a block of code in ` VariableEditorForm\VariableEditorForm.tsx`  which is used to call `refreshPreview` when the user clicks anywhere on the Edit Variable Form. Technically when they click outside the <Box /> which not dimension. 
To understand what I am talking about you can take a quick look at 
https://mui.com/material-ui/react-click-away-listener/
I think this was a trick to refresh the Edit Form after changes, imitating the onBlur behavior. 
1. Change a control value
2. Click anywhere on the Form 
3. The  `refreshPreview` should be called
Since we are moving away from onBlur behavior, and all interactions should happen through onClick event, this old piece of code causes a bug. For instance, if I click on a button to get …
> [BUGFIX] Remove ClickAwaya to avoid unnecessaey endpoint call

- ui/app/src/views/projects/dashboards/HelperDashboardView.tsx
- ui/dashboards/src/components/DashboardToolbar/DashboardToolbar.tsx
- ui/dashboards/src/components/LeaveDialog/LeaveDialog.tsx
- ui/dashboards/src/components/LeaveDialog/index.ts
- ui/dashboards/src/components/index.ts
- ui/dashboards/src/views/ViewDashboard/DashboardApp.tsx
- ui/dashboards/src/views/ViewDashboard/ViewDashboard.tsx
Add an optional confirmation dialog when the user try to close/refresh/change manually the url with unsaved change on a dashboard.
**KNOW ISSUE:**
If you navigate with react-router links (`<Link>`), it will not trigger this popup. For this, we need to add another custom popup with `Prompt` or `useBlocker`. However, it need a complete refactor of the router: we need to change declarative mode data mode (https://reactrouter.com/start/modes).
I will do it in a separate PR, hopefully it will not be to hard 🙏
Chrome:
Firefox:
- Is the data inconsistent? You need to mock API …
> [FEATURE] dashboard: add optional confirmation dialog on unsaved leave

- ui/dashboards/src/components/Panel/Panel.tsx
- ui/dashboards/src/components/Panel/PanelHeader.tsx
Closes #3254 
This change adds/removes the panel header title according to the text ellipsis
> [FEATURE]: Add tool tip in case of panel header ellipsis

- ui/dashboards/src/components/PanelDrawer/PanelEditorForm.tsx
- ui/plugin-system/src/components/MultiQueryEditor/QueryEditorContainer.tsx
- ui/plugin-system/src/components/PluginEditor/PluginEditor.tsx
- ui/plugin-system/src/components/PluginEditor/plugin-editor-api.ts
- ui/plugin-system/src/test/utils.tsx
Closes https://github.com/perses/perses/issues/3242
Closes https://github.com/perses/perses/discussions/3201
Discussed in details https://github.com/perses/perses/issues/3242 with @andreasgerstmayr 
This PR wraps the PanelEditorForm with a new Time Range. Whenever the Run Query Button is pressed a fresh time range is generated, forcing  the query to be executed. So, whether the spec has changed or not, the query is executed, and no cached result will be returned. 
The following picture is self-explanatory 
- …
> [BUGFIX] Force a refresh time range when the Run Query Button is clicked everytime

- ROADMAP.md
as agreed during the Perses sync meeting, we are setting a deadline for dropping react 17 support.
> [ignore] set a deadline for dropping react 17 support

- ui/plugin-system/src/model/time-series-queries.ts
- ui/plugin-system/src/runtime/time-series-queries.ts
Relates to #3340 
This PR adds an abort signal specifically to plugin get_time_series_data. 
This is the 1/2 and there will be the signal usage in plugin side as well. 
When plugin http requests are pending, in case of dashboard unmount all dangling requests should be aborted. 
React Query **_QueryFn_** generates the abort signal itself. We just need to pass this signal to the actual fetch method. 
The React query has a subscription to the component life-cycle, meaning if the component is being unmounted, all queries in pending states will be aborted.   
- Is the data …
> [BUGFIX]: Add abort signal to plugin get time series data

- ui/app/src/model/fetch.ts
- ui/app/src/utils/browser-storage.ts
- ui/core/src/utils/fetch.ts
- ui/plugin-system/src/components/MultiQueryEditor/QueryEditorContainer.test.tsx
- ui/plugin-system/src/remote/PluginLoaderComponent.test.tsx
Fixes #3361
Uses `globalThis` instead of `global` to ensure compatibility across different JavaScript environments. `global` is node specific, while `globalThis` is a standard that works in both Node.js and browser environments. The globalThis object is already in use in other parts of the codebase ([here](https://github.com/perses/perses/blob/9b21ce5364088dc58464c93ef62cf1875ce197b5/ui/dashboards/src/context/DashboardProvider/common.ts#L32-L36) and [here](https://github.com/perses/perses/blob/9b21ce5364088dc58464c93ef62cf1875ce197b5/ui/components/src/utils/component-ids.ts#L25-L27)) and the tests pass with this change.
N/A
See …
> [BUGFIX] use globalThis object over global

- ui/app/src/model/migrate-client.ts
- ui/app/src/views/import/GrafanaFlow.tsx
UI implementation of https://github.com/perses/perses/pull/3358
- Added a checkbox for using default datasource in Perses
https://github.com/user-attachments/assets/38e4d7db-5ce7-4a64-9d0b-87ce11320b6f
> [ENHANCEMENT] Allow UI to select default datasource during migration

- ui/plugin-system/src/components/Variables/variable-model.test.ts
- ui/plugin-system/src/components/Variables/variable-model.ts
- ui/plugin-system/src/model/variables.ts
Relates to #3340 
This PR adds the Abort Signal to the fetch data source variables. (Just missed)
> [BUGFIX] Add abort signal to datasource variables query

- ui/.gitignore
- ui/plugin-system/src/remote/remotePluginLoader.test.ts
- ui/plugin-system/src/remote/remotePluginLoader.ts
- ui/plugin-system/src/test/mock-data.ts
Fixes #3371
Updates the `remotePluginLoader` to correctly pass the `baseUrl` to the `loadPlugin` function. This ensures that plugins are loaded from the correct base URL, preventing potential issues with loading resources.
Also added a test file for this one specifically.
N/A
> [BUGFIX] pass baseUrl to loadPlugin

- .github/workflows/go.yml
- Makefile
- cue-test/common/transform.cue
- cue-test/common/url.cue
- scripts/validate-cue/validate-cue.go
In the past we got [such typo](https://github.com/perses/perses/pull/3012) released before we noticed the problem when trying to rely on the schema on the plugins side.. This PR aims to address that by putting in place a proper "framework" to validate the CUE schemas hosted in this repo: the new folder `cue-test` at the root of the repository mirrors the same file structure as the `cue`  folder (= same sub directories, file names and package names). `<filename>.cue` from each side combined together (using `cue vet`) should evaluate successfully.
Only few tests are defined in this PR, to be completed later now that the base is in place.
> [IGNORE] Validate CUE files

- ui/components/src/context/SnackbarProvider.tsx
The goal was to preserve the formatting (spaces and line breaks) of error messages returned by the backend, to be displayed as-is in the error toasts. This is mainly useful for the lengthy errors returned on some failed CUE validations. This is achieved by passing down the right CSS customization ([white-space: 'pre-wrap'](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#pre-wrap))
Still not ideal to have very verbose errors like this but until we have a better solution, this will be more intelligible displayed this way.
Before:
After:
- Is the data …
> [ENHANCEMENT] Improve display of error messages returned by the backend

- internal/cli/cmd/plugin/generate/templates/module/rsbuild.config.ts.tmpl
Add the getPublicPath function to the plugin generation template
> [ENHANCEMENT] add a public path function for plugins generation for reverse proxies

- ui/app/rspack.config.mjs
- ui/app/src/components/datasource/DatasourceDrawer.tsx
- ui/app/src/components/variable/VariableDrawer.tsx
- ui/app/src/config.ts
- ui/app/src/context/Config.tsx
- ui/app/src/model/config-client.ts
- ui/app/src/model/remote-plugin-loader.ts
- ui/app/src/model/url-builder.ts
- ui/app/src/views/projects/dashboards/HelperDashboardView.tsx
- ui/app/src/views/projects/explore/ProjectExploreView.tsx
- ui/plugin-system/src/remote/remotePluginLoader.test.ts
- ui/plugin-system/src/remote/remotePluginLoader.ts
- ui/plugin-system/src/runtime/UsageMetricsProvider.tsx
This PR adds some necessary changes to enable reverse proxy support, allowing the application to work correctly when deployed behind a reverse proxy with a custom base path.
There is still an issue with the plugin files having been compiled with a specific base path (`/`) but this will be tackled in a future PR.
Closes #2579
**Plugin System Updates:**
- **`remotePluginLoader.ts`**: Modified to accept an options object in addition to a single string so that the baseUrl is handled correctly while maintaining the original behavior of the original implementation.
- **Multiple React components**: Updated to pass `getBasePathName()` to remotePluginLoader for consistent base path handling
**API Request Updates:**
- **`UsageMetricsProvider.tsx`**: Added `baseUrl` parameter to ensure API requests …
> [BREAKINGCHANGE] Improve support for reverse proxy configuration

- ui/app/src/model/auth-client.ts
- ui/app/src/model/config-client.ts
- ui/app/src/model/migrate-client.ts
- ui/app/src/model/plugin-client.ts
- ui/app/src/model/url-builder.ts
The PR #3377 broke few functionalities like getting the list of the plugins in app.
This PR aims to fix that.
As a side effect I have renamed the field `apiUrl` by `apiURL` as URL is not a word.
/cc @lachieh
> [ignore] fix usage of apiPrefix vs apiURL

- internal/cli/cmd/plugin/start/devserver.go
- internal/cli/cmd/plugin/start/devserver_windows.go
- internal/cli/cmd/plugin/start/start.go
- internal/cli/cmd/plugin/start/start_test.go
This allows `percli plugins start` command to detect the port used by the plugin(s). This will allow to remove the manual port configuration from the plugins side. The current port discovery reading the plugin configuration was kept for backwards compatibility.
This requires that the plugin dev server reports its port adding some configuration on the plugin side. (Follow up PR)
```
server: {
printUrls: ({ urls }) => urls,
cors: { origin: '*' },
},
```
> [FEATURE] Implement port capturing for plugin dev servers

- internal/cli/cmd/plugin/generate/templates/module/rsbuild.config.ts.tmpl
- internal/cli/cmd/plugin/start/devserver.go
- internal/cli/cmd/plugin/start/devserver_windows.go
- internal/cli/cmd/plugin/start/start_test.go
Extends the regex for plugin port matching based on the following template, that will be added to plugins:
```
[PERSES_PLUGIN] PORT="3000"
```
> [ENHANCEMENT] add custom pattern for matching plugin ports
